### ISSUE TITLE
Change singular headers to plural in NHSL

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1001]
More NHSL visualization tweaks: 

@wsalesky Our mid-page headers for NHSL entries are singular ("Edition," "Catalogue," etc.). We would like to make them plural. I believe these are pulled from the ODD file. Is it best for me to change the ODD file to plural, or do you have a fancy-schmancy pluralizer function? 

Thanks!

**Comment by nathangibson** [comment]
E.g., http://wwwb.library.vanderbilt.edu/work/1

**Comment by wsalesky** [comment]
Done.

**Comment by nathangibson** [comment]
Yay, thank you!

**Comment by nathangibson** [comment]
Sadly, I don't think this is going to work as is. E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9724. Should we put an extra gloss containing the plural label in the ODD file?

| Currently   |      Should Be      |
|----------|-------------|
| Final Rubrics |  Final Rubrics | 
| Incipit (Opening Line) |    Incipits (Opening Line)   |   
|Explicit (Closing Line) | Explicits (Closing Line) |    
|Original Language Edition with Syriac Evidences|Original Language Editions with Syriac Evidence|
|Editions|Editions|
|Apparatuss|Apparatuses|
|Manuscript|Manuscripts|
|Ancient Version|Ancient Versions|
|Digital Catalogue|Digital Catalogues|
|Print Catalogue|Print Catalogues|
|Glossary|Glossaries|

**Comment by wsalesky** [comment]
Hum, yes I suppose we could try that. I think otherwise it will be to convoluted to get plurals correct via the xslt. 

Let me know when it is added and I will adjust the lookup.

**Comment by nathangibson** [comment]
All right, there you go! E.g., 

```
<gloss type="sg">Glossary</gloss>
<gloss type="pl">Glossaries</gloss>

```
https://github.com/srophe/srophe-eXist-app/commit/4ae8bd0d27161c7361f82b89ddfa03f287b1ad59
