### ISSUE TITLE
Print & Digital Catalogues

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1002]
@wsalesky We decided to distinguish between print and digital catalogues. I've updated the data and changed the labels in the ODD, but I guess there's still something else that needs to be switched. Bibl items under "Print Catalogues" and "Digital Catalogues" are now just displaying as plain text rather than as bibl entries. 

Would you please apply to `//bibl[@type=('syriaca:PrintCatalogue','syriaca:DigitalCatalogue')` the same settings you had for `syriaca:Catalogue`? (This includes moving them below manuscripts.) Thanks!

**Comment by nathangibson** [comment]
E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1

**Comment by wsalesky** [comment]
Done.
