### ISSUE TITLE
NHSL Section Header Table of Contents buttons

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1004]
At top of work records, please put buttons above identity box for each header category (editions, manuscripts, etc.) in the record (not including the ones in the identity box). These should jump to the correponding section. These should be in the order the headers appear on the page, and the buttons should only appear if that category is actually on the page.

**Comment by wsalesky** [comment]
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1
for a working example.

**Comment by nathangibson** [comment]
I like this and it will be a big help. Maybe could we change "Table of Contents:" to "Jump to:" and make it not a button? Thanks.

**Comment by wsalesky** [comment]
I think this can be closed? @nathangibson?

**Comment by nathangibson** [comment]
Yes, thanks!
