### ISSUE TITLE
Collapse 8+ items in bibl sections of work records

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1005]
Please collapse items 8 or higher in bibl sections (editions, manuscripts, etc.) on work record pages. This can be an inline "Show All" / "Hide" button.

**Comment by nathangibson** [comment]
@wsalesky This is working well but we would like a couple tweaks. 

1. Can we set the limit higher, so that it shows 5 items instead of just 2? 
2. It's easy to miss the "Show" link. A couple things could help:
 a. Could you include a count, so that instead of, e.g., "Show all Manuscripts" it says "Show all 23 Manuscripts"? http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/77 as example.
  b. *If* it's easy, it would be nice to do a gradient fade on the last couple lines before the "Show all" so that there's a visual cue. 

Thanks!

**Comment by wsalesky** [comment]
Limit set to 8. Leaving open so I can add in the fancy gradient fade.

**Comment by nathangibson** [comment]
Thanks!

**Comment by wsalesky** [comment]
@nathangibson The fancy gradient is actually quite difficult unless you have a fixed height element, which we do not for lists. I can leave this open, and if I get a chance to reinvestigate I will.

**Comment by nathangibson** [comment]
No problem. Gradient isn't important. Feel free to close and we can reopen later if needed. Thanks!
