### ISSUE TITLE
Reorder bibl sections of work records

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1006]
Please put bibl sections of work records in the following order on the HTML page. (I'm indicating the `@type` here.) Would it help if I just arranged them in the correct order in the ODD file? 

1. lawd:Edition
2. syriaca:Apparatus
3. syriaca:Manuscript
4. syriaca:AncientVersion
5. syriaca:ModernTranslation
6. syriaca:DigitalCatalogue
7. syriaca:PrintCatalogue
8. syriaca:Glossary

As before, lawd:Citation only shows up in Sources list.

Thanks!

**Comment by wsalesky** [comment]
Done.
