### ISSUE TITLE
Problem with SPEAR aggregate page for the test doc

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1009]
The aggregate page for the test doc and for the Chronicle of Edessa are identical, but they shouldn't be: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/spear/119

An earlier version of this xml file, made by copying the Chron. of Ed. file, has some information in the header that shouldn't have been there. When I noticed the problem in the html, I removed that from that legacy information from the header hoping the problem would resolve itself. It did not. Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz They had duplicate tei:idno's on the server, even though it was correct on github. I'm guessing there was a bad webhook at some point.  I manually updated the dev server record.
