### ISSUE TITLE
Ptr appears unexpectedly in Bibliography Display 

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1011]
Last footnote of http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/81 has the following: 

`A. Juckel, " Bible, New Testament manuscripts," in Sebastian P. Brock et al. (eds.), The Gorgias Encyclopedic Dictionary of the Syriac Heritage ( Piscataway, NJ: Gorgias Press, 2011) http://syriaca.org/bibl/115`

Why does the bibl URI appear at the end?

Thanks!

**Comment by wsalesky** [comment]
The idno in this record (http://syriaca.org/bibl/115) appears in a different place then in other bibl records. I believe that was some holdover code and have suppressed it. idno's should now all be rendered via templates with `mode="links"` this will render them with the link/icon/tooltip combination.
