### ISSUE TITLE
Name variants in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1017]
@wsalesky SPEAR aggregation pages are currently incorrectly grabbing some name variants. See here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201. The third name variant is actually a name for an anonymous group that happens to include the URI for person/2201. 

In such cases, the name variant applies only to the URI in the ref attribute on the persName element that is the immediate child of the person or personGrp element.

`<div uri="http://syriaca.org/spear/119-29">
<listPerson>
<personGrp>
<persName ref="http://syriaca.org/person/2233">
The nobles of
<persName ref="http://syriaca.org/person/2201">Abgar</persName>
of
<placeName ref="http://syriaca.org/place/78">Edessa</placeName>`

Thanks Winona

**Comment by dlschwartz** [comment]
That code didn't render very well in the issue. See here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/119-29/tei

**Comment by wsalesky** [comment]
So which names do you expect to see here?

**Comment by dlschwartz** [comment]
The third example, "The nobles of Abgar....", appearing here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201 
should not appear as a name variant for Abgar VIII. 

Rather, this name variant should only appear as a name variant here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2233

I think the app is considering any name variant factoid to be a name variant of any URI appearing inside the persName element. Instead, it should consider the name variant factoid to be a name variant only for the immediate child of the person or personGrp element. 

Does that help?
