### ISSUE TITLE
Factoid advance button

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1018]
@wsalesky Would it be possible to add a factoid advance button for SPEAR like we have on dev for advancing from one URI to the next? It would be very helpful to have this here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/796-1

For editing purposes, I would like to be able to click through all of the factoids in a single document to ensure they are visualizing properly. It will also allow some editing of the data in html instead of doing all of it in TEI.

Thanks

**Comment by wsalesky** [comment]
Okay. You have to use the short version of the URL, we should probably discuss short URLs for SPEAR in general, for now you can use this pattern for factoids: 

http://wwwb.library.vanderbilt.edu/spear/119-8

**Comment by dlschwartz** [comment]
Thanks!
