### ISSUE TITLE
Wording on relations in keyword module

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1019]
Please change subject to keyword and record to keyword and refers to encompasses.

Religion encompasses 134 keywords.

This keyword has broader match with 1 keyword.

**Comment by wsalesky** [comment]
@nathangibson were you going to change the text in the ODD file? Or should I make a special case for keywords? 

> Religion encompasses 134 keywords.

**Comment by nathangibson** [comment]
@wsalesky Can you remind me, where would I make this change? I believe this is just the passive of the skos:broadMatch relation, right? So do we need different glosses for active and passive?
