### ISSUE TITLE
Missing links on factoid pages

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1026]
It would be great if we could include links to places and persons on individual factoid pages. For example,

Links appear here in the events box at the bottom:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/place/18

When I go the the factoid page is get the factoid without the links:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/119-531

Thanks.

**Comment by wsalesky** [comment]
You mean links within the text of the factoid?

**Comment by dlschwartz** [comment]
Yes. In the first link above, if you scroll down to the events box and look at the text for the event, you get links to Aleppo, Antioch, etc. in the text for the event.

However, when you go to the factoid page (second link above), those links do not show up.

Does that help explain it?
