### ISSUE TITLE
Choice with dates in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1027]
I'm not sure why there is a difference between these two factoids and how they display the two dating systems. They encoding looks identical to me

Compare: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/119-531
and
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/119-542

Note also that the second example that shows up strangely on the factoid page, shows up fine here:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/place/18

**Comment by wsalesky** [comment]
119-542 is trying (unsuccessfully to output the tei:relation element in a sentence. ) I will need to revisit the logic for how these work.

**Comment by wsalesky** [comment]
I'm not sure what this should look like in English:

```
<listRelation>
<relation ref="syriaca:CloseConnection" ana="event" mutual="http://syriaca.org/spear/119-542 http://syriaca.org/spear/119-424"/>
</listRelation>
</listEvent>
```

What do you think @dlschwartz ?

**Comment by dlschwartz** [comment]
We encode for two different types of relationships in event factoids. The English rendering of these can be found in column E here: https://docs.google.com/spreadsheets/d/1aDICk8lrQ7cospr2yVlMYLXavMbaTDxbgr1GDrqfWDw/edit#gid=2112895728. Thanks Winona.

**Comment by wsalesky** [comment]
How do you want the relationship to look on this page: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/119-542

**Relationship:**  This relationship is used to indicate that two or more event factoids refer to closely related events such as meaningful close proximity, cause and effect, part to whole, etc. Related: http://syriaca.org/spear/119-542 and  http://syriaca.org/spear/119-424

Or (the text of the factoids? Maybe with links to each actual factoid)
**Relationship:**  This relationship is used to indicate that two or more event factoids refer to closely related events such as meaningful close proximity, cause and effect, part to whole, etc.  In May A. D. 540 ( Iyār A. Gr. 851 ) Chosroes broke the peace and invaded Roman territory . He laid waste Shura , Aleppo , and Antioch  and Male

Or: 
**Relationship:**  This relationship is used to indicate that two or more event factoids refer to closely related events such as meaningful close proximity, cause and effect, part to whole, etc. 

-  In May A. D. 540 ( Iyār A. Gr. 851 ) Chosroes broke the peace and invaded Roman territory . He laid waste Shura , Aleppo , and Antioch 
- Male


Or something else.  Suggestions welcome?

Currently we try to make a sentence, which is not working so well. I think I need to overhaul the code.

**Comment by dlschwartz** [comment]
How about this -- 
"Relationship: Factoid http://syriaca.org/spear/119-542 and factoid http://syriaca.org/spear/119-424 deal with closely related events."

On the individual factoid pages I think this should be sufficient as the user will have the option to click through to the other event factoid. Through the event graph the user will also be able to see additional connections.

**Comment by dlschwartz** [comment]
I just re-read this. I guess the sentence approach is not working, sorry. Give me just a minute.

**Comment by wsalesky** [comment]
Actually I think what you proposed will work, and will speed things up as well. 
Let me implement it and then you can see what you think.

**Comment by dlschwartz** [comment]
OK, great. Alternately, we could try
"SPEAR contains two or more factoids dealing with a closely related event: http://syriaca.org/spear/119-542 and http://syriaca.org/spear/119-424"

And for the sameAs relationship
"SPEAR contains two or more factoids dealing with the same event: http://syriaca.org/spear/119-542 and http://syriaca.org/spear/119-424"

**Comment by dlschwartz** [comment]
Alternately, we could give only the passive attribute
"SPEAR contains at least one additional factoid dealing with a related event: http://syriaca.org/spear/119-424"

And for the sameAs relationship
"SPEAR contains at least one additional factoid dealing with the same event: http://syriaca.org/spear/119-424"

**Comment by wsalesky** [comment]
Okay, I have made some adjustments. There are  some other display issues I noticed in SPEAR that I will try to address in the next few days as well, such as empty names: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/119-241

Let me know what you think of the current relationship output.

**Comment by dlschwartz** [comment]
Actually Winona, I just recently realized that some sex factoids do not have notes that they should have. I need to put those in.

**Comment by dlschwartz** [comment]
And I think the relationship factoid page looks good. Thanks.
