### ISSUE TITLE
Move NHSL landing page to production

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1028]
Would like http://wwwb.library.vanderbilt.edu/exist/apps/srophe/nhsl/index.html to show on production, except that "Biblical Works" should *not* link anywhere and should be titled "Biblical Works (forthcoming)".

We are not ready to push data from non-BHSE works to production. 

You can mention here any issues with data headers or otherwise that need to be fixed so that search, browse, etc. still work on NHSL when we do this. 

Thanks!

**Comment by wsalesky** [comment]
Done.

**Comment by nathangibson** [comment]
Looks great!
