### ISSUE TITLE
Navigation Menu and Sliders Changes

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1029]
Please revise the "publications" drop down menu in the following way:

Change the order and introduce indentations:

Gazetteer
SBD
-Authors
-Qadishe
NHSL
-BHSE
-Bible
MSS
Taxonomy
Gateway to the Saints
SPEAR
Works Cited
Documentation

**Comment by davidamichelson** [comment]
For the main slider at www.syriaca.org/index, list only main modules and in this order:
Gazetteer (Places), SBD (Persons), NHSL (Works), MSS (Manuscripts), SPEAR (Factoids), Works Cited (Citations) [Note some of these labels have changed, and some modules are removed]

Eventually (but not by the 23rd): Please add the following to the main slider:
Taxonomy (Keywords), Gateway to the Saints (Hagiographica)


Eventually (but not by the 23rd): Please add a slider to syriaca.org/persons/index.html

This slider should have SBD (All Persons), Authors (Authors), Qadishe (Saints)

**Comment by davidamichelson** [comment]
In the sliders, please revise the label so the pop up label for the module becomes a live link (for example The Syriac Gazeetter is...)

**Comment by wsalesky** [comment]
Updated on dev. Should I move the new index page and menu to production?

**Comment by davidamichelson** [comment]
Will that be easy to merge? It may not be since it is not identical (ie there is no Taxonomy or Spear). Dev is probably fine for now unless it is easy. 

On the other had if you could make the SBD index page slider on dev that woudl be great.

**Comment by davidamichelson** [comment]
Lastly, just a note to discuss having a front and center search box below the slider. Probably not, but we should discuss.

**Comment by wsalesky** [comment]
I think this has been completed. Reopen if I have missed anything.
