### ISSUE TITLE
Anonymous 2234 in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1030]
@wsalesky Most of the anonymous and anonymi show up here in browse: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=persons&alpha-filter=Anonymous

This is exactly where they should show up. However, Anonymous 2234 does not show up there but instead shows up under the As.

I can't figure out why but I hope this is an easy one. Thanks!

**Comment by wsalesky** [comment]
It is misspelled in the title. 
Anonmyous

See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2234/tei

**Comment by dlschwartz** [comment]
I should have caught that! Sorry and thanks.

**Comment by wsalesky** [comment]
That is okay, I didn't notice at first either!
