### ISSUE TITLE
Connecting data to the wrong persons

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1031]
@wsalesky This issue is related to #1017 but deals with other types of person data. See occupation here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201 

The second occupation is not an occupation held by Abgar, but rather an occupation held by others that relates to Abgar. 

I think things are sorted out for name variants. The problem is with other types of person data. The factoid only applies directly to the persName ref="URI" that is the immediate child of either the person element or the personGrp element, depending on whether the factoid is for an individual or a group. 

Here is an example:
`<div uri="http://syriaca.org/spear/119-30">
                <listPerson>
                    <personGrp>
                        <persName ref="http://syriaca.org/person/2233"/>
                        <occupation ref="http://syriaca.org/keyword/nobles">
                            <note>These men were the nobles of <persName ref="http://syriaca.org/person/2201"> Abgar </persName>
                                in <placeName ref="http://syriaca.org/place/78"> Edessa
                                </placeName>.
                            </note>
                        </occupation>
                    </personGrp>
                </listPerson>
            </div>
            `
This occupation factoid indicates the occupation of only the persName that is the immediate child of personGrp. If multiple person URIs appear in a note, that constitutes a relationship but does not constitute an assertion that this occupation factoid indicates the occupation of every person whose URI appears. 

Another way to think of this is that the self closing persName element is there to indicate the person to whom the occupation directly applies. There is no text node because it is only there to be read by the computer. Every person factoid (birth, death, citizenship, education, etc.) has this structure with a self-closing element and a person URI (except name variants which we got sorted in #1017). 

I hope my explanation is clear enough Winona. Please let me know if you have any questions. Thank you!

P.S. I haven't found too many of these as most notes only have one person URI. Occupation and education are the places where the problem would be mostly likely to emerge because a descriptive note can easily contain multiple person URIs.

**Comment by wsalesky** [comment]
Fixed
