### ISSUE TITLE
Strange data in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1033]
@wsalesky See here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?fq=;fq-Type:head&view=advanced.

Somehow, this file (https://github.com/srophe/srophe-app-data/blob/dev/data/spear/schema/schemas/odd4odds.odd) seems to have been ingested into SPEAR even though it is in spear/schema/schemas and not in spear/tei.

**Comment by wsalesky** [comment]
I would move the spear schema folder to the app under documentation. Anything in the data app, under the data directory will get indexed by eXist.

**Comment by dlschwartz** [comment]
Ah, very good! I will do that. Should I put in in dev or master?

**Comment by wsalesky** [comment]
Dev please

**Comment by dlschwartz** [comment]
Great, thanks
