### ISSUE TITLE
Error on taxonomy search box

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1034]
When I search for "syrian" in the top-right search in taxonomy (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/taxonomy/browse.html?fq=;fq-Broad%20Match:http://syriaca.org/keyword/ethnicity&view=facets) I get the following error. (Could be just that I'm on a slow connection?)

> Proxy Error
> 
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request GET /exist/apps/srophe/taxonomy/search.html.
> 
> Reason: Error reading from remote server
> 
> Apache/2.2.15 (Red Hat) Server at wwwb.library.vanderbilt.edu Port 80

**Comment by wsalesky** [comment]
Looks like a bad connection on your end. I get results.

**Comment by nathangibson** [comment]
OK, thanks. The weird thing is everything else seems to be working, just slowly on this connection.

**Comment by nathangibson** [comment]
And unfortunately this is the connection people will be on tomorrow :-(

**Comment by wsalesky** [comment]
The advanced browse is probably slower then the categories tab. I will take a look later and see if there is anything I can do to speed it up.

**Comment by nathangibson** [comment]
I think there are still problems. Unfortunately this is really important for the workshop tomorrow. Regardless of which page I'm on, entering something in the top-right search box gives me a 502 error. The advanced search works but doesn't actually display results. E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/taxonomy/search.html?qs=rhetor*&headword=&related-terms= says "2 results" but does not display them.

**Comment by wsalesky** [comment]
I will take a look tonight

**Comment by wsalesky** [comment]
@nathangibson There is a quick fix up on dev right now, so you should at least get some results. I will take a closer look later tonight. Please add any additional bugs to this issue.

**Comment by nathangibson** [comment]
Fantastic! Advanced search is now working correctly. However I get different results for the top-right search box http://wwwb.library.vanderbilt.edu/exist/apps/srophe/taxonomy/search.html?q=rhetor* than for "search anywhere" field in advanced search http://wwwb.library.vanderbilt.edu/exist/apps/srophe/taxonomy/search.html?qs=rhetor*&headword=&related-terms=. The search box gives returns *all* keywords.

**Comment by wsalesky** [comment]
Okay. I think this addresses both of the issues mentioned above.
