### ISSUE TITLE
Editions, etc. for literary traditions

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1036]
When you are available again (i.e., not urgent), can you check out http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9606 ? The edition in the record is showing up in "Sources" but not in "Editions"? It may be that we turned off editions for literary traditions, but we have now come up with a use case for them (and the other types of bibls that can be cited in a work record). Thanks!

**Comment by wsalesky** [comment]
Fixed.

**Comment by nathangibson** [comment]
Thanks!
