### ISSUE TITLE
editors.xml unavailability kills dev server records

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1037]
When I try to load records on the dev server, I can't because it can't access documentation/editors.xml on the prod server. 

At the moment this is happening on all records I try to load, e.g., http://wwwb.library.vanderbilt.edu/person/13

Can we set up a fallback to the dev server editors.xml or some way to keep this from stopping the record display? Thanks!

Error:
```
exerr:ERROR XSL transform reported error: Document has been marked not available: http://syriaca.org/documentation/editors.xml [at line 107, column 33, source: /db/apps/srophe/modules/lib/global.xqm]
In function:
	global:tei2html(node()*) [203:25:/db/apps/srophe/modules/lib/global.xqm]
	app:display-work(node(), map) [217:18:/db/apps/srophe/modules/app.xql]
...
```

**Comment by wsalesky** [comment]
Fixed.
