### ISSUE TITLE
More Information menu items are no longer easily accessible from anywhere

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1040]
After we redid the home page the following menu items got buried:
see here: http://syriaca.org/project-team.html

More Information
(see links below in the HTML)
What is Syriac?
Project Overview
Project Team
Project Partners
Media Releases
Support Our Work
Contact Us

Should we add these items to the menu found under "Editorial Documentation:
http://syriaca.org/documentation/index.html

Could I please delegate that to you @wsalesky and @dlschwartz to work out please?

```
            <ul class="nav nav-tabs nav-stacked">
                <li>
                    <a href="about-syriac.html">What is Syriac?</a>
                </li>
                <li>
                    <a href="about-srophe.html">Project Overview</a>
                </li>
                <li>
                    <a href="project-team.html">Project Team</a>
                </li>
                <li>
                    <a href="project-partners.html">Project Partners</a>
                </li>
                <li>
                    <a href="media-releases.html">Media Releases</a>
                </li>
                <li>
                    <a href="http://vu.edu/syriac">Support Our Work</a>
                </li>
                <li>
                    <a href="contact-us.html">Contact Us</a>
                </li>
            </ul>
```

**Comment by davidamichelson** [comment]
If we do integrate this with documentation we may wish to change the sidemenu onthose pages to the documentation side menu for consistency of navigation

**Comment by wsalesky** [comment]
@davidamichelson  @dlschwartz  What about adding an 'About' dropdown next to the 'Publications' dropdown in the main nav?

**Comment by davidamichelson** [comment]
I like that. But I also think integrating those pages into the wiki makes
sense in terms of making them easy to update. Could we some how have an
about column?

**Comment by wsalesky** [comment]
@davidamichelson Do you want to add them to the wiki, or just add them as an additional column/menu on the documentation pages?

**Comment by davidamichelson** [comment]
Maybe just add them to the wiki?

**Comment by wsalesky** [comment]
@dlschwartz 
I added an 'About' dropdown to the main pages and added an additional menu to the documentation pages. 

I think this works, but let me know what you think.

**Comment by dlschwartz** [comment]
I like the drop down. I think it's important to front this. There may not be much you can do, but I did notice that things got a bit wonky when I reduced the size of my browser.
![about](https://user-images.githubusercontent.com/4984270/27440367-1f636f48-5730-11e7-9eba-23e89c729267.PNG)
This isn't a huge deal but maybe you can tweak things a bit. We should get broader input on Tuesday but I'm in support.

**Comment by wsalesky** [comment]
What browser are you using? Firefox?

**Comment by dlschwartz** [comment]
I'm in Chrome on a PC.

**Comment by wsalesky** [comment]
What happens when you go a little smaller? (Can you post a screen shot?)

**Comment by dlschwartz** [comment]
This is an image from slightly larger than the earlier:
![about2](https://user-images.githubusercontent.com/4984270/27441874-5e82849e-5734-11e7-9f47-091b396c3ad0.PNG)

And this is an image from smaller than the earlier image. Note that there is no way to get to the label "About Syriaca.org". The bar on the far right is scrolled all the way up.
![about3](https://user-images.githubusercontent.com/4984270/27441976-9d9226a8-5734-11e7-9217-4382188a8294.PNG)

**Comment by wsalesky** [comment]
Thanks! Those menu items should be pushed into the little 'hamburger menu' on the smaller sizes. So this is clearly a bug. I will take a another look.

**Comment by dlschwartz** [comment]
Great. One more thing. Should we move the "Documentation" link from the "Publications" dropdown and place it into the "About" dropdown?

**Comment by wsalesky** [comment]
I like that idea. Should I go ahead, or should we check in with @davidamichelson  at the next meeting?

**Comment by dlschwartz** [comment]
Since we're just on production at the moment, let's go ahead and do it so that everyone can look at it. It really isn't a "publication" anyway. I think it would be much preferable to have it in "about". Am I right that it wouldn't take a lot of work to move it back if need be?

**Comment by wsalesky** [comment]
Yes, it is easy, I will make the change.

**Comment by wsalesky** [comment]
Done.

**Comment by wsalesky** [comment]
Resolved and moved to master.
