### ISSUE TITLE
bibl cites manuscript prose description

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1042]
In http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9515 Print Catalogue 2 (#bib9515-14) it says "(Print Catalogue based on Print Catalogues 2.)" In other words it cites itself. 

The underlying relationship is `<relation active="#bib9515-11" ref="lawd:hasCitation" passive="#bib9515-14"/>` (https://github.com/srophe/srophe-app-data/blob/dev/data/works/tei/nhsl/tei/9515.xml#L237). 

The RDF verb we are using requires that the cited item be the subject and the item containing the citation be the object -- so the active and passive here are reverse of our normal relationships. 

Can we change the prose so that it says "Print Catalogue cites Manuscript 3" ? The abstract version of this would be: [Passive item type] cites [Active item type] [Active item number]. The logic here could be that if `@passive` refers to the containing bibl, then the other item mentioned will be found in `@active` .

**Comment by wsalesky** [comment]
@nathangibson How would you like to handle a relationship that cites a full uri? 
See the 1st Print Catalogue on the above record. TEI looks like this: 

```
<listRelation>
<relation active="http://syriaca.org/manuscript/124" ref="lawd:hasCitation" passive="#bib9515-6"/>
</listRelation>
```
Can I just print out the URL or do you want a full citation from that URL?

**Comment by nathangibson** [comment]
Sorry I was slow getting back to you on this. It is possible to grab the reference to the manuscript list item whose bibl pointer matches this? 

Thus "(Print Catalogue cites http://syriaca.org/manuscript/124.)" would instead be be "(Print Catalogue cites Manuscript 2.)" [Example from http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9515]

The xpath for this bibl would be //bibl[@type='syriaca:Manuscript' and ptr/@target='http://syriaca.org/manuscript/124']

**Comment by wsalesky** [comment]
Looks like there are two that reference it, should they both be listed?
 
```
<bibl type="syriaca:Manuscript" xml:id="bib9515-3" source="#bib9515-7">
<title type="shelfmark">
Sinai, St. Catherine Monastery, Syriac 30 (Syriac Sinaiticus)
</title>
<ptr target="http://syriaca.org/manuscript/124"/>
<date notBefore="0250" notAfter="0550">4th/5th cent.</date>
<listRelation>
<relation active="#bib9515-3" ref="lawd:embodies" passive="http://syriaca.org/work/9515"/>
</listRelation>
<note>
Includes (as palimpsest) Lk 1:1–16, 38–5:28; 6:12–24:52
</note>
</bibl>
<bibl type="syriaca:Manuscript" xml:id="bib9515-4" source="#bib9515-6">
<title type="shelfmark">
London, British Library, Add MS 14451 (Codex Curetonianus)
</title>
<biblScope unit="folio" from="53a" to="88a">Foll. 53a-88a</biblScope>
<ptr target="http://syriaca.org/manuscript/124"/>
<date notBefore="0425" notAfter="0525">probably latter half of 5th cent.</date>
<listRelation>
<relation active="#bib9515-4" ref="lawd:embodies" passive="http://syriaca.org/work/9515"/>
</listRelation>
<note>
Contains Lk 2:48–3:16; 7:33–15:21; 17:24–24:44. From 24:44-end is taken from
<bibl>
Luke (Peshitta Version)
<ptr target="http://syriaca.org/work/74"/>
</bibl>
</note>
</bibl>
```

**Comment by nathangibson** [comment]
This was a mistake. I’ve just removed one of the references.

**Comment by wsalesky** [comment]
Okay. I think I have it working correctly now.
