### ISSUE TITLE
NHSL landing page div margin causes horizontal scroll

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1044]
https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/nhsl/index.html#L109 Not sure why the margin is needed on this page and not on others but it is causing the page to scroll horizontally when the window is approx. 1000 to 1350 px wide (FF 53.0.3 on Mac 10.10.5). Hard to capture with a screenshot but I'll try. 

<img width="580" alt="screenshot_6_15_17__2_54_pm" src="https://user-images.githubusercontent.com/3083452/27182371-34a31020-51db-11e7-9936-edae60596b4e.png">

**Comment by wsalesky** [comment]
I removed it. If we need some additional space, we can add padding, but I think it is fine without. .

**Comment by nathangibson** [comment]
Thanks!
