### ISSUE TITLE
Comma separate multiple glosses in a single language in Taxonomy module

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1045]
@wsalesky See http://wwwb.library.vanderbilt.edu/exist/apps/srophe/keyword/anchorites. When we have multiple English (or any other language) glosses they each appear as separate lines. Can we group these by language and comma separate them? Right now this is encoded as follows:
` <gloss xml:lang="en">
               <term>eremites</term>
            </gloss>
            <gloss xml:lang="en">
               <term>hermits</term>
            </gloss>`
Please let me know if I should make changes here, such as putting multiple term elements inside a single gloss xml:lang="x" element.

Thanks Winona.

**Comment by wsalesky** [comment]
Done.

**Comment by dlschwartz** [comment]
Brilliant! Thanks.
