### ISSUE TITLE
blank result in SBD search

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1046]
Search for http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=nazi* result 9 doesn't have any text or URI. Not sure if this is a data or app issue.

<img width="419" alt="syriaca_org__the_syriac_reference_portal" src="https://user-images.githubusercontent.com/3083452/27341768-7936db0c-55de-11e7-95b6-70c3588eddbf.png">

**Comment by wsalesky** [comment]
I think it is a data problem, this is the record that is returned: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2783

The idno in the body uses type='URL' not type='URI'
See: https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/2783.xml#L175

Perhaps the code needs to be a little more flexible also.

**Comment by nathangibson** [comment]
Thanks, I've fixed the record.
