### ISSUE TITLE
blank search results

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1047]
This search http://wwwb.library.vanderbilt.edu/exist/apps/srophe/nhsl/search.html?q=Aristotelis+Categoriae+et+Liber says "5 matches for Keyword" but doesn't return any.

**Comment by wsalesky** [comment]
This is a hierarchical browse issue. I was waiting for RDF resolutions.

**Comment by wsalesky** [comment]
RE: #971

**Comment by nathangibson** [comment]
I'll close it in that case?
