### ISSUE TITLE
Can we move abbreviations to identity box?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1048]
Please move Abbreviations `/TEI/text/body/bibl/title[@type='abbreviation']` to identity box between Abstract and Reference Numbers. Thanks!

**Comment by wsalesky** [comment]
@nathangibson 
I changed the code, can you give me a record to spot check this change on?

**Comment by wsalesky** [comment]
@nathangibson never mind. I found one.

**Comment by nathangibson** [comment]
Great, thanks!
