### ISSUE TITLE
Change literary tradition skos:broadMatch visualization wording

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1050]
As hard as we tried to generalize the wording for composite URI skos:broadMatch relations, we think it's just too vague for literary traditions in NHSL (`/TEI/text/body/bibl[@type='syriaca:literaryTradition']`). 

So could we please change the wording (for works only)? I like the old wording: "This tradition comprises at least 4 branches." @davidamichelson Would you agree or do you have something different to suggest?

Example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9646 
Currently says: "Matthew (literary tradition) refers to 4 works."

Thanks!

**Comment by nathangibson** [comment]
Please also change the header at the top of the popup window to match. Currently says "Luke (literary tradition) contains works" http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9648.

**Comment by wsalesky** [comment]
Fixed.

**Comment by nathangibson** [comment]
Thanks!
