### ISSUE TITLE
Popup not loading for literary tradition branches

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1052]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9648 doesn't load when you click "See all 6 records."

**Comment by wsalesky** [comment]
@nathangibson  I only see 5 records and no link to the popup? And it does work for 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9501

Are you still having this issue?  Maybe I can get a screen shot?

**Comment by wsalesky** [comment]
Fixed. (You may need to do a hard refresh to see the change.)

**Comment by nathangibson** [comment]
Oops, I probably changed one of the relations and it now has 5 instead of 6. Anyway, I'll close this for now.
