### ISSUE TITLE
BQG landing page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1055]
Hi W,

Here is the list of editors for the landing page.

Dr. Haya Al Thani (Qatar University)
Dr. Saif al-Murikhi (Qatar University)
Dr. Abdulrahim Abu-Husayn (American University of Beirut)
Dr. George Kiraz (Beth Mardutho: The Syriac Institute)
Dr. Mario Kozah (American University of Beirut)
Dr. David Michelson (Vanderbilt University)
Dr. Thomas Carlson (Oklahoma State University)

Also, just an FYI, I think we should aim at Aug 15 rather than Aug 1 for this.

Thanks!

**Comment by davidamichelson** [comment]
Also here is draft text for the paragraph on the landing page:

Beth Qaṭraye, Syriac for “region of the Qataris”, is a term found in Syriac literature referring to
the region of North-East Arabia including Qatar and Bahrain from the fourth to the ninth
centuries. Beth Qaṭraye was an important cultural, linguistic and religious crossroads in the pre-
Islamic and early Islamic period, when it produced one of the most widely translated Syriac
authors of all time (Isaac of Nineveh, called after his bishopric, who is also known as Isaac
Qaṭraya or “the Qatari”). A number of other important Syriac authors also came from Beth
Qaṭraye in this period, and scholarship has so far only focused on these Syriac authors and their
writings rather than other aspects of Beth Qaṭraye. The objective of _The Beth Qaṭraye Gazetteer_  is to collect and analyze information on the pre-Islamic and early Islamic historical geography and toponyms of the Beth Qaṭraye region.

**Comment by davidamichelson** [comment]
One more edit, everywhere that the word Beth Qaṭraye appears needs the unicode small dot under the t in Qaṭraye please.

**Comment by tacarlson** [comment]
I almost have the data in order, but I will be out of the office 7/29-8/5

**Comment by davidamichelson** [comment]
Wow! Great work! One thing that Winona will need us to do is make a series
stmt specific to BQG. Would you like me to make that?

**Comment by davidamichelson** [comment]
Right, sorry too vague, I am happy to draft that, but will need to do it
next week.

You can see an example of how we mark records that appear in multiple
volumes with a series/Stmt in person/13.

**Comment by wsalesky** [comment]
stale issue
