### ISSUE TITLE
Corrections/additions button down on dev

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1064]
One of our contributors has been getting errors on the corrections/additions button (e.g., for http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1469). I'm getting the same message "ERROR for site owner:
Invalid domain for site key"

and then "please try again" when I try to submit.

Production seems to be working I think.

**Comment by wsalesky** [comment]
@davidamichelson I think you have the recaptcha information, can you check our settings and see if you can add the dev server to the same key?

**Comment by wsalesky** [comment]
stale issue.
