### ISSUE TITLE
Qadishe volume is not filtering out non-saints in Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1065]

**Comment by wsalesky** [comment]
@davidamichelson Production or Dev? Can you add a link to the issue so I can easily see where the problem is?

**Comment by jsaintlauren** [comment]
On the Production server... for example see this:

http://www.syriaca.org/q/browse.html?lang=&alpha-filter=M

**Comment by wsalesky** [comment]
Okay, thanks!

**Comment by wsalesky** [comment]
Resolved. Thanks.
