### ISSUE TITLE
Syriac (?) characters not displaying in NHSL title

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1069]
At http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9726 I'm seeing some unicode boxes in one of the titles. It looks like all the Syriac characters are there, so I'm not sure why the boxes are appearing. 
Is this an issue with my computer, the data, or the srophe app?
<img width="489" alt="categories__aristotle___anonymous_version" src="https://user-images.githubusercontent.com/3083452/30819157-2806aaa0-a21e-11e7-834b-f74416721131.png">

**Comment by wsalesky** [comment]
It looks like it is in the data, you can see it by opening the file in oXygen. 
<img width="894" alt="screen shot 2017-09-25 at 12 26 08 pm" src="https://user-images.githubusercontent.com/1168206/30819499-d9152ae2-a1ec-11e7-8ba8-66a8b5f4829d.png">

I can delete them, but perhaps you should do it, just to make sure there isn't any missing data represented by the boxes.

**Comment by nathangibson** [comment]
Thanks, I've fixed it now.

**Comment by wsalesky** [comment]
Thanks!
