### ISSUE TITLE
Change to RDF Serialization

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1091]
In event factoids, get rid this serialization forschema:location:
//div/@uri | schema:location | //div/listEvent/event/desc//placeName/@ref | n/a

**Comment by davidamichelson** [comment]
New serialization for all modules including SPEAR and Gazetteer etc.

all | //div/@uri | dcterms:hasFormat | @uri/html, @uri/tei, @uri/ttl, @uri/RDF

**Comment by davidamichelson** [comment]
Two new serialization for sources of the RDF and factoid:

all | //div/@uri | dcterms:isPartOf | rdf:resource="http://syriaca.org/spear/URI" |   |   | derived from teiHeader//publicationStmt/idno@type="URI"(with /tei removed)


all | //div/@uri | dcterms:source | rdf:resource="http://syriaca.org/work/URI" |   |   | (may be multiple) derived from teiHeader//sourceDesc ALL URIs with http://syriaca.org/work/URI

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz 
For the new sources (the above comment.)
Do I include the work URIs in the relation element? Both? Just passive?
RE: https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/John_Ephesus_Lives_26.xml#L91

Thanks!

**Comment by dlschwartz** [comment]
@wsalesky We only want to grab this xpath: //sourceDesc/p/title/@ref. I can ensure that this is in every sourceDesc, regardless of whether or not there is a containing relationship. The goal is ultimately to remove the listRelations from the sourceDesc: https://github.com/srophe/srophe-app-data/issues/730#issuecomment-363198171. I'll do that once we have everything we need in the works RDF. Thanks.

**Comment by wsalesky** [comment]
Thanks for the clarification.

**Comment by wsalesky** [comment]
@dlschwartz This line causes trouble when outputting RDF from SPEAR:
https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/John_Ephesus_Lives_55.xml#L304

**Comment by dlschwartz** [comment]
@wsalesky This is an editing problem as in, I haven't yet finished editing the workshop contributions from last spring. In a way, all of SPEAR is draft data as I keep tweaking the data model. However, some of the drafts are more drafty than others.  I know there are a few places where we don't have URIs where they are required, etc. Perhaps your transform can handle when data is missing but not when we have something like this, an xml syntax error. I have fixed and pushed this particular problem. Please let me know if more pop up. Thanks.

**Comment by wsalesky** [comment]
It can not handle the invalid namespaces. You can just comment that line out and it will run fine, and the data will still be there, holding a place. Thanks for the fix! Looks like everything else is running okay.

**Comment by dlschwartz** [comment]
Got it. I've actually added a relationship to fix this. It's one we needed.

**Comment by wsalesky** [comment]
Even better!

**Comment by wsalesky** [comment]
I think this can be closed.
