### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1094]
@wsalesky, on all modules of dev except SPEAR and MSS I get the following pop-up any time I try to access a record: "Cannot contact reCAPTCHA. Check your connection and try again." I just have to click "OK" to bypass to the record but it would be nice if we could fix this. Thank you.

**Comment by wsalesky** [comment]
@davidamichelson The dev server needs to be registered with reCAPTCHA, I wonder if the address is  wrong and that is why we are getting the error?

**Comment by davidamichelson** [comment]
Done
