### ISSUE TITLE
"See all records" not working

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1095]
@wsalesky The "See all records" button in NHSL for showing containing works does not seem to be working. I've checked work/10541, work/10543, and work/9501. The first two are new works and I thought it might be a problem with the data but I couldn't see anything off. I checked 9501 because it used to work. Turns out it no longer does. 

I was about to submit this when I noticed another (related?) problem. The page (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9501) lists three containing works before giving the option to "See all records". The titles of the three works that appear are correct. However, they all have the URI of the containing record attached to them. The incorrect URI appears both in the URI line of the abbreviated record and when you use the "Copies record title & URI to clipboard" button.

Thanks

**Comment by wsalesky** [comment]
@dlschwartz interesting (by which I mean, oh no!) I will take a look, this is most likely related to the dct: namespace switch.

**Comment by nathangibson** [comment]
For me, the "See all" works on work/9501 ... if you give it about 15 seconds to load! And once it loads the URIs in that popup look correct.

**Comment by dlschwartz** [comment]
Weird, the "See all" on work/9501 now works and in that long list shows the correct URIs. However, for the three preview works that appear on the main page of work/9501 above the "See all" button, the containing work URI (9501) appears on each of those.

**Comment by wsalesky** [comment]
Okay, this should be displaying correctly and also should be faster. Let me know if you are still experiencing slow load times.

**Comment by dlschwartz** [comment]
Looks great! Thanks.
