### ISSUE TITLE
abstract in search results

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1096]
@wsalesky and @nathangibson I'm not sure what's causing this, data or app, so I'm just writing this up here. A search for "severus letters" turns up his letters (which is great!) but some of the abstracts appear in the results and some only get the first letter of the abstract. I checked the data and can't see a difference in how the encoding of the abstract is structured, so I don't think it's a data problem but I'm not sure.

Here's the search I performed: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/nhsl/search.html?q=severus+letters&start=1

Thanks.

**Comment by wsalesky** [comment]
@dlschwartz @nathangibson looks like an app bug to me. Due to nested content. Should be easy to resolve.

**Comment by wsalesky** [comment]
This seems to have been resolved with this commit : c9ab23544724aed58e199a5d4f88e73e672cdfa8
