### ISSUE TITLE
Replace IDHMC logo with CoDHR logo

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1101]
We should change all IDHMC logos on landing pages to CoDHR logos. It's not pressing though. Thanks.
![codhr-logo](https://user-images.githubusercontent.com/4984270/39130831-ad4fe38e-46d3-11e8-980e-49ac5f0d0143.png)

**Comment by dlschwartz** [comment]
I forgot to add that the link should also change, throughout Syriaca.org but also on e-GEDSH. It's now http://codhr.tamu.edu. Thanks.

**Comment by wsalesky** [comment]
Added to e-GEDSH, Syriac Corpus, Syriaca.org
