### ISSUE TITLE
How to encode personGrp

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#1103]
@dlschwartz We need a way to encode personGrp to distinguish them from person factoids in SPEAR RDF. Any thoughts?

**Comment by dlschwartz** [comment]
@wsalesky foaf:group should work fine: http://xmlns.com/foaf/spec/#term_Group. Do you have an idea of how to implement it? I'd have to think about that. (I'm in my LOD course right now, discussing databases actually.)

**Comment by wsalesky** [comment]
I was thinking of using rdf:type. An example: 
`http://syriaca.org/spear/119-13 rdf:type foaf:group`
in addition to 
`http://syriaca.org/spear/119-13 rdf:type syriaca:personFactoid`

**Comment by dlschwartz** [comment]
In that context, would it be best to use syriaca:personGrpFactoid? Am I right that what you write above would basically assert that the factoid is a group then what we want to assert is that it is a factoid that contains data about a personGrp?

**Comment by wsalesky** [comment]
Hum, yes, that might be right. And/Or perhaps we need to add the foaf:group to the actual person factoid instead?

```
http://syriaca.org/person/2210 foaf:name 'Workers in the government of Edessa in November A. D. 201 Teshri II A. Gr. 513'

http://syriaca.org/person/2210 rdf:type foaf:group

```

**Comment by dlschwartz** [comment]
I think that would be a good approach. Would we then want to add this where relevant

http://syriaca.org/person/# rdf:type foaf:person

**Comment by wsalesky** [comment]
currently the have lawd:Person should we change it?

**Comment by dlschwartz** [comment]
Oh that's right. No, if we have lawd:Person we should keep that.

**Comment by wsalesky** [comment]
okay, so I will just add the `rdf:type foaf:group` Now I just have to figure out how to query that correctly.
