### ISSUE TITLE
Dates display in SPEAR events results

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1105]
@wsalesky In the events results display in SPEAR, we get Gregorian and non-Gregorian dates appearing side-by-side. It would be great to tweak how these display. We should always display the text node of date calendar="Gregorian" as plain text and any other date should appear next to it in parentheses. Would it be possible to have this in the results section? Right now it appears correctly on the factoid page (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/119-28) but not the results page. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz The results page is directly from the RDF, so I will need to change how the RDF is generated and then rerun the page. I will do that after our meeting, shouldn't be a problem.

**Comment by wsalesky** [comment]
Fixed. (May need to rerun RDF on dev when it is back up. )
