### ISSUE TITLE
Dates in SPEAR timeline

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1106]
@wsalesky It looks like we are catching all dates in the SPEAR timeline, regardless of calendar. When I look at the timeline bar on the events browse page, the highest date is 830. The only dates in SPEAR currently that go that high are dates according to the Seleucid calendar. I have been working on the schema for SPEAR in hopes of doing a bit of editing on the SPEAR documents over the next week or so. I've realized that there is an inconsistency currently allowed in how non-Gregorian dates are encoded. I'm working to fix that asap. However, the solution I implement will ensure that only the @when attributes on date elements with calendar="Gregorian" should be calculated in the timeline. My fix will ensure that all date elements require a @calendar attribute and that whenever we have a date element there will be a calendar="Gregorian". In the meantime, I think you can tweak the timeline to grab only dates where calendar="Gregorian". Thanks.

**Comment by wsalesky** [comment]
@dlschwartz okay. This is another case of RDF data tweaking.

**Comment by wsalesky** [comment]
@dlschwartz I think this is fixed. (dev is down but it looks good locally. )
