### ISSUE TITLE
LOD Box to SPEAR factoid pages

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1108]
@wsalesky Please add the LOD box to SPEAR factoid pages. Thank you.

**Comment by wsalesky** [comment]
@dlschwartz Added to the factoid pages: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/3020-16

Do you also want it on the aggrigate pages? 
example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/430

**Comment by dlschwartz** [comment]
@wsalesky Yes! Let's put it there too. Great idea. Thanks.
