### ISSUE TITLE
Factoid pages from Chron. Ed. not displaying

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1109]
@wsalesky Factoid pages from the Chronicle are not displaying. Might this be a problem with the links to the Corpus? A quick spot check of the other works suggest they're fine. Thanks.
![chonedevent](https://user-images.githubusercontent.com/4984270/43743590-12ec76ec-999c-11e8-8c60-b59425495812.JPG)
![chonedperson](https://user-images.githubusercontent.com/4984270/43743600-1b3e9500-999c-11e8-9f52-bf8fbd84ba3b.JPG)

**Comment by wsalesky** [comment]
@dlschwartz I think you just happened to hit the server when it was being restored. Should work now.

**Comment by dlschwartz** [comment]
@wsalesky Uh oh, now I get a different problem. The data isn't showing up at all.
![spear](https://user-images.githubusercontent.com/4984270/43781064-adedbb44-9a21-11e8-9a83-b16df7743f6d.JPG)

**Comment by wsalesky** [comment]
@dlschwartz Try now
