### ISSUE TITLE
work URIs in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1112]
@wsalesky The first bibl in this factoid is missing data because it points to a work URI instead of a bibl URI. The work URIs in SPEAR are place holders until we can get a proper URN and a text to point the URN to. We should simply drop these from the display and display only bibl elements that contain a bibl URI.

**Comment by wsalesky** [comment]
@dlschwartz link to record?

**Comment by dlschwartz** [comment]
@wsalesky Ah, how did I forget my link? 

Here's the xml: https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/John_Ephesus_Lives_56.xml#L434

Here's the current display: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/847-17

In some instances there are multiple bibl URIs but every factoid should have at least one bibl URI.

**Comment by wsalesky** [comment]
@dlschwartz can you screen shot and highlight the problem area? My brain needs some extra help today.

**Comment by dlschwartz** [comment]
The circled bit is a display of the citedRange but not the work. Compare image below with the tei link above. Without a URN, it doesn't make sense to display the work or the cited range. I think we should simply not display any bibl element that doesn't have a syriaca.org/bibl URI. 
![workuri](https://user-images.githubusercontent.com/4984270/44409827-ba705900-a528-11e8-83d6-0812a2fd5efe.JPG)

**Comment by wsalesky** [comment]
I see. I will take care of it.

**Comment by wsalesky** [comment]
@dlschwartz This one is fixed.
