### ISSUE TITLE
Legacy data (?) in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1113]
@wsalesky The first thing I noticed is that the sex element data is still appearing and the trait type="gender" data is not appearing. This is the case even though there are no longer any sex elements in the tei. This appears to be the case only on the browse pages, which suggests a SPARQL problem. If you do a keyword search for female you get many hits.

Then I noticed the following oddity:
I just wanted to look at the Chronicle events to check the pulling in of the Syriac from the Corpus. 
![browsechron](https://user-images.githubusercontent.com/4984270/44349525-d4476880-a462-11e8-90fa-f980340c12d0.JPG)

When I selected "See more", it took me here:
![browsechronselect](https://user-images.githubusercontent.com/4984270/44349594-fb9e3580-a462-11e8-9298-5b29869a4d87.JPG)

However, when I searched for "the Daisan river flooded Edessa", it took me here:
![searchchronevent](https://user-images.githubusercontent.com/4984270/44349653-1d97b800-a463-11e8-9725-c7422026d833.JPG)

Note the different URI numbers. That change was made about three weeks ago: https://github.com/srophe/srophe-app-data/commit/fe8c0b2de1b79127c51740fc6b45e7da77503cfe#diff-6a6705da5bed7bae3566a94792915338. It looks like the new data shows up when accessed through search but that old data is still visible in browse.

**Comment by wsalesky** [comment]
Hum, that seems to indicate a problem with the RDF generation. I think I will need to investigate this tonight.

**Comment by dlschwartz** [comment]
Oh, and I might not be updating the RDF correctly. I select "run" here (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/sparql/update-rdf.html) and it doesn't give me much indication of anything happening. I've selected "run" a handful of times in the last three weeks. Perhaps I've never actually run anything.

**Comment by wsalesky** [comment]
I'm going to work on it tonight, after 8 EST. As for the update rdf, it takes a long time, and on the dev server gets a server timeout message, however, it does continue to run in the background after returning the error. So while not very informative on the dev server it is running. I suspect a combination of RDF generation problems and SPARQL issues. Hopefully I can get it all fixed tonight for you.

**Comment by dlschwartz** [comment]
Okay, thanks Winona!

**Comment by wsalesky** [comment]
@dlschwartz I think this one is fixed as well.
