### ISSUE TITLE
Taxonomy Link

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1114]
@wsalesky The link on the factoid page that would take you to the taxonomy says "The Syriac Gazetteer". Can that read "View entry in A Taxonomy of Syriac Studies"? Thanks.
![taxonomylink](https://user-images.githubusercontent.com/4984270/44418966-79d00a00-a53f-11e8-8123-5d67d9e2dd46.JPG)

**Comment by wsalesky** [comment]
@dlschwartz okay, this one is fixed.

**Comment by dlschwartz** [comment]
@wsalesky One quick thing here, it looks like the link on "A Taxonomy of Syriac Studies" points to production instead of dev. I get a 404 error: Document /db/apps/srophe/keyword/councils/index.html not found

**Comment by wsalesky** [comment]
@dlschwartz  Fixed.
