### ISSUE TITLE
Gender display

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1115]
@wsalesky You've worked some magic on the keywords to have English instead of URIs (not sure if you're pulling from the taxonomy or converting URIs in the app). Can we apply the same procedure to the Gender keywords that we've applied to the Occupation keywords in the image below? Thanks!

![keywords](https://user-images.githubusercontent.com/4984270/44469403-04bb0e00-a5ed-11e8-855b-8a52b050c484.JPG)

**Comment by wsalesky** [comment]
@dlschwartz They are using the taxonomy records, I do not think there are records for the gender URIs. Can you add them? Or should I just display the last part of the URI.

**Comment by dlschwartz** [comment]
@wsalesky Oh of course. I've pushed those to dev but I'm not sure the web hooks grabbed them.

**Comment by wsalesky** [comment]
Fixed.
