### ISSUE TITLE
Search in Taxonomy

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1116]
@wsalesky I've found some issues with search in the taxonomy. I expect these are easy to fix but just so you know they aren't the highest priority. Thanks.

The search box at the top of all taxonomy pages doesn't seem to return any results. The same is the case for "Search Anywhere" in advanced search. (Am I right that these should perform the same search?)

The "Headword" search in advanced seems to search everywhere. This headword search for "orators" should return no results because "orators" is a gloss in the "rhetors" entry but not a headword: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/taxonomy/search.html?qs=&headword=orators&related-terms=

"Related terms" on the other hand seems to work as expected, returning results of glosses but not headwords, i.e. no results for "Rhetors" which is a headword but not a gloss: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/taxonomy/search.html?qs=&headword=&related-terms=Rhetors

**Comment by wsalesky** [comment]
@dlschwartz Thanks, I will take a look.

**Comment by wsalesky** [comment]
Fixed

**Comment by dlschwartz** [comment]
Thanks!
