### ISSUE TITLE
Error in API results

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1118]
On behalf of eKtobe:
The API is not functioning again. Last time I checked, it looked like it was spitting out results in a kind of XML although FF was expecting JSON. Not sure if that's the reason.
For questions, please reach out to the eKtobe team -- probably [Cyril Masset](https://www.irht.cnrs.fr/?q=fr/annuaire/masset-cyril) on the dev side and [André Binggeli](https://www.irht.cnrs.fr/?q=fr/annuaire/binggeli-andre) on content/admin issues.

**Comment by nathangibson** [comment]
I can't give an example since Syriaca appears down at the moment.

**Comment by wsalesky** [comment]
@nathangibson can you provide the link or specific API call?

**Comment by wsalesky** [comment]
@nathangibson Thanks for reporting this. I have fixed it on both sites.

**Comment by nathangibson** [comment]
Thanks!
