### ISSUE TITLE
White space in search results

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1119]
@wsalesky I noticed the following problem with name parts run together in the results of this search: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=ephrem. The name parts are all properly separated at http://syriaca.org/person/701.

![whitespace](https://user-images.githubusercontent.com/4984270/47739212-e0aa2780-dc42-11e8-95bf-9f9865067750.JPG)

I haven't found this in other modules.

**Comment by wsalesky** [comment]
@dlschwartz thanks, I will take a look.

**Comment by wsalesky** [comment]
@dlschwartz Seems to have gotten fixed somewhere along the line.
