### ISSUE TITLE
Incorrect page title for some modules

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1122]
In the new app, person entries (and perhaps some other entry types) are displaying "The Srophe web application" as the page title in the browser. This also affects the Zotero metadata. 

E.g., http://syriaca.org/person/13 is incorrect but on dev it is correct: http://wwwb.library.vanderbilt.edu/person/13. Also it seems NHSL is displaying the title correctly: http://syriaca.org/work/1000.

**Comment by wsalesky** [comment]
@nathangibson Thanks I will take look.

**Comment by wsalesky** [comment]
@nathangibson resolved. Thanks for catching that.

**Comment by nathangibson** [comment]
Thanks!
