### ISSUE TITLE
URL rewriting for module/volume home pages

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#1124]
URLs for module and volume home pages are working differently from the way they used to. 

E.g., http://syriaca.org/persons and http://syriaca.org/authors show an XML file. With trailing slash, e.g., http://syriaca.org/authors/ they redirect to the less-than-pretty eXist path http://syriaca.org/exist/apps/srophe/authors/index.html. 

Not sure if this is related but the page http://syriaca.org/nhsl/index.html doesn't display the banner images. FF 63.0.1. on Mac 10.14
![new_handbook_of_syriac_literature](https://user-images.githubusercontent.com/3083452/48554133-db550a00-e8dd-11e8-82fc-7def8e015c62.jpg)

**Comment by wsalesky** [comment]
@nathangibson Thanks Nathan, I will take a look.

**Comment by wsalesky** [comment]
@nathangibson Is NHSL live? I thought it was not? That is a dev page on prod, because I know the Bible module is not live.

**Comment by wsalesky** [comment]
Resolved.

**Comment by nathangibson** [comment]
NHSL is supposed to be live as BHSE is part of it. It now looks correct. (The Biblical Works volume is not linked—it merely says “forthcoming.”) Thanks!

**Comment by wsalesky** [comment]
Okay. Sorry, it was actually just missing a link to the correct css.
