### ISSUE TITLE
Change to display of deprecated persName or placeName and other deprecation notes.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1129]
@wsalesky This is related to https://github.com/srophe/srophe-app-data/issues/744 and illustrated in record: http://syriaca.org/place/1471.html

We will to start adding @type="deprecated" directly as an attribute to persNames or placesNames that are deprecated.

For example: 
Example of new encoding:
<placeName xml:id="name1471-5" xml:lang="en" source="#bib1471-3" type="deprecated">Antaracus</placeName>

Please make the following change to the HTML. When a persNames or placesName has @type="deprecated", do not display it in the list of names.

**Comment by wsalesky** [comment]
Fixed.
