### ISSUE TITLE
language documentation page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1135]
@wsalesky In our headers we currently refer to this file: http://syriaca.org/documentation/langusage.xml (the misspelling might be original to the address or might be a type on our part. Since we can't find either, we aren't certain).

Dan and I don’t see that file anywhere. But we do have https://github.com/srophe/srophe-eXist-app/blob/master/documentation/isostandards.xml which does the same thing. 

Any idea on if we ever had a file called langusage.xml? If not no worries, we will point to this instead http://syriaca.org/documentation/isostandards.xml

But there is a problem in that http://syriaca.org/documentation/isostandards.xml does not load, although it is present on git hub. Any thoughts?

I think this may all be related to the refactor.

**Comment by wsalesky** [comment]
Fixed the link issue. I do not see any langusage.xml even in the old versions I have stashed on my laptop.
