### ISSUE TITLE
SPEAR text box label

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1137]
@wsalesky The label on the text box that brings text from the Corpus into the SPEAR factoid page reads "Text from The Oxford-BYU Syriac Corpus". Since the name has changed, could we change that to "Text from The Syriac Corpus"? Thanks.

**Comment by wsalesky** [comment]
Sure

**Comment by dlschwartz** [comment]
Thanks @wsalesky
