### ISSUE TITLE
title and buttons cut off

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1138]
@wsalesky At certain screen sizes, like my laptop, I get the title cut in half and the tei, print, etc. buttons totally missing. I normally look on my large screen in my office where everything looks fine. Unfortunately, it's best to grab screen shots from a smaller screen and then I'm missing things. Thanks.
![title](https://user-images.githubusercontent.com/4984270/56909142-413ce480-6a6d-11e9-869a-bfe3efecffcd.JPG)

**Comment by wsalesky** [comment]
@dlschwartz Thanks I will take a look.

**Comment by dlschwartz** [comment]
Thanks!
