### ISSUE TITLE
Webhooks for Documentation

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1140]
@wsalesky I just pushed https://github.com/srophe/srophe-eXist-app/blob/master/documentation/editors.xml

But it has not updated at http://syriaca.org/documentation/editors.html

Should the webhooks do that?

**Comment by wsalesky** [comment]
@davidamichelson Yes, they should. Let me do some troubleshooting

**Comment by wsalesky** [comment]
I added it manually. There is a problem with webhooks on production.
