### ISSUE TITLE
Update browse

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#1145]
Browse pages:

- Sorted by Keyword (multiple languages eventually)
- Sorted by Author (multiple scripts)

Faceted Browse within Keyword and Author

- Publication Date
- Multiple Keyword/author combination (like in Spear)
- Types of Keyword (wait on this)
  - Ancient Author (person)
  - Place
  - Work

**Comment by davidamichelson** [comment]
Current functionality to mirror is here: http://www.csc.org.il/db/browse.aspx?db=SB

**Comment by davidamichelson** [comment]
The browse by "heading" for the bibl module, will actually be browse by all Syriaca.org URIs tagged in the data (Keywords, Persons, MSS, Places, etc.). We will want to have a browse by all tags and also facet by person, place, etc.

Present just the tag/heading list and then when selected show results, with facet options on the side

**Comment by davidamichelson** [comment]
We need to decide on what this default browse is called: Heading, Topic, Subject, Tag

Let's go with "Subject"

Sub-categories are:
Topic
-Genre?
Persons
Places
Works
Historical Era
Historical Authors

Separate browse by "Publication Information"
Author
Historical Authors
Place of Publication
Date of Publication

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz is there a relation element in the bibl data linking to the keywords?

**Comment by dlschwartz** [comment]
@wsalesky I haven't really been involved in the Zotero export so I'm not really sure. @davidamichelson?

**Comment by wsalesky** [comment]
@davidamichelson Perhaps the Zotero script needs to be rerun, can you send me the zotero info for the correct Zotero group? I will do all of this locally before moving it to the dev app.
