### ISSUE TITLE
SPEAR visualization: general

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1148]
@wsalesky I'm not sure about the best plan for approaching this rebuild so I'm just going to jump in with a series of issues. This first one will contain helpful links, some changes to SPEAR data, and some reminders I think might be helpful.

The xml files are here: https://github.com/srophe/draft-data/tree/master/data/spear/SPEAR_updates/tei 

In case it's helpful to see the schema, it's here: https://github.com/srophe/srophe-eXist-app/blob/master/documentation/SPEARschema/out/SPEAR.rng

- All div elements now have an @xml:id but the URI is stated in the factoid inside an idno element
- All div elements have a @resp attribute. It would be great to see the encoder's or encoders' name(s) on the factoid pages
- In person factoids, the persName directly nested under person indicates the subject of the factoid even if other person URIs appear elsewhere
- Person factoids can be about individuals person or groups personGrp

**Comment by dlschwartz** [comment]
Here is a link to the [data types file](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes) I link to in a number of the issues on data visualization. This should contain an example of each type of person factoid, event factoid, and relation factoid. I thought it might be helpful to have this all in one place.

**Comment by wsalesky** [comment]
Closing.
