### ISSUE TITLE
SPEAR visualization: landing page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1149]
@wsalesky I'm thinking that what we want here is something more like gazetteer landing page than the old SPEAR landing page. In particular, I'm not sure there's much value in a list of all factoids, especially since you only see a fraction of them without having to advance at the bottom. However, I would still like to use of tabs that persist at the top of every page so users can navigate easily.

Tabs:
- Browse Persons
- Browse Events
- Browse Relations
- Browse Places

Let's try this and if the "Browse" part of the above doesn't work we can simply remove that.

I'll need to get you some text and maybe an image for the bulk of the page but let's get started without that at first.

**Comment by wsalesky** [comment]
@dlschwartz do you have any images or anything else you would like to see on the landing page? I can probably move my changes over tomorrow, but I don't have anything on the landing page currently.

**Comment by dlschwartz** [comment]
@wsalesky I still like the one on the current landing page but maybe we should use it differently. I would be happy with the same layout as the Gazetteer but with [this image](https://upload.wikimedia.org/wikipedia/commons/d/da/Moqimu_mosaic_Edessa.jpg) replacing the map. 

I also found these images ([1](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Funerary_mosaic_Louvre_AO22917_n01.jpg/400px-Funerary_mosaic_Louvre_AO22917_n01.jpg), [2](https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Funerary_mosaic_Louvre_AO28293_n01.jpg/524px-Funerary_mosaic_Louvre_AO28293_n01.jpg), [3](https://upload.wikimedia.org/wikipedia/commons/c/c0/Funerary_mosaic_Louvre_AO28294_n01.jpg)) but I can't really think of how we would use them.

**Comment by wsalesky** [comment]
@dlschwartz What do you think of this updated home page: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/index.html

**Comment by wsalesky** [comment]
@dlschwartz do you want to make any changes to the home page or can I close this?

**Comment by dlschwartz** [comment]
@wsalesky I have a couple of things we can discuss in our meeting today. The one thing that should change for sure is the text. Can you cut the last paragraph and change the second-to-last paragraph to:

SPEAR provides scholars in Syriac Studies, Classics, Byzantine, and Islamic Studies access to a prosopgraphical database containing information on all of the individuals and groups appearing in the Syriac texts included in the database. SPEAR offers multiple search fields enabling researchers to return hits for a wide variety of queries and analyze relationships between ethnicity, language, occupation, religious confession, etc. Furthermore, each piece of data directs the user to a specific citation in one or more primary source texts.

**Comment by dlschwartz** [comment]
@wsalesky sorry, that's actually a bit repetitive of what's in the previous paragraph. Let me take another crack at this.

**Comment by wsalesky** [comment]
@dlschwartz Let me know about the updates for the home page. I think I am waiting for text.

**Comment by dlschwartz** [comment]
@wsalesky Here's the text. Thanks!

Syriac Persons, Events, and Relations Project (SPEAR) is a prosopographical database providing information about persons and their relationships within the context of historical events. SPEAR uses a "factoid" approach to prosopography that captures data points asserted in historical texts. A factoid differs from a fact in that it indicates an assertion made by a primary source text, rather than a piece of information that a modern editor affirms as true. This approach allows for the fullest dataset possible and captures data of particular importance for social history. For example, a fictional biography of a saint can still reveal a great deal of information about how people understood saints and the town councilors, clergy, and peasants with whom they interacted. The factoid approach is critical for creating a database of use to social historians as well as historians of the political or religious institutions upon which traditional print prosopographies have focused.

SPEAR provides a prosopography drawn from Syriac source material that is relevant to Syriac Studies, Classics, Byzantine Studies, and Islamic Studies. It contains information on all of the individuals and groups appearing in the Syriac texts included in the database. SPEAR offers multiple search fields enabling researchers to return hits for a wide variety of queries including parameters such as ethnicity, language spoken, occupation, etc. Each piece of data directs the user to a specific citation in one or more primary source texts and keyword tagging used throughout the dataset links this prosopographical material to Syriaca.org's bibliography database.

SPEAR provides a rich collection of Linked Data on persons encoded using the TEI standards for XML markup. The current release is a beta version designed to make this data available to researchers and the public. Future development plans include the development of greater capabilities to perform faceted search and browse on this dataset.

**Comment by dlschwartz** [comment]
@wsalesky I forgot to mention that I'm still thinking about the "browse sources" we discussed last week. I need some place to discuss the sources included and I would also like a place where I can mention the encoders who worked on a text. This is especially important since I would like to solicit contributions and would want to highlight these kinds of contributions. I will put some options together for folks to discuss when we meet next Monday.

**Comment by wsalesky** [comment]
Added.
