### ISSUE TITLE
SPEAR visualization: browse persons

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1150]
@wsalesky This page should contain a list of all the person URIs contained in SPEAR. 

The name listed should be the Syriaca headword from the person record and the list should be alphabetized by that Syriaca headword in the person record. It would be great to grab English and Syriac when available. 

A link on each of those names should take users to a page aggregating all data in SPEAR about that person.

**Comment by wsalesky** [comment]
@dlschwartz Any facets on this browse?

**Comment by wsalesky** [comment]
@dlschwartz never mind, I see it is a different issue.

**Comment by wsalesky** [comment]
@wsalesky  - done pending approval

**Comment by wsalesky** [comment]
@dlschwartz please close the visualization issues, if they meet expectations.

**Comment by dlschwartz** [comment]
@wsalesky Looks great, thanks!

**Comment by dlschwartz** [comment]
@wsalesky oops, one more. Can gender, sanctity, and occupation facet? Thanks.

**Comment by wsalesky** [comment]
Same as: https://github.com/srophe/srophe-eXist-app/issues/1156
