### ISSUE TITLE
SPEAR visualization: browse relations

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1153]
@wsalesky This page should contain a list of all the events in SPEAR.

The link on each factoid should take users to the individual factoid pages.

**Comment by wsalesky** [comment]
note to self: done

**Comment by wsalesky** [comment]
@dlschwartz please close the visualization issues, if they meet expectations.

**Comment by dlschwartz** [comment]
Thanks @wsalesky
