### ISSUE TITLE
SPEAR visualization: browse places

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1154]
@wsalesky This page should contain a list of all the place URIs contained in SPEAR.

The name listed should be the Syriaca headword from the place record and the list should be alphabetized by that Syriaca headword in the person record. It would be great to grab English and Syriac when available.

A link on each of those names should take users to a page aggregating all data in SPEAR about that place.

**Comment by wsalesky** [comment]
@dlschwartz No facets? Do you want a map?

**Comment by dlschwartz** [comment]
@wsalesky I think a map would be great! Thanks for thinking of it. The best option I can think of for faceting on places would be keywords used in the same factoid. A person search for persons appearing in the same factoid as a place would be a possibility as well. Give me a minute to think on this. Thanks.

**Comment by dlschwartz** [comment]
@wsalesky I just looked at the advanced search on the Gazetteer. I trust we can use Gazetteer data to allow browse by place type. I think that would be a nice feature. It would be fantastic to have this along with a search by related person box (like on the Gazetteer search page) that would return all the places appearing in the same factoid as the person URI searched for. Thanks Winona.

**Comment by wsalesky** [comment]
We could put the type filter right on the map like we are doing for The Beth Qaṭraye Gazetteer.
See: 
<img width="1396" alt="Screen Shot 2019-10-03 at 11 46 47 AM" src="https://user-images.githubusercontent.com/1168206/66142569-ac1db900-e5d3-11e9-83d2-ce540cf71922.png">

**Comment by dlschwartz** [comment]
@wsalesky In theory this would be great. I'm guessing everything in the Beth Qaṭraye Gazetteer has coordinates. I'm not sure what the percentage is, but many places in the Syriac Gazetteer do not. This might be best over on the side and used to sort the full list of place types rather than just those with coordinates.

**Comment by wsalesky** [comment]
Sounds good.

**Comment by wsalesky** [comment]
Note to self: links on maps will have to be changed to go to SPEAR entry.

**Comment by dlschwartz** [comment]
@wsalesky I'm getting some bugs in results here. Some of the place types show a count on the main browse page but then nothing appears when I select it. An example is "Synagogue" but there are others. Also, in some cases the count shows a different number from what appears when that place type is selected. See "Church" in this example.
![placeBrowse02](https://user-images.githubusercontent.com/4984270/66932384-20595300-effd-11e9-9b1c-8b083e05b858.JPG)
![placeBrowse01](https://user-images.githubusercontent.com/4984270/66932387-23ecda00-effd-11e9-8141-10fe9cb3fa9b.JPG)

**Comment by wsalesky** [comment]
Thanks I will take a look.

**Comment by wsalesky** [comment]
Inconsistent capitialization in place types. Facet code now accounts for this.
