### ISSUE TITLE
SPEAR visualization: place aggregation page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1155]
@wsalesky I've liked the place aggregation pages you've produced in the past. I hope that code is still around and you can just use it as is. That seems like a great place to start at least.

**Comment by dlschwartz** [comment]
@wsalesky similar to the person aggregation page, we've lost some data here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/place/572.
![placeAggregation](https://user-images.githubusercontent.com/4984270/66935434-9364c880-f001-11e9-81b4-638377aec522.JPG)

**Comment by wsalesky** [comment]
@dlschwartz Fixed. There are no person factoids referencing places, that box should not show up at all.
