### ISSUE TITLE
SPEAR visualization: browse persons page facets

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1156]
@wsalesky This is where things have always gotten messy. I trust we want to keep this along the left hand side. I'm probably getting too greedy here (please tell me if I am!) but might we be able to have faceted browse by:
- gender: [sample code](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes#L269)
- ethnicity: [sample code](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes#L304)
- sanctity: [sample code](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes#L251)
- occupation (this might be cumbersome, if so we can drop it): [sample code](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes#L194)

**Comment by dlschwartz** [comment]
<div type="factoid" xml:id="factoid-7" resp="#ktorabi #dschwartz">
                <idno type="URI">http://syriaca.org/spear/3012-7</idno>
                <listPerson>
                    <person>
                        <persName ref="http://syriaca.org/person/2416"/>
                        <trait type="gender" ana="http://syriaca.org/keyword/female">
                            <note type="desc"><persName ref="http://syriaca.org/person/2416"
                                    >Thecla</persName> was female.</note>
                        </trait>
                    </person>
                </listPerson>
                <bibl type="primary"><ptr target="http://syriaca.org/bibl/668"/><citedRange
                        unit="part">1.02</citedRange><citedRange unit="pp">12</citedRange></bibl>
            </div>

**Comment by dlschwartz** [comment]
<div type="factoid" xml:id="factoid-23" resp="#ktorabi">
                <idno type="URI">http://syriaca.org/spear/10510-23</idno>
                <listPerson>
                    <person>
                        <persName ref="http://syriaca.org/person/3218"/>
                        <trait type="ethnicLabel" ana="http://syriaca.org/keyword/syrian">
                            <note type="desc"><persName ref="http://syriaca.org/person/3218">John
                                    Urtaya</persName>was Syrian.</note>
                        </trait>
                    </person>
                </listPerson>
                <bibl type="primary"><ptr target="http://syriaca.org/work/10510"/><citedRange
                        unit="pp">554</citedRange></bibl>
                <bibl type="primary"><ptr target="http://syriaca.org/bibl/2033"/><citedRange
                        unit="pp">208</citedRange></bibl>
            </div>

**Comment by dlschwartz** [comment]
<div type="factoid" xml:id="factoid-4" resp="#ktorabi">
                <idno type="URI">http://syriaca.org/spear/794-4</idno>
                <listPerson>
                    <person>
                        <persName ref="http://syriaca.org/person/1524"/>
                        <state type="sanctity" ana="http://syriaca.org/keyword/saints">
                            <note type="desc"><persName ref="http://syriaca.org/person/1524"
                                    >Zeʿora</persName> was a saint.</note>
                        </state>
                    </person>
                </listPerson>
                <bibl type="primary"><ptr target="http://syriaca.org/work/794"/><citedRange
                        unit="pp">18</citedRange></bibl>
                <bibl type="primary"><ptr target="http://syriaca.org/bibl/1409"/><citedRange
                        unit="pp">18</citedRange></bibl>
            </div>

**Comment by wsalesky** [comment]
note to self: done

**Comment by dlschwartz** [comment]
@wsalesky I referenced this in another issue but these options don't currently offer faceted browse. Thanks.

**Comment by wsalesky** [comment]
Closing this, just so I can keep track of things
