### ISSUE TITLE
SPEAR visualization: browse events page facets

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1157]
@wsalesky Again, potentially messy. Can we try to allow users to facet on keyword URIs? These keywords are located on @ana attributes on the event element: [sample code](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes#L329).

**Comment by wsalesky** [comment]
@dlschwartz how would you like keywords to sort? (See question on relations browse page issue)

**Comment by dlschwartz** [comment]
@wsalesky numeric (see answer on relations browse page issue).

**Comment by wsalesky** [comment]
@dlschwartz please close the visualization issues, if they meet expectations.

**Comment by dlschwartz** [comment]
Thanks @wsalesky
