### ISSUE TITLE
SPEAR visualization: browse relations page facets

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1158]
@wsalesky Again, potentially messy. Let's try to allow users to facet on relations keywords, but just the keywords located the [@ref attribute](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes#L365) on the relation element. For this faceted browse we won't include the keywords on the [@type attribute](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes#L366).

**Comment by wsalesky** [comment]
@dlschwartz how would you like the keyword facets sorted? Alphabetical or numeric (keywords with the most hits appearing first)?

**Comment by dlschwartz** [comment]
@wsalesky I think numeric would be great. It will immediately show what the sources in the database emphasize. Let's do it that way. Thanks for asking.

**Comment by wsalesky** [comment]
@dlschwartz please close the visualization issues, if they meet expectations.

**Comment by wsalesky** [comment]
Fixed
