### ISSUE TITLE
SPEAR Visualization: @resp on Factoid pages

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1159]
@wsalesky I've always thought these looked good. I would like to add two things that we've never done before. I'll use separate issues.

Every div has a @resp attribute [[link to example](https://github.com/srophe/draft-data/blob/master/data/spear/SPEARdataTypes#L9)] with one or more pointers to the person responsible for the factoid. A full name is listed in the header of each document and the correct name can be found at  /TEI/teiHeader/fileDesc/titleStmt/editor by matching the @ref substring-after '.xml'. Otherwise, full names are also located in [this list](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/editors.xml#L128) which is what the schema validates against.

**Comment by wsalesky** [comment]
@dlschwartz Any preference where you would like the name to show up? At the bottom of the factoid? Top? Any specific formatting?

**Comment by dlschwartz** [comment]
@wsalesky Let's put it at the bottom, like we would expect in an encyclopedia article. It will need some introduction though. How about: "This data collected by n1, n2, and n3" as needed. Feel free to play around with this a bit if what I'm suggesting looks odd for whatever reason. Thanks.

**Comment by wsalesky** [comment]
Note to self: Added.

**Comment by wsalesky** [comment]
@dlschwartz please close the visualization issues, if they meet expectations.

**Comment by dlschwartz** [comment]
Thanks @wsalesky

**Comment by dlschwartz** [comment]
@wsalesky sorry, I just saw something here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/847-18. With multiple names, there is a space between the name and the comma.

**Comment by wsalesky** [comment]
Fixed.
