### ISSUE TITLE
SPEAR Visualization: Linked data to the right of the page.

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1161]
@wsalesky All of the links on the browse pages and the aggregation pages should keep users in SPEAR. The links on the right should take users out of SPEAR to other modules. I believe this can all come from stuff you've already built for person URIs, place URIs, and keyword URIs. I've liked what you did in the past in this regard. I hope this is pretty straightforward. Please let me know if there are any questions.

**Comment by wsalesky** [comment]
@dlschwartz please close the visualization issues, if they meet expectations.
