### ISSUE TITLE
Display issue in events

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#1168]
http://localhost:8787/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/3058-18

**Comment by wsalesky** [comment]
@dlschwartz This is a problem in the data, there are no spaces before and after the persName element. 
<img width="776" alt="Screen Shot 2019-10-15 at 12 59 02 PM" src="https://user-images.githubusercontent.com/1168206/66852762-addc6a80-ef4b-11e9-9751-2d26a91c102d.png">

**Comment by dlschwartz** [comment]
@wsalesky thanks. I had noticed that and fixed some of it but need to do a systematic fix. Thanks.

**Comment by dlschwartz** [comment]
@wsalesky I fixed this. I'll close this but if you see anything else that I missed I'd appreciate it if you could let me know. Thanks.
