### ISSUE TITLE
Non-gregorian dates

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1170]
@wsalesky on the browse events page, the non-Gregorian dates show up correctly: "28 October A. D. 457 (28 Teshri I A. Gr. 769)". However, they don't show up correctly on the factoid page, i.e. there's no parentheses around the non-Gregorian part. Example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/8559-344

The parentheses also don't appear in the timeline. It's not a problem if there is some limitation about what can appear there. I just thought I would mention it. If there were an option to display only the date in the reg element on the timeline, that would be fine.

**Comment by wsalesky** [comment]
Fixed.
