### ISSUE TITLE
Source errors in dates

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1172]
@wsalesky dates are hard. When there is an error in a date, we've collected the error in a sic element and the correction in a corr element. See: https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/8559.xml#L1331. 

I'm not sure what to do with this. Can you think of any way to visualize this as is? If not, I could move the sic element down to the note (see below). It separates it from the central portion of the factoid in ways that I don't find ideal but that I could live with.

```
<choice>
   <corr>
      <date when="-0044" calendar="Gregorian"srophe:computed-start="-0044-01-01">44 B.C.</date>
   </corr>
</choice>
...
<note>
   The author includes the following date but it is clearly an error:
   <sic>
      <choice>
         <reg>
            <date notBefore="-0046-10" notAfter="-0045-09" calendar="Gregorian" >46/5 B.C</date>
         </reg>
         <orig>
            <date when-custom="0266" datingMethod="Seleucid">A. Gr. 266</date>
         </orig>
      </choice> 
   </sic>
</note>
```

I could also do both. Everything would appear in the body of the factoid but then the note would contain a repetition of the incorrect sic date. The sic element would not get displayed in the event description but would get displayed in the note. Please share your ideas on this one. Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz Why don't we leave the code as is and see if I can get the display how you would like. What is the preferred output of the first bit of code?

**Comment by dlschwartz** [comment]
@wsalesky this is really tricky. This isn't particularly elegant but it gets everything in there. 
"In 44 B.C. [not 46/5 B.C. (A. Gr. 266)] Augustus became King of Rome."
Combined with the note "The author has apparently mistaken the date of Augustus' accession." this should be clear enough. Also, the Syriac text (and eventually English translation) will also get sucked into this page so the user can see factoid and text together.

**Comment by wsalesky** [comment]
fixed.
