### ISSUE TITLE
Change "more" to "see factoid page"

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1173]
@wsalesky it seems that some of the data types have a link to the factoid page that reads "more" while most of them have "See factoid page". 

Here is one link: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201

I see it on occupations and social ranks but it may appear elsewhere.

**Comment by wsalesky** [comment]
Fixed!
