### ISSUE TITLE
Birth date and death date not showing in person aggregation page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1174]
@wsalesky I don't see examples of birth place and death place appearing in the "Person factoids about ...." section on a person aggregation page.

Death
HTML: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/13
TEI: https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/8559.xml#L3796

Birth
HTML: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/608
TEI: https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/8559.xml#L1916

**Comment by wsalesky** [comment]
@dlschwartz How do we want dates in a `tei:choice` element to display? See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/13

**Comment by dlschwartz** [comment]
@wsalesky I think on the aggregation page we should just have "Ephrem died on 9 June 373". And actually, the aim of the factoid page is to present a human readable version of the data so there as well I believe we would want the same. For serialization into RDF we'd get into the `tei:choice` element.

**Comment by wsalesky** [comment]
Fixed.
