### ISSUE TITLE
aggregation page appears even if there is no data in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1175]
@wsalesky the app creates an aggregation page for any person URI that exists in our person data even if there is no spear data about that person. Most users aren't likely to do what I did, which is take an aggregation page URL and replace the person number. Is there an easy fix for this? If not, let's not worry about it. Also, when we implement a search by person URI we'll want to make sure it doesn't return a stub aggregation page like the following when there is no SPEAR data about a person.

http://syriaca.org/person/5 appears in SBD but not in SPEAR and we still get this:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/5

**Comment by wsalesky** [comment]
@dlschwartz what do you think should happen here? A page that says 'No SPEAR data on this person' ? A redirect to a 404?  Something else?

**Comment by dlschwartz** [comment]
@wsalesky I hate to have a 404 error. The "No SPEAR data on this person" might be the best option. I think people are unlikely to type in a URI but they could do. I do this for element pages in the TEI guidelines all the time. It's a very handy shortcut. Thanks.

**Comment by wsalesky** [comment]
Fixed.

**Comment by wsalesky** [comment]
Just found an issue in this. See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/place/18

Note to self: Need to test if there are any factoids in each of the aggrigate types.

**Comment by wsalesky** [comment]
Fixed again.
