### ISSUE TITLE
Facoid page, pull text from Corpus using URN

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1177]
@wsalesky can we pull text from the Corpus using URN and display it on the factoid page? These are bibl elements with type="urn". 
https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/8559.xml#L100
Thanks.

**Comment by wsalesky** [comment]
@wsalesky Note to self, need to use ajax to load this (make sure CORS is enabled).

**Comment by wsalesky** [comment]
@wsalesky Note: works beautifully locally but throwing an error on dev.

**Comment by wsalesky** [comment]
@dlschwartz Success, finally! Sorry it took so long. 
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/8559-1  

as an example.

**Comment by dlschwartz** [comment]
@wsalesky excellent! Thanks so much. Interestingly, I'm getting it on Firefox but not Chrome. I've done a hard refresh a couple of times. I'll try clearing the cache. It's great to have the Syriac back. Thansks.

**Comment by dlschwartz** [comment]
Clearing the cache worked. Thanks.
