### ISSUE TITLE
Person/place search box

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1178]
@wsalesky please add faceted search boxes to the events browse and the relations browse pages. On events, search by person and place would be great. On relations, only person would return results. 

I looked at the advance search page on the Gazetteer: http://syriaca.org/geo/search.html. It requires someone to enter in the entire URI. Might it be possible to auto populate the search box with the "http://syriaca.org/person" (or /place as appropriate) portion of the URI so that the user only needs to enter the number. It makes for a lot of typing. If there's an easy way to address this it would be great. 

Thanks Winona.

**Comment by wsalesky** [comment]
Added
