### ISSUE TITLE
Notes not showing up

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1194]
@wsalesky the child note type="desc" is not showing up in the following contexts on either the aggregation page or factoid page

birth/date OR choice/reg/date
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2245

death/date OR choice/reg/date
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2205

birth/placeName
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/1625

death/placeName 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2032

education
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2032

nationality
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2562

residence/placeName
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/48

state type="sanctity"
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/958

state type="mental"
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/1866

**Comment by dlschwartz** [comment]
@wsalesky by the way, there are a couple types of data that are only in draft data and have not yet been moved over to the dev branch. Both langKnowledge and trait type="ethnicLabel" should work the same as the above. I'm not sure what will happen when these get moved over to dev.

Also, it might help to know that the child note is properly displayed with trait type="physical", trait type="gender", socecStatus, and occupation. Thanks Winona.

**Comment by wsalesky** [comment]
Fixed.
