### ISSUE TITLE
Factoid types, esp. birth and death

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1195]
@wsalesky birth/death place factoids each getting registered as both birth/death date and birth/death place:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/1546
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2032

I'm wondering if all factoids should have a subtype attribute: name, birthPlace, birthDate, deathPlace, deathDate, education, languageKnown, citizenship, occupation, residence, socialRank, 
sanctity, gender, physicalTrait, ethnicLabel, event, relation. I can easily add this using RegEx and it would help address the problem.

**Comment by wsalesky** [comment]
@dlschwartz I can catch this in the XSLT. Taking a look today.

**Comment by wsalesky** [comment]
@dlschwartz I think this has been fixed.

**Comment by dlschwartz** [comment]
@wsalesky Thank you. I've added the subtype attribute on div in case you hadn't seen that. I did it late on Friday and forgot to send you a message about it. Thanks.
