### ISSUE TITLE
SPEAR on the Syriaca.org landing page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1197]
@wsalesky on the Syriaca.org landing page the SPEAR box needs a short blurb and some sample data.

Text: “SPEAR is a prosopographical database providing information about persons and their relationships within the context of historical events.”

Sample data on dev: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201

Sample data on production (I think?): http://syriaca.org/spear/aggregate.html?id=http://syriaca.org/person/2201

Thanks

**Comment by wsalesky** [comment]
Done
