### ISSUE TITLE
Qualifier relationships

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1198]
@wsalesky  we will need to display the "qualifier" relationships. These are the one's with a namespaced value in column F here: https://docs.google.com/spreadsheets/d/1aDICk8lrQ7cospr2yVlMYLXavMbaTDxbgr1GDrqfWDw/edit?pli=1#gid=0. 

These don't need to display in the list on the browse relations page but just on the factoid page itself. 

I would suggest that after the display of the desc, there should appear the following,
"Qualifier: " followed by the attribute value without the namespace and with spaces added before the capital letters. Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz I was wondering how to handle that data. ;)

**Comment by wsalesky** [comment]
@dlschwartz Added. Will show up when the new version of the data is loaded.

**Comment by dlschwartz** [comment]
@wsalesky I forgot to check this. We only have one example in dev at the moment (more in draft data): http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/814-3. I think it might be best to drop the parentheses and comma separate these two values in the display. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz done!
