### ISSUE TITLE
TEI:note/@type="deprecation" display in HTML needs punctuation fix

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1205]
example record: http://syriaca.org/place/1494.html

For TEI:note of @type="deprecation" the HTML inserts a number and a period and a colon.

For notes of @type="incerta" the HTML is just the textnode. (see http://syriaca.org/place/78)

Please make the @type="deprecation" match the @type="incerta" as plain in style. No number or punctuation needed.

This change should apply to all versions of the app including BQG

Thanks!
DM
![Screenshot 2019-12-18 15 26 50](https://user-images.githubusercontent.com/3083773/71124948-961f9d80-21ab-11ea-90c5-04b6b9dbad97.png)

**Comment by wsalesky** [comment]
Done
