### ISSUE TITLE
Relationships between events

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1206]
@wsalesky I found an error in the display of relationships between events. I thought there was an old issue on this I could re-open but I can't seem to find it. The "Relation:" option is correct and the "Relationship:" option is incorrect. What's appears there should be generated out of a <desc> element inside <relation>. What's appearing in the "Relationship:" option is being generated by the app.

Also, the link doesn't work. It takes the user to an aggregation page with no results rather than to the other event factoid page. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz example record to check?

**Comment by dlschwartz** [comment]
@wsalesky I thought I put a link in there. Sorry. http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/8559-554

**Comment by wsalesky** [comment]
@dlschwartz This is fixed. Should I update the data on the dev server to include the new relationships with descriptions? Otherwise this code breaks the relationship factoid display (until the new data is up).

**Comment by dlschwartz** [comment]
@wsalesky yes, let's go ahead and update that data. Thank you.

**Comment by wsalesky** [comment]
Done: https://github.com/srophe/srophe-app-data/pull/785

**Comment by dlschwartz** [comment]
@wsalesky great, thank you.
