### ISSUE TITLE
Relation, change @ref to @name

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1208]
@wsalesky in writing up an article on SPEAR I've realized that I have a datatype error I need to fix. I've incorrectly used @ref on the relation element. I will need to change that to @name. The values will stay the same. This will be relevant to all relation factoids and to relations in event factoids. Rather than break everything, I've made that change in a branch of dev ([ref-2-name](https://github.com/srophe/srophe-app-data/tree/ref-2-name)). Feel free to merge that change into dev whenever it suits you. Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz Okay. I will try to get to it tomorrow.

**Comment by wsalesky** [comment]
@dlschwartz I tested this and it does not seem to break anything, so I have merged it into dev. Let me know if you run into any problems.

**Comment by dlschwartz** [comment]
@wsalesky this looks great, thanks. And I love how fast things are now that we have desc elements in relation factoids!!!

**Comment by wsalesky** [comment]
@dlschwartz Great to hear that the speed is better!
