### ISSUE TITLE
Factoid citations

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1209]
@wsalesky, @davidamichelson, @jsaintlauren, @wlpotter 
It would be great if everyone could weigh in on this just quickly. Here's what I've got in response to our discussion earlier. 

We can re-label "Text from the Syriac Corpus" as "Source" and always include that box, even if there is no URN. This could be pulled from the sourceDesc. The sourceDesc element always has one bibl element with a work URI [//sourceDesc//bibl/ptr/@target]. The parent bibl element will always have a title element child and may have an author element child. This box would then always include "[author name-when available], [title with work URI hyperlink]". If the factoid contains a URN, the text would display below with a link reading: "See text at The Syriac Corpus".

We can re-label "Sources" as "Citations". Following the note about unsourced information, we could have two sections: "Factoid Citations" [for bibl elements that are direct children of the div element] and "Note Citations" [for bibl elements that are children of note elements]. 

Factoid without URN or note:
![simpleFactoid](https://user-images.githubusercontent.com/4984270/73199563-ae63d000-40fa-11ea-9164-2345fe3e2400.png)

Factoid with URN but no note:
![factoidSource](https://user-images.githubusercontent.com/4984270/73199644-d4897000-40fa-11ea-8fa6-01da4c557588.png)

Factoid with URN and with a discursive note:
![noteCitation](https://user-images.githubusercontent.com/4984270/73199671-e408b900-40fa-11ea-9f00-68c8036aa530.png)

**Comment by wsalesky** [comment]
@dlschwartz I think this works. Can you remind me of the XPath to build the Source title and idno?

**Comment by dlschwartz** [comment]
@wsalesky the bibl element containing the information needed will be here: 
/TEI/teiHeader/fileDesc/sourceDesc/listBibl/bibl[ptr/@target='http://syriaca.org/work/{\d+}']. 

That bibl should always contain a title element and the work URI is the value of the @target on ptr. That bibl may also contain an author element.

**Comment by wsalesky** [comment]
@dlschwartz Added. Please let me know how it looks.

**Comment by dlschwartz** [comment]
@wsalesky I think this addresses a number of the concerns addressed on Monday. I've got some (I hope) minor tweaks. 

Ideally, I'd like the factoid pages without URNs to look a lot like those that do have URNs. It might help to put "source" and "citations" into separate boxes, more like on the old URN box, even when we won't import the text. 

Also, it would be great if we could list the source like we would an abbreviated bibliography entry, so "Author Name [when present], _Title in Italics_". 

Here is a mock-up of these two suggstions from [spear/3020-21](<http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/3020-21>). I've split the boxes here to suggest vaguely what I have in mind.
![sourceRevision](https://user-images.githubusercontent.com/4984270/73555391-2986f800-4413-11ea-8e96-063a9160ea11.png)


Below is a mock-up from [spear/8559-387](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/8559-387). Two things here. First, I like the division between the two sections: "source" and "citations". I think the priority ought to be one format that looks good whether or not there is a URN displaying text (the same font, indent, etc.). Perhaps we can have two boxes like below, with text formatted to look like the text in the image above. This would be a small grey box when no URN is present but when a URN is present that text could appear in a white background with the grey border like in the current URN text box. Let me know if this presents challenges though. Also, I think it would help users to see a separate section for note citations.
![NoteRevision](https://user-images.githubusercontent.com/4984270/73555974-26d8d280-4414-11ea-945b-efce50516e18.png)

Thanks Winona

**Comment by wsalesky** [comment]
@dlschwartz How does it look now?

**Comment by dlschwartz** [comment]
@wsalesky that's great. I'm pretty sure that addresses the concerns expressed last Monday. It also offers a straightforward and consistent system. Thanks!
