### ISSUE TITLE
@resp on factoid div not always working correctly

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1210]
@wsalesky in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/3020-21 we have a blank space following "This data collected by". There might be a data problem but the full name of the contributor should be in the header. If that's where you're looking and it's not there, I'll fix the data because it should be there.

**Comment by wsalesky** [comment]
Fixed.
