### ISSUE TITLE
individual keyword pages

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1213]
@wsalesky I've got one more. The individual pages have changed too. Here's a screenshot of the old layout. 

![image](https://user-images.githubusercontent.com/4984270/74379096-c602b000-4dac-11ea-80e3-b8ebf9e97474.png)

I like the way the headwords (term syriaca-tags="#syriaca-headword") pop in this version and I think having just a bit more info in the relationship box will help users decipher what that's all about. Thank you.

**Comment by wsalesky** [comment]
@dlschwartz Fixed!

**Comment by dlschwartz** [comment]
Looks great. Thanks!
