### ISSUE TITLE
Change "sex" to "gender" on aggregation page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1214]
@wsalesky can you please change "sex" to "gender" on the person aggregation pages? Thank you.

![image](https://user-images.githubusercontent.com/4984270/74590729-99ca7780-4fd6-11ea-8883-7f8101e5de45.png)

**Comment by wsalesky** [comment]
Fixed

**Comment by dlschwartz** [comment]
Thanks!
