### ISSUE TITLE
Events in person/place aggregation page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1215]
@wsalesky we decided to remove the "sort by" feature from the [browse events page](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=events). It looks like it's still appearing on the [events in the person aggregation page](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201) and [events in the place aggregation page](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/place/10). 

It's also no longer rendering correctly there. With "chronological" selected it says gives an undated category with dated events.
![sortEvents](https://user-images.githubusercontent.com/4984270/74590932-d4351400-4fd8-11ea-8c05-1df46e0555a5.png)

With "textual" selected it uses the URI as a heading. 
![sortEventsTextual](https://user-images.githubusercontent.com/4984270/74590937-e3b45d00-4fd8-11ea-80a8-a180166926d4.png)

If we could just have this section of the aggregation page work like the list of events on the "browse events" page I think that would be great. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz How does it look now?

**Comment by dlschwartz** [comment]
@wsalesky This is great. Thanks Winona!
