### ISSUE TITLE
Please change how location/@type="nested" data displays

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1225]
This issue is based on a change to the encoding documented here: https://github.com/srophe/srophe-app-data/issues/803

Please see http://syriaca.org/place/78/tei for data example

When data is encoded in location/@type="nested" please:

- [ ] Separate the nested child elements with one or more commas

- [ ] Display any att.datable information with any leading zeros trimmed from years and converting negative dates to BCE

By att.datable we mean:
att.datable (@Calendar, @period)
att.datable.w3c (@when, @notBefore, @notAfter, @from, @to)
att.datable.iso (@when-iso, @notBefore-iso, @notAfter-iso, @from-iso, @to-iso)
att.datable.custom (@when-custom, @notBefore-custom, @notAfter-custom, @from-custom, @to-custom, @datingPoint, @datingMethod)

Please convert the attribute name to a label and then display with it the attribute value

Example code
```
<location type="nested" source="#bib78-1" to="0641">
<region ref="http://syriaca.org/place/145">Osrhoene</region>
<country ref="http://syriaca.org/place/166">Roman Empire</country>
</location>
```

Example display:

**Location**
- Within Osrhoene, Roman Empire (to 641).<sup>1<sup>

**Comment by wsalesky** [comment]
fixed
