### ISSUE TITLE
SBD headwords on browse page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1228]
@wsalesky the browse index doesn't seem to be listing any Syriac headwords. It displays the English headword followed by an em-dash and then nothing. TSG uses an en-dash. Also, it does not list " - [Syriac Not Available]" like TSG does.

**Comment by wsalesky** [comment]
Fixed. See https://github.com/srophe/srophe-eXist-app/issues/1229
