### ISSUE TITLE
Individual SBD pages missing headwords

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1229]
@wsalesky the pages seem to have replaced the headword on the person pages with other data. See for example http://syriaca.org/person/1535 where instead of the English headword we get "Gateway to the Syriac Saints". With http://syriaca.org/person/215 the headwords (English and Syriac) have been replaced with "The Syriac Biographical Dictionary"

**Comment by wsalesky** [comment]
@dlschwartz I changed the code to be more flexible, but these are also still using the old syriaca-tags attribute, not the srophe:tags attribute. This should keep any legacy data displaying correctly. 
 
see: https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/215.xml#L180

**Comment by dlschwartz** [comment]
Of course. Sorry that detail got by me. Thanks!

**Comment by dlschwartz** [comment]
@wsalesky the English and Syriac headwords seem to have disappeared again. I'm guessing this came about following the batch changes to add the `@srophe:tags` attribute? Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz Fixed. Hopefully I caught all the variations this time. These were code with: 
`<persName xml:id="name1535-h" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Aaron the Solitary</persName>`

So they somehow missed the batch update. I may have to go through the data again to try and catch the leftover syriaca-tags.

**Comment by dlschwartz** [comment]
@wsalesky thanks! I've spot checked and things look pretty good.
