### ISSUE TITLE
SPEAR factoid pages

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1231]
@wsalesky dev is up and running again but the individual factoid pages don't display: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/8559-510.

**Comment by wsalesky** [comment]
@dlschwartz I have the pages working except for the SPARQL request, something has gone wrong there, a code regression I think. I'm working through the code to see if I can find it, but wanted to give you an update.

**Comment by dlschwartz** [comment]
@wsalesky great, thank you!

**Comment by wsalesky** [comment]
@dlschwartz This is fixed. I'm not sure how it happened by the code on the server was overwritten and out of sync with the code in the development branch. Let me know if you run into any other issues.
