### ISSUE TITLE
Documentation page links

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1232]
@wsalesky @davidamichelson am I right that we should have links under "Editorial Documentation" and "Technical Documentation"? http://syriaca.org/documentation/index.html

**Comment by wsalesky** [comment]
Fixed. Change in github wiki code caused menus to not be found.

**Comment by dlschwartz** [comment]
Thanks!

**Comment by davidamichelson** [comment]
Thanks all! I thought I had made an issue for this but don't see it, so
glad you did this. Thanks for the quick fix Winona!

**Comment by dlschwartz** [comment]
@wsalesky this problem is back. Thanks.

**Comment by wsalesky** [comment]
Fixed.
