### ISSUE TITLE
Terms not appearing in Taxonomy

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1236]
@wsalesky the terms don't appear to be showing up on the taxonomy pages. Compare http://syriaca.org/keyword/rhetors with https://github.com/srophe/srophe-app-data/blob/master/data/subjects/tei/rhetors.xml#L103 and following. Thank you.

**Comment by wsalesky** [comment]
Fixed. Sorry about that!

**Comment by dlschwartz** [comment]
Thanks!
