### ISSUE TITLE
Clickable labels on module pages

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1238]
@wsalesky I just noticed that the icon and label ("The Syriac Biographical Dictionary") in the top banner of SBD links to The Syriaca Gazetteer and not to SBD.

Also, the text in the same position on the Guide to the Syriac Saints links correctly to the Guide but the text reads "The Srophe Web Application"

Thanks

**Comment by wsalesky** [comment]
Fixed
