### ISSUE TITLE
Odd Browse Function

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#1266]
This record: https://syriaca.org/person/1336 has the following names:

```
<persName xml:id="name1336-2" xml:lang="en" resp="http://syriaca.org" srophe:tags="#syriaca-headword">Kenan</persName>
<persName xml:id="name1336-3" xml:lang="fr-x-fiey" source="#bib1336-1">KENAN</persName>
```

For some reason it does not show up in browse: 
https://syriaca.org/q/browse.html?lang=&alpha-filter=K
https://syriaca.org/q/browse.html?lang=fr&alpha-filter=K&element=tei:person/tei:persName

But it does show up in search:
https://syriaca.org/q/search.html?q=Kenan

Why would this be? Could it be related to the fact that there is no persName xml:id="name1336-1" with 1 on the id?

**Comment by wsalesky** [comment]
@davidamichelson this is fixed in the updated version.
