### ISSUE TITLE
Taxonomy reboot

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#1269]
@wsalesky I've uploaded the new taxonomy files into srophe-app-data. Some of the features we used to have should only be rebuilt once we get new RDF from the records. I think it's best to streamline everything now. Hopefully that will make this a pretty easy job. 

Browse Page:
This seems to be working fine as is. We should simply remove the "Categories" and "Advanced Browse" tabs. We've made some changes to the TEI and we'll want to use the RDF to display these once we serialize that new data. For now, simple browse is sufficient.

Record Page:
I've made notes in this image. Hopefully that works alright. For the most part, this should work like our other data types so again I hope this is pretty easy.
![record](https://user-images.githubusercontent.com/4984270/157964118-735d5b49-ef4a-4ace-b224-e8605db43689.jpg)
![record2](https://user-images.githubusercontent.com/4984270/157964163-0e1fc30f-e546-4f41-9907-3b3d335edc9c.jpg)

Thanks Winona. Please let me know if you would like me to create individual issues for each of these.

**Comment by dlschwartz** [comment]
@wsalesky yes, these are on master. Here's the commit: https://github.com/srophe/srophe-app-data/commit/b8c0effe0e16e38faf7f8b660b51271cd0c250a3.

**Comment by wsalesky** [comment]
Done

**Comment by dlschwartz** [comment]
Thanks!
