### ISSUE TITLE
Changes to branding

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#133]
Thomas will create a logo with a g from Estrangelo Antioch of Talada

Use the maroon for the Gazetteer and use the blue from the alternate logo for Syriaca.org

**Comment by davidamichelson** [comment]
@wsalesky I have uploaded some logos here: https://github.com/srophe/srophe-eXist-app/tree/Module-Home-Pages/srophe-app/resources/img

**Comment by davidamichelson** [comment]
@wsalesky 

Here are some thoughts on colors:

Gazeteer: Orange/Brown as currently
Saints: Some kind of blood or dark red
Spear: A nice green
Persons: Keep purple as currently
Syriaca.org home page: Keep blue as currently

**Comment by jsaintlauren** [comment]
Hurray!!! 


So exciting!!

**Comment by wsalesky** [comment]
Sounds good. I'm working at night this week, so I will not get to it until later. Hopefully will have them up for tomorrow's meeting.

**Comment by wsalesky** [comment]
First pass at icons and colors up of development site.
