### ISSUE TITLE
New 404 for syriaca entity not found

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#138]
When someone clicks on a link (e.g. on geo/about.html) for a person or a bibl, the link is broken (404), but we want to tell people the entry is coming soon.  So we need a special 404 for http://syriaca.org/person/* and http://syriaca.org/bibl/* .

Dave needs to ask Dale about how to do this.

For now, I will comment out the links so they are not broken.  But I will need to put the links back in later.

**Comment by wsalesky** [comment]
This is a stale issue. Has been resolved for quite a while.
