### ISSUE TITLE
timeline for a single death-date

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#249]
I looked at the mockup for Ephrem's entry in persons, and his death date is 373, which is displayed on the timeline.  But I noticed, to the right of the 373 line is "Jan. 2," which seems to imply that he died on the stroke of the new year (not known to be false, but unlikely).  It would be better to have the default "zoom level" set to show decades, rather than hours.

I tried to "zoom out" to see what it would look like, and I could zoom out to show "Feb." to the right of the 373 line, but then it did not allow me to zoom out farther.  Is there a limit to how far it can be zoomed out?  A timeline which can only show two months at a time will have limited use for our lifetime data (necessarily mostly blank) in addition to being misleadingly over-precise for all of our dates (most of which do not have month data).

**Comment by wsalesky** [comment]
I finally had a chance to look into this. It looks like zoom level is capped at 10 (You can click 10 time in either direction). With one date on the timeline we get this odd looking timeline as @tacarlson has mentioned, it resolves itself if more dates are on the timeline, but there is not currently a way to set the scale. I can investigate other timelines widgets that may be more flexible.
