### ISSUE TITLE
Arabic Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#26]

**Comment by wsalesky** [comment]
See: https://github.com/srophe/srophe-eXist-app/issues/531

Still need list of Arabic letters before we implement, but the underlying code is in place.

**Comment by nathangibson** [comment]
Here are 2 files for Arabic alphabetization. They are csv but have a txt extension so I could upload them here.

**I recommend using the "simple" one**, unless, at some future date, we actually have a lot of weird characters in our Arabic names. The difference is that the "simple" one I reduced to only the characters in common use, whereas the "complete" one has characters I hardly ever or never come across in Arabic. (I also removed the ones labeled Farsi or Urdu from both files.)

I assume you can make some characters equivalent to others for alphabetizing? **Each row contains the equivalents.**

I doubt we want to get into the complexity of taking into account vowels or the doubled-consonant sign for our alphabetization. This would matter for a dictionary, but I doubt it will for us. Practically speaking, this means you will need to **strip out characters in the range U+064B - U+0656 before alphabetizing**. 

[ar-alphabetization-complete.txt](https://github.com/srophe/srophe-eXist-app/files/249496/ar-alphabetization-complete.txt)
[ar-alphabetization-simple.txt](https://github.com/srophe/srophe-eXist-app/files/249497/ar-alphabetization-simple.txt)

**Comment by tacarlson** [comment]
You will also need to ignore prefix ال for alphabetizing Arabic place names, and ابن for Arabic personal names.

________________________________

**Comment by nathangibson** [comment]
Yes — ال/أل/ٱل when it is attached to the front of a word and ابن/إبن/بن when it is a separate word.

**Comment by wsalesky** [comment]
Thank you @tacarlson and @nathangibson I will work something up and let you know when it is ready for evaluation.

**Comment by wsalesky** [comment]
i may need some hand holding to get the Arabic correct. @nathangibson, if you have time tomorrow?

**Comment by nathangibson** [comment]
Yep, I should be able to.

**Comment by nathangibson** [comment]
For display purposes (e.g., the alphabet at the top of the browse page), use the letters in the first column of the file I attached previously. (If you're viewing the file in a text editor, the first column might appear on the right since it is right-to-left text.)

**Comment by wsalesky** [comment]
Hum. I will put something up, and then you will have to vet it.

**Comment by wsalesky** [comment]
My less then elegant first stab. You can reorder the elements in the browse.xqm

https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/modules/browse.xqm#L324

See live on any browse page with lang='ar'
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/browse.html?lang=ar&sort=%DC%90

**Comment by nathangibson** [comment]
OK, just edited it (I think the right-to-left column thing caused some confusion, but it should be good now).

**Comment by nathangibson** [comment]
I'm not seeing any changes show up yet on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/browse.html?lang=ar&sort=%DC%90.

**Comment by wsalesky** [comment]
For the app I have to push the changes manually. (Safer that way) will do it tonight.

**Comment by nathangibson** [comment]
The letters in the header are correct now. 

If you need a label for the "Arabic Language" tab, you could use "اللغة العربية".

While we don't yet have many (if any) works with Arabic titles, we should have quite a few persons and place names. I tried persons, and only got 1 for the first letter and none for the other letters. (Not sure if it's supposed to be working yet or not.)

**Comment by wsalesky** [comment]
@nathangibson working on this today. Will ping you if I need any help with sorting etc. Thanks for reordering.

**Comment by wsalesky** [comment]
Okay, here is a trial run, with sorting and filtering. I'm sure we will need to adjust how the filtering works. 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?lang=ar&sort=%D9%B1

**Comment by wsalesky** [comment]
Also, I tried filtering out characters in the range U+064B - U+0656 before alphabetizing, let me know if it is successful. And if not, I will need some very specific examples. For fixing. Thanks!

**Comment by jsaintlauren** [comment]
Wow!!!
Impressive.

**Comment by wsalesky** [comment]
Great! This can easily be plugged into any collection, so once we have debugged it we can hook it up on the other relevant collections.

**Comment by nathangibson** [comment]
Sorry, was in class. Will check it in a moment.

**Comment by nathangibson** [comment]
Not sure why, but this seems to have reverted back to displaying at the top the first version of the Arabic alphabet instead of the version I corrected it to yesterday. Should I correct it again?

**Comment by wsalesky** [comment]
Hum, yes please, I must have accidentally overwritten it. Sorry!

**Comment by nathangibson** [comment]
OK, I've corrected that. It looks like lines 134-143 are also affected. Should I correct that too?

I've gone through each letter and the filtering is working great! Also, "ال" is being ignored as it should be.

However, I can't make any sense of the sorting order. Is the sorting definitely on?

**Comment by nathangibson** [comment]
When the name parts are marked with a sort attribute, can we filter and sort them in order of the sort attribute value? E.g., person/215 should be treated as "هارون، الراهب" and filed under "ه" instead of "ر". 

`<persName ...>
<addName type="untagged-title" sort="2">الراهب</addName><forename sort="1">هارون</forename></persName>`

**Comment by nathangibson** [comment]
A couple display issues: 
 1. Spaces/line breaks between Arabic name parts are being eliminated when displayed on the browse page. E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/215 correctly shows "الراهب هارون" on the record view, but shows "الراهبهارون" on the browse. Can we preserve spaces in the browse view the same as you've done for the record view? 
 2. Can we emphasize the Arabic names more in the Arabic browse view? E.g., to put the Arabic name on the same line with the English and Syriac and make it the first one (if reading from right-to-left)?
[English name] - [Syriac name] - [Arabic name]
Also, it would be great to make the proportion of the Arabic font size to the English the same as it is in the "Names" section of the record view.

**Comment by nathangibson** [comment]
OK, I think that's all from the fire hose for now. Thanks for all your work on this! I had never appreciated how difficult alphabetization is (especially in Arabic) until now!

**Comment by wsalesky** [comment]
Thanks @nathangibson!
Lines 134-143 should not be a problem, order is not important there. 

I added a Arabic collation, but I think I need to do some more work to get the names to use the sort order attribute. Hope to get it up today.

**Comment by wsalesky** [comment]
@nathangibson can you tell, is it ignoring characters in the range U+064B - U+0656?

**Comment by nathangibson** [comment]
Hmm, I can't really tell at this point b/c it still doesn't seem to be sorting alphabetically at all. 

The spaces are showing up in names now, though.

**Comment by wsalesky** [comment]
Okay. Well next up is making sure the sort attribute is being used correctly. Hopefully that will help.

**Comment by nathangibson** [comment]
Let me know if you need examples.

**Comment by wsalesky** [comment]
Okay, how about now?

**Comment by nathangibson** [comment]
It's much better -- on the whole, it's working, but there are some minor issues. I'll round those up and give them to you one at a time. 

I think it is correctly ignoring characters U+064B - U+0656, but it is a little hard to tell since we don't have very many of those characters in our dataset yet.

**Comment by wsalesky** [comment]
Okay. Well we can always adjust as we get more data.

**Comment by nathangibson** [comment]
It looks as if there's still no spacing between name parts. (Perhaps this is causing some other issues with alphabetization too?) Spaces are only showing up when they are inside a single name part. E.g., 
`<forename sort="1">ابرهيم</forename><addName type="untagged-title" sort="2">اسقف تلبسم</addName>`
Should be "ابرهيم اسقف تلبسم" but instead it is "ابرهيماسقف تلبسم".

**Comment by wsalesky** [comment]
Can I have the URI for that name?

**Comment by nathangibson** [comment]
Sorry, it's http://syriaca.org/person/221

**Comment by nathangibson** [comment]
So far it seems that "ال" on the beginning of a word is correctly being ignored.

**Comment by nathangibson** [comment]
I don't understand why person/208 is coming before person/198. It doesn't seem to be a sort attribute issue. The forename is the same, but the next name part for each of them (addName sort="2") should make person/198 come first.

**Comment by nathangibson** [comment]
FWIW, TextWrangler agrees with me :-)

**Comment by wsalesky** [comment]
Okay, so let's clarify. :) 
Are the nameParts sort='2' not sorting correctly perhaps? I have the nameParts ordering on the sort attribute, so, I'm frankly not sure how it handles the two with sort=2. We may have to add a secondary sort.

**Comment by wsalesky** [comment]
How about now? I added a secondary alphabetical sort.

**Comment by nathangibson** [comment]
That fixed it!

**Comment by wsalesky** [comment]
Excellent! This is an interesting process. ;)

**Comment by nathangibson** [comment]
:-)

Something interesting is going on with two "Davids" (273 & 144). The sort=1 name for both of them is "داود", so they should show up on the "د" page, whereas they appear on the "ا" page. However, the sort attribute is being taken into account for ordering the names, since they are grouped together.

**Comment by wsalesky** [comment]
Ops. I add the new sort only the view function, not to the 'filter' function. Should be fixed now.

**Comment by nathangibson** [comment]
Great, that fixed it!

**Comment by nathangibson** [comment]
OK, I'm about to stop for the evening. I'll give you the rest of what I come up with in the next 15 min.

**Comment by nathangibson** [comment]
Actually, it's looking in really good shape. Filtering is working well based on sort attributes. The spacing between name parts is mostly fixed, but I did catch this one that is run together: "ايلياالراهب" (person/63) instead of "ايليا الراهب".

**Comment by nathangibson** [comment]
Other than that, I'm satisfied with leaving this in its current state.

**Comment by wsalesky** [comment]
Awesome. Thanks and have a good night.

**Comment by nathangibson** [comment]
Please add to all modules

**Comment by wsalesky** [comment]
Added Arabic browse to all modules. Other language tabs can be added on a module-by-module basis using the following code:

`<li data-template="browse:tabs" data-template-text="English" data-template-param="lang" data-template-value="en" data-template-sort="A"/>`

With:

- data-template-text = The text to appear on the tab
- data-template-param = 'lang' (the language parameter passed to the browse function, do not change)
- data-template-value = The language code for desired language.
- data-template-sort = First letter to sort on.
