### ISSUE TITLE
Write script to add URIs to Spear data

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#262]

**Comment by davidamichelson** [comment]
@wsalesky Okay this is done, see new data in the draft data for Spear.

**Comment by wsalesky** [comment]
Opps, looks like URIs are not allowed in the xml:id after all. Sorry! We will have to be somewhere else. I can do a find and replace to remove the uri, and insert it elsewhere. I have to do an update on the data anyway, to replace bibl id's. 

In the <bibl type="primary"><biblScope type="pp"><ptr target="#bib633-1"/>1</biblScope></bibl>
target="#bib633-1"
should be:
target="#bibl633-1"
Missing the 'l', once that is fixed the sources should work as well.
