### ISSUE TITLE
Bug in constructing person url in spear

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#271]
See http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/person/780 and http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe/spear/factoid.html?id= http://syriaca.org/person/780 (with space)

**Comment by wsalesky** [comment]
There are spaces in the data: <persName ref=" http://syriaca.org/person/780">
Data still needs to be uploaded to draft data folder.
