### ISSUE TITLE
Better error handling for page not found

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#280]
Edit controller.xql to better handle page not found errors

**Comment by wsalesky** [comment]
Think 404 and 500 errors will need to be handled by Dale. 
Redirects should be put in place to direct users to: /404.html or /error-page.html

**Comment by nathangibson** [comment]
Probably this is related -- I noticed that when I try looking up a URI that doesn't exist in the Gazetteer, e.g., http://syriaca.org/place/10000, I get a blank page instead of a 404.

**Comment by wsalesky** [comment]
@nathangibson thanks, yes, that should go on this issue as well.

**Comment by wsalesky** [comment]
@davidamichelson I think this can be closed.
