### ISSUE TITLE
Main menu on landing page (of dev server for now)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#285]
Currently reads:  gazetteer     persons     spear     manuscripts     documentation

Should read: Gazetteer  Persons  Authors  Saints   SPEAR     MSS     documentation

We can decide later if instead some of these should have drop down menus, but for demo and information purposes it would be good for each to have their own index.html page.

in terms of the URLS we can work that out later too.

**Comment by davidamichelson** [comment]
Just to clarify, Persons should have all persons as now. Saints should lead to  http://wwwb.library.vanderbilt.edu/saint/index.html and we should create a new one for authors that will be http://wwwb.library.vanderbilt.edu/authors/index.html

**Comment by davidamichelson** [comment]
Please change persons to SBD

**Comment by davidamichelson** [comment]
Make uniform across all headers

**Comment by davidamichelson** [comment]
On main Syriaca.org Landing page please add second line to header and in second line include logos for each module. First line can now read Syriaca.org: Syriac Reference Portal.

On each module landing page no need for logos.

In the drop down menu include the logos please.

**Comment by wsalesky** [comment]
@davidamichelson  We still need an icon for manuscripts.

**Comment by davidamichelson** [comment]
I've uploaded it to resources in the Dev branch now, but don't worry if you don't have time.

**Comment by wsalesky** [comment]
@davidamichelson 
Just finishing up this issue, I have two versions of saints:
Qadishē or Saints, which should be used in the navbar?

Here is what I plan on having, let me know if I overlooked anything. Thanks!
Gazetteer SBD Authors Saints SPEAR MSS documentation
