### ISSUE TITLE
How to display person entries that are part of both persons and authors and or saints.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#288]
For all authors and saints display the logo below the header and have it be a live link to the landing page for authors or saints.

When a person is in both authors and saints, split the logos both at top of the page.

Place this above the headword.

**Comment by wsalesky** [comment]
@davidamichelson Here is an example of a person who is also a saint. Let me know if this works for you, or if it is not prominent enough:

http://wwwb.library.vanderbilt.edu/person/1108

**Comment by davidamichelson** [comment]
Hmm, I think it will need to be more prominent, but this is a great start!

**Comment by wsalesky** [comment]
Move to below uri, make larger:
This entry is a part of: all submodules. 

Make index, a dropdown to all submodules included.
