### ISSUE TITLE
Spear Visualization Issues on Dates

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#309]
@wsalesky Here are some issues to fix.

There are a couple of issues. First when we have a date with a corr and sic, we need to visualize both dates: http://wwwb.library.vanderbilt.edu/spear/factoid.html?id=http://syriaca.org/spear/633-119

Would it be possible to include it by both dates in a list and the timeline?

Also, we have some odd dates that use reg and orig:
http://wwwb.library.vanderbilt.edu/spear/factoid.html?id=http://syriaca.org/spear/633-60

These also need visualize differently, should sort based on reg and included the text node for orig in parenthesis. Also note there is an escaped back slash in the html for some reason.

One more date edit is here: http://wwwb.library.vanderbilt.edu/spear/factoid.html?id=http://syriaca.org/person/Anonymi09

For some reason the A. Gr. date is not in parenthesis as it is elsewhere (see http://wwwb.library.vanderbilt.edu/spear/factoid.html?id=http://syriaca.org/spear/633-129). Is this an issue in the TEI.

**Comment by wsalesky** [comment]
@davidamichelson - Can we go over this on Wednesday? I think it is mostly fixed.
