### ISSUE TITLE
Timeline in Spear

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#310]
How does the timeline format the headings and body of each element in the timeline? Can we edit this at all?

**Comment by wsalesky** [comment]
We can change the format a bit. I'm not entirely sure how flexible it is. So you want to give me a wish list, and I will see what I can do?

**Comment by wsalesky** [comment]
@davidamichelson any thoughts on what/how you would like to customize headings?

**Comment by wsalesky** [comment]
Either suppress heading, or change so date is heading.

**Comment by wsalesky** [comment]
I think this can be closed. The date is the heading currently.
