### ISSUE TITLE
Person factoids which contain multiple URI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#311]
@wsalesky When a person factoid (persName) contains child perseName elements with other URIs in them, please ignore these child elements for indexing as a person factoid.

For example, in this bit of code:https://github.com/srophe/draft-data/blob/master/data/spear/tei/ChronEdessa_Complete_Draft_Newer.xml#L3859

The description of http://syriaca.org/person/Anonymi10 contains http://syriaca.org/person/Anonymi9, but we do not want http://syriaca.org/person/Anonymi10 to display on the page for http://syriaca.org/person/Anonymi9 but it does currently: http://wwwb.library.vanderbilt.edu/spear/factoid.html?id=http://syriaca.org/person/Anonymi09

NEVERMIND THE ABOVE, instead we need better labeling and a list of name variants

**Comment by wsalesky** [comment]
Link to factoid from person/events display?

**Comment by wsalesky** [comment]
Add name variants. Name variants include all text nodes.

**Comment by davidamichelson** [comment]
All factoids listed in boxes should link to the factoid not to the person or place URI

**Comment by wsalesky** [comment]
Add link to factoids from person factoid box. 
Sort results of person factoids box.

**Comment by wsalesky** [comment]
I think this can be closed. Updates on other bugs seem to have resolved this.
