### ISSUE TITLE
Nitpicky: place records changelog //change/@who has space before xml:id

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#312]
I was looking at several place records yesterday and it seemed that in every case, the `@who` attribute on the `<change>` element in the change log had an extra space before the xml:id of the editor responsible for the change.  I think this is valid TEI, but not standard.  Is it worth "fixing" by removing any leading spaces there?  Or are they being used for something?

**Comment by wsalesky** [comment]
The spaces are not useful, but also not causing a problem. I would recommend leaving them for now. Before we do our next data release, I can change them.
