### ISSUE TITLE
perhaps hide "simplified" names added only for search functionality?

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#314]
E.g. place/2264 has four names added to enable easier searching (Aqra, ‘Aqra, Aqrā, and ‘Aqrā), in addition to the headword (ʿAqra) and the form of the name found in our source (ʿAqrā).  Should we hide the four names added for search functionality?  They have no source, although we'd wish to show any of them for which we actually had a source, and of course we always wish to show the syriaca-headword form.  So perhaps the logic should be something like:

`If( not (#syriaca-simplified-script) or @source or #syriaca-headword) then show name`

**Comment by wsalesky** [comment]
@tacarlson yes, that sounds reasonable to me. @davidamichelson?
