### ISSUE TITLE
Need a form/widget that identifies next available URI and allows one to claim it.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#316]
@wsalesky @tacarlson We need to figure out how to allow claiming numbers even when there is not a file.

**Comment by davidamichelson** [comment]
Could the exist app read a published google sheet?

**Comment by davidamichelson** [comment]
Okay for now @tacarlson create a google doc let's hold off on more than that.

**Comment by davidamichelson** [comment]
@wsalesky Let's discuss this on Wed. Please.

**Comment by wsalesky** [comment]
Done.
