### ISSUE TITLE
Gazetteer Enhancement: Next page of search results at bottom of result page

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#318]
At present, if there are more than 20 search results for the Gazetteer, you have to scroll back up to the top of the page to click on subsequent pages of results.  It would be great if we could duplicate the links to subsequent pages of results at the bottom as well as the top of the page.

**Comment by wsalesky** [comment]
Change made on dev, merge change into Prod as well.

**Comment by wsalesky** [comment]
Added to production site as well.
