### ISSUE TITLE
Gazetteer Enhancement: Adding other names to the Browse list?

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#320]
At present only headwords are listed on the browse list.  Should we add other place names to the browse list.  I don't think it needs to be the case that every place is in the browse list in only one place.  If we did so, we'd wish to exclude names automatically generated for the purpose of broader search results (e.g. with different kinds of apostrophes), so perhaps the rule should be to index any name that is the headword (inclusive or) has a source attribute.  Then the question would be whether or not to index names that are pointed to by deprecation notes because they're so bad.

These enhancements are not highest on the priority list, of course.  I just enter them here so that we have a record of thinking of them, in case we have the opportunity to improve the Gazetteer at some point.

**Comment by wsalesky** [comment]
This was added in the development branch. See: modules/lib/short-rec-view.xqm
