### ISSUE TITLE
URIs and Landing Page URLS

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#325]
URIs for Data:

syriaca.org/person
syriaca.org/work
syriaca.org/place
syriaca.org/object*
syriaca.org/tag*
syriaca.org/manuscript
syriaca.org/spear

Landing Pages:

syriaca.org/geo
syriaca.org/spear
syriaca.org/q
    syriaca.org/lives
    syriaca.org/saints
syriaca.org/persons
syriaca.org/authors
syriaca.org/texts
syriaca.org/mss
syriaca.org/tags*
syriaca.org/objects*

*not currently underdevelopment

**Comment by wsalesky** [comment]
@davidamichelson  
Are 
syriaca.org/q
and 
syriaca.org/saints
the same thing?

**Comment by dlschwartz** [comment]
I believe that "saints" is the landing page for the Gateway to the Syriac
Saints and that "q" and "lives" are for each of the two components of the
Gateway.

On Tue, Apr 7, 2015 at 11:38 AM, Winona Salesky <notifications@github.com>
wrote:

> @davidamichelson <https://github.com/davidamichelson>
>
> Are
> syriaca.org/q
> and
> syriaca.org/saints
> the same thing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/srophe/srophe-eXist-app/issues/325#issuecomment-90640274>
> .
>



-- 
Dr. Daniel L. Schwartz
Assistant Professor
Department of History
Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

**Comment by wsalesky** [comment]
Oh, yes, that sounds familiar. Thank you!
