### ISSUE TITLE
Embedded Syriac Fonts

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#338]
For HTML and PDF.

**Comment by wsalesky** [comment]
@davidamichelson There are a number of fonts in the zip file, do we want to include them all on the server, it looks like we currently only use: Estrangelo Edessa, Serto Batnan, and East Syriac Adiabene. 

Also, are I am assuming they are open source and can be included in the github repository. Let me know if that is not the case. Thanks!
-Winona

**Comment by davidamichelson** [comment]
I will check on this and get back to you.

**Comment by wsalesky** [comment]
I believe this can be closed.
