### ISSUE TITLE
Admin module not displaying attestations or footnotes correctly

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#343]
I went to the admin module (and by the way I love the pending/approved marking down the line!) and navigated to the in-process record for place/801 (Atel).  Since this issue is publicly visible, I won't paste the link here.  The attestation and footnotes for the record were not displayed correctly, but were given just as plain text (with the exception of the footnote "2" after the attestation) as if they were just dumped from the TEI:

Attestation of name ܐܵܬܹܝܠ in a note in Jerusalem, Saint Mark's Monastery, Ms. 181 [HMML SMMJ 00181]. (not before 1633-09-01, not after 1634-08-31) 2
David WilmshurstThe Ecclesiastical Organisation of the Church of the East, 1318-191382, 85-86, 91, 114Jerusalem, Saint Mark's Monastery, Ms. 181 [HMML SMMJ 00181]358v

**Comment by wsalesky** [comment]
@tacarlson Should be fixed.
