### ISSUE TITLE
Gazetteer advanced search leads to HTTP 500 error

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#351]
HTTP Status 500 - An error occurred while processing request to /exist/apps/srophe/place/search.html: Cannot forward after response has been committed

type Exception report

message An error occurred while processing request to /exist/apps/srophe/place/search.html: Cannot forward after response has been committed

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: An error occurred while processing request to /exist/apps/srophe/place/search.html: Cannot forward after response has been committed
	org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:383)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:164)
root cause

java.lang.IllegalStateException: Cannot forward after response has been committed
	org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50)
	org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:567)
	org.exist.http.urlrewrite.XQueryURLRewrite.applyViews(XQueryURLRewrite.java:416)
	org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:371)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:164)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.50 logs.

Apache Tomcat/7.0.50

---
I was on http://syriaca.org/place/341 when I clicked the "advanced search" button.

**Comment by wsalesky** [comment]
Thank you Thomas! Fixed.
