### ISSUE TITLE
Admin module does not allow changing status without posting comment

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#355]
Changing the status on a record in the admin module does not work if no text is entered into the comment box.  The comment can be deleted afterward, but it would be nice to separate the two functionalities of record status and record comments.

**Comment by tacarlson** [comment]
Okay, now I can't even get that to work.  On place/104, I enter my name, email address, new record status, and comment text, and click "submit," and it reloads the page without my comment and with a cleared form.  Returning to the records list shows the same status, even after refreshing the page.  Most oddly, that also reverted the status on place/993 to "Pending", though I had earlier successfully changed its status to "Approved."

**Comment by wsalesky** [comment]
I will try to add this functionality in. The approval method is pretty primitive, and a record can not currently be un-approved, which I would think would be useful in the future as well.
