### ISSUE TITLE
Admin module is no longer allowing me to upload new records

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#356]
I broke the Admin module.  Sorry!  When I attempt to upload new records, it gives me the following exception:

```
<exception>
<path>/db/apps/srophe-forms/modules/upload.xql</path>
<message>
exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 8, column 15]
</message>
</exception>
```

**Comment by wsalesky** [comment]
@tacarlson just to let you know I am working on this. It is baffling as all the permissions are set correctly.

**Comment by wsalesky** [comment]
@tacarlson Please try now and let me know. I did all my testing logged in as you and have been able to consistently add, delete and comment. Let me know if you have any trouble, and please attach any relevant error messages to the issue. Thanks, and sorry for the delay!
