### ISSUE TITLE
For some person files the description and date are not showing in the search preview

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#360]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=Daniel

See item number 4 in the results (e.g. http://wwwb.library.vanderbilt.edu/person/1203). Should display a floruit date and a description in the result list.

**Comment by davidamichelson** [comment]
While we are at it here is a revision of how we would like the search result page to display:

Display sorted by date.
Display date, full description, and URI for each result.
Create an algorithm in which results whose TEI files only have one source (bibl) are relegated to a separate list of results at the bottom of the list.


1. Daniel bar Ṭubanitha  - ܕܢܝܐܝܠ ܕܛܘܒܢܝܬܐ
(author, 550 — 750, 7th cent.?)
Bp of Tahal in Beth Garmai, URI: http://syriaca.org/person/439

2. Daniel of Mardin - ܕܢܝܐܝܠ ܡܪܕܝܢܝܐ 
(author, 1327 Birth)
Author. URI: http://syriaca.org/person/256

**Comment by wsalesky** [comment]
Note to self: xquery may only be displaying tei:desc, abstract for this record is in tei:note@type=abstract.

**Comment by wsalesky** [comment]
Note to self: change saints transform to use tei:desc rather then tei:note

**Comment by wsalesky** [comment]
Sort by: relevance, date, apha.

**Comment by wsalesky** [comment]
Some records do not have birth/death dates, but do have floruit:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/308

Should I use this date in the display?

**Comment by wsalesky** [comment]
@davidamichelson  

Also, what dates should I be sorting by, just birth and death? Include floruit? Any dates?

**Comment by wsalesky** [comment]
Current implementation uses birth date, if no birth, uses death date. Dates are not used for sorting in gazetteer.

**Comment by wsalesky** [comment]
Still need to deal with scoring resources with only one bibl lower.

**Comment by wsalesky** [comment]
Relevance now based on internal lucene ranking * num of tei:bibl elements.
