### ISSUE TITLE
incorrect citation style for journal articles

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#362]
Footnote 5 on place/168 currently reads:
Jacques Marie Vosté, “Les inscriptions de Rabban Hormizd et de N.-D. des Semences près d’Alqoš (Iraq)” in , Le Muséon (n.p.: n.p., 1930), pp: 266-268, 271-272, 274-276, 281-284, 286-287.

It ought to read:
Jacques Marie Vosté, “Les inscriptions de Rabban Hormizd et de N.-D. des Semences près d’Alqoš (Iraq),” *Le Muséon* 43 (1930), pp: 266-268, 271-272, 274-276, 281-284, 286-287.

The journal information is embedded in the `<monogr>` element (because that's what TEI requires), so our citation transformer is apparently expecting an editor, publication place, and publisher, which are not relevant for journal citations.  On the other hand, the volume number is encoded as `<biblScope unit="vol">` within the `<monogr>` and is currently ignored by the citation transformer.  I think the clearest flag on a bibl entry that this is a journal rather than an actual monograph is that the  `<monogr>/<title>` has `level="j"`.

**Comment by wsalesky** [comment]
@tacarlson Sorry, just getting to this. What citation style are we using? I will create a new template for journals.

**Comment by tacarlson** [comment]
Eh, we're kinda using something like Chicago style, but not exactly like. =-)  I'm thinking for journals:

Author, "Title," *Journal Title* Vol# (date), pp: page#s.

**Comment by wsalesky** [comment]
Okay. Working on it now. Will be working through the other citation issues as well.
