### ISSUE TITLE
missing partial citation information on admin module

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#363]
For place records http://wwwb.library.vanderbilt.edu/exist/apps/srophe-forms/place.html?id=http://syriaca.org/place/2578 and http://wwwb.library.vanderbilt.edu/exist/apps/srophe-forms/place.html?id=http://syriaca.org/place/582 the last footnote only has the journal and date information from the bibl record, not the article author and name.  It currently looks like:
, Harvard Ukrainian Studies (n.p.: n.p., 1983), pp: 405-430.

when it should look like
Marlia Mundell Mango, "Where was Beth Zagba?" *Harvard Ukrainian Studies* 7 (1983), pp: 405-430.

This sort of citation is handled more correctly in the Gazetteer (see previous issue), so I wonder whether the citation handler in the Admin module has gotten out of sync with that in the Gazetteer code.

**Comment by wsalesky** [comment]
Handled by latest commit. 74fcd5ae2512f1fe22c5bb0f73b6f5ab4509b455
