### ISSUE TITLE
Mystery bug: cannot approve one place

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#365]
Here's a strange bug: I was able to approve other place records, but http://wwwb.library.vanderbilt.edu/exist/apps/srophe-forms/place.html?id=http://syriaca.org/place/2559 does not allow me to change its status to approved, even with adding a comment.  Any ideas?

**Comment by wsalesky** [comment]
There was already an empty comment file, I may have created it while testing, and the permissions were off. I deleted the old comment file and approved the record.
