### ISSUE TITLE
Bibliography: not citing chapter within book

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#370]
The footnote on http://syriaca.org/place/2563 presently cites Li Tang and Dietmar W. Winkler (eds.), *From the Oxus River to the Chinese Shores: Studies on East Syriac Christianity in China and Central Asia* (Berlin: LIT, 2013), pp: 347, 351.

What it should cite is Jasmine Dum-Tragut, "Assyrians in Armenia: An Interdisciplinary Study" in Li Tang and Dietmar W. Winkler (eds.), *From the Oxus River to the Chinese Shores: Studies on East Syriac Christianity in China and Central Asia* (Berlin: LIT, 2013), pp: 347, 351.

The relevant bibl record is http://syriaca.org/bibl/656

What makes this confusing is that this sort of case is already handled for articles within GEDSH (e.g. http://syriaca.org/place/137 cites Takahashi's article).  Looking at the TEI for place/137 seems to indicate that the citation does not come from http://syriaca.org/bibl/385 (Takahashi's article), but instead the TEI only cites http://syriaca.org/bibl/1 (GEDSH).  In other words, this seems to be a hack which is now biting us, and we need to figure out how to make the bibliography generator deal with actual articles/chapters within a larger work.

**Comment by wsalesky** [comment]
I think there is some confusion, at least on my part about what information to use from the place record and what to use from the bibl record. Currently reason this does not work is because the title in the the place record is not marked as level='a'. Take a look at it now, when I added level='a' to the TEI on the dev server: http://wwwb.library.vanderbilt.edu/place/2563.html

It is closer (still would need some work).

**Comment by tacarlson** [comment]
The way I understand it, both the level='a' title and the level='m' title should be taken from the bibl record; the `<title>` in the place record is only for human readability.  I think only the `<citedRange>` should be taken from the place record for the displayed footnote.  This is clearly not how we're doing it with the GEDSH article citations, which cite the bibl URI for the GEDSH volume rather than the bibl URI for the GEDSH article (though each article has a bibl record).  So I think we'll need to find a workflow to put those article URIs into the earlier records.  I could probably do that with XSLT.

**Comment by wsalesky** [comment]
Okay. Well, I will adjust the bibliography xslt, and then we can figure out the best way to get those article URIs into the necessary records.

**Comment by wsalesky** [comment]
@tacarlson How does this version look?
http://wwwb.library.vanderbilt.edu/place/2563.html

**Comment by wsalesky** [comment]
@tacarlson just checking in with you on this citation issue. I believe it has been resolved.

**Comment by tacarlson** [comment]
That looks good!  My only quibble is that a comma would be nice after the chapter title (unless the chapter already ends with a punctuation mark of some kind, if that's possible).  But this is good as is.  Thanks!
(Sorry for the delay: medical road trip and then start of semester.)
