### ISSUE TITLE
Weighting search results

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#374]
Weighting search results for places
1. First if in placeName
  a. exact hits rank higher than partial match
  b. Weight subsets by place type: settlement, diocese, region
2. Search term in desc
3. Search term in record

Weighting search results for persons
1. First if in persName
  a. exact hits rank higher than partial match
2. Search term in desc
3. Search term in record

**Comment by wsalesky** [comment]
Preliminary work done, ranking should be slightly better. Have not factored in place types. Review of current (dev) results list would be useful. @davidamichelson @tacarlson 

example search: http://wwwb.library.vanderbilt.edu/geo/search.html?q=edessa
compared with : http://syriaca.org/geo/search.html?q=edessa

**Comment by tacarlson** [comment]
Ranking looks better to me!  Thanks!

**Comment by wsalesky** [comment]
Great!
