### ISSUE TITLE
Dev Server Works Visualiztion

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#397]
These comments can be see in this record:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/251

Please change the labels as follows:
Add whitespace and plural in label: AncientVersion -> Ancient Versions
Add whitespace and plural in label: ModernTranslation -> Modern Translations

In the Ancient Versions sections, please add a prefix to each entry generated from the language code of the bibl. Thus in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/251
The HTML should read:

Ancient Versions
Soghdian: N. Sims-Williams, The Christian Sogdian Manuscript C2, (Schriften zur Geschichte und Kultur des Alten Orients. Berlin Turfantexte 12) Berlin 1985, p. 154-157.

The key to these language codes can be taken from the XSLT function:
Latin = la
Greek = grc
Arabic = ar
Armenian = hy
Georgian = ka
Soghdian = sog
Slavic = cu
Coptic = cop
Ethiopic = gez
Syro-Palestinian = syr-pal
Karshuni = ar-syr

Lastly, the bullets are appearing in multiple sizes again but that can wait til last.

Thanks!

**Comment by davidamichelson** [comment]
I guess order the languages by alphabetic please.

**Comment by wsalesky** [comment]
Fixes all, including the bullets. The footnote size remains problematic.

**Comment by wsalesky** [comment]
Opps, missed that last comment. Will try to get them ordered tomorrow.

**Comment by davidamichelson** [comment]
You are too much of a great thing! Thank you.
