### ISSUE TITLE
Feature request: "Dashboard" for each submodule

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#401]
Number of records
Number of contributors
Number of data points (count tei:body/descendant::*/text() )

**Comment by wsalesky** [comment]
@davidamichelson A sample of the "Dashboard" feature up on the dev server for the Gazetteer: 
http://wwwb.library.vanderbilt.edu/geo/index.html

We can talk about refining during our meeting. Will be simple to plug in for all submodules and even on the home page if desired.

**Comment by davidamichelson** [comment]
Change "Records" to "Places"
Change Details sentence: This number represents the count of places currently described in the *Syriac Gazetteer* as of [Current Date].

Re: Contributors
Changes Details sentence to: This number represents the count of contributors who have authored or revised an entry in the *Syriac Gazetteer* as of [Current Date]. [Then list the contributors by alphabetical, please].

Re: Data Points
Changes Details sentence to: This number is an approximation of the entire data, based on a count of XML text nodes in the body of each TEI XML document in the *Syriac Gazetteer* as of [Current Date].
