### ISSUE TITLE
Fixing Titles of Works TEI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#403]
Hi @wsalesky ,

I have fixed the XSL except I can't get the title of the document to match the new headwords. Could you try to fix it please.

Also, my machine no longer wants to convert the CSV. The latest CSV is here: https://github.com/srophe/draft-data/tree/master/data/works/Zanetti_XSL_Conversion, could you please run it and upload the results please?

Thanks,
DM

**Comment by davidamichelson** [comment]
I found it the Header template and fixed. but please do upload the CSV.

**Comment by wsalesky** [comment]
Done!
