### ISSUE TITLE
Please reorder data in Works Visualizations

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#406]
Please list Prologues, Incipits, Explicits before Editions on the page.

**Comment by wsalesky** [comment]
In what order would you like: Manuscripts, Modern Translations, Ancient Versions?

**Comment by davidamichelson** [comment]
Order should be: Prologue, Incipit (Opening Lines), Explicit (Closing Lines), Editions, Modern Translations, Ancient Versions, Manuscripts.

**Comment by davidamichelson** [comment]
Thanks!
