### ISSUE TITLE
Change the IDNO visualizations for Works

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#407]
In the gray box please make the following change based on example for record:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/250

Reference Numbers [Label]
Syriaca.org/work/250 = BHS: 29 = BHO: 1013-14

(please create a truncated version of the URI to lead the list)

**Comment by davidamichelson** [comment]
Note the URI for us should be hot clickable (but takes one back to the same page)

**Comment by wsalesky** [comment]
Why truncated? I would think we would want the whole URI?
