### ISSUE TITLE
For Works: Related Work

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#408]
Similar to the check and compare headwords in places, can we please  have a "related works" section that displays the works with same headword based on English or Syriac?

**Comment by wsalesky** [comment]
@davidamichelson my xquery did not find any matches, does that sound correct? perhaps I need to normalize-space() on the headwords?

**Comment by wsalesky** [comment]
@davidamichelson scratch that, bad xquery. I do get matches.

**Comment by wsalesky** [comment]
@davidamichelson Did we talk about how to visualize the relationships? I don't see it in the meeting notes. Essentially I want to translate the name attribute into an english sentence.  Building this as a module to handle all our relationships, so think broadly. 

Works: dcterms:subject
Persons: born-at, died-at, has-literary-connection-to-place
Places:  share-a-name, contained, contains

**Comment by davidamichelson** [comment]
Sorry this sat unanswered. Yes a module would be great! @nathangibson could you please start a documentation file with all of the relation terms we use?

For works: let's use "share-a-title" for works with the same head word please.

**Comment by wsalesky** [comment]
Okay. This is also tied to issue srophe/persons#3. I will try to keep them linked.

**Comment by davidamichelson** [comment]
Do you need feedback on this from me?

**Comment by wsalesky** [comment]
I think we need to create a list of "translations", how each of the above relationships should look in the HTML. It would be nice to be able to use generic enough language to use this module for all our relationships, across all the modules. 

Here is a link to the in process module so you can get an idea of what I'm talking about: 
https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/modules/lib/get-related.xqm

**Comment by wsalesky** [comment]
Change title to: 
"Relations"

**Comment by davidamichelson** [comment]
Just a note to ask if in the mean time we might implement the share a name relation. We will need to run analysis on the data. Please remind me to discuss.

**Comment by nathangibson** [comment]
I've added a documentation page for relations at https://github.com/srophe/srophe-eXist-app/blob/master/srophe-app/documentation/relations.html. Still needs some editorial discussion.

**Comment by wsalesky** [comment]
I have uploaded this to the dev server for review.

**Comment by nathangibson** [comment]
Thanks!

**Comment by nathangibson** [comment]
OK, @wsalesky , we've reviewed this and I've made the changes to the dev branch. Can we put the relations documentation page into production now? Or do we need to pull it into the master branch first?

**Comment by wsalesky** [comment]
Please add it to the master branch as well.

**Comment by wsalesky** [comment]
Oh, looks like it was pushed to master... not dev. That is fine, it can be rebased into dev.

**Comment by nathangibson** [comment]
Oops, sorry about that. Looks like I have to manually switch branches using the dropdown in the Github app even after I already did that for the pull. Weird.

**Comment by wsalesky** [comment]
I find the client to be a pain in the next, sadly sometimes it is just easier to use the command line. At least you always know where you are.

**Comment by nathangibson** [comment]
Hmm! Also, please note that we are deprecating the @type for relations. We will only be using @name, but we are including any categorizations of relations in our definitions. For your purposes, you'll want to note the "Vizualized as" column, as we'll probably ask you at some point to put e.g. "disambiguation" relations in one place on the page and others in the sidebar.

**Comment by wsalesky** [comment]
Okay. Thanks. Is it ready to go on the production server?

**Comment by nathangibson** [comment]
Yep!

**Comment by nathangibson** [comment]
Arrrgh, I don't understand. Looking at Github online, both the dev and master branches have the old (draft) version of relations.html, not the new one. The one one my computer is the updated one, but it's showing "0 changes" in the app. What do I do?

**Comment by wsalesky** [comment]
Sorry, that was my fault, I merged the commit the wrong way when attempting a rebase. Should be fine on master branch now, will need to take a look at dev.

**Comment by nathangibson** [comment]
OK, yes, that's correct on the master branch. Thanks!

**Comment by wsalesky** [comment]
Not sure I have ever gotten a rebase correct on the first try. Sorry.

**Comment by nathangibson** [comment]
No problem :-)
