### ISSUE TITLE
What are our three preferred Syriac fonts?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#409]
I can't seem to find the CSS where we force the use of three Syriac fonts (one for each script). Can you please remind me and also we should write that into the documentation. Please remind me to discuss.
Thanks!

**Comment by wsalesky** [comment]
Check in main.css line: 216:
https://github.com/srophe/srophe-eXist-app/blob/master/srophe-app/resources/css/main.css#L216

Three fonts are:
Estrangelo Edessa
Serto Batnan
East Syriac Adiabene
