### ISSUE TITLE
Add use of revisionDesc/@status for "approved" and "pending" records

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#410]
This would be useful in admin module.

**Comment by davidamichelson** [comment]
Okay so let's add the following values:
for now: "published" for fully approved and "draft" for unapproved.

Steps for W:
Please mark all Gazeteer data as "published" (that is in the data repo-places on production server).
Please mark all approved records in the admin module as "underReview".
Please mark all other TEI data as "draft".

@nathangibson Please document.

**Comment by wsalesky** [comment]
@davidamichelson @nathangibson @tacarlson @dlschwartz All new TEI records should be generated with a `<revisionDesc status="draft"> ` (or other approved term) on initial commit. @davidamichelson We may need a list of approved status terms.
