### ISSUE TITLE
bibl within notes is not bing output correctly by xslt

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#417]
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/297

**Comment by davidamichelson** [comment]
W, can you fix this or should we?

**Comment by wsalesky** [comment]
This is an xslt fix. Should be a quick fix, maybe by the end of the day today.

**Comment by davidamichelson** [comment]
Okay, if there are more things to do the XSLT let me know as I have some fixes to do myself.

**Comment by wsalesky** [comment]
Sorry, I meant this the tei2html.xslt. Change has been made.
