### ISSUE TITLE
Adding Partielle to Works Data

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#418]
Example document: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/297/tei

*Please write a regex/exquery that checks /TEI/text/body/bibl/note/bibl/author for the string ```(partielle)```
*If the string is found it should be deleted and the following attribute added to the bibl element of which author is a child: (TEI/text/body/bibl/note/bibl/ )```ana="partialTranslation"```

Examples.

Original:
```<bibl><author>Jansma, T. (partielle)</author></bibl>```
Change to:
```<bibl ana="partialTranslation"><author>Jansma, T. (partielle)</author></bibl>```

**Comment by wsalesky** [comment]
@davidamichelson Please spot check records.
