### ISSUE TITLE
Pre-Exist DB version of Gazetteer App still live?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#425]
@wsalesky @paregorios 

Dear Wonderful Developer Friends,

Somehow I just discovered that the pre-Exist DB version of the Gazeteer (hosted on http://srophe.github.io/) is still live. See http://srophe.github.io/srp-places-app/places/360.html

Could you please figure out how to take it down?

Thanks,
D

**Comment by paregorios** [comment]
This should be as easy as deleting the "gh-pages" branch on srophe/srp-places-app, I think.

**Comment by paregorios** [comment]
Shall I?

**Comment by wsalesky** [comment]
Yes please.

**Comment by paregorios** [comment]
Done. The e.g. link provided by @davidamichelson now returns 404.

**Comment by wsalesky** [comment]
Thanks @paregorios!

**Comment by davidamichelson** [comment]
Thanks All!
