### ISSUE TITLE
For Saints Persons without a <note> @type=abstract

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#428]
For any persons records where /tei:TEI/tei:text/tei:body/tei:listPerson/tei:person/@ana["#syriaca-saint"] without a /TEI/text/body/listPerson/person/note/@type[abstract]

Please auto generate a ```<note>``` of @type=abstract (/TEI/text/body/listPerson/person/note/@type) with the following information:

The note should be located immediately after the last /TEI/text/body/listPerson/person/persName

```[Person headword] is a saint commemorated in [work based on URI from 1st attestation in Person record= /tei:TEI/tei:text/tei:body/tei:listPerson/tei:person/tei:event/@type["attestation"][1]], a work by surviving in at least [count of manuscripts (/TEI/text/body/bibl/note/@type["MSS]) from work record] manuscripts including [1st manuscript in work record, /TEI/text/body/bibl/note/@type["MSS'][1]].```

Example record: http://wwwb.library.vanderbilt.edu/person/1998/tei and http://wwwb.library.vanderbilt.edu/work/890

```Pīlīpōs is a saint commemorated in Philip (text) [Syriaca.org/work/890]], a work surviving in at least 6 manuscripts including ms Berlin, Königliche Bibliothek, syr. 74 (Sachau 9), f. 52v-65v.```

```<note type="abstract" source="#bib[personURI#]-1"><persName ref="http://syriaca.org/person/[personURI#]">Pīlīpōs</persName> is a saint commemorated in <bibl ref="Syriaca.org/work/890">Philip (text) [Syriaca.org/work/890]</bibl>, a work surviving in at least 6 manuscripts including <bibl type="MSS">ms Berlin, Königliche Bibliothek, syr. 74 (Sachau 9), f. 52v-65v</bibl>.</note>```

Note: personURI#=the URI number of the record where this note is being inserted.
Note: when you pass through the bibl containing the "ms Berlin, Königliche etc." please add in an @type of MSS so we can tag it with an URI later.

**Comment by davidamichelson** [comment]
Keep the underlying XML bibl tags for the MS if you can.

'''<bibl>ms Berlin, Königliche Bibliothek, syr. 74 (Sachau 9), f. 52v-65v</bibl>'''

**Comment by davidamichelson** [comment]
Please source the note as source="#bib1998-1"

**Comment by davidamichelson** [comment]
I will give you the example here in TEI in a minute

**Comment by davidamichelson** [comment]
Okay its ready. Thanks!

**Comment by wsalesky** [comment]
Please review and comment on new additions. Thanks!

**Comment by wsalesky** [comment]
Remove tei:quote from generated notes and change text: 'manuscripts including' to 'manuscripts, including'

**Comment by wsalesky** [comment]
I believe these changes have all been made.
