### ISSUE TITLE
Saints Overlap Records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#429]
Hi Winona,

To document there here is a list of the URIs of the overlap records. When you have time, could you please check to see where they ended up? If it turns out we need to rerun them from the spreadsheet please let me know first because I see there are two URI 9 and two for URI 856 and I will fix that in the spreadsheet first.

One other odd note, URI 1093 shows up here but is also in the incomplete folder.

For reference:
In previous times of running the TEI from the spreadsheet it sorted out those who had a syriaca.org uri into their own folder called “Overlap”: see this older version: https://github.com/srophe/draft-data/tree/930944c1727d1bd63951fcfbc128bc4a741334e3/data/saints/overlap

The URIs in question include 
13.xml 	

173.xml 	

209.xm

Thanks,
Dave

9
9
10
13
25
26
42
44
50
51
52
57
67 or 325
69
75
93
97
106
113
122
126
145
170
173
209
212
227
238
271
306
315
320
321
326
354
356
360
366
376
423
430
451
452
477
511
512
513
530
544
550
561
573
624
628
635
637
650
655
680
709
721
744
779
780
784
785
809
811
821
825
826
834
856
856
883
886
1093

**Comment by wsalesky** [comment]
@davidamichelson I pushed a new version of the data, using the xslt transform. For the duplicate ids I added an a and b file.
