### ISSUE TITLE
Browsing HTML entries

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#431]
Hi Winona,

Just a quick note to ask, at one point we had a secret browse that was by number for the Gazetteer. Is that browse still available? I had a reason to use it recently.

Also, I wondered. On the Admin module or somewhere it would be nice to have an arrow button that lets you advance to the next record (by number or by headword alpha) from one record page to another.

Let's discuss briefly on Thursday, but don't do any actual work on these.

Thanks,
Dave

**Comment by wsalesky** [comment]
Hi Dave, 
We did have a browse by number, but do not any longer. We can add it back in if you like. 
-Winona

**Comment by davidamichelson** [comment]
Sure but silently: one would need to know the URL
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/browse.html?view=numeric&sort=1

**Comment by wsalesky** [comment]
Okay you can now access this feature using the ?view=numeric parameter. It is a little slow, I will look into that this week.

**Comment by davidamichelson** [comment]
Hmm, I can't it to work, what is the escape character between numeric and parameter as a URL?

**Comment by wsalesky** [comment]
Sorry, this is what I mean:
http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe/bhse/browse.html?view=numeric

It is very slow, I think I need to check the indexes on the dev server.

**Comment by davidamichelson** [comment]
It's probably just slow because it is loading a huge html page?
