### ISSUE TITLE
BHSE Landing Page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#433]
This applies to http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe/bhse/index2.html

We like this version.

Changes, delete all of the text in the red area around the search box.

Inside the search box, change "Search" to "Search for Texts"

Please remove the search box from the menu bar. Instead put the Syriaca.org logo as a live link to the home of Syriaca.org.

Please replace the home "menu" menu with the mobile menu button showing three lines in a square and put it far right on the header menu, to the right of the Syriaca.org logo (see https://www.google.com/search?q=mobile+menu+button).

Please change "index" to browse, keep it to left of Syriaca.org logo.

**Comment by wsalesky** [comment]
What will the main nav look like for internal pages?

**Comment by wsalesky** [comment]
Do we want to pull any of these design elements into the internal pages?

**Comment by davidamichelson** [comment]
The mobile menu button at least

**Comment by wsalesky** [comment]
Done expect for the mobile menu. I'm a little uncomfortable about that change, we can talk about it at the meeting, but I think it would be misleading/inappropriate in this context.

**Comment by wsalesky** [comment]
Also, do you think you will want an about page?

**Comment by davidamichelson** [comment]
Please add: Menu for BHSE: Logo/BHSE browse about help contribute Logo/Qadishe Logo/Syriaca.org (with dropdown) and search box for module pages but not landing page.

**Comment by davidamichelson** [comment]
Please add sponsor logos: Fondazione Internazionale Balzan Fondazione,
NEH, Vanderbilt University, Jean and Alexander Heard Library, Vanderbilt University, Princeton University, Marquette Logo

**Comment by wsalesky** [comment]
Still need logo for Marquette

**Comment by davidamichelson** [comment]
Okay, I have a change of plans. On:

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/index.html
and
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/q/index.html

instead of linking to other module, let's include the Q logo and "Gateway
to the Syriac Saints" and link to the
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/saints/index.html page

Thanks,
Dave

(p.s. incase J-N hates this change, maybe keep a copy to roll back to of
what we have now).

**Comment by davidamichelson** [comment]
One more request, I would like to start editing the prose for these pages
(BHSE and Q). Can you please let me know if the pages on github are fine
for me to edit?

Thanks,
DM

**Comment by davidamichelson** [comment]
just to clarify when I say "linking to other module" I mean in the upper
right hand corner.

**Comment by wsalesky** [comment]
Pages are up to date on github. (dev branch)

**Comment by wsalesky** [comment]
I added the new link to BHSE:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/browse.html

However, it causes some ugly wrapping. We would need to either make the sub-module links into a dropdown  or maybe have: Browse | About (dropdown with help and contribute) | Gateway to the Syriac Saints | Syriaca.org

Or maybe just have icons without text for Gateway to Syriac Saints and Syriaca.org (with text when you hover over the icon). 

Thoughts?
