### ISSUE TITLE
Advanced Search Options for BHSE

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#435]
For BHSE please add search by:
Change "Full-text" to "Key Word" in the box in grey put "(English, French, Syriac)"
Title in the box in grey put "(English, French, Syriac)"
Author (need to work out how the URIs and names work here, maybe we use the forms here to find the URI)
Related Persons (drop down of relationship), (need to work out how the URIs and names work here, maybe we use the forms here to find the URI)
Prologue (with search box gray labelled Syriac, French)
Incipit (with search box gray labelled Syriac, French)
Explicit (with search box gray labelled Syriac, French)
ID Number: change drop down to radio buttons.
Editions: in the search box in grey put "(Key Word)"
Modern Translations: in the search box in grey put "(Key Word)"
Ancient Versions: in the search box in grey put "(Key Word)"
Manuscripts:  in the search box in grey put "(Key Word)"
Sources:  in the search box in grey put "(Key Word)"

**Comment by davidamichelson** [comment]
We can take up persons at a later date.

**Comment by wsalesky** [comment]
New search options have been added. Please test and review.

**Comment by nathangibson** [comment]
Not getting author search to work (at least as string). Searching for "Jean" gives me 0 records, whereas there should be a bunch with "Jean d’Éphèse, LES" in the author field.

**Comment by wsalesky** [comment]
Thanks @nathangibson I will take a look.

**Comment by nathangibson** [comment]
Going through the search fields one by one...
I'm also getting some false positives (I think) for search by related persons. Searching for "Abraham" gives 37 results that do not all seem related, including, e.g., http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe/work/230 which does not mention any Abraham.

**Comment by wsalesky** [comment]
@nathangibson do you know the URI for a record with Jean in the author field? Troubleshooting now.

**Comment by wsalesky** [comment]
@nathangibson never mind. The author field was not being indexed. Author search should be working now. "jean" returns 122 matches.

**Comment by nathangibson** [comment]
Great! Thanks!

Also, I'm not sure why the "Editions" field has "(French, Syriac)" while the other bibliography-type fields have "Keyword". I would think "Editions" should also be "Keyword."

**Comment by nathangibson** [comment]
If I put quotation marks on the beginning of a string but accidentally leave them off the end, I get this error.
<img width="1301" alt="screen shot 2015-11-18 at 7 37 13 pm" src="https://cloud.githubusercontent.com/assets/3083452/11250288/18ab7e80-8e2c-11e5-840a-2522787cf801.png">

**Comment by wsalesky** [comment]
probably just bad copy and pasting.

**Comment by nathangibson** [comment]
Ahh, I see.

Oddly, I can get results searching for a number of different "Sources", but not for "Zanetti" or "Detienne" in the "Sources" field. Perhaps this is b/c their names are not actually in the bibl--only a pointer to the bibl? Obviously this is not a big problem at the moment, but once we generate bibl records for the other sources, could one still search by the author's name to return hits from the "Sources"?

**Comment by wsalesky** [comment]
I think we could search the record and also the bibl record, but currently we do not. May be able to add that in today... will have to investigate.

**Comment by nathangibson** [comment]
OK, I don't know how important it is. @davidamichelson would have a better read on that.

**Comment by nathangibson** [comment]
Perhaps you already know this, but when a search in the ID number field, it seems to be searching BHS & BHO numbers, regardless of which radio button I choose. For example, selecting "Syriaca.org URI" and searching for "246" returns only http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe/work/466 , which is BHS 246. The work/246 is not in the results at all.

**Comment by nathangibson** [comment]
OK, that's all I've managed to break! :-) Thanks for the hard work on this, and it's incredible functionality despite my efforts to find everything wrong with it.

**Comment by wsalesky** [comment]
Thanks for all your help @nathangibson, will work through this list today! RE: idno, 246 is not a syriaca.org URI, it would have to be http://syriaca.org/work/246. This is an exact match so you would have to get the id correct. However, you should get 0 results for that search, so clearly something is not working as it should.

**Comment by nathangibson** [comment]
Ahh, right, so we have to include the entire URL. Got it.

**Comment by wsalesky** [comment]
@nathangibson I think I have addressed the false positives in the Related Persons search (over eager regex), can you take a look when you get a chance? Thanks!

**Comment by davidamichelson** [comment]
For the following fields:
Authors:
Related Person:
Editions:
Modern Translations:
Ancient Versions:
Manuscripts:
Sources:

Please accept a Syriaca.org URI in addition to keyword

please change the placeholder text in the box to say... 

"English, French, Syriac Keyword or Syriaca.org URI" (delete all parens)

For the ones that just say keyword change to "Keyword or Syriaca.org URI"

**Comment by davidamichelson** [comment]
For results please explore "keyword in context" search results. If that does not work, please show the full node that was searched (incipit, etc).

**Comment by davidamichelson** [comment]
On Id number

Please change label: to "Id Number of Text"
Please remove button for "Any" (keep as silent default)
Please remove Syriaca.org button

On search terms:
1. Only accept numeric values (strip off anything)
2. If any is default, then recreat Syriaca URI and include in results
Else, just return the BHS etc.

For order of the Radio buttons please use BHO, BHS, CPG

For the placeholder text just use a number "3490"

**Comment by davidamichelson** [comment]
Please add a "New Search" button on the results page that takes the user to advanced search with fields clear.

**Comment by davidamichelson** [comment]
Label for sources should be "References"
