### ISSUE TITLE
Handling individual persons and individual works records in HTML

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#439]
Still going back and forth on how to handle records that are in more than one module. Can we try this:

In the SBD header, we need: 

Browse (dropdown with Browse SBD, Browse Qadishe, Browse Authors)
About (dropdown with About SBD, About Qadishe, About Authors)
Help
Contribute
Syriaca.org (full dropdown)
 
As relevant for each person page the headers for Qadishe and Authors should be added but without dropdown menus and the icon should be a link to the landing page for the module.

Then we need to create a new works module called "New Handbook of Syriac Literature" (NHSL) that contains BHSE in the same way that SBD contains Qadishe.

In that header, we need: 

Browse (dropdown with Browse NHSL, Browse BHSE)
About (dropdown with About NSHL, About BSHE)
Help
Contribute
Syriaca.org (full dropdown)
 
When relevant (at present for all records) the work page the header for BHSE should be added but without dropdown menus and the icon should be a link to the landing page for the module.

**Comment by wsalesky** [comment]
Do you have a Syriac letter to use for the NHSL module?

**Comment by davidamichelson** [comment]
Hmm, good point. I think we did somewhere, probably SYRIAC LETTER KAPHܟ
&#1823; &#x071F
