### ISSUE TITLE
Table padding for relations page

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#447]
@wsalesky could I get your help with table padding for https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/documentation/relations.html ? Some of the columns are jammed together. Not sure if I should be using a different CSS class?

**Comment by wsalesky** [comment]
@nathangibson we may want to add some additional padding to the main.css. I can take a look.

**Comment by wsalesky** [comment]
Also, perhaps a smaller font? Also in main.css
