### ISSUE TITLE
Browse SBD by Type

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#465]
Browse by type in SBD is just showing placeholders when I click on the type (Author/Saint/Unknown). E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?view=type&type=syriaca-author 

Is this just not done yet or is it a bug?

**Comment by wsalesky** [comment]
Should use abc menu on type browse, or any browse result over 25 or 50.
