### ISSUE TITLE
Add "active" (=floruit) to concise results view of persons?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#466]
Sorry if there's already an issue for this -- I couldn't find it. 
I think we want to add "active [date]" to the concise results view that we see for persons on search results, etc. (the same way as it shows "died ..."). Assuming no objection from @davidamichelson

**Comment by nathangibson** [comment]
This would be using the <floruit> element.

**Comment by wsalesky** [comment]
@nathangibson example record? Thanks!

**Comment by wsalesky** [comment]
@davidamichelson any objection to this addition?
