### ISSUE TITLE
Extraneous output at top of search results page 

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#468]
When I do a search such as http://wwwb.library.vanderbilt.edu/exist/apps/srophe/q/search.html?coll=q&type=&q=&name=Gabriel&start-date=&end-date=&date-type=&gender=&state=&related-place=&place-type=&related-persons=&mentioned=, I get some extra stuff after "Resource" and "Name." It spits out "collection('/db/apps/srophe-data/data/persons/tei')//tei:body[ancestor::tei:TEI/descendant::tei:titleStmt/tei:title/text() = 'Qadishe: A Guide to the Syriac Saints'][ft:query(descendant::tei:person/tei:persName,'Gabriel',common:options())]/ancestor::tei:TEI"

<img width="613" alt="gateway_to_the_syriac_saints__volume_ii__qadishe" src="https://cloud.githubusercontent.com/assets/3083452/12020991/749b5362-ad82-11e5-8f1a-7dbe3ed034ed.png">

**Comment by wsalesky** [comment]
Sorry. That is something I use for debugging. Guess I forgot to remove it!

**Comment by nathangibson** [comment]
No problem!
