### ISSUE TITLE
Move bibl record notes (@lang=fr) to Work records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#471]
For any bibl records with a note/@lang=fr please move the note to be a child of the same bibl id element in any work records with that same bibl id and delete it from the bibl record.

**Comment by wsalesky** [comment]
@davidamichelson  
Will wait to run this until @jsaintlauren is done editing and merges her changes into dev branch. 
There are only 7 records so it is a simple change.

**Comment by wsalesky** [comment]
Moved to app-data repository
