### ISSUE TITLE
Error when clicking on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1092

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#482]
When I try to go to  http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1092 I get the following error (Mac OS 10.10.5, FF 43.0.4). Is this malformed data or some other problem?
![syriaca_org__the_syriac_reference_portal](https://cloud.githubusercontent.com/assets/3083452/12679102/8b7a9366-c6a2-11e5-9877-cecf6a1d0cf9.jpg)

**Comment by wsalesky** [comment]
There are two records with the same id:
https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/1092.xml

and:
https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/saints/tei/1092.xml

They need to be merged, or resolved in some way.

**Comment by nathangibson** [comment]
Oh, yes, these should be merged. Should I do that manually, then delete one of them?

**Comment by wsalesky** [comment]
Sure.
