### ISSUE TITLE
Cross module search box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#484]
Please create an HTML page that allows for searching all collections (don't need to add this to menu, just a standalone page is fine for now).

It should have keyword and also search by entity:

PersName
PlaceName
Title Element
Bibl Element (Bibliographic Entries)
Syriaca.org URI

**Comment by wsalesky** [comment]
Very basic search available for cross module searching.

**Comment by wsalesky** [comment]
Some odd results, poor weighting. Example: search for edessa in placeName.

**Comment by davidamichelson** [comment]
Could this go on the main Syriaca.org home page?
