### ISSUE TITLE
SPEAR: Short Descriptions in Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#490]
In Person and Place browse, show the short description from relevant Syriaca.org module (similar to search results in Gazetteer etc.)

In Event Browse, show a preview of the textnode

In relation and keyword browse just show the human readable version of the keyword or relation (Dan needs to provide this).

**Comment by wsalesky** [comment]
What about having the visualizations on the relation tab? Or both visualization and textual list?
