### ISSUE TITLE
Visualization of Spear

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#495]
Please attempt a d3.js visualization for the tei:listRelations with URIs as nodes and tei:relation @name as edges

if that works then do the same for tei:listEvent with URIs as nodes and tei:event @ref as edges.

**Comment by wsalesky** [comment]
Can temporarily be viewed here:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/modules/relationships.xqm

**Comment by wsalesky** [comment]
Added some experimental bubble charts for event and relationships:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/modules/d3xquery/bubble.html
