### ISSUE TITLE
Some GEDSH entries not showing in bibliography

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#502]
E.g., http://wwwb.library.vanderbilt.edu/person/995. This is only in the dev module. http://syriaca.org/person/995 is showing it correctly. This seems to be only for the entries that cite GEDSH directly (http://syriaca.org/bibl/1), not the ones that cite sub-articles with different URIs. 

Perhaps this has something to do with the following error that I get when I try to go to bibls 1, 2, 3, and 4. E.g.,  http://syriaca.org/bibl/1/tei says:

XML Parsing Error: junk after document element
Location: http://syriaca.org/bibl/1/tei
Line Number 97, Column 1:<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:syriaca="http://syriaca.org" xml:lang="en">
^

**Comment by wsalesky** [comment]
Fixed. File had been overwritten on the server. Just replaced it with the version on github.

**Comment by nathangibson** [comment]
Thanks!
