### ISSUE TITLE
Google results include admin module

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#504]
I just googled "Telneshe syriaca" and the second hit was:
[http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe-forms/browse.html](http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe-forms/browse.html)

Do we want our admin module to be publicly visible through Google?  If not, we probably need to figure out how to exclude our admin module from Google results.

**Comment by wsalesky** [comment]
We do not. I will contact Dale. 
Thanks!

**Comment by wsalesky** [comment]
Dale has blocked access to port 8080. Should resolve this issue.
