### ISSUE TITLE
Center image on Gazetteer home page when image is full width

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#512]
If the window is not wide enough to have the "Welcome to the Syriac Gazetteer" to the right of the circle image, the box of the circle image becomes full width, and the caption bridges this full width, but within this box the circle is left-justified.  Instead, it would be nice if the circle image were centered within the box of the circle, when the "Welcome" text is moved below the image rather than beside it.

**Comment by wsalesky** [comment]
Done.

**Comment by tacarlson** [comment]
Thanks, Winona!

**Comment by wsalesky** [comment]
No problem!
