### ISSUE TITLE
Searches with apostrophe (') in SBD return error

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#515]
E.g., searching for "l'Ibère" (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=l%27Ib%C3%A8re) gives the following error:

![syriaca_org__the_syriac_reference_portal](https://cloud.githubusercontent.com/assets/3083452/13876713/6fcdac18-ed06-11e5-845f-11ec9a0c8253.jpg)

**Comment by wsalesky** [comment]
What record should I be able to return with this search?

**Comment by nathangibson** [comment]
Well, in that case I was looking for a record that doesn't exist. So a better example would be "Jacques l'Intercis" which should return http://syriaca.org/person/1296.

In doing that search, I see that the problem is with the straight apostrophe (') but not the curly apostrophe (’). (Searching for "Jacques l’Intercis" works.)

**Comment by wsalesky** [comment]
Interesting... thanks!

**Comment by wsalesky** [comment]
Okay, that should do the trick. Thanks @nathangibson
