### ISSUE TITLE
abstract display on search results

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#529]
I searched for "Sis" on the Gazetteer, and the first result was what I wanted, but I noticed that the abstract text was displayed as "A city in ..."  

The actual abstract of http://syriaca.org/place/190.html is "A city in Cilicia which was the capital of the Armenian Kingdom of Cilicia" (with the first "Cilicia" being a reference link to that place).  

It appears that the search result is only displaying the abstract to the first reference link, which is not ideal behavior in this instance.  Instead, the abstract as displayed in the search results can flatten any reference links.

**Comment by wsalesky** [comment]
Will show up when we push new module in May.
