### ISSUE TITLE
relations graph in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#530]
The graphs of relationships here: http://wwwb.library.vanderbilt.edu/spear/browse.html?view=relations, do not seem to work right now. However, the graphs of events work fine. A colleague is giving a paper on linked data and she really wants to grab a few screen shots of what we're doing. Thanks.

**Comment by wsalesky** [comment]
When would she need this by? I'm done for the day, but can work on it tonight if it is critical.

**Comment by dlschwartz** [comment]
Tomorrow should be fine. Thanks Winona!

**Comment by wsalesky** [comment]
This is fixed on the dev server. (Still need to push the changes to github.)

**Comment by dlschwartz** [comment]
Great, thank you Winona.
Dan

On Tue, Apr 12, 2016 at 10:44 AM, Winona Salesky <notifications@github.com>
wrote:

> This is fixed on the dev server. (Still need to push the changes to
> github.)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/srophe/srophe-eXist-app/issues/530#issuecomment-208969910>
>



-- 
Dr. Daniel L. Schwartz
Assistant Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
www.syriaca.org <http://syriaca.org/>
