### ISSUE TITLE
Create additional language browse(s)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#531]
Start with transliteration, but we will also want Arabic and French for sure and probably all languages.

**Comment by tacarlson** [comment]
This will require either:
(1) curating a headword list in every language for which we have names, or
(2) abandoning the headword browse model to allow browsing by all (or all non-deprecated) names.

I think would favor option 2, but we may need to experiment to see what option 2 looks like in practice.

**Comment by wsalesky** [comment]
We discussed this today at the meeting. What would you think of a dropdown menu, allowing users to select any of the available languages in the placeNames as a browse option?

**Comment by tacarlson** [comment]
I have no objection to that, or any of a variety of other ways of serving the option to users.  My comment was rather about our data model for the browse functionality.

**Comment by davidamichelson** [comment]
I would favor a middle way in which for some language browse lists the name is curated (English, Syriac for sure) but for others, the first listed name in document order for the specified language is offered. This would lead to a few mistakes but on the other hand for some languages, such as Greek it is unlikely we would really have the depth of time to go through and pick a head word for Greek.

**Comment by wsalesky** [comment]
Is there a language code we are using for "transliteration"? If so is it standard across all the collections?

**Comment by nathangibson** [comment]
GEDSH transliteration is always “en-x-gedsh”, across all the collections.

**Comment by wsalesky** [comment]
Thanks

**Comment by wsalesky** [comment]
The additional filter has been added, it can be tested by plugging in any language code into the lang parameter:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/q/browse.html?lang=ru
or
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/q/browse.html?lang=en-x-gedsh

More challenging is the display. Should we change the display title to use the name in the selected language? Or should we retain the title as the headwords, and highlight in some way the name in the selected language? Also, we will need to add additional alphabetical menu browse options for Arabic, Russian, etc. 

Thoughts on display challenges are welcome.

**Comment by wsalesky** [comment]
I will need a list of Arabic characters in 'abc' order. Can be pasted in here, or I can use this, if it is correct: 
https://en.wikipedia.org/wiki/Arabic_alphabet#Alphabetical_order

**Comment by wsalesky** [comment]
New options added to 'q' as an example:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/q/browse.html

This browse should work with any language we currently have encoded. To add a new option to a browse page add the following code to the browse.html: 

`<li data-template="browse:tabs" data-template-value="Transliteration" data-template-language="en-x-gedsh" data-template-sort-letter="A"/>`

With "data-template-value" as the text you want to appear in the tab, "data-template-language" as the language code, and "data-template-sort-letter" as the first letter in the alphabet, defaults to 'A' if left blank. 

I will need a list of characters for any languages we are using that do not use the latin alphabet, to add the correct alphabetical browse menu at the top of the page.

**Comment by davidamichelson** [comment]
We will decide on what languages we need and get back to you. We want visible English, Syriac, Transliteration, Arabic, French. Then a drop down menu "Other Languages": Armenian, Greek, German, Russian, etc. we will edit into a list: https://github.com/srophe/srophe-eXist-app/issues/514

**Comment by nathangibson** [comment]
OK, I've put the Arabic alphabetization table here: https://github.com/srophe/srophe-eXist-app/issues/26.

**Comment by nathangibson** [comment]
Russian (xml:lang="ru") is a lot simpler (yay). 
Upper Case:
А
Б
В
Г
Д
Е
Ё
Ж
З
И
Й
К
Л
М
Н
О
П
Р
С
Т
У
Ф
Х
Ц
Ч
Ш
Щ
Ъ
Ы
Ь
Э
Ю
Я
Lower Case:
а
б
в
г
д
е
ё
ж
з
и
й
к
л
м
н
о
п
р
с
т
у
ф
х
ц
ч
ш
щ
ъ
ы
ь
э
ю
я

If we need something later that includes Cyrillic characters from non-Russian languages, we can cross that bridge when we come to it.
