### ISSUE TITLE
use VIAF API to look up Worldcat results

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#535]
Currently we are just displaying WorldCat results for records that have an idno with a worldcat URI. We would like to display results also for persons like http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2785 for whom we have VIAF URIs but not Worldcat.

**Comment by wsalesky** [comment]
With the WorldCat lookup we are returning works by the selected person; viaf returns information about the person, they are not quite equivalent. We can get the world cat id from the viaf record and then grab the works that way if that sounds like what we want. Or were you hoping to display something else from VIAF?

**Comment by wsalesky** [comment]
Also, note to myself, WorldCat record count does not seem to match up in our display and WorldCat's:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/13

and 

http://worldcat.org/identities/np-ephraem$syrus$ca%20306%20ca%20373/

**Comment by nathangibson** [comment]
So a clarification: We do want to display WorldCat results (rather than VIAF info), but the question is how to grab it using the VIAF IDs. I think we would want to use the VIAF ID to return the WorldCat ID, as you suggested. (Alternatively, if there's a way to search WorldCat using the VIAF ID, that is also fine.) 

An additional complication is that we often have multiple VIAF IDs for each person (i.e., VIAF has duplicate records). If there's a way to display WorldCat results from all of these, that'd be super. If we can only display results from one, then you can just use the first VIAF ID listed in the record (not including the one that's in the format http://viaf.org/viaf/sourceID/SRP|person_...). Make sense?

**Comment by wsalesky** [comment]
Great! Yes, I think we can make that happen.

**Comment by wsalesky** [comment]
I was looking at Ephrem as an example record. Looks like the viaf records resolve to the already linked WorldCat link. Should we add this for cases only where there is no WorldCat link? Is the WorldCat link something that we want physically in the records? 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/13/tei

**Comment by nathangibson** [comment]
1. Yes, only for cases where there is no WorldCat link.
2. Let's check with @davidamichelson  whether we should pull the WorldCat link into the records.

**Comment by wsalesky** [comment]
See: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2785

**Comment by nathangibson** [comment]
Great! When we already have a WorldCat identity, can we just show one and not both? See http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/239 <http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/239>.

**Comment by wsalesky** [comment]
Fixed.
