### ISSUE TITLE
dev server not updating from srophe-app-data?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#537]
@wsalesky Did you say the dev server is supposed to update automatically from srophe-app-data dev branch? It doesn't look like it is.
Compare author element on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1001 with https://github.com/srophe/srophe-app-data/blob/dev/data/works/tei/1001.xml.

**Comment by wsalesky** [comment]
Looks like there was an error with this request, I re-ran it, so the data should be up now.
