### ISSUE TITLE
extra space in author names

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#539]
There's an extra space showing before the closing parenthesis in author names. E.g., "Ephrem — ܐܦܪܝܡ (Éphrem )" should be "Ephrem — ܐܦܪܝܡ (Éphrem)" in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1000.

**Comment by nathangibson** [comment]
Oops, I think the space got removed in the wrong place, or is displaying wrong due to bidi text issues. There should still be a space between the Syriac and the “(“ of the French name, but not between the French name and the “)”. 
Now it is “Ephrem — ܐܦܪܝܡ (Éphrem ) <http://syriaca.org/person/13>” but it should be “Ephrem — ܐܦܪܝܡ (Éphrem)”.

**Comment by wsalesky** [comment]
@nathangibson This is what I am seeing:
Ephrem — ܐܦܪܝܡ (Éphrem)

Is that incorrect? (Looks like there is a space between the Syriac and opening parentheses.)

**Comment by nathangibson** [comment]
Nope, it looks perfect now.

**Comment by wsalesky** [comment]
I suspect browser caching. ;)
