### ISSUE TITLE
Implement record redirection

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#546]
Once we have resolved https://github.com/srophe/srophe-app-data/issues/104, please implement record redirection. This will include:
1. Redirecting the browser to the new URI (perhaps an `<idno type="redirect">` -- see above issue) after 5 seconds, or at least displaying a clickable link to go there. @davidamichelson which one do we want?
2. Displaying a description of the deprecation (perhaps head + desc + notes + bibl that have type="deprecation" and are direct child of body -- see above issue) in place of or on top of record content.

related: https://github.com/srophe/srophe-eXist-app/issues/528

**Comment by wsalesky** [comment]
See #104

**Comment by nathangibson** [comment]
This is great, and it’s working perfectly, except that it redirects to the production server instead of the dev server.

**Comment by wsalesky** [comment]
Boy, you want everything. ;)

There you go. Should redirect to whatever server it is hosted on.

**Comment by davidamichelson** [comment]
Thanks! We can review this on Wed.

**Comment by nathangibson** [comment]
Super, thank you! Actually, if you want to talk about “everything,” we could start minting URIs in Syriac script ;-)

**Comment by davidamichelson** [comment]
Could we make the lag time a bit longer on the redirect, it is too short to read.

**Comment by nathangibson** [comment]
Also, I just tweaked the wording of the 301.html page on the srophe-eXist-app dev branch.
