### ISSUE TITLE
Links for sources

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#553]
Make the links in the person/place records hot clickable to the bibl pages.
When the site already has a favicon, display that. Otherwise, use an open-book style favicon.

**Comment by wsalesky** [comment]
Can I have some example bibl records that have links to other sources?

**Comment by nathangibson** [comment]
@wsalesky By now, I hope you won't be surprised when I give you a complicated answer :-)

Below are some examples, but note that in creating bibl records, I at least have used 2 types of external links:
 1. `idno[@type='URI']` to point to records that describe the same entities as our records do, which may or may not provide access to the material
 2. `ref[not(ancestor::note)]/@target` to provide a link where the user can access the material

I don't think you need to visualize these two different types differently, but this is a note to self and others ( @davidamichelson , @dlschwartz ) that we should discuss and document whether this is how we want to keep doing it. I made the distinction primarily for RDF purposes. Should we discuss tomorrow? 

E.g., http://wwwb.library.vanderbilt.edu/bibl/824 (archive.org as ref)
http://wwwb.library.vanderbilt.edu/bibl/1301 (WorldCat as idno),
http://wwwb.library.vanderbilt.edu/bibl/790 (HathiTrust as idno),
http://wwwb.library.vanderbilt.edu/bibl/1348 (HathiTrust as ref),
http://wwwb.library.vanderbilt.edu/bibl/1700 (UniversitätBonn as ref)

**Comment by wsalesky** [comment]
Let's discuss this a little more at our meeting on Wednesday.

**Comment by wsalesky** [comment]
We should discuss what to do with zotero id's

**Comment by wsalesky** [comment]
First draft up. Still need icons for the various sites we link to. Looking at variouse branding and rights statements on the websites to see what is fair use re logos.
