### ISSUE TITLE
Issues with Syriac text

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#555]
Different fonts with Firefox and Chrome?

**Comment by wsalesky** [comment]
This should resolve the font issue, and also the issue with Firefox (which as it turns out was also a font issue). Wraps Syriac headwords in a span with a lang tag, which is used by our css to load the appropriate fonts. Reopen if issues persist on other operating systems.

**Comment by jsaintlauren** [comment]
Looks great to me now!  Thanks!!
