### ISSUE TITLE
Schema tweaks

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#556]
@wsalesky When you get a chance, would you be able to help with a couple minor schema tweaks that are preventing practically all of our files from validating? 

I'm trying to allow seriesStmt in the header and allow `@source` globally. I think I succeeded with seriesStmt but not with source. In generating RNC from ODD, Roma also made a bunch of other changes, perhaps having to do with updates to the TEI guidelines. 

See these two commits:
https://github.com/srophe/srophe-eXist-app/commit/129dec865a052905db0e098013e6ed52190f6f40
https://github.com/srophe/srophe-eXist-app/commit/fb50345df98137fd7c8a361913768d8b9f0c6be6

cc: @davidamichelson

**Comment by wsalesky** [comment]
Okay, seriesStmt is validating for me. I will take a look at `@source.`

**Comment by nathangibson** [comment]
Thanks!

**Comment by wsalesky** [comment]
Changing the source to be global is much more complicated then I initially thought, will work through it, but also note there is an open bug on the TEI repository about doing this. 
https://github.com/TEIC/TEI/issues/536

**Comment by nathangibson** [comment]
Yes, they are planning to change source to global, so far as I understand. I thought it would be a simple change in our schema, which is why I was trying to do it. Mainly, that and the seriesStmt issue have meant that none of our documents validate, which is both annoying and makes it easier for us to introduce actually invalid data without noticing it. The seriesStmt is the most pervasive one, so fixing that will help. Source is primarily a problem on BHSE records. So if source is complicated, I don’t know whether it is worth bothering about. @davidamichelson ?

**Comment by wsalesky** [comment]
So the problem with source is that by adding it to the global attributes, on some elements it gets added twice (as they are calling it via another attribute group). So I would have to add it to global, and then remove it from the other attribute groups it belongs to (I think there are only two) but I wonder if we just wanted to wait for it to make its way through the TEI-C process instead.

**Comment by nathangibson** [comment]
Maybe we should discuss this tomorrow too.

**Comment by nathangibson** [comment]
Also, just as a note: We might consider including `<term>` (core module) and `<tag>` and `<att>` (tagdocs module) as these would be useful for documentation. I tried using them for taxonomy documentation, only to realize that our schema excludes them.

I think we are planning on discussing the schema today.

**Comment by wsalesky** [comment]
Okay. Here is my attempt. I had to manually edit the schema doc because Roma was incorrectly listing it as 0 or 1 (with the ? operator). Seems to be working okay for me. Would you like to test it before I push it to the production branch?

**Comment by wsalesky** [comment]
Hum, changes are taking a while to show up on git hub. Have pushed to the dev server, so you can use this url to validate against: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/syriaca-tei-main.rnc

**Comment by davidamichelson** [comment]
Hi Gang, thanks for working on this but just a reminder that @dlschwartz is taking over on schema work, so please keep notes for him.

**Comment by nathangibson** [comment]
Yep, discussing the future of the schema was something we didn’t get to in last week’s meeting.

**Comment by wsalesky** [comment]
Merged into master branch and pushed to production. We should be able to validate all our records now.
