### ISSUE TITLE
Wildcard search issues

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#557]
Search for "tell 'ada" in production Gazetteer returns place/198 and place/233 (as it should) [http://syriaca.org/geo/search.html?q=tell+%27ada]
but search for 

> "tell 'ad*"

 [http://syriaca.org/geo/search.html?q=tell+%27ad*] or "tell 'ad?" [http://syriaca.org/geo/search.html?q=tell+%27ad%3F] returns nothing.

**Comment by nathangibson** [comment]
Github turned my asterisk in the original message into italics.

**Comment by wsalesky** [comment]
Same as https://github.com/srophe/srophe-eXist-app/issues/480

I need to contact the eXist list. Thanks for the reminder.

**Comment by wsalesky** [comment]
Ah, no, this is a different error. not related to #480

**Comment by wsalesky** [comment]
#480 still an issue.
