### ISSUE TITLE
Searching for keyword "the" in SBD does not return anything

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#560]
Is this because it is intentionally excluded from index, we would like to be able to search for it in a name. See http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?coll=sbd&type=&q=the&name=&start-date=&end-date=&date-type=&gender=&state=&related-place=&place-type=&related-persons=&mentioned=

**Comment by davidamichelson** [comment]
Great, could we see the stopwords list somewhere? @nathangibson We should publish it in the documentation.

**Comment by wsalesky** [comment]
It is currently a very short list, please add to it: 
this
and
that

(Done just for testing)
Code goes here: 
https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/collection.xconf
