### ISSUE TITLE
For Bibl Module: Full Citation Information section

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#564]
Please relabel or restyle:

For Title: please style as quotes or italics

For Idno, if @type = URI please label as "URI" if other, label as "Other ID Number:"

Please break up imprint into:
"Publisher"
"Place of Publication" (if possible make hot clickable to gazetteer)
"Date of Publication"

Instead of biblScope, relabel as 

biblScope unit=“pp” — “Pages:”

biblScope unit=“vol” — “Volume:”

biblScope unit=“entry” — “Entry:”

biblScope unit=“col”/“column” — “Column:”

also: 
part = "Part:"
series = "Series:"
issue = "Issue"
tomus = "Tome"
fasc = "Fasicule"

"Monograph/Journal" should be changed to "Publication"

Prefered Citation = typo = Preferred Citation

**Comment by nathangibson** [comment]
Also let's make "Ref:" into "See Also:" for now.
