### ISSUE TITLE
Bibl Module Cited By

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#565]
Please change "Cited by:" to "Cited in:"

**Comment by nathangibson** [comment]
Also, some records have weird text: "10 record(s) cite this work. **per page 5**" 
E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1072
http://wwwb.library.vanderbilt.edu/bibl/1092

**Comment by wsalesky** [comment]
Sorry @nathangibson that was something I put in for debugging and forgot to remove! Should be gone now if you refresh.
