### ISSUE TITLE
Subject Headings (fake for now)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#567]
Between the Preferred Citation and the full citation, add a "Subject Headings" section.

For now populated with the English headword of any URI that cites the item. (could be static not hot linked)

Eventually clicking could return a search result of bibl items also cited by same URI and ideally then a facet that would let you filter to see all bibl items that are cited (or linked to) by any set of 2 or more URIs.

**Comment by wsalesky** [comment]
@davidamichelson How would you feel about having this placed in the right menu? Anything not in the xml needs xquery to generate it, if I break up the xml display (center column) it requires some extra xquery work. (Not a problem to do, but also makes the code a little more complicated and less reusable.)

**Comment by davidamichelson** [comment]
Yes that would be fine, especially for now. Let's put them above the ```Cited In:``` box and label their box as ```Subject Headings:``` 
If you can get them up even in a non-clickable form by Monday that would be great!
I love the candy buttons for links too btw!

**Comment by wsalesky** [comment]
Initial display is added. Will work on having them linked by Monday. I suspect for usability an expanding/collapsing list may be better. Let me know if you have a preference. 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1

**Comment by nathangibson** [comment]
I would weigh in on the side of expanding/collapsing.

**Comment by nathangibson** [comment]
Awesome that this is working already. Three things:
 1. We don’t need the footnote numbers on the subject headings (`@source` could be stripped off or just not visualized). 
 2. Can we separate them with semicolons, or put them in boxes like the persNames are in person records, or something to separate them?
 3. Is there a reason that some are bolded and others aren’t?

Thanks!

**Comment by wsalesky** [comment]
@nathangibson  What do you think of a bulleted list (collapsible?)

**Comment by nathangibson** [comment]
Hmm, well bullets take up a lot of space if there’s only one per line. I have no problem with them if we can put more than one per line.

**Comment by wsalesky** [comment]
Lets try wrapping the names in the 'pills' as we do for additional names on the search results page, and see how that looks.

**Comment by davidamichelson** [comment]
pills is my preference. Great Work!

**Comment by wsalesky** [comment]
Okay, expand option after 10? 20?

**Comment by wsalesky** [comment]
Okay, I added a search function to the controlled vocabulary. We can discuss it further at the next meeting. If any of you are working this weekend and run across any bugs I will be doing some more work later tonight and possibly tomorrow. So let me know.

**Comment by davidamichelson** [comment]
Looks terrific. WE can discuss and test on wed.
