### ISSUE TITLE
Bibl Module Curated By

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#568]
instead of "How to Cite" (skip) but include a "About this Entry"

About this Entry (keep)

Not needed: Entry Title

Publication Date: June 30, 2014
Curated by:
    David A. Michelson , general editor, Syriaca.org: The Syriac Reference Portal
    Thomas A. Carlson and David A. Michelson , editors, The Syriac Gazetteer
    Thomas A. Carlson and David A. Michelson , entry contributors, “Edessa — ܐܘܪܗܝ”

Additional Credit:
    Initial Barsoum entry creation by David A. Michelson
 etc.

**

**Comment by davidamichelson** [comment]
Sorry to re-open, I see that in the text (which I gave you-sorry!) there are some odd white spaces which are also reproduced here (and in the gazetteer).

Using this as my reference: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/859 the white space issues are:
```Publication Date: January 4, 2016```
Please change to ```Date Entry Added: January 4, 2016```

```Authorial and Editorial Responsibility:``` In this section there is a leading whitespace before the commas after the author names, please remove:
    ```*David A. Michelson , general editor```
    ```*David A. Michelson , editor```
    ```*and Nathan P. Gibson , entry contributors```

In this last line, several things are confusing:
``` and Nathan P. Gibson , entry contributors, “S. Dometios le martyr et S. Dometios le médecin”```
Instead, based on the TEI it should look like this (with no title):

```*Nathan P. Gibson, contributor```
```*Ugo Zanetti, contributor``` [these draw on the @role=creator]

Additional Credit: --this section is perfect :)

**Comment by davidamichelson** [comment]
It may be that our header is inconsistent with the other modules, we should change the header not the XSLT if that is the case.

**Comment by wsalesky** [comment]
I do not think it is the TEI (sadly). Will get to it tomorrow or this weekend.

**Comment by wsalesky** [comment]
Hi Dave, 
Should these changes apply only to the bibl module? Or to all the citations?

**Comment by davidamichelson** [comment]
These changes are only for the bib module where the "phrases", author, editor, publication date are already used elsewhere with a different meaning, thus it would be confusing, is the "editor" for the citation described by the bibl record or  for the encoder of the tei file.

**Comment by davidamichelson** [comment]
FYI, I still see spacing problem in firefox and Chrome:

Authorial and Editorial Responsibility:
David A. Michelson , general editor, Syriaca.org: The Syriac Reference Portal
David A. Michelson , editor,
Ugo Zanetti and Nathan P. Gibson , entry contributors, “S. Dometios le martyr et S. Dometios le médecin”

**Comment by davidamichelson** [comment]
Okay, one more change, which is due to the fact that I don't like my own change ;)

Please change ```Credit for this Entry``` to ```About this Online Entry```

**Comment by wsalesky** [comment]
Okay. This will take a little extra time, as I don't want to override changes for the other modules. Will get to it tomorrow.

**Comment by davidamichelson** [comment]
Let's wait until Wed and we can discuss first as I think there may be a miscommunication here. Sorry!

**Comment by davidamichelson** [comment]
Yes please go ahead.

**Comment by wsalesky** [comment]
Done. However there is a one remaining display issue under 'Editorial Responsibility:' 
David A. Michelson, editor,

After the 'editor,' there should be the title/@level='m' which the bibl module does not have. Should I just remove the comma and leave it as 'David A. Michelson, editor' or should we do something else?

Thanks.

**Comment by wsalesky** [comment]
Looks okay now.
