### ISSUE TITLE
Link to Bollandists

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#571]
We would like to include an institutional link to this partner project in BHSE http://www.bollandistes.org/online-resources.php?pg=bollandistdatabases. We will provide a jpg soon.

**Comment by davidamichelson** [comment]
Probably will be this: http://pinakes.irht.cnrs.fr/img/bollandiste.png

**Comment by wsalesky** [comment]
Should these be listed in any particular order?

**Comment by davidamichelson** [comment]
Please also add Bolandists to http://wwwb.library.vanderbilt.edu/exist/apps/srophe/saints/index.html

Please dd the Marquette logo found at http://wwwb.library.vanderbilt.edu/exist/apps/srophe/saints/index.html to the http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/index.html

In all modules, please remove the box around the Balzan Logo

In the main landing page please add Bollandists, TAMU IDHMC (http://idhmc.tamu.edu/), and Marquette to http://wwwb.library.vanderbilt.edu/
