### ISSUE TITLE
Bibl Module Candy Buttons

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#572]
Could we include the non Syriaca.org ones in the Bibl module as well? For example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/986 has buttons for 1 Thomas of Marga. The Syriac Text, Introduction etc., E.A. Wallis Budge.

It would be great if on the page for that bibl: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1602 the following items had the book icon as a hotlink:
```URI: https://archive.org/details/bookofgovernorsh01thomuoft

...

URI: http://zotero.org/groups/392292/items/BFDD44KS

See Also: http://archive.org/details/bookgovernorshi01thomgoog 
```

**Comment by wsalesky** [comment]
@davidamichelson Like this?

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1602
