### ISSUE TITLE
HTML Styling for Persons: Move Descriptions Up to above timeline?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#575]
@nathangibson It's a thing of beauty when Winona's XSLT implements a feature we would like to request even before we request it!
@wsalesky this record: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/9 has two notes, one of @type="abstract" and a new second one of @type="description". Not knowing what would happen, I pushed it to dev and the gazetteer code visualized it 👍 

Being too hard to please, I am thinking that for persons, it might be good to move the description list up to above the timeline because these descriptions are very important for records shared between modules. Can you do that please?

Thanks!

**Comment by wsalesky** [comment]
How does this look? 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/9

**Comment by davidamichelson** [comment]
Great, there are still some issues in how this person/9 is rendering,
perhaps we can discuss on Wed:

Sex: male9
<http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/9#bib9-9> Martyr:
Martyr9
<http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/9#bib9-9>

Known Religious Communities

*This list is not necessarily exhaustive, and the order does not represent
importance or proportion of the population. Dates do not represent starting
or ending dates of a group's presence, but rather when they are attested.
Instead, the list only represents groups for which Syriaca.org has
source(s) and dates.*

   - Ch. of E.

**Comment by wsalesky** [comment]
Render all tei:state in the grey box, remove 'Known Religious Communities'
