### ISSUE TITLE
Bibls 2,3,4 return eXist error

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#576]
E.g., http://wwwb.library.vanderbilt.edu/bibl/3 gives the attached error.

Does this have something to do with the fact that there are multiples of several elements in different languages?

[bibl-3-exception.txt](https://github.com/srophe/srophe-eXist-app/files/274450/bibl-3-exception.txt)

**Comment by wsalesky** [comment]
Interesting! I did not realize that tei:namePart can have child elements. That is what is causing the error.

**Comment by nathangibson** [comment]
Not sure I understand, but it’s working now, so thanks! The TEI is validating in my Oxygen.

**Comment by wsalesky** [comment]
This is the sort of thing I mean:
```
<persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name261-6" xml:lang="en-x-gedsh" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">
    <forename sort="1">Shemʿun</forenam e>
   <addName type="untagged-title" sort="2">of
        <placeName ref="http://syriaca.org/place/8">Amid</placeName>
   </addName>
</persName>
```
The sort was sorting on (esentially) `tei:addName/text()` which has two children, a text node 'of' and a te:placeName element, so 2 nodes. Sort can only accept a single node.

**Comment by nathangibson** [comment]
Ahh, I see.
