### ISSUE TITLE
Investigate use of relation vrs listRelation

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#579]
relation example:
http://wwwb.library.vanderbilt.edu/person/2747/tei

listRelation example:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/429/tei

Default code currently matches on listRelation in app.xql

**Comment by nathangibson** [comment]
@davidamichelson  Perhaps relevant is that I think we have listRelation in the wrong place in most/all work records. It is invalid TEI to have it directly as the last child of body, like we do. Instead it should go before the closing bibl tag or inside some other containing element. We need to change this programatically but I didn't want to do so before consulting with you on whether it would break anything.

**Comment by davidamichelson** [comment]
Okay, let's discuss tomorrow. Sounds like we need to change this.

**Comment by wsalesky** [comment]
Code for //tei:relation
