### ISSUE TITLE
Bug with person 958

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#580]
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/958
I'm not sure if this is an app or data issue. I suspect app, although I have not found any other records that have this problem.

**Comment by davidamichelson** [comment]
At first glance the TEI looks fine. Does it validate?

**Comment by wsalesky** [comment]
Yes, it validates. Must be something in the xquery, still looking.

**Comment by wsalesky** [comment]
XSLT bug.
