### ISSUE TITLE
404 error for person/325

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#582]
Person/325 is present in the srophe-app-data repo (https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/325.xml) and seems to be well-formed XML, but returns a 404 error for http://wwwb.library.vanderbilt.edu/person/325.

**Comment by wsalesky** [comment]
I suspect it is not on the dev server for some reason. It works on my machine. I will reload all the person records on the dev server tonight around 8:30 EST it may solve a few bugs.

**Comment by wsalesky** [comment]
Okay, seems to be up now.
