### ISSUE TITLE
Visualizing multiple dates inside birth/death/floruit

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#583]
We've run into situations now where we need to provide alternate (competing) dates for the same birth/death/floruit, with source information. Dave and I discussed, and we think the best solution is to put multiple `<date>` elements inside the birth/death/floruit, each with its own attributes, data, and source info. E.g., from http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/122/tei. 
```
<death>
  <date when="0724" syriaca-computed-start="0724-01-01" source="#bib122-1">724</date>
  <date when="0726" syriaca-computed-start="0726-01-01" source="#bib122-7">0726</date>
</death>
```
Can we visualize this as "Death: 724(1) **or** 726(7)", with the numbers in parentheses being footnotes? In other words, the same way as we are currently visualizing birth/death/floruit, just with an " or " in between.

cc: @davidamichelson

**Comment by wsalesky** [comment]
This is no longer working
