### ISSUE TITLE
Bug in short record view

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#584]
See descriptions with mixed content:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=+Anonymi&start=20

Need to strip tags or render them correctly.

**Comment by wsalesky** [comment]
@nathangibson These records have the titles enclosed in escaped brackets.
ie: 
` &lt;title ref=”http://syriaca.org/work/119”&gt;The Chronicle of Edessa&lt;title&gt;`

when it should be:
` <title ref=”http://syriaca.org/work/119”>The Chronicle of Edessa<title>`

I also see some odd quotes in there. How were these records generated? Using the forms?

**Comment by nathangibson** [comment]
Hmm, I think this came from a Google spreadsheet that I transformed with an XSLT, forgetting that I needed to redo the `<` `>` and smart-quotes. Do you want me to run a find and replace?

**Comment by wsalesky** [comment]
Yes please.

**Comment by nathangibson** [comment]
I think this should be fixed now.

**Comment by wsalesky** [comment]
Thanks!
