### ISSUE TITLE
Thoughts on moving related places map to right sidebar

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#586]
This would put it in line with the other relationships. (Currently there is a little bit of repetition there.) It might be nice to have them all together, although then that right hand menu starts to get quite long. 

Thoughts? @davidamichelson @nathangibson @dlschwartz @jsaintlauren

**Comment by nathangibson** [comment]
I like the consistency of having mentioning the places relations listed with the others, but it is a bit repetitious. I also like having the extra detail about the places that shows up in the relationship list view. So I would put in a vote for the following (but I have a feeling you're going to say this doesn't work well with your reusable templates!): 

In the relationships sidebar, put a "Places" section that has a "See below" link to an anchor at the map section.  
Under the map, break out the places using the short detail view you're currently using in the relationships bar. 

For instance, http://wwwb.library.vanderbilt.edu/person/13, which currently has under the map on a single line:
"This author has an unspecified connection to places: Nisibis,2 Edessa,2 al-Jabal al-Muqaddas,2 Amida,2 "

Could instead be 
**This author has an unspecified connection to places:** 
Nisibis (settlement) - ܢܨܝܒܝܢ
Names: Nṣibin Nusaybin Ṣoba Nisibin Ṣōbā
City in Mesopotamia and important center of early Syriac Christianity.
URI: http://syriaca.org/place/142

Edessa (settlement) - ܐܘܪܗܝ
...

**Comment by wsalesky** [comment]
Show hide relations similar to gazetteer: 
http://syriaca.org/place/18.html

**Comment by wsalesky** [comment]
Make time line smaller. Move map up to above description... 

Order: 
Identity
Description
map
timeline
description.

**Comment by wsalesky** [comment]
Updated relationships to use show/hide function as in Gazetteer. 
See: 
http://wwwb.library.vanderbilt.edu/person/13

Uses the `<desc>` for the description, if it exists, otherwise tries to construct one from the name attribute. We can discuss if a little post processing of the `<desc>` is desirable, it could be nice to have it say: 

> This author has an unspecified connection to 5 places.

rather then:  

> This author has an unspecified connection to places.

**Comment by jsaintlauren** [comment]
I love it!   Nice work, W!

**Comment by wsalesky** [comment]
Wonder if the count is less 2 or less we should just show them?

**Comment by nathangibson** [comment]
My personal preference would be to show 2 or 3 regardless, with a “View More” link to expand it. But if this goes against what you were told earlier, just ignore me :-)

**Comment by wsalesky** [comment]
We can talk about it at the next meeting. My understanding was to mirror the Gazetteer display, but it feels kind of empty to me when there is only 1 or two names to display.

**Comment by wsalesky** [comment]
Stale issue that has been resolved.
