### ISSUE TITLE
Revise Syriaca.org Main Landing Page before release

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#589]

**Comment by davidamichelson** [comment]
Links to funders needs to stay
Blog posts needs to say but abbrevieate
Very short prose with link to fuller about

**Comment by wsalesky** [comment]
First attempt:
http://wwwb.library.vanderbilt.edu/index3.html

**Comment by wsalesky** [comment]
Do we want some additional options?
