### ISSUE TITLE
Display of editions/translations/ancient versions

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#599]
@wsalesky Now that we have ptrs in for editions/translations/ancient versions, can we tweak the display of these? 

We would like these to essentially display the same as the items in the "Sources" section, except to preserve the language labels ("Latin: ", "Armenian: ") etc. and the witness explanation ("Edition from manuscript witness 1. See below.") Right @davidamichelson ?

But the citation style and the icon links to the bibliographic record / external repositories should be the same as in Sources. 

Right now there is some messy data still in the bibl elements themselves, especially in citedRange, so I realize this may throw some things off. Also, we have to decide https://github.com/srophe/srophe-app-data/issues/207 before it will look nice.

**Comment by wsalesky** [comment]
@nathangibson Can I have some good records to test the new display on?

**Comment by nathangibson** [comment]
OK, I just cleaned up 
http://wwwb.library.vanderbilt.edu/work/270
http://wwwb.library.vanderbilt.edu/work/600
http://wwwb.library.vanderbilt.edu/work/700
so you can try those.

**Comment by wsalesky** [comment]
@nathangibson Can you take a look when you get a chance?

**Comment by nathangibson** [comment]
For the most part this is looking great. Here are the issues I've noticed so far:

 1. The icon link to the bibliographic record actually just points to the work record.
 2. No external ("See Also") type of links are displaying. E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/270 edition no. 2 (bibl/1725) does not have the archive.org link displayed.
 3. All items should end with a period. It looks like references to entire books (no cited ranges) do not have a period. See work/270 ancient version (Armenian).

Thanks!

**Comment by wsalesky** [comment]
Okay, added the  see also, and period. 

What do you think about floating the link icons to the right? I find it looks messy with them bunched up right next to the citation text, but I'm not sure the float:right is the best solution either.

**Comment by nathangibson** [comment]
This is working now, yay!

Hmm, I like the float right idea, but I'm struggling with the fact that it's hard to visually distinguish the text blocks from each other and therefore I don't clearly associate the icons with the text. 

We should probably wait until we can discuss with the others tomorrow before tweaking this too much. 

Some ideas to discuss:
1. Move the icons in front of the entry text instead of after?
2. Reduce the icon size? 
3. When there are two Syriaca icons for the same entry (e.g., bibl/270 Sources no. 3), make the hover text for each say "Link to Syriaca.org Bibliographic Record for [title of resource]"? E.g., "Link to Syriaca.org Bibliographic Record for *De scriptoribus Syris orthodoxis*" and "Link to Syriaca.org Bibliographic Record for *Bibliotheca orientalis Clementino-Vaticana*" respectively.

**Comment by wsalesky** [comment]
Add zotero icon.

**Comment by nathangibson** [comment]
@wsalesky Looks like there are some issues displaying citedRanges for editions/translations/ancient versions. For example, in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/893, "Editions" should have "William Wright. Apocryphal Acts of the Apostles (Williams and Norgate, 1871)**, vol. 1: p. 128-169**."

**Comment by wsalesky** [comment]
Opps. Thanks for catching that!

**Comment by nathangibson** [comment]
`<idno type="ISBN">` seems to be displaying in work records as a link. E.g., http://wwwb.library.vanderbilt.edu/work/555 Editions no. 1 has a link to http://wwwb.library.vanderbilt.edu/work/978-90-429-0042-4 , which seems to be manufacturing a link from the ISBN at http://wwwb.library.vanderbilt.edu/bibl/2088. The ISBN shouldn't be a link at all. Thanks!

**Comment by wsalesky** [comment]
Thanks @nathangibson. The fix is to only display `idno/@type='URI'` a side effect of this is that it no longer links the Zotero ids. We can discuss if we want them linked or not.

**Comment by nathangibson** [comment]
I think this would be what we want since the only Zotero links we want to display when the bibl is cited are the `<idno type="URI">` , not the `<idno type="zotero">`.

**Comment by nathangibson** [comment]
i.e., http://wwwb.library.vanderbilt.edu/work/555 Editions are showing up how they should now.

**Comment by wsalesky** [comment]
Okay, sounds good.
