### ISSUE TITLE
Space not showing in search result view

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#600]
On http://wwwb.library.vanderbilt.edu/exist/apps/srophe/search.html?q=Asia&start=20 search result 32, there is no space in "CentralAsia" in the title or the citation even though the space does show correctly in the record (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/796).

**Comment by wsalesky** [comment]
Tricky! Thanks for catching that.
