### ISSUE TITLE
First author not showing in "How to Cite This Entry"

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#602]
E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1166 and many others.

**Comment by wsalesky** [comment]
I think this is because there is a mismatch in @jsaintlauren xml:id

In the above record she is listed as: jnmsaintlaurent
In the editors.xml she is: jnsaint-laurent

Here is a list of distinct values across all our data for editors:
  http://syriaca.org/editors.xml#tcarlson
    http://syriaca.org/editors.xml#dmichelson
    http://syriaca.org/editors.xml#uzanetti
    http://syriaca.org/editors.xml#ngibson
    http://syriaca.org/editors.xml#dschwartz
    http://syriaca.org/editors.xml#jnsaint-laurent
    http://syriaca.org/editors.xml#jfiey
    http://syriaca.org/editors.xml#dkiger
    http://syriaca.org/editors.xml#dgreeson
    http://syriaca.org/editors.xml#thannah
    http://syriaca.org/editors.xml#raydin
    http://syriaca.org/editors.xml#wwright
    http://syriaca.org/editors.xml#jarnwine
    http://syriaca.org/editors.xml#ejohnson
    http://syriaca.org/editors.xml#emjohnson
    http://syriaca.org/documentation/editors.xml#dmichelson
    http://syriaca.org/documentation/editors.xml#tcarlson
    http://syriaca.org/documentation/editors.xml#ngibson
    http://syriaca.org/documentation/editors.xml#jnmsaintlaurent
    http://syriaca.org/documentation/editors.xml#dschwartz
    http://syriaca.org/documentation/editors.xml#jwalters
    http://syriaca.org/documentation/editors.xml#amccollum
    http://syriaca.org/documentation/editors.xml#lyarbrough
    http://syriaca.org/editors.xml#cdetienne
    http://syriaca.org/documentation/editors.xml#abinggeli
    http://syriaca.org/documentation/editors.xml#mdebie
    http://syriaca.org/documentation/editors.xml#uzanetti
    http://syriaca.org/documentation/editors.xml#cdetienne

**Comment by wsalesky** [comment]
I'm okay with having a rule to print out what is in the tei:editor text() if there is no match in the editors.xml, but we should probably also do a little data cleanup.

**Comment by jsaintlauren** [comment]
Sorry!! 

My name only causes stress!!

**Comment by wsalesky** [comment]
Should we move this over to app-data?

**Comment by nathangibson** [comment]
Yes, the primary issue is data cleanup.

**Comment by wsalesky** [comment]
Moved to app-data repo. https://github.com/srophe/srophe-app-data/issues/211
