### ISSUE TITLE
Optimize graphics for Retina displays 

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#605]
Are the Syriaca.org and resource logos and header images optimized for retina displays? Just checking since they look less than sharp for me — not saying you need to do something about this now.

**Comment by wsalesky** [comment]
@nathangibson for you and your fancy monitor. 

New icons are fonts so they scale better. Will work on getting high res versions of the photos we are using for background images as well.

**Comment by davidamichelson** [comment]
Ha, my monitor is now 4+ years old, so I can't comment.

**Comment by nathangibson** [comment]
Thanks, looks nice :-)
