### ISSUE TITLE
Paths to URIs for MSS

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#615]
"Single part" manuscripts will have only one uri for the whole document, it will be found at `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/idno`

"Multi part" mansucripts are manuscripts that are physically composed of several smaller manuscripts bound together. These will have at least three URIs per document (one for the bound manuscript, and one each for the individual parts). The bound manuscript's URI will be located at the same path as a single part MS: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/idno`

The individual parts' URIs will be located at: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/msIdentifier/idno` each in a separate tei:msPart.

An example of an multipart manuscript is 100.xml :https://github.com/srophe/srophe-app-data/blob/dev/data/manuscripts/tei/100.xml#L75

**Comment by wsalesky** [comment]
This has been done, however I think the display needs some work. 
example:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/100

and msPart:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/101
