### ISSUE TITLE
Bug in q

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#622]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/321

Looks like it is in the timeline function.

**Comment by wsalesky** [comment]
@nathangibson what is the thinking behind having these two dates in this floruit  element? http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/321/tei

The current xquery handles multiple floruit elements, but not multiple dates within a floruit element. I can fix that, but I want to make sure I understand the way the elements are being used correctly. 
Thanks!

**Comment by nathangibson** [comment]
This one looks like it's the result of a bit of a messy merge, but we do want to allow multiple date elements inside floruit per #583 . Let me know if that still doesn't make sense.

**Comment by nathangibson** [comment]
In other words, it is "[date A] or [date B]"

**Comment by nathangibson** [comment]
@davidamichelson thoughts? It might be difficult to give you criteria to show just one of them, but showing two could be confusing. Would it be hard to use the earliest date for the beginning and the latest date for the end? 
Also, if we're putting multiple dates, did we ever tell you which date the page header/short description should show? I guess we need to figure that out too.

**Comment by davidamichelson** [comment]
@wsalesky Please bring this up on Thursday at meeting
