### ISSUE TITLE
Search Results in Works are displaying the Author Name as a Work Title

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#626]
The HTML page for this record appears correctly (i.e. without a Syriac version of the title): http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1242

But when this page shows up in this search result:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/search.html?q=Eve

It appears to have a Syriac title, but actually the Syriac is not the title, but the Syriac version of the author's name and should not display as a title.

It appears to be grabbing the Syriac from here:
```
<author xml:lang="fr" source="#bib1242-1" ref="http://syriaca.org/person/573"><persName xml:lang="en-x-gedsh" syriaca-tags="#syriaca-headword"><forename sort="1">John</forename><addName type="untagged-title" sort="2">Chrysostom</addName></persName> — <persName xml:lang="syr" syriaca-tags="#syriaca-headword"><forename sort="1">ܝܘܐܢܝܣ</forename><addName type="untagged-title" sort="2">ܟܪܘܣܘܣܛܘܡܘܣ</addName></persName> (<persName xml:lang="fr"><forename>Jean</forename><addName type="untagged-title">Chrysostome</addName></persName>)</author>
```

**Comment by wsalesky** [comment]
Interesting. Should these authors have `@syriaca-tags="#syriaca-headword` ?

**Comment by davidamichelson** [comment]
No, I bet that was imported when the names were imported! I will delete
them all.

**Comment by davidamichelson** [comment]
Fixed with https://github.com/srophe/srophe-app-data/pull/346

**Comment by davidamichelson** [comment]
Hmm, well it didn't quite fix, but maybe I did not reindex correctly? Please see:

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1242/tei

and

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/search.html?q=Eve

The first result (work/1242) on this result page should not be displaying Syriac

**Comment by davidamichelson** [comment]
Ack, nevermind, I upload the files in the wrong place!

**Comment by davidamichelson** [comment]
Okay, good news, once I uploaded the files correctly it did fix. thanks
