### ISSUE TITLE
persName refs inside bibl titles are displaying as text

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#631]
@wsalesky @davidamichelson
Bibls with persNames in the title display fine in the bibl module but not in Sources for persons. E.g., http://wwwb.library.vanderbilt.edu/bibl/675 has 
```
<title xml:lang="en" level="m">The Sixth Book of the Select Letters of <persName ref="http://syriaca.org/person/51">Severus Patriarch of Antioch</persName> in the Syriac Version of <persName ref="http://syriaca.org/person/1014">Athanasius of Nisibis</persName></title>
```
which shows up on the page http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2596 as 
> The Sixth Book of the Select Letters of http://syriaca.org/person/51Severus Patriarch of Antioch in the Syriac Version of http://syriaca.org/person/1014Athanasius of Nisibis

This probably affects a bunch of the SPEAR records. We should probably just suppress the ref value, but if needed we could remove persNames from bibl titles. Note that we don't want to change the display of bibls (works) that appear in abstracts, only ones that appear in the bibliography for the record.

**Comment by wsalesky** [comment]
I would rather suppress the @ref. Will look into it. It is curious that the 2 versions are different, I thought they were using the same xslt.
