### ISSUE TITLE
Empty citedRange

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#632]
@davidamichelson @nathangibson 
I noticed some empty cited ranges in the sources. Should these labels be suppressed, or will they have data eventually?
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2596 (section and URL)

bibl #4

**Comment by nathangibson** [comment]
These were probably some blank columns that were not eliminated in the spreadsheet XSLT conversion for SPEAR. We should suppress them, or even delete them from the data. Which do y'all think is better?

**Comment by wsalesky** [comment]
I think if they are not needed they should be removed from the data.

**Comment by wsalesky** [comment]
@nathangibson should I run a script to remove these or would you like to?

**Comment by nathangibson** [comment]
Yes, please do! I won't get around to it very soon!

**Comment by davidamichelson** [comment]
@wsalesky yes could you please remove any blank cited ranges from any records?

But once that is done, we think there is some other problem with the bibls here:

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2596 

same in 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2597 and higher.

**Comment by davidamichelson** [comment]
They are not populating correctly.
