### ISSUE TITLE
Please add display for works in author records

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#634]
Add a block between description box and map for displaying works authored by the person. (Grab `author/@ref` from works.)

Box should first display note (if present) of type="authorship".
Then a dynamically generated list:
1. “The New Handbook of Syriac Literature lists these works by [author name]:” 
2. Show the first 3 "[author role]: [English title syriaca-headword] ([URI]) short abstract
3. “Show [number] more” button

**Comment by wsalesky** [comment]
@nathangibson can you suggest a sample person to test this on?

**Comment by wsalesky** [comment]
Demo in place but I'm noticing a lot of slowdown in load time. Investigating today. (Could also have the full list in a popup, may be a more visually pleasing way to look at it.)

**Comment by wsalesky** [comment]
http://wwwb.library.vanderbilt.edu/person/13

**Comment by nathangibson** [comment]
Looking great, other than the load time as you mentioned. Perhaps we can tweak details at tomorrow’s meeting. Thanks so much!

**Comment by jsaintlauren** [comment]
Great!!

**Comment by wsalesky** [comment]
Speed is better, will probably want to add a 'sort' option to the results in the popup window.

**Comment by nathangibson** [comment]
Please change header text to 
“Works by [author name - English only] in the New Handbook of Syriac Literature”

**Comment by nathangibson** [comment]
Also please include `author/@role` value (if present) before work title per number 2 above.

**Comment by wsalesky** [comment]
Okay, added the `author/@role` and put back the popup. 

These results can also be seen in BHSE by searching for author ID:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/search.html?author=http://syriaca.org/person/13&start=1&sort=alpha

**Comment by wsalesky** [comment]
@nathangibson if it looks good to you, you may close the issue.

**Comment by nathangibson** [comment]
Thanks!
