### ISSUE TITLE
When a person has a work in their abstract weird results show in the search results

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#635]
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=qoqa

which returns this for result number 2:

2
The Monks of the Monastery of Mar Sabrishoʿ of Beth Qoqa [http://syriaca.org/work/1999] Names: The Monks of the Monastery of Mar Sabrishoʿ of Beth QoqaCouvent de Sabrisho‘ de Beth KokaA short and anonymous hagiographic text, The Monks of the ...Matches:1. (persName) The Monks of the Monastery of Mar Sabrishoʿ of Beth Qoqa2. (title) The Monks of the Monastery of Mar Sabrishoʿ of Beth Qoqa3. (placeName) Beth Qoqa Monastery4. (persName) Sabrishoʿ of Beth QoqaURI: http://syriaca.org/person/1659

**Comment by wsalesky** [comment]
@davidamichelson can you clarify? What is displaying incorrectly?

**Comment by davidamichelson** [comment]
This appears to be fixed.
