### ISSUE TITLE
Visualizing deprecated records

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#637]
@wsalesky @davidamichelson @dlschwartz @jsaintlauren @tacarlson 
We've had to deprecate some person records in Q that do not make sense to redirect to another URI. E.g., "Martyrs (cause de la commémoration des)" https://github.com/srophe/srophe-app-data/blob/dev/data/deprecated/persons/tei/saints/tei/1893.xml 
How should these display if someone tries to go the URL? It is unlikely that anyone will ever visit these, but as a matter of principle these are supposed to be stable URIs and thus should resolve to something. 
If there's a redirect, they simply get a message about that and are sent to the new URI. These are in the same format but simply do not have a redirect. There's a message in the `body/desc[@type='deprecation']` that says "This record has been deprecated." Should this message be displayed as a big banner at the top / over the top of the page?

**Comment by davidamichelson** [comment]
I would vote for the deprecation message (same as what one gets with a redirect) but then a redirect to the browse page rather than leaving them on the page.

**Comment by wsalesky** [comment]
I like that solution as well. (Redirect to browse page.)
