### ISSUE TITLE
MSS Browse feature

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-eXist-app#639]
@wsalesky 

We would like to organize the browse function at http://wwwb.library.vanderbilt.edu/exist/apps/srophe/mss/browse.html
according to repository, located at this path:
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/repository

**Comment by PGAMiller** [comment]
Looking at our current displays for manuscripts, maybe we can organize it to mirror how we identify current location, in the top left of a manuscript page? For example, http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/1123 is reads "United Kingdom - London - British Library - Oriental Manuscripts"
Maybe then it can be organized by Country, then City, then Repository, then collection (if we have it)?
@davidamichelson does this sound like an effective way to organize the browse? Including country and city makes sense to me, and it mirrors a display we already have.

**Comment by davidamichelson** [comment]
Let's plan to have two default browse options (similar to the English/Syriac browse tabs). These will be:

1. Library (should be by distinct value in /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/repository, we will actually mark all of these with place URIs eventually). This one should group only by library and then list by Syriaca URI but listing the shelfmark from the library as well. 

2. Country (should be by distinct value in /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/country, we will actually mark all of these with place URIs eventually). (This browse will have a tree that opens to grouped by city (settlement) and then by library (should be by distinct value in /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/repository, we will actually mark all of these with place URIs eventually).

**Comment by davidamichelson** [comment]
@PGAMiller  will make a mock up on a google doc with examples

**Comment by wsalesky** [comment]
@PGAMiller, @davidamichelson Should I wait for the mockup, or should I just work something up based on @davidamichelson comments above?

**Comment by PGAMiller** [comment]
@wsalesky @davidamichelson 
Here is a link to the Google Document that has the mock up of the display for each entry. I have also copied over Dr. Michelson's above notes on the organization for the browse functionality.
https://docs.google.com/document/d/1N8_qvoY40CsaaNi240J3ydUh1Ha9k3UEY6_dwa9UsrI/edit?usp=sharing
Let me know if there are any questions!

Dr. Michelson, should I pass ownership of the document over to your gmail account so that you can modify it if necessary?

**Comment by wsalesky** [comment]
Thanks! I will work something up for our Monday meeting.

**Comment by wsalesky** [comment]
First round up: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/mss/browse.html

Some refinement is necessary. Using the facet function for browse, which I think works better then the tabs across the top. We can discuss this at our meeting.

**Comment by wsalesky** [comment]
I have some questions about altIdentifier display. 
See: 
http://localhost:8080/exist/apps/srophe/manuscript/1211

**Comment by davidamichelson** [comment]
In browse, change the label "title" to "Shelfmark" in the results list. It is still pulled from tei:title however.

**Comment by davidamichelson** [comment]
Please label the alternate identifiers by their type:

"BL-Shelfmark" render as: "BL"
"Wright-BL-Arabic" render as: "Wright"
"Wright-BL-Roman" render as: "Wright"

**Comment by davidamichelson** [comment]
For now please show all alt identifiers

**Comment by davidamichelson** [comment]
Please move the sentence:  This manuscript contains 3 component manuscripts to above the list of alt identifiers.

**Comment by davidamichelson** [comment]
For all manuscripts that have components list only the first two with this sentence: "The component parts of this manuscript have various dates including: [Date of msPart @n="1"] and [Date of msPart @n="2"]

**Comment by davidamichelson** [comment]
Please replace the existing classDecl for all manuscripts in app-data with this one:
https://gist.github.com/PGAMiller/1cd784205a6ed3a396a2f3fbdeb206af

**Comment by wsalesky** [comment]
@davidamichelson @PGAMiller I have updated the classDecl in the manuscripts data. Will be working through the rest of the list today.

**Comment by davidamichelson** [comment]
Thanks!

**Comment by wsalesky** [comment]
Okay. I think I caught all the changes. Please review and close if it looks good. @davidamichelson @PGAMiller
