### ISSUE TITLE
MSS 1 has no physDesc

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-eXist-app#640]
@wsalesky 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/1
Currently this manuscript is displaying none of its physDesc details. I think this is because of a pathing issue for the multiple part MSS files (we get a similar issue on this manuscript, for example): http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/530

The path for multi-part manuscripts should be:
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/

**Comment by davidamichelson** [comment]
Just to be clear here, we want these MSS to be reachable through all of their URIS but in limited ways, thus if one calls up the URI for the whole file then one gets the physical description for all parts (thus two or more physical descs) but if one calls up the URI for only one part then one gets only that part's contents. WE can discuss the best ways to handle this in person perhaps.

**Comment by wsalesky** [comment]
@PGAMiller I think this has been resolved. Let me know if not.
