### ISSUE TITLE
MSS 1002 Tagged locus not displaying text

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-eXist-app#641]
@wsalesky 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/1002

Within some p tags, numbers marked as loci aren't displaying as text. Here are the paths I've found for them in manuscript 1002.

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/supportDesc/collation/p/locus/

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/supportDesc/condition/list/item/p/locus/

**Comment by PGAMiller** [comment]
I have also found that tagged loci are not appearing in note tags as well. The path for these would be:

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msContents//msItem/note/locus/

**Comment by wsalesky** [comment]
How should these be displayed? Thoughts? @PGAMiller @davidamichelson

**Comment by davidamichelson** [comment]
These should just display as plain text as if they were inside the <p without being marked up at all. Thus here it should display line 115 as "...leaves being wanting at the beginning, and after foll. 86, 87, and 88."
