### ISSUE TITLE
1113: Displaying shelfmark names in notes

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-eXist-app#642]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/1113

@wsalesky 

Currently has data missing in the notes section; need to display the text (shelfmark identifiers) in the following path:
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msContents/meItem/note/listBibl/bibl/msIdentifier/idno/

**Comment by davidamichelson** [comment]
See this section in the HTML for 1113: 
```
(see above, nos.

    .

. and

    .

.). 
```

**Comment by wsalesky** [comment]
@davidamichelson perhaps we can talk about this one at a meeting. Not sure how they should be displayed.
