### ISSUE TITLE
Displaying "Wright's Catalogue" in <recordHist>

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-eXist-app#643]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/1116

@wsalesky 

The above is an example, but in general the website is currently displaying "Origin:
Manuscript description based on . abbreviated by the Syriaca.org editors."

The text we need to input ("Wright's Catalogue" for most of the manuscripts, but not all) is located at the following path:
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/additional/adminInfo/recordHist/source/bibl/ref/

**Comment by davidamichelson** [comment]
We shoudl work URIS into here:
```
<recordHist>
                  <source>Manuscript description based on <bibl><ref target="#Wrightpart2">Wright's Catalogue</ref></bibl>. abbreviated by the Syriaca.org editors.</source>
</recordHist>
```
