### ISSUE TITLE
Authors lacking a space after their first name

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-eXist-app#645]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/1120

@wsalesky 

This is relatively minor, but I noticed that in the author attribute, the people's names lack a space after the first name, linking parts of their name into a single word. (For example, "Markthe Monk" instead of "Mark the Monk"). I will check to see if this is consistent across single part manuscripts as well, but the path for this in multipart manuscripts is as follows:

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/msContents/msItem/author/@ref

**Comment by wsalesky** [comment]
Fixed, but some English names are not showing up because we still need to update all the names to have an English headword (in this case Mark the Monk has a `en-x-gedsh` headword). So missing names should be self resolving. Spacing should be fixed though.
