### ISSUE TITLE
ERROR An IO exception occurred: Too many open files [at line 48, column 17]

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#647]
Hi Winona,

I have been getting this error alot from the production server, usually when trying to run a search:
```
/db/apps/srophe/modules/view.xqlexerr:ERROR An IO exception occurred: Too many open files [at line 48, column 17]
```
Tonight it was generated from http://syriaca.org/place/298.html when clicked out of a search result list

It often resets on refresh, but I get the error sporadically on Chrome and Firefox and on two different Macs. It seems to be only on the production server though.

**Comment by wsalesky** [comment]
See email.
