### ISSUE TITLE
Origin not displaying in history (MSS 1269)

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-eXist-app#650]
@wsalesky 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/1269

It looks like many files (including the above example) aren't displaying the origin date (and place when appropriate) for a manuscript in the history section, near provenance and acquisition. Data located at the paths below:

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/origDate/

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/origPlace/

The origDate element might have either both @notBefore and @notAfter attributes for when we have a range of dates the manuscript could be from, or an @when attribute when we have a singular date.

**Comment by wsalesky** [comment]
@PGAMiller  Do we want to display the date range, or just the text value? My first thought was to write a rule that prints the text value if available, otherwise it constructs a date range from the attributes. Let me know what you think.

**Comment by davidamichelson** [comment]
Please display both thus in this case: "XIII (1200-1300)" constructed from the textnode (range)
