### ISSUE TITLE
Videos are too large for me to deploy as part of .xar

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#689]
@nathangibson @davidamichelson We can discuss alternative ways to handle videos, hosting them outside the app, or loading them later etc.

**Comment by davidamichelson** [comment]
I just saw this now. Was this part of how I crashed things? I will look into alternate hosting. I could load them to the blog for example?

**Comment by wsalesky** [comment]
No, sadly that is unrelated. The videos are in the app, not the data repo. It would be great if you could load them on the blog and we can just adjust the links from the tutorials.

**Comment by davidamichelson** [comment]
fixed
