### ISSUE TITLE
SPEAR error messages

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#690]
I get error messages on:
http://wwwb.library.vanderbilt.edu/spear/browse.html?view=persons
http://wwwb.library.vanderbilt.edu/spear/browse.html?view=places

**Comment by wsalesky** [comment]
Sorry! I made some changes for manuscripts, must have broken something. Will fix tonight.

**Comment by dlschwartz** [comment]
Thanks!

On Mon, Jul 25, 2016 at 11:25 AM, Winona Salesky <notifications@github.com>
wrote:

> Sorry! I made some changes for manuscripts, must have broken something.
> Will fix tonight.
>
> Sent from my iPhone
>
> > On Jul 25, 2016, at 12:06 PM, Daniel Schwartz <notifications@github.com>
> wrote:
> >
> > I get error messages on:
> > http://wwwb.library.vanderbilt.edu/spear/browse.html?view=persons
> > http://wwwb.library.vanderbilt.edu/spear/browse.html?view=places
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2DeXist-2Dapp_issues_690-23issuecomment-2D235005254&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=gma4o6VCV7wEzgjhEl5H15yGgOn9zWbg6H7ZX4bqXws&s=6BdN3b-9DtY-ENUr4WrFbajhvYZRjkxwZ0H_AVC5gY8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzl3srC-5FzKMmgmOWk6uXkNcnKQ9rWks5qZOOIgaJpZM4JUSIy&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=gma4o6VCV7wEzgjhEl5H15yGgOn9zWbg6H7ZX4bqXws&s=CvoC8-jqMI_fABsAh8xca1y8JPxtxgtdF-klvjkVnWY&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
www.syriaca.org <http://syriaca.org/>
