### ISSUE TITLE
New Syriaca.org Landing Page for August 2016

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#695]
This is for commentary on: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/index.html

**Comment by davidamichelson** [comment]
Please add Mary as the image for Saints on the main page.

**Comment by davidamichelson** [comment]
Add what is "Syriaca.org" section?

**Comment by davidamichelson** [comment]
For landing page only change the dropdown menu name from Syriaca.org to "Publications"

**Comment by davidamichelson** [comment]
Persons needs an image

**Comment by dlschwartz** [comment]
Rename "events" to read "SPEAR"

**Comment by davidamichelson** [comment]
All modules need short descriptions and a favorite record.

**Comment by dlschwartz** [comment]
[Image for SPEAR ](https://commons.wikimedia.org/wiki/File:Moqimu_mosaic_Edessa.jpg)

**Comment by davidamichelson** [comment]
Main advanced search, could be improved: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/search.html

**Comment by nathangibson** [comment]
Icon link at bottom of each module is broken.

**Comment by nathangibson** [comment]
![img_0990](https://cloud.githubusercontent.com/assets/3083452/17223797/7a6b40d0-54fe-11e6-9a03-c1cf7839a16a.PNG)
![img_0991](https://cloud.githubusercontent.com/assets/3083452/17223807/81cdc276-54fe-11e6-8d87-46f02a07acd7.PNG)

**Comment by davidamichelson** [comment]
Could the carousel advance one each time we refresh? Not essential now

**Comment by davidamichelson** [comment]
@wsalesky Could you give us an ideal character count for the short description for the carousel?

**Comment by davidamichelson** [comment]
The record and sentence for bibl module are posted here: https://github.com/srophe/srophe-eXist-app/issues/702#issuecomment-236299313

**Comment by wsalesky** [comment]
Need "What is Syriaca.org?" content for home page. @davidamichelson

**Comment by davidamichelson** [comment]
Please make the "short descriptions" clickable so that they take you the respective index pages. Thank you!

**Comment by davidamichelson** [comment]
Could we try out the full module names on the carousel at the bottom? Thus instead of SBD, Syriac Biographical Dictionary? Etc? I know this may become cumbersome, but it would be nice if we can, even if the font is small.

**Comment by wsalesky** [comment]
@davidamichelson Just wanted to let you know that I'm working on this. So far I have not found a way to include the full title and the icon without things getting out of wack. (Bad alignment between icon and text, and wrapping titles even with very small fonts.)

What about having the full title in the rollover section, where the short blurb and sample record show up, and the bottom icon and text match the icon and text in the dropdown 'hamburger' menu?

**Comment by davidamichelson** [comment]
@wsalesky Here are the missing sentences and models

Sentences:

SBD:  _The Syriac Biographical Dictionary_ is a multi-volume guide to persons related to Syriac culture or history.

Sample: person/779
Authors: _A Guide to Syriac Authors_ is a handbook of persons who wrote in Syriac or otherwise had an influence on Syriac literature.

Sample: person/13

**Comment by nathangibson** [comment]
Ohh, I like your choice of SBD sample person :-)

**Comment by nathangibson** [comment]
@davidamichelson What would you think about changing authors short description to read

> **_A Guide to Syriac Authors_** is a handbook of persons who wrote in Syriac or otherwise influenced Syriac literature.

("influenced" instead of "had an influence on")

Also, @wsalesky we should add "Example record:" above Ephrem like we have for the other modules.

**Comment by davidamichelson** [comment]
Need prose for landing pages and image citations
