### ISSUE TITLE
Global Search for Syriaca.org Debugging

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#696]
Please test: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/search.html

**Comment by tacarlson** [comment]
I got excited about this and what it might enable, so I played around with it a little.  I think it will be really cool!

Here are a few design ideas to think about which I noted in the process:
1. Search result lists from multiple modules (e.g. including both places and persons) should perhaps have some indicator as to what type something is (e.g. searching for "Awgen" in keyword, 1 is a place, 2 an author, 3-5 places, 6 a person, 7 a text, 8 a saint, etc.)

2. I am perhaps not understanding how the Syriaca URI search is supposed to work.  When I searched for http://syriaca.org/place/78 I received 9055 search results, the third of which already has no reference to this URI in its TEI.

3. We may want some pop-up instructions.  I was unable to obtain any results from the Citation search using such common prompts as "Assemani" or "GEDSH".

**Comment by tacarlson** [comment]
Oddly, GitHub renumbered my points 2 and 3 as points 1 (bis) and 2...

**Comment by wsalesky** [comment]
Thanks @tacarlson.
Sounds like #1 is a bug. I will take a look. I think you are correct on the need to differentiate the results based on data type, I will come up with some options and solicit feedback.

**Comment by wsalesky** [comment]
I fixed a few of these bugs. Still troubleshooting the search by "Syriaca.org URI"

**Comment by davidamichelson** [comment]
I think this can wait until after Rome

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz @nathangibson @jsaintlauren 

What would you expect to have returned by the Syriaca.org URI search (http://syriaca.org/search.html)?

Just the matching record? Or any record that also references that URI (in say a relationship). 
Thanks!
-Winona

**Comment by nathangibson** [comment]
I would think the matching record on top but perhaps also references to that URI lower down in the search. IMHO.

**Comment by wsalesky** [comment]
All references:
ref
target
passive
active
mutual

**Comment by wsalesky** [comment]
Have enabled this, there are bad things happening with ordering.

**Comment by wsalesky** [comment]
Fixed order, investigating lag in speed.

**Comment by wsalesky** [comment]
Fixed lag in speed and bad sorting.

Function of global 'Syriaca.org URI:' is to retrieve any records that contain the URI as a string and also any records that refer to the URI via ref, target, passive, mutual, active attributes. Results are weighted so the record with tei:idno matching search URI will be returned at the top (most relevant).
