### ISSUE TITLE
Visualizing literary traditions

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#697]
@wsalesky We are creating a new type of work record called "literary tradition". (See https://github.com/srophe/srophe-app-data/issues/463) 
If a work is referenced as `@passive` in a `<relation name="syriaca:part-of-tradition">`, then please do the following in the main body of the record. (Example is http://syriaca.org/work/2057 referenced by http://syriaca.org/work/410 and other records.)

Header that says "This tradition is extant in [count number] of branches"
followed by a description contained in `<note type="literary-tradition">` (if present)
followed by a list of the works that link to it in the following format:
[Work title] URI: [work URI] [list of Manuscript witnesses for the work, except for ones that contain the word "undetermined"] 

Let me know if this makes sense. Thanks!

**Comment by wsalesky** [comment]
@nathangibson is this one that should happen before Rome?

**Comment by nathangibson** [comment]
We were hoping so, but perhaps we should discuss today.

**Comment by nathangibson** [comment]
Thoughts @jsaintlauren @davidamichelson ?

**Comment by jsaintlauren** [comment]
I would say we could try, but I don't think it is as high of a priority as
other things that Winona has on her plate. :) Dave?

**Comment by davidamichelson** [comment]
Okay, this should wait until after Rome

**Comment by nathangibson** [comment]
Note to self: We should probably change this RDF property to "syriaca:isPartOfTradition" since I think RDF properties normally use camelCase.

**Comment by dlschwartz** [comment]
Quick question, how does camel case deal with a colon? Should this example
have "is" or "Is"?

On Tue, Sep 20, 2016 at 8:18 AM, nathangibson <notifications@github.com>
wrote:

> Note to self: We should probably change this RDF property to
> "syriaca:isPartOfTradition" since I think RDF properties normally use
> camelCase.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2DeXist-2Dapp_issues_697-23issuecomment-2D248298679&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1AwCjIJR-xe_HGU_rkJA1NjA0sAw7Tv_IwSbCTEZR9Q&s=xREpYHnpuBSLa3Mik19hWwAMrVBP2z4D70RVDQOU09Y&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzuTNFf4jGOWsx2FrnaK6EjcfZCJ2ks5qr90-2DgaJpZM4JXhEl&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1AwCjIJR-xe_HGU_rkJA1NjA0sAw7Tv_IwSbCTEZR9Q&s=Z6mNhT6TSp4XhEFF6jA9A9wesWbWtEKht-sVuy99c8c&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by nathangibson** [comment]
E.g., LAWD uses “hasAttestation” so when you add the prefix it would be “lawd:hasAttestation”.

**Comment by dlschwartz** [comment]
Very good, thanks.

On Tue, Sep 20, 2016 at 2:58 PM, nathangibson <notifications@github.com>
wrote:

> E.g., LAWD uses “hasAttestation” so when you add the prefix it would be
> “lawd:hasAttestation”.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2DeXist-2Dapp_issues_697-23issuecomment-2D248416275&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=uStisdVV2nIGc3w4r5ENBlW7crseAxU768DOCb21wHs&s=a8iv4nVsI5oFKInQWoZVybk7MTWltacnkkSnPhMKIRI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzqJ6gDyRBM1p3nBqwbUD9jwyKcBGks5qsDrwgaJpZM4JXhEl&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=uStisdVV2nIGc3w4r5ENBlW7crseAxU768DOCb21wHs&s=vmixT_QQaJr8HvwcJ1Dim3xTCwu8wjBg20UPRI7wfag&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by wsalesky** [comment]
@nathangibson Do we need to revive this issue? I do not think I did any work on it, but also not sure if other NHSL work supersedes this?

**Comment by nathangibson** [comment]
The functionality we're going for here will be similar to isPartOf (containing) relations. We should definitely discuss the details (perhaps this Wed.?). If it's quick you could mock it up using the code you did for isPartOf relations. 

cc: @davidamichelson

**Comment by wsalesky** [comment]
Okay, is this going to be 'syriaca:part-of-tradition' or will it be  'syriaca:isPartOfTradition'

**Comment by wsalesky** [comment]
Sample visualization:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/2057

**Comment by davidamichelson** [comment]
Revise this label: This tradition is extant in 4 branches.

Please say: This tradition is extant in at least 4 branches

**Comment by davidamichelson** [comment]
Change to:

Branches
This tradition comprises at least 4 branches.

**Comment by wsalesky** [comment]
Done.

**Comment by nathangibson** [comment]
Literary tradition records seem to have stopped showing their constituent branches. E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/2057 and http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9628. I assume because of the relation `@ref` change? The `relation/@ref` is now skos:broadMatch, e.g, http://wwwb.library.vanderbilt.edu/work/1 and http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/410.

**Comment by nathangibson** [comment]
Here's one that came up yesterday (gentle reminder)

**Comment by nathangibson** [comment]
Not sure if this is related to the literary traditions issue we discussed yesterday (the one you needed some time to solve). Anyway, it's important so I just don't want this one dropping off the radar. Thanks!

**Comment by nathangibson** [comment]
@wsalesky If you get a break from workshop stuff, this is one of the top NHSL issues I would like to get solved. It was working earlier -- it may be just a matter of updating it to recognize the skos:broadMatch relation.

**Comment by wsalesky** [comment]
I will take a look tonight. Thanks for the reminder.

**Comment by wsalesky** [comment]
Done.
