### ISSUE TITLE
Faceted Search for Persons

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#698]
@wsalesky @dlschwartz @davidamichelson @jsaintlauren
I would suggest the following for faceted search for persons. (Header labels in **bold**. Criteria in parentheses.)

**Type**
author (http://syriaca.org/authors in seriesStmt)
saint (http://syriaca.org/q in seriesStmt)

**Include Anonymous?** [no by default]
yes (I think `trait/label="anonymous"` but we need to standardize our data)
no

**Century**
(using dates in birth/death/floruit, but include an "Unspecified" option to include records that don't have a date entered)

**Sex or Gender**
(same as advanced search option, but include a "Unspecified" option to include records that don't have sex marked)

**Has name in** 
(list of languages in `persName/@xml:lang`. Once I finish the language code documentation, you'll be able to pull the human readable name from that. Until then you could just display the language code itself.)

**Office**
(List of `state[@type="office"]`. Currently this is in `@role` but we will probably be moving it to `<label>` instead. Include "Unspecified".)

**Saint type**
(List of `state[@type="saint"]`. Currently this is in `@role` but we will probably be moving it to `<label>` instead.)

**Occupation**
(List of `state[@type="occupation"]`. Currently this is in `@role` but we will probably be moving it to `<label>` instead. Include "Unspecified".)

**Places** (Is it possible to include the name of the place underneath the following categories? If not, it could just be the place names themselves. The code will change when we clean up relation names. This should have a "More" button like you've done on SPEAR advanced browse, since there could be a lot of these.)
Born (`relation[name="born-at"]`)
Died (`relation[name="died-at"]`)
Literary Connection (`relation[name="has-literary-connection-to-place"]`)
Unspecified Connection (`relation[name="has-relation-to-place"]`)

**Found in**
(This is a curated list of standard biographical resources that people might be using.)
"ʿAbdishoʿ bar Brikha, Margānitā" (`bibl[ptr/@target="http://syriaca.org/bibl/6"]`)
"Abūnā, Adab" (`bibl[ptr/@target="http://syriaca.org/bibl/643"]`)
"Assemani, Bibliotheca Orientalis" (`bibl[ptr/@target=("http://syriaca.org/bibl/7","http://syriaca.org/bibl/644","http://syriaca.org/bibl/709","http://syriaca.org/bibl/1209","http://syriaca.org/bibl/1700","http://syriaca.org/bibl/2034")]`)
"Barsoum, Scattered Pearls" (`bibl[ptr/@target=("http://syriaca.org/bibl/2","http://syriaca.org/bibl/3","http://syriaca.org/bibl/4")]`)
"Baumstark, Geschichte" (`bibl[ptr/@target="http://syriaca.org/bibl/638"]`)
"Brock, Literature" (`bibl[ptr/@target="http://syriaca.org/bibl/645"]`)
"Chabot, Littérature" (`bibl[ptr/@target="http://syriaca.org/bibl/640"]`)
"Duval, Littérature" (`bibl[ptr/@target="http://syriaca.org/bibl/644"]`)
"Fiey, Saints Syriaques" (`bibl[ptr/@target="http://syriaca.org/bibl/650"]`)
"Gorgias Encyclopedic Dictionary" (`bibl[title="The Gorgias Encyclopedic Dictionary of the Syriac Heritage"]`)
"Macuch, Geschichte" (`bibl[ptr/@target="http://syriaca.org/bibl/642"]`)
"Minov, Comprehensive Bibliography" (`bibl[ptr/@target="http://syriaca.org/bibl/5"]`)
"Ortiz de Urbina, Patrologia Syriaca" (`bibl[ptr/@target="http://syriaca.org/bibl/641"]`)
"Prosopography of the Later Roman Empire" (`bibl[ptr/@target=("http://syriaca.org/bibl/672","http://syriaca.org/bibl/673","http://syriaca.org/bibl/674","http://syriaca.org/bibl/676")]`)
"Wright, Literature" (`bibl[ptr/@target="http://syriaca.org/bibl/639"]`)
"Zanetti & Detienne, Bibliotheca Hagiographica" (`bibl[ptr/@target="http://syriaca.org/bibl/649"]`)

Eventually we will want state[@type="confession"], but our data is probably not good enough to try this yet.

**Comment by nathangibson** [comment]
OK, I've updated the list of desired facets for person search. Feedback?

@wsalesky I'm happy for you to go ahead and try this. However, if there are things above that would require you adding new features to the faceted search, please wait until we can discuss with D & D.

**Comment by wsalesky** [comment]
@nathangibson Thank you. I think I will need to do a little work to get some of these to work. I'm sticking this in the todo list after the bibl citations get ironed out. So may not happen by Thursday.

**Comment by nathangibson** [comment]
No problem. We could wait until Thursday for any of the problematic ones.

**Comment by wsalesky** [comment]
I don't think I understand what I am supposed to facet on for 'Found in'

**Comment by nathangibson** [comment]
It would facet for the sources cited by the person records appearing in the results. However, simply grouping by the `ptr/@target` wouldn't work because some of the important titles (e.g., GEDSH and Assemani) are referenced using ptrs for parts of the work on the article or volume level. That's why I provided the list with XPaths for each. But if this is complicated we should discuss whether it's worth it. I can see a use case where someone is looking for a particular "John" that appears in Wright, and so they want to view only those "Johns." But being able to do this is not that important and could probably be done with the advanced search, right?

**Comment by wsalesky** [comment]
Hum, I will save that for last. Still working through a number of bus and issues, but you can take a look at the in progress version:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?view=facets

It is fun to see what is going on across the data.

**Comment by nathangibson** [comment]
This is seriously cool! It will really help people explore the data, as well as narrow down searches. It will also help us identify messy data :-). Thanks for working on this. Let me know when you want me to test it.

**Comment by wsalesky** [comment]
NOTE to self: Reset start param to 1 when adding a facet value.

**Comment by wsalesky** [comment]
@nathangibson This is ready for testing. I do need to hook up names to the URI displays for Literary Connection, Born, Died, etc. I also need to translate the lang codes into something more readable, I forget, do we have an data dictionary somewhere that provides this info?

**Comment by nathangibson** [comment]
Great! Will test! As for human-readable language codes, I’m supposed to be working on that … :-) 

Related: https://github.com/srophe/srophe-eXist-app/issues/514

**Comment by nathangibson** [comment]
Browse by type (author/saint) seems to be working correctly.

**Comment by nathangibson** [comment]
What is the default sort? Kind of funny that when you filter to authors, our colleague George Kiraz shows up first.

**Comment by nathangibson** [comment]
The more/less buttons repeat the first 5 labels when you expand.

**Comment by nathangibson** [comment]
This is just so awesome. It makes me so happy!

**Comment by nathangibson** [comment]
The number count in parentheses beside each filter label seems to be counting matching elements rather than matching records. Is that what it's supposed to do? As a user, I would expect it to be showing me a count of records. Not a big deal, and for most criteria it's the same, but it's way off on names, for instance.

**Comment by nathangibson** [comment]
When the remaining result records have no data for certain categories (e.g., no birth location), then those categories show up just as text headers. E.g., see "Born," "Died," etc. for http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?fq=;fq-Sex%20or%20Gender:eunuch;fq-Century:300-400&view=facets. This behavior is a little disorienting. Could we perhaps have "(0)" appear either beside or under these headers?

**Comment by nathangibson** [comment]
I like the way the chosen filters show up as bubbles at the top left of the page. However, could we prefix the label to them? E.g., "Has name in: en" rather than just "en"?

**Comment by nathangibson** [comment]
Just FYI: Strange that we are only seeing 2 martyrs. This is probably inconsistent data in the state element (again, my job to work on). But Advanced Search for "martyr" shows 184 matches.

**Comment by nathangibson** [comment]
OK, done testing. As you see, I came up with some tweaks, but I couldn't break anything. Either the code is sound or you've totally profiled my click behavior and swept all the bugs into other corners. 

This is such a fun way to explore the data! I think our users are going to love it. It's also great for figuring out where we need to clean up data :-). Thanks so much.

**Comment by wsalesky** [comment]
Let's hope it is because the code is sound. ;) I will look into the suggested tweaks. The issue with the element vrs. record was something I noticed as well. I will have to think a little more about this, as I'm not sure what expected behavior for facets should be. We can talk about it at our meeting. 

Also, we can add this to the search results as well if you would like.

**Comment by nathangibson** [comment]
Thanks. Would *love* to see this on search results, though we might want to wait a bit until we have the most obvious data formatting addressed (like sex/gender).

**Comment by wsalesky** [comment]
Sure, although it will use the same code, so fixing any issues in one place will fix it in both.

**Comment by nathangibson** [comment]
Yes, I just mean our data inconsistencies might be more noticeable in search because people will probably be using search more.

**Comment by wsalesky** [comment]
Made some updates, and just for fun, tried plugging it in to BHSE:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/browse.html?fq=;fq-&view=facets

**Comment by nathangibson** [comment]
Very cool! I really like the commemorated facet.

**Comment by nathangibson** [comment]
I wonder why the second facet under commemorated doesn’t have a name ...

**Comment by wsalesky** [comment]
Interesting....

**Comment by wsalesky** [comment]
Fixed. Needed to normalize spaces before tokenizing.

**Comment by jsaintlauren** [comment]
This is really great!

**Comment by wsalesky** [comment]
This is being debugged on this issue:
https://github.com/srophe/srophe-eXist-app/issues/891
