### ISSUE TITLE
Bibl Module Search

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#700]
So this search: al-Lu'lu' al-manṯūr fī ta'rīh al-‘ulūm wa-l-ādāb al-suryānīya (Histoire de la littérature syriaque)

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/search.html?q=al-Lu%27lu%27+al-man%E1%B9%AF%C5%ABr+f%C4%AB+ta%27r%C4%ABh+al-%E2%80%98ul%C5%ABm+wa-l-%C4%81d%C4%81b+al-sury%C4%81n%C4%ABya+%28Histoire+de+la+litt%C3%A9rature+syriaque%29

Should turn up this record: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1386

But does not. Is it not searching tei:bibl/tei:title[2]?

**Comment by davidamichelson** [comment]
Same problem when I just uses smaller snippets of the title.

**Comment by wsalesky** [comment]
The title in the `body/biblStruct/monogr/title` contains 'al-Luʼluʼ al-manthūr fī tārīkh al-ʻulūm wa-al-ādāb al-Suryāniyyah' the title in the `TEI/teiHeader/titleStmt/title` contans 'al-Lu'lu' al-manṯūr fī ta'rīh al-‘ulūm wa-l-ādāb al-suryānīya (Histoire de la littérature syriaque)'

I have been doing the searches on the contents of the body, excluding header info, but I can change that. (I have had to already for manuscripts.)

**Comment by davidamichelson** [comment]
Yep that is problem, I was searching on two phrases from the header title not the body! Don't change your code we want to exclude header info from the search (except perhaps to allow a search by entry editor! but I will file an issue for that).
