### ISSUE TITLE
Bibl Module General Debugging

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#702]
@wsalesky I will begin to post her bugs and revisions for the bibl module.

**Comment by davidamichelson** [comment]
This module should be called "Syriaca.org Works Cited" (so we are not in competition with other Syriac bibliography projects). 

For an icon in the dropdown hamburger menu and in the module header, could you please find an icon that is a stack of books that is similar but distinct from the documentation icon: like this http://image.shutterstock.com/z/stock-vector-books-icon-professional-pixel-perfect-icons-optimized-for-both-large-and-small-resolutions-eps-349647695.jpg

As an FYI, the documentation icon could be red and works cited black.

**Comment by davidamichelson** [comment]
This module should appear in the carousel of the main syriaca.org landing page, but always as the last item. 

Here is a short sentence: Reference list of works cited in Syriaca.org publications.
Sample record: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1396

**Comment by davidamichelson** [comment]
Here is an idea for an image for the works-cited-module. If this is worth pursuing, I will get a good camera and better light, arrange colors etc.:
https://github.com/srophe/projects/blob/master/works-cited-module/books1.png

please crop the image.

**Comment by davidamichelson** [comment]
For the Browse, we want to keep title as the default.

Please add browse sorted by alpha of tei:biblStruct/tei:author/tei:surname[1] (or should this be the default?)

And browse where they are sorted by tei:imprint/tei:date, oldest first?

And browse sorted by alpha of tei:pubPlace?

**Comment by davidamichelson** [comment]
Please make the information in the "Preferred Citation" box a larger font than the reset of the info on the page to make it standout.

**Comment by davidamichelson** [comment]
And will work on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/search.html

**Comment by wsalesky** [comment]
Updated carousel on home page with blurb and image. I like the books image, I also used it for the banner:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/index.html

If you retake the picture, maybe try to reduce the glare? Otherwise I think it works nicely. Thanks!

I'm working through the rest of the list this weekend. (Icon will probably come last, so I have added a place holder in the drop down menu.)

**Comment by wsalesky** [comment]
@davidamichelson  Added additional sort options for bibl module. Please test. Also, looks like there are some misplaced records, due to numbers and quotes in the title string. Should I filter for those? Or should they be changed in the data?

**Comment by wsalesky** [comment]
@davidamichelson I think this is ready to be closed. Please review and close if you agree. Thanks.

**Comment by davidamichelson** [comment]
Okay for the misplaced records that is now issue https://github.com/srophe/srophe-eXist-app/issues/704

**Comment by davidamichelson** [comment]
Closing this and opening a few issues for after rome
