### ISSUE TITLE
Ignore Numeric and Punctuation in Bibl Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#704]
@wsalesky on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/browse.html?view=other&sort=A

Why does this appear in the non-English list?

Title: “Whence Comes Your Holiness, Father?” On the Life of Malkha and John of Asia
Jan J. van Ginkel, "“Whence Comes Your Holiness, Father?” On the Life of Malkha and John of Asia," in G. J. Reinink and Alexander Cornelis Klugkist (eds.), After Bardaisan: studies on continuity and change in Syriac Christianity in honour of Professor Han J.W. Drijvers (Leuven: Uitgeverij Peeters en dép.oosterse Studies, 1999)URI: http://syriaca.org/bibl/2141

**Comment by wsalesky** [comment]
No language tag. I can add test for english start characters, but the quotes at the beginning of the title could be an issue.

**Comment by davidamichelson** [comment]
I bet that is it. I will change the record and see.

**Comment by davidamichelson** [comment]
Okay, we are down to just one record which is causing trouble here: 

Title: “Whence Comes Your Holiness, Father?” On the Life of Malkha and John of Asia
Jan J. van Ginkel, "“Whence Comes Your Holiness, Father?” On the Life of Malkha and John of Asia," in G. J. Reinink and Alexander Cornelis Klugkist (eds.), After Bardaisan: studies on continuity and change in Syriac Christianity in honour of Professor Han J.W. Drijvers (Leuven: Uitgeverij Peeters en dép.oosterse Studies, 1999)URI: http://syriaca.org/bibl/2141 

The issue is that in the test for script (and in alphabetizing) we need to ignore 0-9 and any punctuations (in this case quotation mark) so that this gets alphabetized under W for title.

**Comment by davidamichelson** [comment]
This can wait until after Rome

**Comment by wsalesky** [comment]
This was resolved.
