### ISSUE TITLE
BHSE about page is empty

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#707]
@davidamichelson @jsaintlauren BHSE about page is still needs content, or needs to be removed from the top menu bar. Also the contribute page is empty as well. 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/about.html

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/contribute.html

**Comment by wsalesky** [comment]
Also, help pages are empty.

**Comment by jsaintlauren** [comment]
OK - I will get to this this morning. Thanks!

**Comment by wsalesky** [comment]
Stale issue.
