### ISSUE TITLE
Please make a Srophe App Icon for use with the app

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#709]
@wsalesky Since our app is now being used by LOGAR and hopefully others, we should have a logo to brand it. What do you think about using our current style of logo for it? If we want to be technically correct, it should incorporate the letter used in the authors logo, but I will look around for options and let you know.

**Comment by wsalesky** [comment]
What if we use the one here:
https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/resources/img/syiaca-partner-3.png

Without the 'partner' text on the bottom?

**Comment by davidamichelson** [comment]
This can wait until after Rome, but my suggestion would be that we use the existing aleph icon but instead of the Syriaca.org text we put "srophe" in all lower case. We also recommend that partners who use the icon have it be a button that links to www.syriaca.org/srophe where we will have an about page about the app. How does that sound? Would LOGAR be interested in doing that? I will ask Steve.

**Comment by wsalesky** [comment]
Done:
https://github.com/srophe/srophe-eXist-app/issues/799
