### ISSUE TITLE
Header Image for Persons

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#711]
@wsalesky Would you mind trying a cut of some people from any of these images:

- http://www.bl.uk/onlinegallery/sacredtexts/syriaclect_lg.html
- http://www.artbible.net/3JC/-Mat-21,01-Entre_a_Jerusalem_Entry/slides/13%20SYRIAC%20ENTRY%20INTO%20JERUSALEM.html
- https://s-media-cache-ak0.pinimg.com/564x/34/7e/f5/347ef54d0fa26de2652eacd81a8643ba.jpg
- http://www.warfare.altervista.org/13/Syriac_Gospel-c1220.htm

**Comment by davidamichelson** [comment]
@nathangibson Any suggestions from these? Maybe the women at the tomb?

**Comment by wsalesky** [comment]
Okay. That reminds me can I get a full copy of the image used for saints. I seem to have misplaced mine.

**Comment by wsalesky** [comment]
I liked the women at the tomb. 
See: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html
and:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/index.html

**Comment by jsaintlauren** [comment]
I do, too!

**Comment by nathangibson** [comment]
I also like the women at the tomb.

**Comment by davidamichelson** [comment]
this image should come Monday
