### ISSUE TITLE
Revisions to Footnote Style for Entity Records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#715]
Please edit the new chicagonotes.xls style for footnote to make the following changes.

Based on the citation of http://syriaca.org/bibl/4 as footnote 2 in record http://wwwb.library.vanderbilt.edu/person/13

Should read:

Ignatius Afram Barsoum, _The Scattered Pearls: A History of Syriac Literature and Sciences_, trans. Matti Moosa, 2nd rev. ed. (Piscataway, NJ: Gorgias Press, 2003), entry: 9, pp: 229.

Changes:
- comma after author for monograph not period
- comma after trans. or ed.
- no parens around edition

**Comment by wsalesky** [comment]
This has been resolved by this commit: 
https://github.com/srophe/srophe-eXist-app/commit/c3198c9b706a071239e86dd91d94db9058290123
