### ISSUE TITLE
Starting NHSL landing page and sample work(s)

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#719]
@wsalesky cc: @davidamichelson 
I'm getting some things ready to demo the NHSL at Rome, and some of them will need your support. 

 1. I will be writing some text for the landing page. OK to put this in https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/nhsl/index.html ?
 2. We have some ideas for an image. We'll get that to you soon. 
 3. Where should I put example records where they can be displayed on the dev server? We don't want them to be published to the production server when BHSE goes live. If I put them in https://github.com/srophe/srophe-app-data/tree/dev/data/works/tei but they have a different seriesStmt from BHSE, will they stay off the production server?
 4. The TEI format for new NHSL works is a bit different from BHSE. Some of it is experimental. I'll be in touch regarding some specific adaptations we'll need to make to the XSLT for visualization.

**Comment by wsalesky** [comment]
@nathangibson 
1. Yes, go ahead. I have webhooks set up on the dev server for the app, so you should be able to view your changes immediately. If not let me know. 
2. Great!
3. You can put them in a https://github.com/srophe/srophe-app-data/tree/dev/data/works/tei/nhsl/tei directory, similar to how we did saints. This will allow us to easily keep them separate. Although long term we probably want to move things to the production server based on the `<revisionDesc status="draft">` where status would equal 'published'
4. Okay.

**Comment by nathangibson** [comment]
Sounds great, thanks!

**Comment by nathangibson** [comment]
1. Drafted.
2. See https://github.com/srophe/srophe-eXist-app/issues/723.
3. Done.
4. Will start a new issue. 

Closing this issue.
