### ISSUE TITLE
Map has disappeared for persons

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#720]
@wsalesky Forgot to mention this earlier -- map has not been showing for persons for a while. e.g., http://wwwb.library.vanderbilt.edu/person/13

**Comment by wsalesky** [comment]
@nathangibson Congratulations! You have just bumped our issue list to 100. I have been wondering when we would get there! :)

I will take a look at the map issue. Thanks.

**Comment by nathangibson** [comment]
When it rains, it pours, huh? Glad the rain barrel is half-full instead of half-empty.

**Comment by jsaintlauren** [comment]
@wsalesky we are stopping at the Gucci store for you in Rome :)

**Comment by wsalesky** [comment]
👍
