### ISSUE TITLE
Bibl Module Icon

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#722]
Split from https://github.com/srophe/srophe-eXist-app/issues/702

I love the new bibl module icon. A couple questions about use. Should we use it in the Carousel too? Should we use it in the sources on each entry page (I am inclined to think no for there). Let's discuss at weekly meeting.

**Comment by wsalesky** [comment]
I put it on the carousel on my machine, looks like I need to do a little image cleanup before we can use it with a dark background. Some lazy svg on my part. Will get it cleaned up tonight.
