### ISSUE TITLE
NHSL header image

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#723]
@davidamichelson Is it OK if we have @wsalesky try one of the following for an NHSL header image?
[BNF Syriaque 27, f. 92v from Bibliothèque nationale de France](http://gallica.bnf.fr/ark:/12148/btv1b531151912/f188)
[BNF Syriaque 27, f. 92r from Bibliothèque nationale de France](http://gallica.bnf.fr/ark:/12148/btv1b531151912/f187)
[BNF Syriaque 40, f. 5v from Bibliothèque nationale de France](http://gallica.bnf.fr/ark:/12148/btv1b10527642w/f16)

I'm fine on any of these, at least until we see how they look on the page, so if you have a preference ... 
All of these are in the public domain according to the "detailed information" notice on the page.

**Comment by wsalesky** [comment]
@nathangibson first try. I also liked this one:
http://gallica.bnf.fr/ark:/12148/btv1b10527642w/f16

But it was hard to get enough of the design in the banner. I can fiddle with it more if you like.

**Comment by nathangibson** [comment]
As per yesterday's discussion, we like the one you've done (a lot). If we can just make sure the top of the arches are still visible on wide screens, that'd be great. 

Also, did you see how to download the highest res version? If you click the download icon on the left toolbar, and then select JPEG, you'll see the option "une partie de l'image dans une résolution supérieure". Click that and then select the area of the image you want to download. To me it looks like higher resolution than what I'm currently seeing on the NHSL banner image. Or is that just the way the banner displays on my fancy-schmancy screen? 

@davidamichelson For photo credit what about the following? "Photo Credit: BNF Syr. 27, f. 92r from Bibliothèque nationale de France, Département des Manuscrits, Syriaque 27 (719 CE)"
In the info box under photo credit: "Image in the public domain" 

@wsalesky I'll leave it to you to close this when you're ready.

**Comment by wsalesky** [comment]
@nathangibson Let me know how the new image looks. I had some trouble downloading just a selected part.

**Comment by nathangibson** [comment]
That looks pretty good to me.  I think the differences I see now might be just compression rather than pixelation like earlier. (And I know we need the compression for load time.) I’ll send you an email with what I have, which is probably the same resolution as what you have.

**Comment by davidamichelson** [comment]
hmm, here is what this looks like full screen on 27 inch imac screen (older version, 2560 x 1440 pixels, NOT the Retina 5K).

Could the image be zoomed out a bit more please?

**Comment by wsalesky** [comment]
I did not get a screen shot with that @davidamichelson can you send it via email? The only way to get more of the image to show is if I do not stretch it all the way across the screen (essentially add some padding to either the image or the banner itself).

**Comment by wsalesky** [comment]
@davidamichelson how does it look now?

**Comment by davidamichelson** [comment]
Okay, it looks good to me!

@nathangibson Do we want to add it to the dev server caroussel?

**Comment by nathangibson** [comment]
Yes, please.

**Comment by wsalesky** [comment]
Closing, this was resolved but never closed.
