### ISSUE TITLE
NHSL sample works visualization

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#724]
@wsalesky 
Here's how we want to visualize the sample works (per https://github.com/srophe/srophe-eXist-app/issues/719). You can use https://github.com/srophe/srophe-app-data/tree/dev/data/works/tei/nhsl/tei/2501.xml as an example.

@davidamichelson I think we've discussed most or all of this, but please mention if something here is off.

I'll give this to you piece-by-piece. 
1. We are using `@type` on `<bibl>` with a [lawd:](http://lawd.info/ontology/) type to indicate the type of bibliographic item. This goes directly inside the main work bibl. This is instead of a bibl inside a note with `@type` on the note. 
   1. Anything that should be visualized in the "Editions" section is `@type="lawd:Edition"`
   2. For "Modern Translations" section, `@type="lawd:Translation"`
   3. For "Manuscript Witnesses", `type="lawd:WrittenWork"`. Currently discussing with @davidamichelson what should go inside these bibls (see https://github.com/srophe/srophe-app-data/issues/499), so don't worry too much about how the content displays yet.
   4. For additional "Sources", `@type="lawd:Citation"`. The other types of bibls should also be repeated in the Sources section.
   5. I haven't yet worked out how to mark ancient versions.

**Comment by nathangibson** [comment]
The main work bibl has a subject classification as `@ana` plus a link to a controlled vocabulary at http://syriaca.org/documentation/work-subject-classifications.xml. You can pull the `<label>` text from the item linked there and put it under the titles as "Subject: ". For example, `ana="http://syriaca.org/documentation/work-subject-classifications.xml#history-universal"` should render as "Subject: Universal History".

**Comment by nathangibson** [comment]
3.Under the main work bibl, the following element content can be simply visualized like so:
```
<date>13th century</date>
<extent>2 parts</extent>
```
Date: 13th century
Extent: 2 parts

**Comment by nathangibson** [comment]
4.We will not be using `@n` on edition bibls. I don't think that affects you're visualization in any way-we think it's vestigial. Let me know if there's something you use that for.

**Comment by nathangibson** [comment]
5.In BHSE we are linking editions to MSS using `@corresp` but we are changing this to a `listRelation/relation[@type="mssWitnesses" and @ref="dct:source"]` with the `@passive` pointing to the hash URIs of the bibls for the manuscripts. 

For example, in the BHSE, `@corresp="#bib270-6"` is currently visualized as "(Edition from manuscript witness 1. See below.)" In the new NHSL format, this would be expressed as 
```
<relation type="mssWitnesses" active="#bib2501-1" ref="dct:source" passive="#bib2501-15" source="#bib2501-7 #bib2501-16"/>
```

We plan to change to this format in BHSE.

**Comment by nathangibson** [comment]
6.Translations (`bibl[@type="lawd:Translation"]`) have relations to editions/manuscripts in a similar format. E.g., 
```
<relation type="translationSource" active="#bib2501-4" ref="dct:source" passive="#bib2501-1" source="#bib2501-7"/>
```
This should be visualized as "(Translation from edition 1. See below.)" if the target is a `bibl[@type="lawd:Edition"]` or "(Translation from manuscript witness 1. See below.)" if the target is a `bibl[@type="lawd:WrittenWork"]`.

**Comment by nathangibson** [comment]
7.Manuscript Witnesses. For now, we'll do something as simple as possible for the Rome demo. This will change once we are actually linking to MSS URIs. How does this look
```
<bibl type="lawd:WrittenWork" xml:id="bib2501-14">
                    Bodleian Hunt. 1 ( = <bibl>Payne Smith<ptr target="http://syriaca.org/bibl/1306"/></bibl> 122.9.α), <biblScope unit="pp" from="420" to="556">420-556</biblScope>
</bibl> 
```
for visualizing 

> Bodleian Hunt. 1 ( = [Payne Smith](http://syriaca.org/bibl/1306) 122.9.α), pp. 420-556

Open to suggestions about how to make this simpler -- we could even just do completely raw text and not worry about the links.

**Comment by wsalesky** [comment]
@nathangibson  I loaded the NHSL records so you can track the progress on this ticket.

**Comment by wsalesky** [comment]
@nathangibson what is the reason we are using `bibl/@type` rather then using `note/@type` for these?

**Comment by wsalesky** [comment]
@nathangibson I have made a start. (Made it about halfway down the list. Will continue tomorrow.)
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/2501

**Comment by nathangibson** [comment]
Thanks, looks like this is coming along great! Will send an explanation about `bibl/@type` later today.

**Comment by nathangibson** [comment]
Basically, we have revised the data model for works with an eye to being able to serialize as RDF. `note/@type` + `bibl` seemed more verbose than we needed, plus we would like to use an RDF class on the bibl if possible. Do you see disadvantages to this? @davidamichelson anything to add?

**Comment by wsalesky** [comment]
These are ready for review/tweaking. 
See sample record here:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/2501

**Comment by nathangibson** [comment]
Very cool! I’ll get back to you with details. Thanks so much!

**Comment by nathangibson** [comment]
One thing is we’ll want the NHSL header instead of BHSE.

**Comment by nathangibson** [comment]
This is looking really great. Thanks! Take a deep breath of satisfaction. Now ready for the firehose? If we need to prioritize which ones of these happen before Rome, let me know.
 1. Titles, author, etc. are showing great!
 1. Please use the NHSL header.
 2. The link to "Chronicle" (http://syriaca.org/work/2500) in the abstract:
  1. Can we make it an actual link?
  2. There's an extra period showing up after it.
 3. How are editions sorted? Is it by title? They're showing up in a different order from what they are in the TEI file. I think ideally I'd like to have them either in the order they are in the file or chronologically (which will only work when they point to actual bibl records). You don't need to do anything on this yet -- I want to ask @davidamichelson his thoughts.
 4. Please include a comma and space between edition title and citedRange. (See edition 1.) 
 5. The citedRange should end with a period (not comma). Maybe this is because there's a note after it in the bibl element?
 5. Can we include the text of any `<note>` element after the citation but before the manuscript witness info? This would apply to all citations, including editions, translations, and sources.
 5. Edition 2 correctly uses the plural in the manuscript note ("witnesses") but incorrectly duplicates it. ("Edition from manuscript witnesses 8, manuscript witnesses 7")
 5. Edition 2 should cite manuscripts 1 and 2 (the Bodleian ones), not 7 and 8.
 5. Great that the relation desc is showing as text in brackets. Can we actually put it inside the witness note (the relation it applies to). E.g., edition 3 "(Edition from edition 1 [With corrections from unspecified manuscripts.]. See below.)" Yes, I realize I'll have to adjust my capitalization and punctuation in the desc accordingly.
 4. Can we show the translation language in front of each translation like we do in BHSE (e.g., http://wwwb.library.vanderbilt.edu/work/1044)? The `<lang>` is inside the bibl instead of inside a note.
 5. I think translation 6 (Chronicon Syriacum) should have a relation to Edition 2 (bib2501-1), not 1. This looks correct in the TEI to me.
 6. Let's discuss with the others (esp. @davidamichelson ) whether we will keep the current page order of Editions, Translations, MSS. Don't do this yet, but if we keep the current order, then translation relations to editions should say "See above" whereas translation relations to mss should say "See below". Complicated, I know! 
 7. bibl/ptrs are displaying great in ms witnesses. 
 8. In the manuscript witnesses, can we visualize `ref/@target` as simple links? E.g., ms 3. would read [Firenze BML Or. 366](http://mss.bmlonline.it/s.aspx?Id=AVKpZgTlfJ8ZMCf2i5w5#/book) ( = [Assemani, Palat. Medic.](http://syriaca.org/bibl/foo) 118). See [e-corpus](http://www.e-corpus.org/eng/ref/163871/Firenze_BML_Or._366_%5BAssemani_118%5D/) and [Assemani, Palat. Medic. , 190-197](http://syriaca.org/bibl/foo). Assemani does not mention which folios part 1 comprises. 
 9. In ms witnesses, can we exclude the citedRange from the bibl link so that we can make the citedRange a link to specific pages/units, as we do in the Sources section? See e.g., ms 9.
 10. `<locus>` (sometimes used instead of citedRange) should be visualized in ms witnesses. E.g., ms 2. 
 11. Can we assign Sources/footnote numbers like we do the other numbers (editions, translations, manuscripts), instead of using their xml:ids?
 12. For the relations in the sidebar, can we visualize `ref="dct:isPartOf"` as "is part of"? Right now there's no relation heading. Also it looks like the sidebar grabbed the `relation/desc` text from other relations in the doc. ("With corrections from unspecified manuscripts. Facsimile.")

**Comment by wsalesky** [comment]
@nathangibson I think a list of priorities would be good. I'm going to work on a few other things today and will try to get back to this, but I am starting to feel a little bit of a time crunch!

**Comment by nathangibson** [comment]
Sure. It's almost good enough for me to demo as is. I would rate them as 
Essential: 2, 11, 19
Would be great: 7, 9, 12
Would be nice: 5, 6, 8, 15, 16
Not important: the others

**Comment by nathangibson** [comment]
We just looked over this and noticed the following additional things. I think these would fall into the "would be nice" category above, unless @davidamichelson thinks differently:
20. For Work Titles: 
i. Could we sort by language before alphabetizing them? Syriac first, then English, then by language in alphabetical order of language code. (ar, de, fr, la, etc.)
ii. Can we try listing them without bullets? We might even like to try grouping them by language and putting them in the kind of bubbles you have for person names. Not sure if this will be too much -- we'll just have to try it and see. 
21. There is no footnote citation showing for `relation/@source`. E.g., edition 3 relation should cite footnote 7.

**Comment by wsalesky** [comment]
@nathangibson What does xml:lang='tr' translate to?

**Comment by wsalesky** [comment]
19. For the relations in the sidebar, can we visualize ref="dct:isPartOf" as "is part of"? Right now there's no relation heading. Also it looks like the sidebar grabbed the relation/desc text from other relations in the doc. ("With corrections from unspecified manuscripts. Facsimile.")

For this one, we only want to visualize the relation within the body, not all the bibl relation correct?

**Comment by nathangibson** [comment]
Turkish

**Comment by nathangibson** [comment]
Correct, if I'm understanding you right. Please only visualize in the sidebar the listRelation/relations that are direct children of body/bibl. Alternatively, if it's easier, you could visualize any relations that aren't nested in additional bibls. (At this point the outcome should be the same.) Thanks!

**Comment by wsalesky** [comment]
@nathangibson Do you want the NHSL banner only for NHSL? Or for all works, similar to how we use the SBD banner for all persons? (Note it is more complicated, ie not by Rome, to give BHSE and NHSL different banners).

**Comment by wsalesky** [comment]
4. Editions are now sorted in document order. We can get fancier after Rome if you decide you want to.

**Comment by wsalesky** [comment]
@nathangibson In other modules for relationships we use the name attribute in the way you are using the ref attribute. Is there a reason for the switch? Are they interchangeable?

**Comment by wsalesky** [comment]
RE: 8. Edition 2 correctly uses the plural in the manuscript note ("witnesses") but incorrectly duplicates it. ("Edition from manuscript witnesses 8, manuscript witnesses 7").

Do these ever reference both a manuscript and an edition? If so, I need to leave the wording as above, if they will always be the same type then I can change it.

**Comment by wsalesky** [comment]
@nathangibson I did a few updates tonight. I think this may be as far as I get before Rome. Let me know if you see any glaring issue.

**Comment by wsalesky** [comment]
Note to self: lang tag seems problematic on Edition 7. XML is correct, so must be a XSLT issue.

**Comment by nathangibson** [comment]
This is looking great! Should be fine now for Rome. I'll respond to your questions below just for your reference.

**Comment by nathangibson** [comment]
Re. banner: We should keep BHSE banner on the BHSE works. We can discuss after Rome how to assign other works the proper banners.

**Comment by nathangibson** [comment]
Re. `@ref` vs. `@name`: This is to comply with the recommendations of SAWS regarding RDF serialization. I should look into this more though.

**Comment by nathangibson** [comment]
Re. 8: Well, yes, it's possible they might reference 2 different types. So in that case, can you just change this:
> Edition from manuscript witnesses 8, manuscript witnesses 7
to this:
Edition from manuscript witness 8, manuscript witness 7

**Comment by wsalesky** [comment]
RE 8. This will have to wait until after Rome, but I chose the wrong way to code it. :(  
I assumed the same type.

**Comment by nathangibson** [comment]
No problem. I didn't think of that until you mentioned it. All of this can wait until after Rome. I'm removing the milestone. Thanks so much -- this is in terrific shape for the short amount of time.

**Comment by wsalesky** [comment]
@nathangibson Is this issue still relevant? Or are we working off of our new issues. (Trying to do some cleanup today.)

**Comment by nathangibson** [comment]
Probably all of this is taken care of https://github.com/srophe/srophe-eXist-app/issues/909 but I am cross-referencing that before closing this in case we need to refer back to this.
