### ISSUE TITLE
WorldCat catalog disappeared?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#730]
Did we purposely remove the WorldCat catalog results from author pages, or is this a bug? E.g., http://wwwb.library.vanderbilt.edu/person/480 does not have it but http://syriaca.org/person/480 does. Same with person/13.

**Comment by wsalesky** [comment]
It was commented out. I wonder why I did that... Anyway it has been reinstated.

**Comment by nathangibson** [comment]
Thanks!
