### ISSUE TITLE
Extra whitespace in persnames

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#734]
When there is a comma separating the parts of a persName, it shows up with extra whitespace. This may be a flaw in the encoding. We have included a whitespace and comma in cases where the name is "Last, First" see this example:

```
<persName xml:id="name569-1" xml:lang="en" source="#bib569-1"syriaca-tags="#syriaca-headword">
                        <addName type="family" sort="1">Jacob</addName>, <forename sort="2">Cyril</forename>
                    </persName>
```

in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/569

**Comment by davidamichelson** [comment]
We could change the data and use the sort order if needed.

**Comment by wsalesky** [comment]
Seems to have resolved.
