### ISSUE TITLE
Weird comma in search results

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#737]
Search results page returns the following oddly placed comma (see screenshot)
![syriaca_org__the_syriac_reference_portal](https://cloud.githubusercontent.com/assets/3083452/17477972/d8961e06-5d68-11e6-9e8b-38e5ac92b0ee.jpg)

**Comment by wsalesky** [comment]
@nathangibson I don't see the comma, however I did remove the display of the xpath used for search (just in there for debugging and it slipped by me). Do you still see the comma?

**Comment by wsalesky** [comment]
@nathangibson Never mind. I found the comma.
