### ISSUE TITLE
Search results on production test server include SPEAR

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#738]
Search box on home page -- E.g. first result here http://wwwb.library.vanderbilt.edu/exist/apps/srophe-prod/search.html?q=ephrem -- clicking on it returns an Apache error. 

@dlschwartz @wsalesky Should we remove SPEAR results from home page search box for upcoming push to production server?

**Comment by wsalesky** [comment]
This will be self resolving once we package up the data for production. No SPEAR data will be deployed.
