### ISSUE TITLE
empty parentheses in BHS citations

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#740]
E.g., http://wwwb.library.vanderbilt.edu/person/1109, Sources 1: "Ugo Zanetti and Claude Detienne. Bibliotheca Hagiographica Syriaca (), entry: 479, 971." 

Is this a problem with the data, such as not having a date, or a problem with the XSLT?

**Comment by wsalesky** [comment]
Here is the problem: 
```
<imprint>
<date/>
</imprint>
```

Now I can test to make sure the date is not empty, but I think it makes more sense to not have empty elements (unless they are meaningful). 

Let me know how you would like to handle this one.

**Comment by nathangibson** [comment]
Hmm, yes. Actually, I just added the empty imprint and date yesterday to see if it would solve the problem. Also, it’s not valid TEI without them. Should we put “n.d.” inside the date element in the TEI? Or is there some better way to resolve this?

**Comment by wsalesky** [comment]
Okay. You can leave it as is, although if it is required then I think 'n.d' would be a more valid TEI, empty elements contain no meaning. I did however add a test for empty imprint/dates.
