### ISSUE TITLE
Are records like Ephrem supposed to have "saint" and "author" after headword?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#741]
http://wwwb.library.vanderbilt.edu/person/13 is only displaying "saint" on the top title line. I think "saint" and "author" are supposed to both be labeled using the seriesStmt, right (rather than the `person/@ana`)?

**Comment by wsalesky** [comment]
Thanks!

**Comment by nathangibson** [comment]
I'm seeing both icons now. However, "authors" should be singular "author" and both of the links ("saint" and "authors") are broken :-(

**Comment by wsalesky** [comment]
Opps. Sloppy xpath. Fixed now.
