### ISSUE TITLE
Are we keeping or removing the dashboard for the new production release?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#742]
@dlschwartz @davidamichelson 
Were we planning to keep or remove the "dashboard" on the module home pages for the production release? On the test production site it is still showing up for Gazetteer, Persons, Authors, and Works Cited.

**Comment by tacarlson** [comment]
For the Gazetteer, I would prefer not keeping it.  If anyone wishes to keep it, I would like to discuss it first.


I have no opinion regarding other modules.

________________________________

**Comment by wsalesky** [comment]
I think they should be just for the dev server. Or perhaps moved to the about pages. 

@tacarlson I have removed it from the Gazetteer:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe-prod/geo/index.html

**Comment by wsalesky** [comment]
These will be just for dev.
