### ISSUE TITLE
Menu text alignment

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#745]
It looks to me as if the text for top menu items "Browse" "About" "Help" and "Contribute" is not aligned with the module icons and Syriaca.org drop-down in the top-right. E.g.,  http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/index.html. It's small but noticeable. FF and Safari on Mac OS.

**Comment by wsalesky** [comment]
Can you email me a screen shot?

**Comment by davidamichelson** [comment]
This is not very bad in my mind. Can be after Rome.

**Comment by wsalesky** [comment]
Done.
