### ISSUE TITLE
Do we need ".html" handling for other modules as in Gazetteer?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#746]
@davidamichelson @dlschwartz 
The Gazetteer identifies HTML pages using ".html" suffixes. So far as I understand, this is to be able to make valid RDF statements that distinguish between the entity itself and the page describing it. Currently, our dev server does not add ".html" to URLs, and it gives a 404 if you type one in (e.g., http://wwwb.library.vanderbilt.edu/person/13.html). Should this be changed before we go live?

**Comment by wsalesky** [comment]
That must be an error on my part. I want users to be able to get the pages with or without the .html extension. I will take a look.

**Comment by wsalesky** [comment]
Opps, seem to have caused some issues with 'Works Cited' ...
