### ISSUE TITLE
Tried to build .xar of dev branch, got error

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#747]
Error found while processing repo.xml: err:XPST0017 Function xrest:register-module() is not defined in module namespace: http://exquery.org/ns/restxq/exist [at line 18, column 1]

**Comment by wsalesky** [comment]
Hum. I'm not able to reproduce that error. Can you make sure you have all the latest files? 
Was this running ant, or when you were deploying the app to eXist?
