### ISSUE TITLE
text in search box is too large

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#751]
@wsalesky I hate to be putting so much on your plate, but I figure it's better to mention these things before the release. E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/authors/index.html and http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/index.html
![syriaca_org__the_syriac_reference_portal](https://cloud.githubusercontent.com/assets/3083452/17521493/df7721c0-5e53-11e6-8fa9-6ddb40818e35.jpg)

**Comment by nathangibson** [comment]
or margins are too small

**Comment by wsalesky** [comment]
Thanks!
