### ISSUE TITLE
Extra period after disambiguation note

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#761]
@wsalesky Does the XSLT add a period after `<note type='disambiguation'>`? I'm looking at http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1086 and there seems to be an extra one.

**Comment by wsalesky** [comment]
Interesting, it is only supposed to add the period if the note has no ending punctuation. I have removed it for now, but will have to go back and troubleshoot.
