### ISSUE TITLE
Links to volumes on series pages (SBD & NHSL)

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#762]
@wsalesky @davidamichelson @dlschwartz  @jsaintlauren @tacarlson 
To discuss today if there's time: 
The "Gateway to the Saints" landing page already has a beautiful visualization of the two volumes it contains. However, for the other series landing pages ([SBD](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html) and [NHSL](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/nhsl/index.html)), can we somehow highlight the volumes they contain? 

My suggestion would be to have a box on the right side of the page for each volume, underneath the header/search area. This could have volume number, volume title, short description (same as used on home page), editors, and preview image. For example, SBD would say:

> **Vol. 1: _Qadishe: Guide to the Syriac Saints_**
> Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson (eds.)
> _Qadishe_ is a digital catalogue of saints venerated in the Syriac tradition.

> **Vol. 2: _A Guide to Syriac Authors_**
> David A. Michelson and Nathan P. Gibson (eds.)
> [short description]

**Comment by nathangibson** [comment]
Sorry, I meant tomorrow :-)

**Comment by jsaintlauren** [comment]
Great idea!  Please put on agenda, nathan

**Comment by nathangibson** [comment]
For now, @davidamichelson and I will edit the prose to include the info.

**Comment by nathangibson** [comment]
@davidamichelson What do you think about this for now for listing the volumes: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/nhsl/index.html

If this looks ok I can push it to the srophe-prod branch.

**Comment by nathangibson** [comment]
Note to self: Make bigger and bolder and change to citation style.
