### ISSUE TITLE
Bad spacing in names

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#766]
http://localhost:8080/exist/apps/srophe/person/14

**Comment by nathangibson** [comment]
Just so you know, the Syriac header has the same spacing issue as the English one.

**Comment by wsalesky** [comment]
@nathangibson Thanks. When I have the fix up I will ask you to check the Syriac for me. These names seem to be giving me endless trouble!

**Comment by wsalesky** [comment]
@nathangibson Okay, take a look at the Syriac names please. If they look okay, you can close this.

**Comment by nathangibson** [comment]
Looks great, thank you!

**Comment by wsalesky** [comment]
Yay!
