### ISSUE TITLE
Please change "Manuscript Witnesses" to "Syriac Manuscript Witnesses" for BHSE and NHSL

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#770]
On work pages, please change the section header "Manuscript Witnesses" to "Syriac Manuscript Witnesses".

@jsaintlauren : @davidamichelson and I just discussed this re. NHSL and realized that we only list Syriac ms witnesses -- any other languages go in ancient versions. So this label would be clearer. Sound all right?

**Comment by wsalesky** [comment]
@nathangibson example record please?

**Comment by nathangibson** [comment]
Sorry, clarification: This is the HTML section header "Manuscript Witnesses" inserted by the XSLT for _all_ `note[@type="mss"]` (BHSE) and `bibl[listRelation/relation/@type="mssWitnesses"]`

Applies to all records, but an example would be http://wwwb.library.vanderbilt.edu/work/910

**Comment by wsalesky** [comment]
What about `@type="lawd:WrittenWork"` ?

**Comment by nathangibson** [comment]
Yes. `@type="lawd:WrittenWork" should be the equivalent of `bibl[listRelation/relation/@type="mssWitnesses"]`

**Comment by nathangibson** [comment]
So it's fine to just change it for whatever you have previously coded to be displayed under "Manuscript Witnesses"
