### ISSUE TITLE
TEI URIs for Deprecated Works should be eliminated without a redirect.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#771]
Is this real or a cache problem: http://wwwb.library.vanderbilt.edu/person/2001/tei

**Comment by davidamichelson** [comment]
In anycase this can wait until after rome

**Comment by davidamichelson** [comment]
Note to self, when we have .ttl URIs those should have specially crafted redirect or deprecated statement.

**Comment by wsalesky** [comment]
Hum. I think this is finding them in the depreciated folder. Which maybe should not be part of the production deployment?

**Comment by nathangibson** [comment]
Well, as I think you pointed out earlier @wsalesky , will the redirect work if we don't have the deprecated folder on production? If person/2001 is supposed to redirect to person/44, won't we have to have the deprecated record for 2001 live?

**Comment by wsalesky** [comment]
Ah, yes. Good point. Will have to add a filter in the get-tei function.
