### ISSUE TITLE
 Bug in Bibl Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#772]
When one selects browse by A-Z, please have sublist of A, B, C, as in the other modules.

**Comment by davidamichelson** [comment]
Wait this is working now, but is empty.

**Comment by davidamichelson** [comment]
Okay this is a bug and here is the issue:

This view has the letters: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/browse.html but no data

This view has the data but not the letters: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/browse.html?view=A-Z

**Comment by wsalesky** [comment]
Need to hide 'New search button'. Also need to fix which tab is 'active'
