### ISSUE TITLE
Not sure how to link to XML files from documentation page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#775]
@wsalesky On this page: http://wwwb.library.vanderbilt.edu/documentation/training-materials.html

I want to link to these:
Blank Template File for Single Part Manuscripts
Blank Template File for Multiple Part Manuscripts

I have the path right I think but get this error:

HTTP Status 404 - Document /db/apps/srophe/templates/Blank-template-file-for-single-msPart-entries.xml not found

**Comment by wsalesky** [comment]
You co not have the correct path. Remove the first '/' to make the path a relative path.
