### ISSUE TITLE
Bug in SBD browse, double listing of some but not all persons

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#778]
See this problem here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html (see screen shot)

And also in Q : http://wwwb.library.vanderbilt.edu/exist/apps/srophe/q/browse.html

but not in authors: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/authors/browse.html

From SBD:

![screen shot 2016-08-14 at 5 20 40 pm](https://cloud.githubusercontent.com/assets/3083773/17652515/dc1ad1d6-6243-11e6-895c-9847109c7d35.png)

**Comment by davidamichelson** [comment]
Looks like it is fixed now? I don't see the issue on refresh.

**Comment by wsalesky** [comment]
Great. I reloaded the data.
