### ISSUE TITLE
http://wwwb.library.vanderbilt.edu/work/660 returns 404

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#779]
But record is here https://github.com/srophe/srophe-app-data/blob/dev/data/works/tei/660.xml and I don't see problems with it.

**Comment by wsalesky** [comment]
Does not seem to be on the dev server... let me go find it.

**Comment by wsalesky** [comment]
Found.

**Comment by nathangibson** [comment]
Thanks!
