### ISSUE TITLE
SPEAR for Rome

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#781]
@wsalesky it would be great if we could get a list of persons to show up here: http://wwwb.library.vanderbilt.edu/spear/browse.html?view=persons. Ultimately we will want the link in that list to take the user to a page that aggregates all SPEAR information related to that person but for next week a list of all persons in SPEAR would be great. Thanks!

See:
https://github.com/srophe/srophe-app-data/issues/545

@wsalesky I hate to suggest any work on the relationship graph but what you've started working on here is so cool that I really want to show it off. It's a bit buggy though. In September we should hit this but for Rome I'm hoping you can solve one problem. The "all relationships" option consistently does not work. At first I thought it didn't work only with someone like person/51 who is involved in numerous relationships. However, I can't seem to get it to work at all right now. Don't hesitate to say if this is too involved for the time we have to work with. Thanks!

https://github.com/srophe/srophe-app-data/issues/546

@wsalesky your Advanced Browse is also too good for me not to show off. A number of problems have appeared since the last time I used it. The "more/less" buttons seem reversed. The keyword section no longer contains a set of drop down options. Instead it shows a box. It looks like I should be able to type into the box but the box seems to contain the text of an event factoid already. When I click to type, it selects that factoid. Again, please don't hesitate to say whether this is too much for next week. Thanks.

https://github.com/srophe/srophe-app-data/issues/547

**Comment by wsalesky** [comment]
@dlschwartz Browse is mostly fixed. Some odd behavior in a few persNames and the relations do not show up correctly in the list. I will fix the graph first, then resolve the remaining browse issues. Should have everything done in time!

**Comment by dlschwartz** [comment]
Great. Thank you Winona! I'm sure everything will come off really well.
Dan

**Comment by wsalesky** [comment]
Can you tell me your operating system and browse, so I can be sure to test the version you will be using on Sat. ?

**Comment by dlschwartz** [comment]
Hi Winona,
Thanks for thinking of this. I use Chrome on a PC.
Thanks,
Dan

**Comment by davidamichelson** [comment]
As usual you are too thoughtful Winona!!!

**Comment by davidamichelson** [comment]
Winona, when you are ready today could you please push new .xar files and that way we will have offline copies please 

Thanks!

**Comment by davidamichelson** [comment]
Oh by today, I mean Friday pm your time

**Comment by wsalesky** [comment]
New .xar files:
prod:
data :
https://github.com/srophe/srophe-app-data/tree/master/build/srophe-data-2.0.xar
app:
https://github.com/srophe/srophe-eXist-app/tree/master/releases/srophe-2.0.xar

dev
data:
https://github.com/srophe/srophe-app-data/tree/dev/build/srophe-data-1.25.xar
app:
https://github.com/srophe/srophe-eXist-app/tree/dev/releases/srophe-1.88.xar

**Comment by wsalesky** [comment]
@dlschwartz I have the relationships working now, but it is very slow, especially for someone like Severus of Antioch (aka person/51). One way to make this faster would be to not display any names on the graph itself, have either unlabeled nodes or have just the uris and then only fetch the names when the user clicks on the node. This would(should) vastly increase the speed. 

What do you think?

**Comment by wsalesky** [comment]
Spoke to soon. Working beautifully on my local machine and not on dev.

**Comment by dlschwartz** [comment]
Winona,
We expect to be able to run this locally tomorrow. Also, I hope to have all
the relationships pre-loaded in separate tabs rather than generate the in
the moment. I think we are in great shape. Thank you so much! I really
appreciate all your efforts.
Thanks,
Dan

**Comment by wsalesky** [comment]
Okay, I have it working. The catch is that you must use the 'query' button. If you enter the uri and press return, it will clear the search not submit it. I will see if I can fix that, but it may not happen until after Rome. 

I will load a new version of the dev app for deployment this afternoon so you have it. Please let me know if you install it and have trouble. 
Thanks!

**Comment by dlschwartz** [comment]
Perfect. Thank you.
Dan

**Comment by wsalesky** [comment]
Okay, I added a very simple output for relationships when they show up in the browse by source page. It needs work, but is better then the blank lines that were showing up before. 

I have also updated the 1.88.xar for the app, so these changes should all be there. Please let me know if you run into any problems.
