### ISSUE TITLE
Record: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1167

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#782]
Seems to crash the server

**Comment by wsalesky** [comment]
There are two tei:ptr elements within a single bibl element. Is this something I should anticipate, or is this incorrect?

```
<bibl xml:id="bib1167-5">
<author>
<persName>
<forename>J.B.</forename>
<surname>Chabot</surname>
</persName>
</author>
<title>La légende de Mar Bassus</title>
<ptr target="http://syriaca.org/bibl/1768"/>
<citedRange>(Paris, 1903), 72 pages</citedRange>
<note>reprinted in</note>
<author>...</author>
<ptr target="http://syriaca.org/bibl/1768"/>
<citedRange>III, 248-69</citedRange>
</bibl>
```

**Comment by nathangibson** [comment]
This is incorrect. I am removing the second ptr. This is probably the result of a script gone awry that duplicated the ptr, so this might not be the only instance.

**Comment by wsalesky** [comment]
I can run a script to check for multiple ptrs

**Comment by nathangibson** [comment]
Great!

**Comment by davidamichelson** [comment]
Might be my fault sorry 

What would an x path test be to find these?

**Comment by nathangibson** [comment]
Perhaps //person/bibl[count(ptr) > 1] ?

**Comment by wsalesky** [comment]
yes, that should work

**Comment by wsalesky** [comment]
This seems to be fixed.
