### ISSUE TITLE
email bug

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#788]
<exception>
<path>/db/apps/srophe/modules/email.xql</path>
<message>exerr:ERROR XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: recap:validate($private-key as xs:string, $recaptcha-response as xs:string) item()*. Expected cardinality: exactly one, got 0. [at line 19, column 44, source: /db/apps/srophe/modules/email.xql]
In function:
	recap:validate(xs:string, xs:string) [19:5:/db/apps/srophe/modules/recaptcha.xqm]
	local:recaptcha() [57:19:/db/apps/srophe/modules/email.xql]</message>
</exception>

**Comment by davidamichelson** [comment]
What, why are you creating extra work for yourself :) at least wait for us
to find the bugs and request help

You are too wonderful
