### ISSUE TITLE
404 on place records

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#790]
@wsalesky After the push to production, I'm getting a 404 on place records. E.g., http://syriaca.org/place/78.html and http://syriaca.org/place/78 both are 404. 

@tacarlson We just pushed the dev app to production and are testing it before the Rome demo.

**Comment by wsalesky** [comment]
Working on it.

**Comment by wsalesky** [comment]
Just to clarify, they are still there:
http://syriaca.org/exist/apps/srophe/place/78

But there seems to be an issue with the redirect. Should be resolved shortly.

**Comment by nathangibson** [comment]
Thanks!!

**Comment by wsalesky** [comment]
Fixed by Dale.
