### ISSUE TITLE
Please remove NHSL from publication

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#792]
@wsalesky Can we remove NHSL works from the published data? These are the ones in srophe-app-data/works/tei/nhsl/tei. This doesn't have to happen immediately.

**Comment by nathangibson** [comment]
Just to clarify, we want http://syriaca.org/nhsl/index.html to remain live.

**Comment by davidamichelson** [comment]
Actually we could leave those works but mark their status as Demo?

**Comment by wsalesky** [comment]
Webhooks should now be working for production. You can edit them and let me know if they don't update. Or I can edit them at around 8 tonight.

**Comment by nathangibson** [comment]
Thanks, that should be fine. For now, I'll change status to "demo" in dev which will be fine for my presentation. But I'll leave this issue open and not push to production yet since I don't want to mess anything up at the moment.

**Comment by wsalesky** [comment]
Has this been resolved? It looks like there are no NHSL records currently on the production server. If so, we can close this.
