### ISSUE TITLE
On BHSE, the syriac titles are not displaying correctly and are missing html:span @lang="" 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#793]
For some reason the tei/titleStmt/title that is in Syriac is not displaying correctly in the HTML on firefox or chrome on Mac. (But the rest of the Syriac does display fine).

On Firefox, it shows as boxes while on Chrome it does display but uses a non-standard unicode font.

Not sure why only that element has problems. The titles in other modules are fine. One difference is that in PERSON the Syriac title when rendered as HTML has this element: html:span class="persName" xml:lang="syr" lang="syr" but in BHSE the html title has span lang="" dir="rtl" 

Could the empty lang be an issue?

**Comment by davidamichelson** [comment]
Note this is not a problem in the TEI (which has the lang tag, but in the html)

**Comment by wsalesky** [comment]
Sorry! A typo in the xpath. Fixed on dev and prod, but not in the packages you have. (It is the resources/tei2html.xsl) if you want to update your local version.

**Comment by davidamichelson** [comment]
Thanks! I will update! You are too much! Mille Grazie!
