### ISSUE TITLE
Adjust http://syriaca.org/nhsl search box

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#794]
@wsalesky Please wait until after today (Saturday).

Search box on http://syriaca.org/nhsl should search anything with NHSL seriesStmt, including BHSE. 
Possibly related: https://github.com/srophe/srophe-app-data/issues/613

**Comment by wsalesky** [comment]
@nathangibson I think I may need some clarification on this one.

NHSL records have: 
<title level="s">New Handbook of Syriac Literature</title>
and
<idno type="URI">http://syriaca.org/works</idno>

and BHSE records have?
I see:
<title level="m">Bibliotheca Hagiographica Syriaca Electronica</title>
in the titleStmt, but not in the seriesStmt, should I be matching on the URI's in the seriesStmt instead? 
BHSE = http://syriaca.org/q
NHSL = http://syriaca.org/work

Thanks!
