### ISSUE TITLE
Virtual Keyboard for Syriac

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#806]
James Bennett has written a virtual keyboard that can be embedded in html. You can see it here:
https://sedra.bethmardutho.org/

Please contact Jim about getting the code and we should embed it in all Syriaca.org modules search box.

**Comment by wsalesky** [comment]
Contacted Jim, he is working on the code and will share when it is ready.

**Comment by davidamichelson** [comment]
There is also a keyboard here we might use: Example: http://www.fihrist.org.uk/

**Comment by wsalesky** [comment]
Test run of Syriac keyboard:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/search.html

I could use some testers. @davidamichelson @nathangibson @dlschwartz @jsaintlauren

**Comment by dlschwartz** [comment]
I haven't had a lot of time to test this. The main issue I see right off is that it is difficult to use the wildcard characters. I only managed to do it by getting out of the Syriac keyboard by clicking on a different field. This moved the Syriac text from left adjust to right adjust and allowed me to input the wildcard characters from my keyboard.

**Comment by nathangibson** [comment]
This is great! A couple things:
 1. When I'm on a non-blank results page like http://wwwb.library.vanderbilt.edu/exist/apps/srophe/search.html?q=%DC%A1%DC%AA%DC%9D , clicking on the keyboard button in the top right just sets the field to the search field and changes the typing direction but doesn't actually pull up the keyboard. (FF 49.0.2 on Mac 10.10.5)
 2. The "Enter" button doesn't execute a search, it just sometimes (not always?) closes the keyboard viewer. In my opinion it should either execute the search or we should remove it. 

Not having access to the wildcard characters is not a big deal in my opinion since you can use your regular keyboard to do that. 

A UI suggestion: Perhaps instead of the word "Keyboard" and the gear icon we could just have a symbol, like ⌨ (U+2328)? This would be intuitive and save space.

**Comment by wsalesky** [comment]
Should all text fields include a link to the keyboard?

**Comment by wsalesky** [comment]
List of available keyboards can be found here:
https://github.com/srophe/srophe-eXist-app/tree/dev/srophe-app/resources/keyboard/layouts

We will be adding a dropdown menu to the keyboard allowing users to select from a predefined list.

**Comment by wsalesky** [comment]
Add additional keyboard options. 
Debug, when keyboard is closed, textbox remain  rtl.

**Comment by wsalesky** [comment]
Languages: 
arabic.min.js
ms-Arabic.min.js
ms-Russian.min.js
ms-Greek.min.js

**Comment by wsalesky** [comment]
Okay, new language options added. Please review.

**Comment by davidamichelson** [comment]
Fabulous, now in the spirit of always asking for more ;) Can we get the keyboard to toggle its Syriac font to the three options?

**Comment by wsalesky** [comment]
We can discuss tomorrow.

**Comment by davidamichelson** [comment]
Please add "Mod. Standard", after Arabic, Greek, Russian...

Please add English QWERTY as a new keyboard and label.

Put Syriac (s) first and then others by alphabetical. 

Put Syriac Phonetic first before Syriac Standard

**Comment by wsalesky** [comment]
Done! Please review.

**Comment by nathangibson** [comment]
Seems to be working very well for me. Selecting different languages went fine, and keyboard no longer stays active when I click off of it. 

Only problem I came up with is that clicking the enter key on the software keyboard does not search whereas pressing it on my hardware keyboard does. I feel like we discussed that before but I don't remember if we decided it should be fixed (or the enter key just removed).

**Comment by wsalesky** [comment]
Let me know when we are ready to move this to Production.

**Comment by dlschwartz** [comment]
I glanced back over the comments here and I think we are in good shape with one exception. The enter key on the virtual keyboard does not do anything. Is there a way we can have that button execute the search?

**Comment by wsalesky** [comment]
I think we agreed to table that issue for now. I can force submit on enter, but the code is buggy, and it would take some combing through the source for me to fully debug.

**Comment by dlschwartz** [comment]
Sorry, I'm sure I was just mis-remembering. Thanks.
