### ISSUE TITLE
How to Cite This Entry for Qadishe needs fixing

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#808]
How to Cite This Entry

Jeanne-Nicole Saint-Laurent and David A. Michelson, “John — ܝܘܚܢܢ” in , eds. Jeanne-Nicole Saint-Laurent and David A. Michelson, entry published August 17, 2016, Syriaca.org: The Syriac Reference Portal, ed. David A. Michelson. http://syriaca.org/person/1803.

This should instead read:

Jeanne-Nicole Saint-Laurent and David A. Michelson, “John — ܝܘܚܢܢ” in _Qadishe: A Guide to the Syriac Saints_, eds. Jeanne-Nicole Saint-Laurent and David A. Michelson, entry published August 17, 2016, Syriaca.org: The Syriac Reference Portal, ed. David A. Michelson. http://syriaca.org/person/1803.

The addition is the title.

**Comment by davidamichelson** [comment]
A few more changes needed:


Authorial and Editorial Responsibility:

    David A. Michelson, general editor, Syriaca.org: The Syriac Reference Portal
    Jeanne-Nicole Saint-Laurent and David A. Michelson, editors, _Qadishe: A Guide to the Syriac Saints_
    Saint-Laurent, Jeanne-Nicole and David A. Michelson, entry contributors, “John — ܝܘܚܢܢ”

Additional Credit:

    Editing, proofreading, data entry and revision by Jeanne-Nicole Saint-Laurent
    Data architecture and encoding by David A. Michelson
    Editing, Syriac data conversion, data entry, and reconciling by [Add NAME HERE]
    Editing and Syriac data proofreading by [Add NAME HERE]

**Comment by wsalesky** [comment]
How does this look? (for short run fixes)
http://wwwb.library.vanderbilt.edu/person/1803

**Comment by jsaintlauren** [comment]
Looks good to me! Thank you!

**Comment by davidamichelson** [comment]
Great work on this belatedly from me!
