### ISSUE TITLE
WorldCat identity URIs for authors

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#811]
cc: @davidamichelson 

So I just discovered by accident that there is a way to resolve to a WorldCat identities page directly using a VIAF ID without going to VIAF first. E.g., for Ephrem with VIAF URI http://viaf.org/viaf/100177778/ (= VIAF ID 100177778), the link is https://www.worldcat.org/identities/containsVIAFID/100177778. It seems however that not all VIAF IDs are in WorldCat, e.g., https://www.worldcat.org/identities/containsVIAFID/122046692. 

We might want to consider whether we want to pull WorldCat identity URIs into our records as data as @wsalesky suggested earlier (#535). If so, we would want to wait to do this until VIAF has ingested our latest author info and done the relevant merges. This would involve 
1. Resolve VIAF URI in format http://viaf.org/viaf/sourceID/SRP|person_13 (to make sure we are getting the primary VIAF ID).
2. Grab the resolved VIAF ID (in format http://viaf.org/viaf/100177778/) and use it to query WorldCat (in format https://www.worldcat.org/identities/containsVIAFID/100177778). 
3. If WorldCat identity is returned (instead of 404), insert this into record as an idno. 

What do you think?

**Comment by wsalesky** [comment]
I believe this is being done in SBD currently.
