### ISSUE TITLE
"Indifiers" instead of "Identifiers" in Google Results for http://syriaca.org/documentation/isostandards.html 

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#812]
I can't tell why https://encrypted.google.com/search?hl=en&q=iso%20639%20change%20requests%20syriac 4th result has typo "Indifiers" in page title, though I can't find this in the source code. Is it just Google's outdated cache or do we need to correct the typo somewhere?

**Comment by wsalesky** [comment]
Looks like cached results to me.

**Comment by nathangibson** [comment]
Great, thanks!
