### ISSUE TITLE
Page with SPEAR data for each person in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#815]
The "Persons" tab in SPEAR contains a list of person names with links. Currently, when you click on a name, the link takes you to SBD. That makes perfect sense because that link is to the URI which resolves to the SBD page for that person. However, it would be great if this could instead take the user to a page that aggregates SPEAR data on that person. It would be structured very much like the SBD page for that person, but would contain just SPEAR data. The most significant difference would be the addition of relationship data. The right-hand column could provide a link to the SBD page for more information. I'm afraid this is a deceptively simple request. For starters, I'm not sure how we would manage URLs for these pages. Perhaps we should discuss further with @davidamichelson.

**Comment by wsalesky** [comment]
Opps, that already exists, the link just disappeared.  Here is an example of what we currently have. We can review and update it. 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/person/13

I added the SPEAR link back in, but perhaps we would want the link on the title/person's name to go to the SPEAR page rather then the SBD page?

**Comment by dlschwartz** [comment]
I thought we had something before. This is a great start. I'll poke around
and we can think about changes. Thanks

On Thu, Sep 22, 2016 at 9:00 AM, Winona Salesky <notifications@github.com>
wrote:

> Opps, that already exists, the link just disappeared. Here is an example
> of what we currently have. We can review and update it.
>
> http://wwwb.library.vanderbilt.edu/exist/apps/
> srophe/spear/factoid.html?id=http://syriaca.org/person/13
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__wwwb.library.vanderbilt.edu_exist_apps_srophe_spear_factoid.html-3Fid-3Dhttp-3A__syriaca.org_person_13&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=Vj1SehXnb9JIiwHMzlLbuoMW2AnBub-gBALSP2kHjJE&s=ehb9blSHQ_M6LSl-ZhNvBZPHvbFNHpptUjP1eHi_fqs&e=>
>
> I added the SPEAR link back in, but perhaps we would want the link on the
> title/person's name to go to the SPEAR page rather then the SBD page?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2DeXist-2Dapp_issues_815-23issuecomment-2D248911670&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=Vj1SehXnb9JIiwHMzlLbuoMW2AnBub-gBALSP2kHjJE&s=USHb5HoILXHmsE0_Quos2Z58WC2W5yL3uId4fiU6xJ4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzv8GNWoDPfKCUNHG3TB7SI-2D8g1q-2Dks5qsonrgaJpZM4KDLlF&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=Vj1SehXnb9JIiwHMzlLbuoMW2AnBub-gBALSP2kHjJE&s=6-mhexqj4A_sDOWckdn2oED_03Ihcq1L6Bk2dUgI0Kc&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>
