### ISSUE TITLE
More/less buttons in advanced search for SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#816]
The buttons don't seem to work correctly. This might be because too many options emerge when the more is chosen. It's actually a bit overwhelming for persons and places. And it's only going to get worse as we get more data. Not sure how best to handle this.

**Comment by wsalesky** [comment]
What browser and operating system are you using? This most likely a javascript error. 

Although I do think we should discuss how to handle this display better (when you view more).

**Comment by dlschwartz** [comment]
I'm using Chrome on a PC

On Thu, Sep 22, 2016 at 9:02 AM, Winona Salesky <notifications@github.com>
wrote:

> What browser and operating system are you using? This most likely a
> javascript error.
>
> Although I do think we should discuss how to handle this display better
> (when you view more).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2DeXist-2Dapp_issues_816-23issuecomment-2D248912199&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=-t58bZkC9ABnl3M9CZwiua4UPfzMnQ5J4IoN1Mnullo&s=RC5mVssvWWT87Q1wsbgYYxB03Y9sj13kxHiw0EoRymI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzttGFhwVBpdVS90N98J8v0uWIKy6ks5qsopYgaJpZM4KDL9B&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=-t58bZkC9ABnl3M9CZwiua4UPfzMnQ5J4IoN1Mnullo&s=LqNWwF1bFxlFQqvy2X6XCxZN8GEMMLddVq0p-aEgsUQ&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by wsalesky** [comment]
@dlschwartz I updated the javascript, can you test the more/less function on SPEAR and let me know if the problem has been solved? Thanks.

**Comment by dlschwartz** [comment]
This fix looks great! Thanks.

**Comment by wsalesky** [comment]
Hurrah!
