### ISSUE TITLE
Keyword in advanced browse

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#817]
This should work like the sections for persons and places allowing the user to choose from a list of keyword tags use in SPEAR.

**Comment by wsalesky** [comment]
Perhaps we can discuss this during our next meeting?

**Comment by dlschwartz** [comment]
Sounds good.

On Thu, Sep 22, 2016 at 9:02 AM, Winona Salesky <notifications@github.com>
wrote:

> Perhaps we can discuss this during our next meeting?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2DeXist-2Dapp_issues_817-23issuecomment-2D248912446&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=Css_xx7-4oYGfmhEWlYVYsbQKRhPIIY6-Aet66ylcAc&s=pr07Im6KV6Ge9qt3992FKZtTSnBcb4RfNhnrsk2OL2o&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNztsOAnEjxDtNCnq7qNkfCUFBn0mlks5qsoqOgaJpZM4KDMZD&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=Css_xx7-4oYGfmhEWlYVYsbQKRhPIIY6-Aet66ylcAc&s=EY657wpJe6qC2bDBQBPFpYtUE1foRudTXY5k_4dmhYk&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by wsalesky** [comment]
First pass.

**Comment by wsalesky** [comment]
Updated with more comprehensive keywords xpath.
