### ISSUE TITLE
Toggle in faceted search

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#819]
I may not have paid enough attention to our discussions of faceted search but I'm wondering if we have considered a toggle feature. This would be really useful for SPEAR and maybe other modules. For SPEAR someone may want to see all event factoids that have two or more keywords, or that reference two or more persons. A user may want to see all the keywords that appear in two or more letters. Is this a universally desirable feature or something we might only want to implement in the faceted search for SPEAR?

**Comment by wsalesky** [comment]
Facet module does this.
