### ISSUE TITLE
When one submits to perseids there is a non-functioning Java Script in the pop up

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#822]
When you go to submit from http://wwwb.library.vanderbilt.edu/exist/apps/srophe-forms/review-rec.html?id=http://syriaca.org/place/1814 it asks you to log in. After you do, the pop up says "resubmit" and the word is a link but clicking it does not resubmit, so we shoudl fix it or just turn it off would be better I think.

**Comment by wsalesky** [comment]
@davidamichelson  The resubmit just closes the window so you can resubmit the record. Is that not the behavior you experience?

**Comment by davidamichelson** [comment]
Not in Firefox. I can try to reproduce it over skype today
