### ISSUE TITLE
Add birth and death place to advanced browse for SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#828]
@wsalesky It would be great to add this feature as well. Thanks.

**Comment by wsalesky** [comment]
I added these, but I get no data back. How are they coded in the XML? In SBD we use:
`tei:relation[@name="born-at"]`

**Comment by dlschwartz** [comment]
Sorry, I just checked at it looks like I only have birth dates encoded so far. I thought for sure I had at least one birth place. OK, let's put this one on hold. Sorry.

**Comment by wsalesky** [comment]
Okay, well it is the facet-def, and should show up as you start adding data.
