### ISSUE TITLE
SPEAR factoid display questions

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#830]
How should we display the data in this factoid (we can discuss at next meeting)? 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/3130-2

xml:

```
<div xmlns="http://www.tei-c.org/ns/1.0" uri="http://syriaca.org/spear/3130-2">
<listPerson>
<person>
<persName ref="http://syriaca.org/person/2465"/>
<sex value="M">Male</sex>
</person>
</listPerson>
<bibl type="primary">
<biblScope unit="pp">
<ptr target="#bibl3130-1"/>
178</biblScope>
</bibl>
</div>
```

**Comment by dlschwartz** [comment]
Sorry we didn't get to this in the meeting today. Can we pull the canonical name from SBD: syriaca-tags="#syriaca-headword" and insert it next to "Names:__"? Or preferably "Name:__"?

**Comment by dlschwartz** [comment]
The same format would work for birth date, death date, occupation, etc.
