### ISSUE TITLE
Broken links on http://syriaca.org/exist/apps/srophe/documentation/training-materials.html

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#833]
On this page http://syriaca.org/exist/apps/srophe/documentation/training-materials.html the two links to "Blank template" under "Downloadable Resources" are broken. I'm trying to fix these. It looks to me as if 
`<a href="/templates/Blank-template-file.xml">Blank Template File for Multiple Part Manuscripts</a>`
should be 
`<a href="templates/Blank-template-file.xml">Blank Template File for Multiple Part Manuscripts</a>` 
(no leading slash). But the link http://syriaca.org/documentation/templates/Blank-template-file.xml doesn't work even though it looks like that's what it should be from the Github repo. Any idea what's happening here?

**Comment by wsalesky** [comment]
There are some blank xml:id which are preventing eXist from loading the records, so they never got loaded to the db. They need to have a valid xml:id place holder.

**Comment by wsalesky** [comment]
@nathangibson Would you like me to add 'place holder' xml:ids? And get the records up on the production server?

**Comment by nathangibson** [comment]
@wsalesky I think I just corrected the links and the xml:ids here: https://github.com/srophe/srophe-eXist-app/commit/27e7af9fa86c70b8a5c34209606ddebcba1d9017. Would you mind deploying those to the master branch and to the production server? Thanks!

**Comment by wsalesky** [comment]
Fixed, although looks like eXist is using the wrong mime-type...
