### ISSUE TITLE
Update Syriaca ODD file

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#834]
I believe the latest customizations to the Syriaca schema were made directly in RNG, correct? 

Could we also update the ODD file to bring it up to date with these customizations? I'd like to do some of our documentation in the ODD. 
cc: @davidamichelson @dlschwartz

**Comment by wsalesky** [comment]
I think they were made to the rnc and then converted to the odd. Are they not in sync?

**Comment by nathangibson** [comment]
Great, glad to hear that the ODD may be up to date. I’ll take a closer look.
