### ISSUE TITLE
Names Export for Person and Places

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#835]
@wsalesky Can  you please remind me of where I can find the script for exporting names for use by @gkiraz and SEDRA? We can review it at the meeting tomorrow. Thanks

**Comment by wsalesky** [comment]
I think it was this one:
https://gist.github.com/davidamichelson/a216712476d7a07405316510344a2738

**Comment by davidamichelson** [comment]
Hmm that is not it sadly. I think we wrote it last summer (2015) but we may just need to redo it. I can't seem to find it.

**Comment by davidamichelson** [comment]
Nevermind I did it myself :) https://github.com/srophe/data-exports

**Comment by wsalesky** [comment]
Great!
