### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#836]
I find it slightly confusing to get to SBD (for example) from the landing page for SBD and I think our users might as well. The "test record" link is broken. The "browse" button seems far away once you've started reading the text on the landing page. Can we come up with another way to get people from the landing page to the thing itself?

**Comment by dlschwartz** [comment]
I just checked all the modules and like how the Gazetteer handles this issue.

**Comment by davidamichelson** [comment]
Agree, I think this needs a bigger discussion of modules and volumes in
them.

**Comment by davidamichelson** [comment]
@wsalesky @dlschwartz 

how is this as a mock up:
![screen shot 2016-10-19 at 11 51 24 am](https://cloud.githubusercontent.com/assets/3083773/19536514/dcfb0f9c-9611-11e6-89b6-8c193311e7ad.jpg)

Text:
General Editor: David A. Michelson, Vanderbilt University

Associate Editors: Jeanne-Nicole Mellon Saint-Laurent, Marquette University, Nathan Gibson, Vanderbilt University, Daniel Schwartz, Texas A&M University

The Syriac Biographical Dictionary (SBD) is a multi-volume= name and biographic authority record documenting persons relevant to the field of Syriac studies. 

    About page: an overview of the gazetteer and its contributors.
    Help page: documentation, editorial guidelines, and technical definitions.
    Browse maps: browse persons on an interactive map.
    Theodora: featured person.

Browse:

By Name
• English (2500 e.g. count)
    ܠܫܢܐ ܣܘܪܝܝܐ(1281)  • 
    اللغة العربية(891)  •
• (321) Other Languages

By Person Type

By Date

Browse Subsidiary Volumes:

• Volume 1:Qadishe: A Digital Catalogue of Saints in the Syriac Tradition

• Volume 2:
A Guide to Syriac Authors

Advanced Browse

Advanced Search

**Comment by davidamichelson** [comment]
Actually, do we need it to say Syriac Biographical Dictionary Twice?

**Comment by dlschwartz** [comment]
I like the mock-up!

On Wed, Oct 19, 2016 at 3:37 PM, David Michelson <notifications@github.com>
wrote:

> @wsalesky
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wsalesky&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=OC_Es8Z0zabRbl6KWUzXmFJ3pSOLsZBiabtXJss9CLA&s=Af2R3s0bfYZ0QZ9p8Nzu1m11yZaaempj3guH_CTRXK4&e=>
> @dlschwartz
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dlschwartz&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=OC_Es8Z0zabRbl6KWUzXmFJ3pSOLsZBiabtXJss9CLA&s=AO7u-lnwxWedgXL0y8fXwkyez9F51WpBqiOxtthLRa4&e=>
>
> how is this as a mock up:
> [image: screen shot 2016-10-19 at 11 51 24 am]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_3083773_19536514_dcfb0f9c-2D9611-2D11e6-2D89b6-2D8c193311e7ad.jpg&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=OC_Es8Z0zabRbl6KWUzXmFJ3pSOLsZBiabtXJss9CLA&s=86Q5VqTzTr6yQv4FAbjZYlO_3R21jw6t8g02FeA8DaQ&e=>
>
> Text:
> General Editor: David A. Michelson, Vanderbilt University
>
> Associate Editors: Jeanne-Nicole Mellon Saint-Laurent, Marquette
> University, Nathan Gibson, Vanderbilt University, Daniel Schwartz, Texas
> A&M University
>
> The Syriac Biographical Dictionary (SBD) is a multi-volume= name and
> biographic authority record documenting persons relevant to the field of
> Syriac studies.
>
> About page: an overview of the gazetteer and its contributors.
> Help page: documentation, editorial guidelines, and technical definitions.
> Browse maps: browse persons on an interactive map.
> Theodora: featured person.
>
> Browse:
>
> By Name
> • English (2500 e.g. count)
> ܠܫܢܐ ܣܘܪܝܝܐ(1281) •
> اللغة العربية(891) •
> • (321) Other Languages
>
> By Person Type
>
> By Date
>
> Browse Subsidiary Volumes:
>
> • Volume 1:Qadishe: A Digital Catalogue of Saints in the Syriac Tradition
>
> • Volume 2:
> A Guide to Syriac Authors
>
> Advanced Browse
>
> Advanced Search
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2DeXist-2Dapp_issues_836-23issuecomment-2D254933383&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=OC_Es8Z0zabRbl6KWUzXmFJ3pSOLsZBiabtXJss9CLA&s=30NLKIq8TrHOol4mVtG7lkJajo7UfL5Xlruv6pFJVFs&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzjP5kfnupllcopuLpNy9OXY3qbBkks5q1n-2DFgaJpZM4KbDU2&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=OC_Es8Z0zabRbl6KWUzXmFJ3pSOLsZBiabtXJss9CLA&s=KUs_CxtN1fPFLs1mBOU5m8ZgJ9pHLv8MzChUU9aJAjo&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by wsalesky** [comment]
We don't have an interactive map for persons...

**Comment by nathangibson** [comment]
I've been wishing for an interactive persons map for a while -- it just hasn't been a high enough priority ...

**Comment by wsalesky** [comment]
I don't think it would be that hard to add, I'm guessing it would look something like the related places map on the individual persons page. I will put a little thought into it and see if we can get something up. The code all exists already, in theory it should not be difficult to do. (Famous last words.)

**Comment by wsalesky** [comment]
Updated: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html

**Comment by wsalesky** [comment]
Additional options, we could also add an aggrigate timeline to the homepage if that would be of interest. (Like on SPEAR)

**Comment by davidamichelson** [comment]
You are too much. Map would be great.

**Comment by wsalesky** [comment]
The map for browsing all places with relationships to persons is really slow (another place where I imagine RDF will help us out). Also each person can have multiple places, how would we connect the person and the place? Have the place label and list the person and relationship type in the popup bubble?

**Comment by wsalesky** [comment]
Should this be moved to production?  (without maps)

**Comment by nathangibson** [comment]
I would vote to move it to production.

As far as the maps, what about a marker for each place mentioned (only 1 per place), and put a list of the relationships in the popup bubble (rel. type + person)?

**Comment by wsalesky** [comment]
I'm working on the syriac keyboard today, but that actually sounds like it would be a fairly doable solution. I will take a look tomorrow. Thanks for the idea.

**Comment by wsalesky** [comment]
Moved to production. I am still working on the maps. Trying to make the code fast enough to use on the index page. Should be able to do. Making a new issue for it.
