### ISSUE TITLE
Labelling the Dev Server as Dev

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#842]
To avoid confusion between the published versions of modules and the development server, please create a label that is superimposed on the header for every page on the dev server.

The text for this label, which should large and clear should be:

"Syriaca.org development server: Not for citation. For the published versions, see Syriaca.org [live link]."

**Comment by davidamichelson** [comment]
I love it!

A few tweaks please:

BEfore expansion, please change the label to

DRAFT
see Syriaca.org [live link to home]

After the expansion:

You are viewing a page on the Syriaca.org development server:
Not for citation. For the published versions, see Syriaca.org.

**Comment by nathangibson** [comment]
Awesome. @wsalesky so in the end you couldn’t resist figuring out how to do diagonal text? :-)
