### ISSUE TITLE
Organizing the lists in Persons and Places tabs in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#843]
Can persons and places tabs have a display like SBD and the Gazetteer with the alphabet across the top? For persons, it would also be good to have an option equivalent to the letters of the alphabet for "anonymous" and another for anonymi labeled "groups".

**Comment by wsalesky** [comment]
Take 1:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=places

**Comment by wsalesky** [comment]
Still working on adding source text facet. Also seems a little slow.
