### ISSUE TITLE
Change links in Persons and Places tabs

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#845]
The results of clicking on the tabs for persons and places are a list of persons or places. In each case, the headword includes a link to SBD and a URI with a link to SBD. Only at the bottom is there a link to the SPEAR aggregation page for each entity. I think we should have only two links with the headword linking to the aggregation and the other link prefaced with “For additional information, see [link to SBD]”

**Comment by wsalesky** [comment]
Done
