### ISSUE TITLE
Organizing Relationship Lists

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#846]
I am working on a system for organizing relationships that should be helpful for the list display in this section. https://docs.google.com/document/d/1m_BtaYXCTQ7W8nCvpBuGKYHKLooKsQX-ulqr0t9KsFo/edit. I imagine we would only use the following categories from the first column -- Professional, Household, Personal, General, Religious to display relationships on the person aggregation page.

**Comment by wsalesky** [comment]
@dlschwartz I think this can be closed. Thanks!
