### ISSUE TITLE
Rendering relationship in English sentences

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#847]
I would like to render the relationships on the aggregation pages for persons in English sentences. I have a list of relationships in use or anticipated accompanied by English renderings: https://docs.google.com/spreadsheets/d/1aDICk8lrQ7cospr2yVlMYLXavMbaTDxbgr1GDrqfWDw/edit#gid=0 
If the person whose data is being aggregated is value of the @active or @mutual attribute we could use column D.
If the person whose data is being aggregated is the value of the @passive attribute we could use column F.

**Comment by wsalesky** [comment]
Do you want the sentences added to the TEI, or just in the HTML rendering?

**Comment by dlschwartz** [comment]
Good question and just what I was hoping to discuss in our meeting today. I only need it in the HTML. How would you prefer to do it? What's easier?

**Comment by wsalesky** [comment]
Working on this today... so far speed for dynamic rendering is pretty good.
