### ISSUE TITLE
"Factoid(s)" section in SPEAR persons aggregation

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#848]
I would like this to look like that top gray box in SBD, but labeled "Person Information", This section would list name variants, office, occupation, vocation, sex, birth date, death date, citizenship, social rank, confessor, martyr, saint, physical trait(s). Unfortunately, we have not encountered all of these in our sources yet. In case it helps, see here the basic TEI we would use to encode for these:

```
<state type=“citizenship”>
<state type=“socialRank”>
<state type=”martyr”>
<state type=”confessor”>
<trait type=“physical”>

```

**Comment by dlschwartz** [comment]
state type=“office”
state type=“vocation”
state type=“occupation”
state type=“citizenship”
state type=“socialRank”
state type=”martyr”
state type=”confessor”
trait type=“physical”

**Comment by dlschwartz** [comment]
Great, thanks. Please let me know if you have any questions about my
various GitHub issues. I read Syriac with a student at 2 but I'll try to
keep an eye on my email as much as possible.

On Fri, Oct 21, 2016 at 12:50 PM, Winona Salesky <notifications@github.com>
wrote:

> Sounds good. I'm re-writing a lot of the SPEAR code, I will let you know
> when I have the revised pages up.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2DeXist-2Dapp_issues_848-23issuecomment-2D255433059&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=WvdAbicC1yl79IDqXxOFQruXOO5PZ-Yi56txoqvVr3c&s=CLLyCw6OSb4lQJLW3mPu-Pc_-gtHuisPQxXxamLs0q0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzvgzVGN5s0H9sTSGYhoU6Y-2D-2DtAAgks5q2PtOgaJpZM4KbTew&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=WvdAbicC1yl79IDqXxOFQruXOO5PZ-Yi56txoqvVr3c&s=9jkWM8UbAw6bHIecHDESS_vHf4Q9hUNn_MmnlDwX2Do&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by wsalesky** [comment]
Example person aggregation:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201

**Comment by wsalesky** [comment]
I think it might be useful organize "Person info" we could add some sort options, such as be source, and by data type (element name)

**Comment by dlschwartz** [comment]
@wsalesky I've been working on the schema for SPEAR which has shown me how convoluted some of my encoding has been. Does this reconfiguration of person factoids help? I hope so! https://github.com/srophe/srophe-app-data/blob/dev/Pers_Element_Testing.xml

**Comment by wsalesky** [comment]
I think this one can be closed as well.
