### ISSUE TITLE
"Factoid(s)" section in SPEAR places aggregation

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#849]
In all the places I checked (only a few actually) the top box labeled "Factoid(s)" is blank. I'm not sure what would go in there. A simply list of factoids wouldn't be very helpful. Did you have something else in mind? I think the "Events", "Related Person(s)", and "Related Place(s)" pretty much cover our bases actually. Unless you have some plan for this I'm not seeing, I think we can delete this section from places.

**Comment by wsalesky** [comment]
Sample places aggregation: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/place/78

**Comment by wsalesky** [comment]
I think it might be useful organize "Place info" we could add some sort options, such as be source, and by data type (element name)

**Comment by wsalesky** [comment]
I think this can be closed.
