### ISSUE TITLE
missing Syriac Manuscript data 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-eXist-app#850]
@wsalesky Hi Winona! For some reason the Syriac MS witness data has fallen off the BHSE pages.

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/272

**Comment by jsaintlauren** [comment]
I think that this just happened.

**Comment by wsalesky** [comment]
Okay, I will take a look. Thanks for the heads up.
