### ISSUE TITLE
Strange search results in Safari works cited module (prod app)

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#856]
Some search result items have a weird text display in Safari 8.0.8 (Mac 10.10.5). E.g., http://syriaca.org/exist/apps/srophe/bibl/search.html?q=&title=&author=Brock&pub-place=&publisher=&date=&idno= displays as pictured below. 
![syriaca_org__the_syriac_reference_portal](https://cloud.githubusercontent.com/assets/3083452/19773345/82ebc5c4-9c69-11e6-9034-fe6cc74b03dc.png)

**Comment by wsalesky** [comment]
Added normalize space to template.

**Comment by nathangibson** [comment]
Awesome, thanks!
