### ISSUE TITLE
Weird titles in BHSE search results

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#857]
Search http://syriaca.org/exist/apps/srophe/bhse/search.html?q=peter+the+iberian yields the following. Looked at the data and can't figure out why.
<img width="614" alt="syriaca_org__the_syriac_reference_portal" src="https://cloud.githubusercontent.com/assets/3083452/19804261/8f4900e4-9d0d-11e6-9168-60f3269fd6d5.png">

**Comment by wsalesky** [comment]
Sorry about that. I did not realize there could be nested syriaca-headwords, xslt now checks and grabs only top level headwords as titles. Thanks!
