### ISSUE TITLE
SPEAR individual facoid pages

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#859]
@dlschwartz Did we discuss these yet? Is it just the factoid (with @refs as links?) and the citation? Do we want a side bar on the right linking to aggrigate pages on places/persons mentioned?

**Comment by dlschwartz** [comment]
@wsalesky This is a good question which we haven't gotten into yet. We certainly want to see the factoid and the bibliographic reference. From this fine level of granularity, I think links to the SPEAR aggregation pages for persons and places with URIs as well as to SBD and the Gazetteer entries with each labeled as such would be ideal. As you create these pages, you might find it helpful to look at this: https://github.com/srophe/srophe-app-data/blob/dev/Pers_Element_Testing.xml. It is an update on the range of options for person factoids. This pretty much covers everything and puts it in the proper format. You will see there where text nodes will appear and where machine readable versions will appear. Now that I am done with this, I will go back and edit the TEI. I have a schema in place now that will help with this. Please let me know if I need to do this before you can really work on the individual factoid pages. Thanks Winona.

**Comment by wsalesky** [comment]
Initial factoid pages are up.

**Comment by dlschwartz** [comment]
@wsalesky This is looking great! Thanks.

**Comment by wsalesky** [comment]
I think these are in pretty good shape. Any new changes should be added as a new issue.
