### ISSUE TITLE
Aggregate page for keywords?

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#861]
Should we provide an aggregate page for keywords? I think it might be useful. 
ex: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/keyword/emperor

(I would need to do a little work on the display if this is something we would like to have.)

**Comment by dlschwartz** [comment]
@wsalesky Sorry we didn't get to discuss this earlier today. I think this is a good idea. Thanks.

**Comment by wsalesky** [comment]
Okay. We can talk about tweeks at a different meeting.

**Comment by dlschwartz** [comment]
Yes, let's do that on Wednesday. Thanks

**Comment by wsalesky** [comment]
@dlschwartz I think this one has been resolved, reopen if you feel there is more to be discussed.
