### ISSUE TITLE
error on http://wwwb.library.vanderbilt.edu/work/2501

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#862]
`exerr:ERROR Exception while transforming node: A sequence of more than one item is not allowed as the first argument of tokenize() ("#bib2501-15 #bib2501-14", "http://syriaca.org/work/2501")  [at line 89, column 3]
In function:
	global:tei2html(node()*) [186:18:/db/apps/srophe/modules/lib/global.xqm]
	app:rec-display(node(), map) [39:9:/db/apps/srophe/modules/app.xql]
	templates:call-with-args(function, function*, element(), map) [208:13:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]`

**Comment by wsalesky** [comment]
The culprit:
`<relation type="mssWitnesses" active="#bib2501-1" ref="dct:source" passive="#bib2501-15 #bib2501-14" source="#bib2501-7 #bib2501-16"/>`

That looks like a new way of handling relationships. Although this is not the error I would have expected.

**Comment by nathangibson** [comment]
Yes, this is the record where we have been solidifying the new data format for NHSL. So I'm not surprised it's causing problems. I'll be getting in touch with you soon about visualization of this new data format. (You did a preliminary one for Rome, but there are still some things to work through.) Thanks!

**Comment by wsalesky** [comment]
Okay, I 'fixed' the bug; as in now at least you can view the record. I suspect we will need to make some changes to the display.
