### ISSUE TITLE
Please label quotations in search results

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#865]
For example in  http://syriaca.org/persons/search.html?q=narsai

Search results:

9 matches for Keyword: narsai 

1
Narsai - ܢܪܣܝNames: NarsaïNARSAÏNarsai (Narsetes) Poet and teacher of exegesis at the School of Edessa and at the School of Nisibis ; author of popular verse homilies ( memre ). URI: http://syriaca.org/person/650

this should be in a quotation marks: "Poet and teacher of exegesis at the School of Edessa and at the School of Nisibis ; author of popular verse homilies ( memre )."

**Comment by davidamichelson** [comment]
@tacarlson We plan to push this to production server. It meets a request made to the editors from publications that we quote. Please let us know if you object. This will affect the Gazetteer.

**Comment by tacarlson** [comment]
Seems good.  Always good to mark quotations as such.

Do we need to clean up space before semi-colon and extra spaces within parentheses in order to match the sources?

**Comment by wsalesky** [comment]
@davidamichelson Can I push this change to production?

**Comment by davidamichelson** [comment]
Yes please.

**Comment by wsalesky** [comment]
Done.
