### ISSUE TITLE
Selecting source in  SPEAR source browse produces error

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#868]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?fq=;fq-Source%20Text:The%20Letters%20of%20Severus%20of%20Antioch,%20%22Select%20Letters%22%201.01
gives the following error:

> exerr:ERROR Error while evaluating expression: $hits[ancestor::tei:TEI/descendant::tei:titleStmt/tei:title[1][string(.) = "The Letters of Severus of Antioch, "Select Letters" 1.01"]]. org.exist.xquery.XPathException: err:XPST0003 unexpected token: Select [at line 1, column 113]
 [at line 86, column 4]

**Comment by wsalesky** [comment]
Thanks. Those double quotes in the title are causing some havoc with my facets. Will work on it.
