### ISSUE TITLE
"HI THERE" randomly appearing on the beginning of some HTML text sections

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#869]
E.g., "Description" section of http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2823
"Syriac Manuscript Witnesses" in http://wwwb.library.vanderbilt.edu/work/270
Several places on http://wwwb.library.vanderbilt.edu/work/2501 (experimental record)

**Comment by wsalesky** [comment]
Doh! Sorry, some local testing making over to the dev server...

**Comment by nathangibson** [comment]
I figured :-)

**Comment by wsalesky** [comment]
Fixed.
