### ISSUE TITLE
SPEAR: Work View for Works in SPEAR

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#873]
Please prepare a page for each work that included information similar to the aggregate search page.

This page should be formed on the basis of the work URI found in the header of the TEI file(s)

The information should included counts for the 3 types of factoids, a link to NHSL for information about the work, list of the bibls URIs cited in the factoids, the editors who prepared them.

**Comment by wsalesky** [comment]
Initial version of works page. 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/spear/119

We can discuss at the meeting how it should be organized. And accessed.

**Comment by dlschwartz** [comment]
Great, thanks Winona. I'll put this on the agenda for Wednesday.

**Comment by wsalesky** [comment]
Also, should we change the content of the "Sources" tab to just list these with each title linking to the work aggregate page? This is what would make the most sense to me.

**Comment by nathangibson** [comment]
Well, I still need to create the NHSL resource.

**Comment by wsalesky** [comment]
Okay, will there be a link/ptr/reference to the record in the SPEAR xml?

**Comment by dlschwartz** [comment]
Yes there will be. We haven't put that in yet but we will.

**Comment by wsalesky** [comment]
Okay. Great, I will just leave a "holding place."

**Comment by wsalesky** [comment]
See work done on: 
https://github.com/srophe/srophe-eXist-app/issues/883
