### ISSUE TITLE
Old Deprecated Data Shows up in Search

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#875]
For example, this search http://syriaca.org/search.html?q=Jacob+Nisibis
 returns a record which is deprecated:
5
Eusebius of Samosata - ܐܘܣܝܒܝܘܣ ܕܫܡܝܫܛNames: Ewsebiyōs d-shamishṭEusebiusʾEwsēbyōs da-?mīšāṭEusèbe de SamosateEUSÈBEEusebius was a ...URI: http://syriaca.org/person/1234

**Comment by davidamichelson** [comment]
Note, when you click through the record is no longer there, but it should not be in the search results at all.

**Comment by wsalesky** [comment]
@davidamichelson  Okay. I added a new xconf file for the depreciated data directory. I will need to add this to the data .xar and add a script to deploy it correctly. However it should be functioning correctly on both dev and prod. Please let me know if that is not the case.
