### ISSUE TITLE
Labelling related to Search

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#876]
This is related to #864 and #821 

Please make the following changes to the Advanced Search page and banner:

1. Eliminate the phrase "Wild cards * and ? may be used to optimize search results. Wild cards may not be used at the beginning of a word, as it hinders search speed." Phrase since this is now covered by the "Search Tips? button"

2. Rename the "Search Tips?"  button to "Search Help?" which is more international

3. Move the "Search Help?"  button from its current location at the bottom, to the top of the search form.

Please make the following change to the results page:

4. Change the sentence: "You may wish to expand your search with a wildcard (*) to increase results. See search tips for more details." to "You may wish to expand your search by using our advanced search functions (link) or by using wildcard characters to increase results. See search help (link) for more details.

5. Finally, I am not sure what to do with the banner that says "Advanced Search" it could be turned into a sort of search tool bar with links to advanced search and tips but I think it could also just be deleted?

**Comment by wsalesky** [comment]
I made these changes, let me know what you think. We can move them to production if you approve.

**Comment by davidamichelson** [comment]
Thanks I will look over these search ones today.

**Comment by davidamichelson** [comment]
I think that the changes did not get made on the results page (nos 4-5 above):

For example on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/search.html?q=Test

I get "You may wish to expand your search with a wildcard (*) to increase results. See search tips for more details.


collection('/db/apps/srophe-data/data/works/tei')//tei:body[ancestor::tei:TEI/descendant::tei:title = 'Bibliotheca Hagiographica Syriaca Electronica'][ft:query(.,'Test',common:options())]

**Comment by wsalesky** [comment]
Ops. you are correct. I will add those.

**Comment by wsalesky** [comment]
Added. Will push to master, when I get the go ahead on either popup or toggle for 'Search Tips'
@davidamichelson @nathangibson @dlschwartz @jsaintlauren
