### ISSUE TITLE
Fixing links on landing pages for BHSE and Q

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#878]
@wsalesky Could you please merge just these changes (https://github.com/srophe/srophe-eXist-app/commit/d194486ddeebd092707898c598fb00a75f9130ac) to production. The sample records for BHSE and Q on the landing pages pointed to the Dev server rather than the production. Would you please check that I did the relative paths correctly and if correct please push to the production server? Thanks!

**Comment by wsalesky** [comment]
Done.
