### ISSUE TITLE
Fix relationships in SPEAR

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#879]
Compare:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/13

"Related Persons and Places" on the right with relationship factoids in the center, should "Anonmyous 2234" and "ʿAbshmayya" should also show up here?

**Comment by dlschwartz** [comment]
Yes, I think they should show up but maybe we should discuss in some more detail. Might this just be redundant?

**Comment by wsalesky** [comment]
Well, they are not linked in the description, so they are useful. If we link them in the body of the factoid then it would indeed be redundant. We can discuss.

**Comment by wsalesky** [comment]
I also added the keywords to this section. We could consider adding the bibl citations as well. 
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2268

**Comment by wsalesky** [comment]
This one was fixed, but never closed. Closing now.
