### ISSUE TITLE
Labelling full Syriaca.org search

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#881]
Let's discuss labeling for http://syriaca.org/search.html

**Comment by davidamichelson** [comment]
Change "Search Syriaca.org" to "Search Syriaca.org (All Publications)"
Add sub heading underneath: "More detailed search functions are available in each individual publication" [link: Syriaca.org].

**Comment by davidamichelson** [comment]
Please temporarily supress title and citation until we can label them better.

**Comment by wsalesky** [comment]
@davidamichelson  Shall I push this to master?
See: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/search.html
