### ISSUE TITLE
Easy place to cut and past Headword plus URI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#884]
Dear Colleagues,
I often find myself on our sighting wanting to cut and past the following:
```John of Dalyatha - ܝܘܚܢܢ ܕܕܠܝܬ̈ܗ URI: http://syriaca.org/person/826```
But there is not a single step way to do this, at best one gets:

```John of Dalyatha - ܝܘܚܢܢ ܕܕܠܝܬ̈ܗ(active 8th cent.)   saint  author
The Text Encoding Initiative iconThe Atom format iconThe Print format icon

i

URI: http://syriaca.org/person/826```

Would we like to make a button for this? Would it be of interest to others?

**Comment by dlschwartz** [comment]
This would be helpful. More often, however, I find myself wanting a button to copy the URI. Could we also do a button for this like they have on Pleiades? I recognize that we are more likely to want this than other users, but it would still be nice to have.

**Comment by nathangibson** [comment]
Both of these buttons would be nice.

**Comment by davidamichelson** [comment]
What about implementing https://clipboardjs.com/

**Comment by wsalesky** [comment]
@davidamichelson Do you want to grab dates along with person names when we copy? 

> Aba I, catholicos - ܐܒܐ ܩܕܡܝܐ

or

> Aba I, catholicos - ܐܒܐ ܩܕܡܝܐ (d. 552)

**Comment by wsalesky** [comment]
Demo: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/980
We can tweak if desired.

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz @nathangibson Did we want to push this to productions?

**Comment by dlschwartz** [comment]
This looks good to me. I would say yes. But please let some others weigh in first. Thanks

**Comment by nathangibson** [comment]
I think so. I do like the button next to the URI. I'm a little less certain about whether the clipboard in the page title is too busy.

**Comment by wsalesky** [comment]
@nathangibson I don't love the clipboard near the title either, not sure where else to put it though. Perhaps float it over near the other buttons?

**Comment by tacarlson** [comment]
Is this to be deployed on production modules, or only for internal use on the dev server, like the page counts and the next entry button?


If for production, I am unsure whether the clipboard button is clear enough cross-culturally for a broad audience.  I have seen a link button to copy a URL onto a clipboard, but that is not our use case.


The button next to the title isn't pretty, but separating it off with the other buttons would make less clear what exactly is going onto the clipboard.  Perhaps a small text link underneath the title saying "Copy Title"?


But then, my workflow does not include copying and pasting large numbers of headwords and URIs, so this is a more important feature for some of you than for me.  So I'll leave the shape and placement of this to your preference.

________________________________

**Comment by dlschwartz** [comment]
FWIW, I almost never want to cut and paste headword and URI. I frequently want to cut and paste URIs. If we decide that this button clutters the headword too much and ought to be cut, I'm alright with that. I know others, @davidamichelson, want such a button.

**Comment by davidamichelson** [comment]
Here is the result of our discussion:

For the title: please move the clipboard button to the right of the printer icon. When clicked this icon will copy "Aaron of Alexandria - ܐܗܪܘܢ ܕܐܠܟܣܢܕܪܝܐ - http://syriaca.org/person/980"

For the URI itself please turn "URI:" into a button that copies the URI (similar to the clipboard button). Delete the current clipboard button.

Lastly, when the URI itself is clicked, have it highlight (but not copy) just the URI" "http://syriaca.org/person/980"

Also dont forget to delete the clipboard in the idenity box please

**Comment by davidamichelson** [comment]
Looks great with a couple of tweaks needed please.

First the clipboard box (at least on Firefox for Mac) is slightly bigger than the print and other icon boxes, can you make it the same size please?

Second, the URI button by the URI is nice but now makes the information "i" button a bit crowded. Should we get rid of it?

**Comment by davidamichelson** [comment]
And one more, when I click on the actual URI to highlight it, it is also grabbing the colon: ": http://syriaca.org/person/1092" I think we can just delete the colon from the HTML page since we have the button box now.

**Comment by wsalesky** [comment]
Yes, I think we should get rid of it.

**Comment by wsalesky** [comment]
Okay, how is this:
http://syriaca.org/place/78.html

**Comment by nathangibson** [comment]
I like that.

**Comment by davidamichelson** [comment]
Yes, could we also add these features to the search results and browse previews?

**Comment by tacarlson** [comment]
For someone who is not in on this discussion, the clipboard button to the right does not evidently do anything, and the URI button highlights the URI, but for what purpose is unclear.  Would it be possible to add mouse-over text or some explanation for general users, since we have this deployed on production?

**Comment by wsalesky** [comment]
Yes, we can add a mouse over, and also perhaps a little dialog popup that says 'copied' as done here:
https://pleiades.stoa.org/places/874298

**Comment by tacarlson** [comment]
Seems like a good model, although I do prefer capitalization and sentence punctuation, when possible...

________________________________

**Comment by wsalesky** [comment]
I can add capitalization and punctuation. :) 

For the clipboard we should probably have a full sentence to explain what is being copied:
'Record title and id have been copied to your clipboard.'

Seems a little long, any other thoughts? 

@davidamichelson @nathangibson @dlschwartz @jsaintlauren ?

**Comment by tacarlson** [comment]
Perhaps "Copies record title & URI to clipboard."?

________________________________

**Comment by wsalesky** [comment]
Yes, that is fine for the mouseover, I think we should also have text for a successful action.

**Comment by tacarlson** [comment]
I think "Copied!" is clear and concise, but I do not have strong opinions on the subject.  Unless we want to say "copied" in Syriac... (?????)

________________________________

**Comment by davidamichelson** [comment]
Hi Thomas,

Thanks for these comments, we had an extended discussion on this on Wed so
there is some background here that we should have passed on perhaps.


We will take your comments and discuss them at the next Wed meeting.
Winona, could you please hold off for now until we can be clear on what we
want.

Thanks,
Dave

**Comment by wsalesky** [comment]
Here is an example with the clipboard on the search results. 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=ephrem

Post comments here please.

**Comment by tacarlson** [comment]
I wasn't part of the discussion, and so will abide by what others discuss.  I merely wonder if it might look better if the clipboard were moved to in front of the names, as a specialty bullet point?

**Comment by nathangibson** [comment]
Either way is fine by me. In any case I wouldn’t mind having it even smaller/less pronounced. Not sure if that would be a problem on mobile.

**Comment by davidamichelson** [comment]
I like it as is though I think Dan would like the URI to also be a button
similar to on the entry page?
I am slightly opposed to putting the button before the name since that
slows reading. I wouldn't mind it however if it was put next to the number
for the numbered list of results and made the same size as that?

**Comment by dlschwartz** [comment]
I think this is fine. Because the search results have a URI with hyperlink, I can right click and copy the link. One mouse click isn't actually worth adding another button. It's the page itself you had to highlight the URI and it's nice to have the button. I'm satisfied if everyone else is.

**Comment by wsalesky** [comment]
Should I mock up a version with it near the number? I think it is a little misleading there, as I would then expect it to copy the whole blurb (including name variants and descriptions). 
Let me know.

**Comment by dlschwartz** [comment]
Sorry, I should have commented on that as well. I think it looks good where it is. I also think that it would slow reading if it appeared before the name. And I agree that having it by the number would suggest something other than what this button does.

**Comment by wsalesky** [comment]
Okay. Can I push it to the production server?

**Comment by tacarlson** [comment]
No objection here.

**Comment by dlschwartz** [comment]
@davidamichelson Placing the icon by the number is the last remaining idea on the table. Do you want to pursue that or should Winona push this to production?

**Comment by davidamichelson** [comment]
Leave as is is fine with me

**Comment by dlschwartz** [comment]
Thanks everyone. Please push to production Winona. Thanks.

**Comment by davidamichelson** [comment]
FYI I think this needs to stay open for W to close?

**Comment by wsalesky** [comment]
I will open it, it is a good reminder on for me if it is open.

**Comment by wsalesky** [comment]
Done!
