### ISSUE TITLE
Search Help on SBD

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#892]
On http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html if I click search help I can't scroll or close the pop-up.

**Comment by wsalesky** [comment]
Fixed also changed to collapsing div rather then popup, I think it is better for usability.

**Comment by nathangibson** [comment]
Sorry to reopen -- weirdly the "Search help" button doesn't do anything now for me on this page http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html (FF and Safari)

**Comment by wsalesky** [comment]
Looks like a webhook hiccup. I manually moved the file. Looks okay now.
