### ISSUE TITLE
Grouping person factoids on person aggregation page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#893]
Can we group types of person factoid: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201
@wsalesky please let me know if I should give you come kind of ordering for this. It might be best to start with grouping by type of information and then once we can see that deciding whether or not to order them further.

**Comment by wsalesky** [comment]
First attempt is up. 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201

**Comment by dlschwartz** [comment]
@wsalesky I think this is looking great! I might want to revisit this but for now this is a solid improvement. In the next week or so, I will likely upload a test file that will include a fabricated set of data to give us a few examples of every possible option for a person factoids. I think that will help as we test this display. Thanks Winona.
