### ISSUE TITLE
Bug in rendering relationships in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#895]
Different wording of the same relationship: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2570
Musonius and Alexander Intimate Relationship
Alexander , Musonius , Martyrius had an intimate relationship.

**Comment by wsalesky** [comment]
These are two different factoids, coded with different name attributes:

`<relation ana="personal" name="snap:IntimateRelationship" mutual="http://syriaca.org/person/2571 http://syriaca.org/person/2570"></relation>`

and 
`<relation ana="personal" name="syriaca:IntimateRelationshipWith" mutual="http://syriaca.org/person/2570 http://syriaca.org/person/2571 http://syriaca.org/person/2573"></relation>`

My relationship code handles 'IntimateRelationshipWith' which is the correct code?

**Comment by wsalesky** [comment]
This is a data issue.
