### ISSUE TITLE
404 for Edessa on dev

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#897]

**Comment by wsalesky** [comment]
Looks like a controller.xql issue:
Does not work: 
wwwb.library.vanderbilt.edu/place/78.html

Does work: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/place/78.html

**Comment by wsalesky** [comment]
Unless this is a big usability problem on the dev server I am going to leave this. It works well on production.

**Comment by dlschwartz** [comment]
No problem. I only mentioned it yesterday in the meeting because I stumbled across it. Thanks.
