### ISSUE TITLE
Please research using the github wiki for documentation including slurping it into the app

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#902]

**Comment by wsalesky** [comment]
This is possible. So go ahead and start populating the wiki. I will work on some technical documentation for reusing the app.

**Comment by wsalesky** [comment]
See:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/wiki.html

**Comment by davidamichelson** [comment]
Notes on how to possibly divide this up:
We voted to approve using this moving forward. We will ask Winona to push this to production and redesign the documentation page and we will move some but not all documentation into into this format:

The following ought be moved into the srophe-app-data wiki, but some should be checked with Thomas first:
Dates
Frequently Asked Questions (should check with TAC and call it Gaz FAQ)
Headwords
URI Policies
Technical Terminology
Find out where these are linked from. Will ask Winona.
Should be moved to the APP Wiki:
Syriaca.org API Documentation

The following should stay and be listed under the wikis with the label “Additional Documentation”:
The following are called in documents are:
Language and Script Identifiers
Place Types
Relations
Religious Communities
Have some complications with scripts etc.:
How to View Syriac Text on Syriaca.org
TEI Tag usage in Gazetteer
Using TEI to Catalog Syriac Manuscripts

**Comment by wsalesky** [comment]
Okay, here is an example of how this new format could look: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/index.html

We may need to do some CSS tweaking to get some of the github classes to behave, but overall I think it looks pretty good.

**Comment by nathangibson** [comment]
I like this. The editors may want to discuss what the clearest labels for the 3 sections would be.

**Comment by wsalesky** [comment]
Yes, I agree, better labeling would be useful.

**Comment by wsalesky** [comment]
- Editorial Documentation
- Editorial Reference 
- Technical Documentation

**Comment by wsalesky** [comment]
This has been updated. I will need to work on add some technical documentation.

**Comment by wsalesky** [comment]
When do we want this to move to production?

**Comment by davidamichelson** [comment]
Yes please!

**Comment by davidamichelson** [comment]
@wsalesky @dlschwartz Could you please move this to production before next week? Thanks!

**Comment by wsalesky** [comment]
Moved to production.
