### ISSUE TITLE
Surprising behaviors of "Browse"

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#904]
http://syriaca.org/geo/browse.html defaults to listing the first page of A results in English, but it differs from  http://syriaca.org/geo/browse.html?lang=en&sort=A in a few particulars:

1. browse.html (with no paramaters) seems to use the older alphabetization which does not ignore opening single quotations or similar characters and does not ignore "al-"

2. When I click the "All" button to the right, browse.html without parameters lists all 2488 entries regardless of which letter they begin with (using the older alphabetization) whereas browse.html?lang=en&sort=A lists only 188 A entries.  (This may have been intended as a feature, but it surprised me given the prominence of "A" in the browse view.)

3. The links to particular English letters in browse.html have an empty "lang=" parameter, and clicking on it removes "English" from a tab.

**Comment by wsalesky** [comment]
Thanks @tacarlson I will take a look.

**Comment by wsalesky** [comment]
@tacarlson I think I have resolved all of these issues. Would you mind reviewing them and letting me know if you find anything unexpected. If they work as expected I will move it to production. 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/geo/browse.html

**Comment by tacarlson** [comment]
Sorry for the delay!  Sudden home repair issue occupied (or "ate") a couple days.

This now behaves as I would expect, so feel free to push to production.  

One niggling question: when a user visiting browse.html (with no parameters) clicks on a letter, the link includes an empty "lang=" parameter (e.g. "browse.html?lang=&sort=C").  The dev version now maintains "English" in a tab in larger script, so the page displays as expected, but I was surprised that "lang=" did not get a value such as "en".

Thank you for all your work!

**Comment by wsalesky** [comment]
The default language is English, so if it is not specified, then it will be English, this  can be specified in the lang parameter or not, it does not matter functionally. 

I have moved the changes to Production. Please let me know if you find any unexpected behavior. Thanks!
