### ISSUE TITLE
Extra whitespace

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#906]
Is the extra whitespace before the comma ("Budge , Ernest") in Budge , Ernest Alfred Wallis - ܒܕܓ - http://syriaca.org/person/404 from the TEI or the CSS?

**Comment by wsalesky** [comment]
Looks like a problem in the XSLT.

**Comment by davidamichelson** [comment]
Please fix in search results.

**Comment by wsalesky** [comment]
It is fixed in search.
