### ISSUE TITLE
iOS Syriac display of http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#907]
@wsalesky Just FYI, I noticed that the SBD home page does not display the Syriac text on iOS 9 (see screenshot), whereas it does on other pages. I added `lang="syr"` to the span and now it displays correctly. It also changed this to our default font. 

![img_1231](https://cloud.githubusercontent.com/assets/3083452/21181465/5be420d8-c1fe-11e6-9bfc-6d48c5db9a69.png)

**Comment by wsalesky** [comment]
Great! Did you change it on Production as well?

**Comment by nathangibson** [comment]
I haven’t pushed it to production yet. You’re welcome to if you think it’s safe.

**Comment by wsalesky** [comment]
Done!
