### ISSUE TITLE
Visualization of works in new NHSL format

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#909]
Once you've pushed the records from https://github.com/srophe/srophe-app-data/issues/648 to the dev server, let me know and we'll see what needs to be adjusted in the visualization. 

Related: https://github.com/srophe/srophe-eXist-app/issues/724

**Comment by wsalesky** [comment]
Looks like duplicate records were uploaded. I'm reloading them, works may be problematic for the next 30 minutes or so.

**Comment by nathangibson** [comment]
No problem. Thanks for doing this. Sorry if I caused problems when I merged your branch.

**Comment by wsalesky** [comment]
I think this has been resolved.

**Comment by nathangibson** [comment]
Thanks @wsalesky ! The biggest issues here have been resolved. However, there is still some tweaking -- I hadn't yet explained the details as I wasn't sure what it would be until I saw it on the page. Feel free to move these to separate issues if that's easier: 

1. It appears it is no longer pulling the citation info from the works cited module. E.g., the first item under "Editions" at http://wwwb.library.vanderbilt.edu/work/850 says "Brooks, E. W.LES 3p. 268 [614] - 273 [619]" instead of pulling the info from http://syriaca.org/bibl/2033. 

2. I have now included human readable labels for the `@type` on bibls in the ODD file (https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/documentation/syriaca-tei-main.odd). You can grab these using the following xpath (where lawd:ConceptualWork) is an example of the bibl type you want to grab: `//elementSpec[@ident='bibl']/attList/attDef[@ident='type']/valList/valItem[@ident='lawd:ConceptualWork']/gloss`. You can use these for the headings (instead of e.g. "Syriaca:ModernTranslation" as well as any place you need to formulate text from relations). Would you prefer that these be upper or lower case?

3. Relations inside /TEI/text/body/bibl/bibl/listRelation should be visualized as follows: 
 a. You can suppress display of all `relation[@ref='lawd:embodies']`. This exists only for RDF serialization later. (Right now this is showing as, e.g., "Relation : #bib850-3 - http://syriaca.org/work/850")
 b. For `relation[@ref='dct:source']` you can also suppress the extra "Relation: " text. E.g., work/850 shows "Relation : #bib850-3 - #bib850-6". The text "(Edition from syriaca:Manuscript 1. See below.) (Edition from . See below.)" should become "(Edition from Manuscript 1. See below.)" I.e., this uses the gloss mentioned above and does not duplicate. 
 c. I would like any relation inside bibl to be able to display a `relation[@ref='dct:source']`. E.g., for http://wwwb.library.vanderbilt.edu/work/9501 the first Modern Translation would say "(Modern Translation from Edition 1. See above.)"

4. For some reason, bibls of type syriaca:Manuscript and syriaca:ModernTranslation are all run together instead of being a numbered list. 

5. The relationships sidebar is showing up even when there are no relationships: e.g., http://wwwb.library.vanderbilt.edu/work/9501. 

OK, that's all I see right now, other than #911 and #912. Thanks so much!

cc: @davidamichelson

**Comment by wsalesky** [comment]
@nathangibson Working through this list today. 
While fixing the relationships I found this in the data:
`<relation type="mssWitnesses" active="#bib9501-6" ref="dct:source" passive="#bib9501-8 bib9501-11" source="#bib9501-1"/>`

The second value in the passive attribute needs a '#' added.

**Comment by wsalesky** [comment]
First pass at these changes. 
http://wwwb.library.vanderbilt.edu/work/9501

**Comment by nathangibson** [comment]
This is looking great! And thanks for catching the faulty passive value. 

I only see two things at the moment:
 1. The heading "Titles:" should be "Titles" (no colon) to match the other headings.
 2. We should discuss citation numbering and citation link targets when we meet. (E.g., the superscript "5" is a link but it appears that its target is a nonexistent anchor since it cites an edition. But we can discuss details in the meeting.)

**Comment by jsaintlauren** [comment]
Excellent work!

**Comment by wsalesky** [comment]
We can just add in an anchor, that was an oversight, not a deliberate exclusion.

**Comment by nathangibson** [comment]
Thanks. Adding in the anchor would help. But also the superscript link itself should make sense as a label. "5" doesn't mean anything to the user when the item it links to is "Edition 1". We can discuss the best way to resolve the human readability.

**Comment by nathangibson** [comment]
Please include duplicates of all bibls that are not `@type="lawd:Citation"` in the "Sources" section. These should be sorted by xml:id.

**Comment by nathangibson** [comment]
Thanks, the Sources are displaying as expected.

However, something seems to have interfered with the "Edition from/Translation from" info. E.g., Edition 4 on http://wwwb.library.vanderbilt.edu/work/9501 has "(Edition from s, .)" and the others are blank "(Edition from .)" Maybe this has something to do with your labeling types of relations?

**Comment by wsalesky** [comment]
@nathangibson  Okay, I think I have the labeling correct now. You may close this if it looks good.

**Comment by wsalesky** [comment]
@nathangibson can this be closed? (Doing my Monday morning issue roundup.)

**Comment by nathangibson** [comment]
Hmm, there is something going on with the edition-manuscript-translation prose in http://wwwb.library.vanderbilt.edu/work/9501. Edition 4 (bib9501-6) should say "(Edition from Manuscripts 2, 3.)" instead of "(Edition from Manuscripts 1, 2.)"
And Modern Translations 1, 2, and 3 should be from Editions 1, 2, and 3, respectively (not all from Edition 1 as they are now). As far as I can tell the problem is in the transformation rather than the data.

**Comment by wsalesky** [comment]
Fixed, good catch.
