### ISSUE TITLE
http://syriaca.org/person/13 error

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#910]
Unfortunately our model record http://syriaca.org/person/13 is throwing an error in FF and Safari (screenshot below).

Possibly related to pushing the records in https://github.com/srophe/srophe-app-data/issues/659#event-895466582 to production? 

![apache_tomcat_7_0_50_-_error_report](https://cloud.githubusercontent.com/assets/3083452/21232604/776bead6-c2ec-11e6-82c3-836fb259a784.png)

**Comment by wsalesky** [comment]
Interesting... I will look into it.

**Comment by wsalesky** [comment]
Bug with Worldcat. Temporarily commented out while I troubleshoot. This way we can at least still use the record.

**Comment by nathangibson** [comment]
Thanks!

**Comment by wsalesky** [comment]
Interesting. It was tied to the new (now rolled back) range indexes I added to speed up record queries by id.
