### ISSUE TITLE
Parent-Child works visualization

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#911]
@wsalesky I now have some model data we can use to start developing the visualization for works that contain other works. The model parent work is Lives of the Eastern Saints (http://syriaca.org/9501) (only on dev server) and the child works are consecutive URIs from http://syriaca.org/792 through http://syriaca.org/850. 

We want to maintain the relationship in the child work. So the child work has something like 
```
<relation xml:id="relation792-1" type="part" active="http://syriaca.org/work/792" ref="dct:isPartOf" passive="http://syriaca.org/bibl/9501">
                        <desc>
                            <label type="order" subtype="part" n="1">part 1</label>
                        </desc>
                    </relation>
```
The active is the child work and the passive is the parent work. The optional desc/label provides a machine-readable (`label[@type="order"]/@n`) and human-readable order. 

Here's my suggestion on how to visualize. Comments from others are welcome. 

**Child Work**
In the relationships sidebar:
**This work is contained in other works.**
[label from above relation/desc]
[Headword link]
[Abstract]
URI: [URI]

**Parent Work**
Child works should be shown in the body of the work under the gray identity box, perhaps using the same or similar code as the "Works by" section of author records (e.g., http://wwwb.library.vanderbilt.edu/person/13). Child works should be sorted and numbered using the `relation/desc/label[@type="order"]/@n` of the child work. 

We will eventually need to figure out how to handle parent-child relationships in search and browse, but the editors need to discuss this first. 

#909 
#724 
cc: @dlschwartz @davidamichelson @jsaintlauren

**Comment by nathangibson** [comment]
Oh no, I just realized I labeled all the relations with bibl/9501 instead of work/9501! Correcting that now.

**Comment by wsalesky** [comment]
@nathangibson  Perhaps we can discuss this tomorrow. 
Sample work:
http://wwwb.library.vanderbilt.edu/work/9501

**Comment by nathangibson** [comment]
Yes, let's do.

**Comment by nathangibson** [comment]
Please sort and number based on `relation/desc/label[@type="order"][1]/@n`

If there are multiple label elements, use only the first one for numbering/sorting in the parent work, but put in parentheses (e.g., "Also found as part 5.")

@nathangibson create a test case and document the fact that the label order matters.

**Comment by wsalesky** [comment]
Do you want the text of the label? Or just the number?

**Comment by wsalesky** [comment]
Okay, how about now?

**Comment by nathangibson** [comment]
Sorting looks correct, thanks!

Now that I see it, I think I do prefer it without the "part" label. But perhaps we should ask the others their opinion? @davidamichelson @jsaintlauren @dlschwartz Check out http://wwwb.library.vanderbilt.edu/work/9501 and http://wwwb.library.vanderbilt.edu/work/68. Do you like it better with or without the "part" or "book" prefixed to the numbers of contained works?

**Comment by dlschwartz** [comment]
I agree that the use of "part" is odd. From the perspective of a catalog, "part" is fine. However, scholars don't always use that language when talking about this kind of thing. In some contexts, the part is indeed a book (i.e. the Pentateuch) but in others that is not the case. Furthermore, the ancient use of "book" for a modern "chapter" might leave people thinking that they should expect to find an entry for Book 8 of The Chronicle of Ps. Zachariah. In short,  I prefer just the numbers as it just keeps things simpler.

**Comment by dlschwartz** [comment]
I forgot to mention something in connection with this issue. I did a search for "Lives of the Eastern Saints" in the search box at the top of the page and got this [](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/search.html?q=Lives+of+the+eastern+saints). It seems odd to me that one of the parts shows up and not all or none. This should probably be a different issue but perhaps @nathangibson should take a crack at writing up something on how to handle this in search since he is the one really working on this at the moment.

**Comment by dlschwartz** [comment]
Sorry, link didn't come through: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/search.html?q=Lives+of+the+eastern+saints

**Comment by wsalesky** [comment]
Done.

**Comment by nathangibson** [comment]
Unfortunately, it still looks like we're having issues with ordering. When you pull up the list of contained works at http://wwwb.library.vanderbilt.edu/work/9501, they are not in the correct order and the numbers displaying beside them are not the numbers in the relation/desc/label. For example, http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/831 has n="40" but shows as "042" and http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/820 has n="29" but shows as "059".

**Comment by wsalesky** [comment]
Fixed!

Note: order is based on the first tei:desc/tei:label, let me know if this causes any issues.
