### ISSUE TITLE
Redirect not working for deprecated records?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#914]
On the production server, records that should be redirected go to the deprecated page. E.g., http://syriaca.org/person/2096. 

On the draft server, the same records go to a 404 page instead of redirecting. 

Not sure how long this has been happening. 

Original issue: #546. TEI encoding for records that should redirect: https://github.com/srophe/srophe-app-data/issues/104#issuecomment-218555443. Possibly related: #771

**Comment by wsalesky** [comment]
Hum. Thanks, I will take a look. Something must have gotten rolled back.

**Comment by wsalesky** [comment]
Hum. I did not do anything, but they seem to be redirecting to me... @nathangibson  Do you still have this problem?

**Comment by nathangibson** [comment]
Yes, right now both servers seem to be going to 404. Not sure why since https://github.com/srophe/srophe-app-data/blob/dev/data/deprecated/persons/tei/saints/tei/2096.xml has a URI type="redirect". But don't worry about this until after the break. I start on break today. Thanks!

**Comment by wsalesky** [comment]
Working on Dev, not Prod, code looks the same... Still debugging.

**Comment by wsalesky** [comment]
Same as: https://github.com/srophe/srophe-eXist-app/issues/986

**Comment by nathangibson** [comment]
Thanks!
