### ISSUE TITLE
Spacing for icon in bibls

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#928]
The final icon in this bibl is spaced oddly (seems to be missing a space). 

See notes for sources 2 and 3 in  http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1584

2 Sergey Minov (ed.), A Comprehensive Bibliography on Syriac Christianity (The Center for the Study of Christianity, The Hebrew University of Jerusalem, 2013), entry: St Anastasia.Link to Syriaca.org Bibliographic Record

3 Sebastian P. Brock and Susan Ashbrook Harvey, Holy women of the Syrian Orient (Berkeley: University of California Press, 1987), pp: 142-149.Link to Syriaca.org Bibliographic RecordLink to Zotero Bibliographic RecordLink to Worldcat Bibliographic record

**Comment by wsalesky** [comment]
Fixed!
