### ISSUE TITLE
Rendering of TEI in titles for Sources section is unable to handle attribute data

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#930]
Somewhat surprisingly (so we could revise the data if need be instead) this record has a problem in the html for the sources list: http://wwwb.library.vanderbilt.edu/person/2679

Note how it renders http://syriaca.org/bibl/675

1 E. W. Brooks (ed.), Text, The Sixth Book of the Select Letters of http://syriaca.org/person/51Severus Patriarch of Antioch in the Syriac Version of http://syriaca.org/person/1014Athanasius of Nisibis vol. 1.2 (Oxford: Williams and Norgate, 1904), pp: 369.

I think we should delete the person URIs from these titles?

Nathan, what do you think?

**Comment by nathangibson** [comment]
Yes, for now I think that's the best solution. Done.
