### ISSUE TITLE
Visualization of http://wwwb.library.vanderbilt.edu/work/1

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#932]
I just added a bunch of stuff to http://wwwb.library.vanderbilt.edu/work/1 using a script. I see some visualization problems. 

 1. Manuscripts (`bibl/@type="syriaca:Manuscript"`) are not showing up in their own section, as they should, only in footnotes. Am I coding something wrong?
 2. I have more info in the manuscripts than in other records. idno and date are not showing. Could we visualize the idno as regular text and the date in parentheses? E.g., 
```
<bibl type="syriaca:Manuscript" xml:id="bib1-14" source="bib1-15">
                    <idno type="BL-Shelfmark">Add MS 14738</idno>
                    <biblScope unit="folio" from="1a" to="1b">Fol. 1</biblScope>
                    <ptr target="http://syriaca.org/manuscript/694"/>
                    <date notBefore="1300" notAfter="1400">xivth cent.</date>
                    <listRelation>
                        <relation active="bib1-1" ref="lawd:embodies" passive="http://syriaca.org/work/1"/>
                    </listRelation>
                </bibl>
```
Would look like 
> Add MS 14738, Fol. 1 (xivth cent.)
 3. Can we have a separate "Catalogues" section for `bibl/@type="syriaca:Catalogue"` as we do for Manuscripts, editions, etc. This could go just below the manuscripts section. 

Thanks!

**Comment by wsalesky** [comment]
Still some display issues, but at least they are showing up. I will come back to this tonight, or tomorrow and get it cleaned up.

**Comment by wsalesky** [comment]
@nathangibson  What the expected display once that ptr to the manuscript is live? 
`<ptr target="http://syriaca.org/manuscript/694"/>`

I don't want to write a patch for the display that will then be overwritten later.

**Comment by nathangibson** [comment]
Yes, understandable. Let's pull @davidamichelson in on this one.

**Comment by nathangibson** [comment]
Also, the "Catalogue" section looks great. Can it go below "Manuscript" section? Thanks.

**Comment by wsalesky** [comment]
@nathangibson For some reason I'm having a terrible time ordering these... trying again today.

**Comment by nathangibson** [comment]
OK, let me know what you need.

**Comment by wsalesky** [comment]
@nathangibson Can you remind me of the order for each of these bibl types? I think I mixed them up. 
These are they types I currently have, in the order I have them:
lawd:Edition 
lawd:Translation
syriaca:ModernTranslation
lawd:WrittenWork 
syriaca:Manuscript 
syriaca:Catalogue

**Comment by davidamichelson** [comment]
Nathan please confer with me on this today thanks

**Comment by nathangibson** [comment]
@wsalesky For the manuscript bibl display with ptr, please use the following: 

> Add MS 14738 [http://syriaca.org/manuscript/694], Fol. 1 (xivth cent.)

**Comment by wsalesky** [comment]
I think this can be closed.
