### ISSUE TITLE
Running Maintenance Scripts in Perseids

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#935]
This is split off from https://github.com/srophe/srophe-eXist-app/issues/874

As part of the Perseids integration, we should include the running of maintenance scripts on the TEI data as part of the finalization of records and before they are fully approved for push to master.

@wsalesky could you please let us know what ways you suggest we integrate that? Would the script be run before or after "finalization"?

**Comment by wsalesky** [comment]
I would recommend adding it to the Syriaca.org admin module, and running them before submitting them to Perseids. I can add a button.

**Comment by davidamichelson** [comment]
Thanks, let's discuss tomorrow. One problem with that is that the record will often get slightly edited while in Perseids and thus the scripts need to be run afterward I think.

**Comment by davidamichelson** [comment]
@wsalesky will inquire of Bridget

**Comment by wsalesky** [comment]
This has been implemented. Bridget is testing it.
