### ISSUE TITLE
Nav Bar Icons

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#936]
Delete the magnifying glass icon
Move keyboard icon to first after search box
Keep gears
Change "font" icon to the word "Font"

In font icon add a choice "Default" as first option. (this option displays the page as encoded).

Bill to corpus app development.

**Comment by davidamichelson** [comment]
Please put on dev and solicit feedback.

**Comment by wsalesky** [comment]
@davidamichelson were we adding more items to the 'gear' option? Or does it just go to the advanced search. I thought we were going to have a drop down menu?

**Comment by davidamichelson** [comment]
I think in th eend it stays the same since the keyboard button is staying
in the nav bar

**Comment by wsalesky** [comment]
New version up on dev for review. 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/index.html

**Comment by davidamichelson** [comment]
Looks good, we would like to have the order be: search box, keyboard, search gear, font please. (ie move font to last.

Second, in the font menu please add as the last item the choice "Help?" and provide a link to: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/wiki.html?wiki-page=/How-to-view-Syriac-script&wiki-uri=https://github.com/srophe/srophe-app-data/wiki

Related to this, could you please review this page and make a brief edit to communicate what we do to make fonts work on mobile: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/wiki.html?wiki-page=/How-to-view-Syriac-script&wiki-uri=https://github.com/srophe/srophe-app-data/wiki

Lastly, I suppose we should remove any old pointers that point to the old version of this page: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/view-syriac.html and point to the new wiki version instead.

Thanks

**Comment by wsalesky** [comment]
Let me know if we are ready to move any of these features to the Production server.

**Comment by dlschwartz** [comment]
I think we are ready to move this to Production now. Thank you Winona!

**Comment by dlschwartz** [comment]
We've got a green light from all interested parties. Let's move this to Production. Thank you Winona.

**Comment by wsalesky** [comment]
Done!
