### ISSUE TITLE
TEI View broken on dev server

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#940]
I seem to get the following error when trying to view any TEI on the dev server (e.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/97/tei): 

> XML Parsing Error: no root element found
> Location: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/97/tei
> Line Number 1, Column 1:

This is on FF. Safari doesn't load anything, not even an error message.

**Comment by wsalesky** [comment]
Interesting. The corpus restxq script interferes with the syriaca.org script.

**Comment by nathangibson** [comment]
Thanks!
