### ISSUE TITLE
Problem with recaptsha in Additions/Corrections

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#941]
I get the following error: ERROR for site owner: Invalid domain for site key

**Comment by wsalesky** [comment]
From what page?

**Comment by dlschwartz** [comment]
I've tried it with several in SBD. For example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1463.

**Comment by dlschwartz** [comment]
It only seems to be a problem on dev, by the way.

**Comment by wsalesky** [comment]
Yes, well dev is using the recaptcha key for prod... I did not realize we would be using this as a feature on the dev branch as well. I can check to see if can share a key.

**Comment by dlschwartz** [comment]
Maybe we don't need it. Sorry to muddy the waters. We have some differences in our data between dev and production when it comes to people who used to share a URI, but whom we have subsequently tired to assign different URIs. I am trying to work out what is going on with this and found an error in the data that I tried to report using this corrections button. I just won't do that anymore. I'll use Github, or production. Thanks Winona.
