### ISSUE TITLE
SPEAR broken after pushing updates

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#942]
My research assistant Kathy and I have both recently pushed changes to SPEAR data. I have made a couple of minor tweaks to the schema and we have both made some changes to the data to bring it into line with the schema. I am now getting a lot of errors throughout SPEAR. Can you please help me troubleshoot this @wsalesky. Thank you.

**Comment by wsalesky** [comment]
Can you post some links to problematic pages? 
Thanks!

**Comment by dlschwartz** [comment]
It's not quite everything but close to it:

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2200

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=events

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=relations

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=places

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=keywords

**Comment by wsalesky** [comment]
Thanks. I will take a look.

**Comment by wsalesky** [comment]
Fixed. Except I now see a bug in events. I will open a new bug for that.
