### ISSUE TITLE
See/Hide bug in relations sidebar

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#944]
When I look at http://wwwb.library.vanderbilt.edu/work/235 (FF 51.0.1 on Mac 10.10.5) it says "This work commemorates 7 persons" then shows the work (not person) record first and then a single person (image 1). When I click "See all 7" nothing changes (image 2). Then when I click the "Hide" button all relations vanish along with the button (image 3). 
![agapius__two_alexanders__two_dionysii__timothy__romulus__and_paesis__text_](https://cloud.githubusercontent.com/assets/3083452/23064501/af150e44-f510-11e6-91ea-f7a499846a01.png)
![agapius__two_alexanders__two_dionysii__timothy__romulus__and_paesis__text_](https://cloud.githubusercontent.com/assets/3083452/23064505/b80a4b90-f510-11e6-813f-5bad41e66081.png)
![agapius__two_alexanders__two_dionysii__timothy__romulus__and_paesis__text_](https://cloud.githubusercontent.com/assets/3083452/23064519/c33831f8-f510-11e6-9e0d-7e9f36cd3de4.png)

**Comment by wsalesky** [comment]
ID mis-match.
