### ISSUE TITLE
Relationships sidebar displays work for "syriaca:commemorated" 

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#945]
For the ref="syriaca:commemorated" relation in works, the relationships sidebar is showing both the work (active) and the person (passive). It should only show the person, right? 
http://wwwb.library.vanderbilt.edu/work/235
http://wwwb.library.vanderbilt.edu/work/835
Possibly related #944

**Comment by wsalesky** [comment]
Yes, these are related, looks like a problem with the indexes, not the code.

**Comment by wsalesky** [comment]
@nathangibson do you need the works on the dev server in the next hour? I think to fix the relationship issues I need to reload the works data. I can wait if you are using it today.

**Comment by wsalesky** [comment]
Same as: https://github.com/srophe/srophe-eXist-app/issues/946

**Comment by nathangibson** [comment]
Go for it. I can use my local copy/github, assuming this won't affect the github repo. Let me know when you're done.

**Comment by wsalesky** [comment]
It will not make any changes, just a little downtime on dev. Thanks.

**Comment by wsalesky** [comment]
Resolved.
