### ISSUE TITLE
Relationships sidebar doesn't show plural for number 2

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#946]
The relationships sidebar correctly says "7 persons" for http://wwwb.library.vanderbilt.edu/work/235 but says "2 person" (singular) and "2 work" for http://wwwb.library.vanderbilt.edu/work/835.

**Comment by wsalesky** [comment]
Same as: https://github.com/srophe/srophe-eXist-app/issues/945

**Comment by wsalesky** [comment]
Resolved.
