### ISSUE TITLE
Do we need to change Perseids board integration in admin module? 

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#947]
When I submit to perseids from the admin module, I get the error "Failed submission: 405 405 Invalid Community". When I log into perseids, I can see the record, it is just not assigned to a board. I believe Bridget created new boards, so the old links are probably broken.

**Comment by wsalesky** [comment]
Sorry, that was my error. I fixed it and submitted a record. Seems to have gone to the correct board, although I now do not seem to have permission to delete it! (person-14)
