### ISSUE TITLE
Missing bullet point & missing space for "See Also" Google

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#948]
On http://syriaca.org/place/15.html , in the "See Also" section in the right-hand column and down, there is are bullet points for Pleiades, ATOM, TEI, and Wikipedia, but not a bullet point for "View in Google Maps".  It also looks like there is no space between the Google Maps icon and the text "View in Google Maps" as there is for the other four entries of "See Also".

**Comment by wsalesky** [comment]
Thanks, I will take a look.

**Comment by wsalesky** [comment]
fixed.
