### ISSUE TITLE
Icon in browser tabs

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#949]
When I have a lot of tabs open as I move back and forth between person, place, and work records, it is super helpful that the Gazetteer records have a gimel with maroon background. The person and work records currently have the alaph with blue background that is for the Syriaca.org homepage. Can you please make the icon that appears in the tab, the icon for the module (not the volume) of which that record is a part. Thanks.

**Comment by wsalesky** [comment]
Done!

**Comment by dlschwartz** [comment]
Thanks Winona! This will be more helpful than you might imagine.
