### ISSUE TITLE
.html suffix does not resolve on dev server?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#950]
404 on http://wwwb.library.vanderbilt.edu/place/1261.html
whereas http://wwwb.library.vanderbilt.edu/place/1261 sends me to the equivalent record on the production server.
Is this the expected behavior?

**Comment by wsalesky** [comment]
@nathangibson this is due to some redirects I think Dale had added to the dev server. These can be accessed by going to: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/place/1261.html

I will check with Dale about removing that redirect.
