### ISSUE TITLE
Unrelated e-gedsh content appearing in sidebar? 

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#951]
For example, look at sidebar on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/342.

> Caught error java:java.net.URISyntaxException: Illegal character in scheme name at index 7: Teacher of biblical interpretation, author, Cath. (540–52). Born from Zoroastrian parents, Aba converted to Christianity and studied at the School of Nisibis. ...

**Comment by wsalesky** [comment]
This seems to be resolved.
