### ISSUE TITLE
Lozenges for Sub-Volumes of Modules on Individual Record Pages

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#962]
This is a new solution to this old issue: https://github.com/srophe/srophe-eXist-app/issues/438

For individual records which are part of a sub-volume, for example http://syriaca.org/person/13 (Ephrem), we currently add "Saint" and "Author" based on the series statement of the xml file.

We would like to change this visualization.

Please remove the current adding of "Saint", "Author", etc and instead add this visualization:

On the same line where the URI is listed (below the headword), please add the following:
This page is an entry in [icon for Q]_Qadishe: Guide to the Syriac Saints_ and [icon for Authors] _A Guide to Syriac Authors_ (both should be live links to syriaca.org/q and syriaca.org/authors)

We would like to compare this option with another with shorter labels so if you could make two branches for us to compare please:
This page is an entry in [icon for Q]_Qadishe_ and [icon for Authors] _Authors_

Thanks!
DM

**Comment by wsalesky** [comment]
Example with long view:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/13

I have to switch out the xslt to switch views, so I can't really do both at once. We can swap in the short view in real time during a meeting if you want to compare them.

**Comment by wsalesky** [comment]
Some options: 
<img width="1422" alt="screen shot 2017-04-05 at 1 52 13 pm" src="https://cloud.githubusercontent.com/assets/1168206/24719281/29edf138-1a07-11e7-9f07-6862065a6a49.png">
<img width="1423" alt="screen shot 2017-04-05 at 1 52 01 pm" src="https://cloud.githubusercontent.com/assets/1168206/24719280/29e86e3e-1a07-11e7-9214-741f5da9f23c.png">

**Comment by davidamichelson** [comment]
I like the first option (in line with URI). I wonder if we could even bump
it up to the line with the headword but justified right?

**Comment by wsalesky** [comment]
And bump the 'candy' buttons up?

**Comment by davidamichelson** [comment]
hmm, maybe swap location of the candy buttons and the volume credits with
candy buttons on URI line?? Otherwise what we have now on dev looks good.
Maybe just leave it for now.

**Comment by wsalesky** [comment]
@davidamichelson Can this be closed?
