### ISSUE TITLE
Error message on persons (bug in authored-by feature?)

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#970]
http://wwwb.library.vanderbilt.edu/person/13 and http://wwwb.library.vanderbilt.edu/person/239 , possibly others: 

> exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: substring-before($source as xs:string?, $search as xs:string?) xs:string?. Expected cardinality: zero or one, got 2. [at line 292, column 45, source: /db/apps/srophe/modules/person.xqm]
In function:
	person:authored-by(node(), map) [217:18:/db/apps/srophe/modules/person.xqm]

**Comment by wsalesky** [comment]
Fixed. (Again, I feel like I have fixed this particular xpath bug several times!) I think there may have been some git issues. (My fault.)

**Comment by nathangibson** [comment]
Thanks!
