### ISSUE TITLE
500 error for TEI source on dev server

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#972]
The TEI Source button everywhere (?) gives a 500 error, e.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/2335/tei

> HTTP ERROR 500
> 
> Problem accessing /exist/apps/srophe/bibl/2335/tei. Reason:
> 
>     Server Error
> 
> Caused by:
> 
> javax.servlet.ServletException: An error occurred while processing request to /exist/apps/srophe/bibl/2335/tei: err:XPST0081 No namespace defined for prefix http [at line 218, column 18, source: /db/apps/syriac-corpus/modules/rest.xqm]
> In function:
> 	api:get-tei(xs:string, xs:string) [-1:-1:/db/apps/syriac-corpus/modules/rest.xqm]

**Comment by wsalesky** [comment]
Yep, sorry, I was ignoring that one.

**Comment by nathangibson** [comment]
I have an xslt that queries it, but I can probably point it to the github files instead for now.

**Comment by wsalesky** [comment]
I can't fix it until tonight so that might be best. Sorry!

**Comment by nathangibson** [comment]
No worries, it looks like github is doing the trick. Thanks!
