### ISSUE TITLE
CTS URNs

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#973]
We would like to look into implementing a bare-bones resolution service for CTS URNs (http://cite-architecture.github.io/). At this point, we would like to be able to resolve URNs pointing to texts in the @srophe/syriac-corpus and to subdivisions within those texts, but do not (yet) need to try to serve up text over an API. 

 ### URN Examples
Some examples of a couple possible ways of doing this (for structure see http://cite-architecture.github.io/ctsurn_spec/ and  http://www.homermultitext.org/hmt-docs/cite/cts-urn-overview.html) : 
`urn:cts:syriacLit:nhsl2500.nhsl2501.syriacCorpus291:1.10 `
Would point to http://syriaccorpus.org/291 section 1 subsection 10, where http://syriaccorpus.org/291 is an edition of http://syriaca.org/work/2501, which is contained in http://syriaca.org/work/2500.

`urn:cts:syriacLit:nhsl2500.nhsl2501.bibl342:1.10`
would point to section 1, subsection 10 of the syriaccorpus record that transcribes http://syriaca.org/bibl/342. The latter is an edition of http://syriaca.org/work/2501, which is contained in http://syriaca.org/work/2500.

### Existing software that might help
The CTS web service uses an index file to map urns to text files. These text files can be plain text or TEI docs. If the latter, need to define some complicated paths. An alternative is to just have  a 2-column text document (with # as separator) in which column 1 is URN for text passage and column 2 is the passage of text in plain text or XML. 
There is also an eXist-db app that runs the CTS service.
I will put you in touch by email with both of the developers.

*Edited examples above to correct dots versus colons.*

**Comment by wsalesky** [comment]
I am starting work on this project. 
@nathangibson can I get some more examples (5-10 would be fine), with explicit expectations for returned results? 

Thanks!
-Winona

**Comment by wsalesky** [comment]
@nathangibson 
Also, should this service point you to the HTML version of the page? Or return the XML version of the page/subsection?

**Comment by nathangibson** [comment]
Great! 

In my opinion, it should return the HTML page (a specific anchor where relevant), but @jedwardwalters and others should weigh in.

# Examples
You'll notice below that sometimes certain parts of the URN are not needed for resolution in our system. For the WORK part of the URN (see http://cite-architecture.github.io/ctsurn_spec/specification.html#syntax-of-a-cts-urn) you can grab the most specific part and ignore the rest.
1. urn:cts:syriacLit:nhsl8501 should resolve to a search results page with all Syriac Corpus texts that are editions of works contained in http://syriaca.org/work/8501. These texts should have `/TEI/teiHeader/fileDesc/titleStmt/title[@ref='http://syriaca.org/work/8501]`
2. urn:cts:syriacLit:nhsl8501.nhsl8503 should resolve to a search results page with all Syriac Corpus editions of http://syriaca.org/work/8503. If there is only one it should go directly to that edition. These texts should have `/TEI/teiHeader/fileDesc/titleStmt/title[@ref='http://syriaca.org/work/8503]`
3. urn:cts:syriacLit:nhsl8501.nhsl8503.syriacCorpus1 should resolve to https://syriaccorpus.org/1. 
4. urn:cts:syriacLit:nhsl8501.nhsl8503.syriacCorpus1:3 should resolve to https://syriaccorpus.org/1#head-3. In the TEI this is the section identified by the path `/TEI/text/body/div[@n='3']`
5. urn:cts:syriacLit:nhsl8501.nhsl8503.syriacCorpus1:3.5 should resolve to https://syriaccorpus.org/1#head-3 line 5. If we don't have marked lines, this should just go to section 3. 
6. urn:cts:syriacLit:nhsl70.nhsl75.syriacCorpus121:5@10 should resolve to https://syriaccorpus.org/121#head-5 verse 10. The TEI path for this is  `/TEI/text/body/div[@n='5']/ab[@n='10']`. If there are no subsections (abs) marked, it should just resolve to section 5. 
7. urn:cts:syriacLit:nhsl8528.nhsl8602.bibl1765 = urn:cts:syriacLit:nhsl8528.nhsl8602.syriacCorpus101. That is, it should resolve to the Syriac Corpus text that identifies http://syriaca.org/bibl/1765 in its `/TEI/teiHeader/fileDesc/sourceDesc`. I think this will come under `biblStruct/*[1]/idno[@type='URI']` but you should see how this question is resolved here https://github.com/srophe/syriac-corpus/issues/100. 

Do you need more examples? Let me know. Thanks!

**Comment by wsalesky** [comment]
Bare bones implementation (still needs some work): 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/CTS/index.html
