### ISSUE TITLE
Controller does not handle record ids that contain characters

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#975]

**Comment by wsalesky** [comment]
This came up in testing the keywords. Will we have id's that are not numeric? 
@davidamichelson @dlschwartz

**Comment by nathangibson** [comment]
My understanding is that the subjects module will use the subject name as the URI. So yes.

**Comment by wsalesky** [comment]
bummer. ;)

**Comment by dlschwartz** [comment]
Let's discuss tomorrow. We could (and really probably should) give subjects numeric URIs just like our other entities. We prefer human-readable in this instance. If we had a good reason to abandon that though, we could consider it.

**Comment by wsalesky** [comment]
It is fine, just takes slightly more mental gymnastics on my part and the part of our controller.xql.
