### ISSUE TITLE
New relation syriaca:isSometimesPartOf

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#978]
We have a new `relation/@ref` value (which I've updated in the ODD and RNG on dev). It is `syriaca:isSometimesPartOf`. This should function exactly the same way as `dct:isPartOf` *except* that on the containing work page we would like a star/asterisk after the text title and text at the bottom of the contained works list saying: "Manuscripts of the larger work only sometimes contain the work indicated."

Example: http://wwwb.library.vanderbilt.edu/work/850 has the following relation:
```
<relation xml:id="relation850-1" type="part" active="http://syriaca.org/work/850" ref="syriaca:isSometimesPartOf" passive="http://syriaca.org/work/9501">
                        <desc>
                            <label type="order" subtype="part" n="60">part 60</label>
                        </desc>
                    </relation>
```
So the entry for http://syriaca.org/work/9501 should list in the contained works 

> 60 Jacob Baradaeus (Translation of His Body) (text) - ܝܥܩܘܒ ܒܘܪܕܥܝܐ   *
> URI: http://syriaca.org/work/850

And the end of that list should have

>   \* Manuscripts of the larger work only sometimes contain the work indicated.

Make sense? Thanks!

**Comment by dlschwartz** [comment]
@nathangibson Should we also have a note of some sort indicating our assessment of the "sometimes"? Possibilities: incerta, dubia, wahrscheinlich, etc. But seriously, a work might appear in the minority of relevant mss but still rightly belong to the group based on text critical standards. Another example, Chrysostom's catechetical homilies never circulated as a single collection (as far as we know) but some believe that they should be considered as a whole and have argued for that. How might we be able to reflect these kinds of nuances?

**Comment by nathangibson** [comment]
At the moment I was mainly trying to give @wsalesky the basic idea so that we can mock it up. But I'm adding this to editors' meeting agenda. In general, I would be in favor of having a generic property to address present needs but which can be expanded in our ontology with more specific sub-properties.

**Comment by nathangibson** [comment]
In other words, we need a basic list of rdf properties to use in `relation/@ref` that we can tell @wsalesky should function for visualization the same as dct:isPartOf. Currently this consists of
- dct:isPartOf
- syriaca:isSometimesPartOf
The types of asterisks and explanatory text could be specific to the property, but the basic functionality would still be to list them in the entry for the literary tradition. Right?

**Comment by nathangibson** [comment]
@nathangibson Change gloss to "may be part of (in some traditions)"

**Comment by wsalesky** [comment]
@nathangibson Ready for review.

**Comment by nathangibson** [comment]
Actually, what we were thinking on this is to just include the "sometimes part of" item in the same list as the regular contained works, but to put an asterisk by the title if the relation is "syriaca:isSometimesPartOf" instead of "dct:isPartOf". Is that complicated to do? If so, we can probably just tweak what you've done here.

**Comment by nathangibson** [comment]
OK, I changed syriaca:isSometimesPartOf to syriaca:sometimesCirculatesWith in the ODD file and in work/850, but this means it no longer displays on work/9501 understandably. Can you update the code with the new relation name? Also the gloss should now be usable. Thanks!

**Comment by wsalesky** [comment]
Done.

**Comment by wsalesky** [comment]
@nathangibson I changed syriaca:isSometimesPartOf to syriaca:sometimesCirculatesWith in the app, however I think the records are still using syriaca:isSometimesPartOf, as they no longer show up.

**Comment by nathangibson** [comment]
It's working for me: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/9501 shows work/850 at the bottom. Is there something else not showing up?

**Comment by wsalesky** [comment]
I think I was just experiencing some fierce data caching. I will close this issue.
