### ISSUE TITLE
Bibliography display issues

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#980]
E.g. http://wwwb.library.vanderbilt.edu/work/10510

Extra leading space in titles and trailing commas at end.

> " Lives of the Eastern Saints III," Patrologia Orientalis vol. 19.2 ( 1925), pp: 206 [552] - 227 [573],  (Edition from Manuscript 1.)

**Comment by wsalesky** [comment]
Related to: 
https://github.com/srophe/srophe-eXist-app/issues/985

Now I just have to find where the space was introduced.

**Comment by wsalesky** [comment]
@nathangibson I fixed the space, in the case of the comma, should it be a period instead?

**Comment by nathangibson** [comment]
Wonderful! Yes final comma should be a period.
