### ISSUE TITLE
Persons Forms for May

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#981]
For the workshop in May it would be ideal if we could produce a very basic record and reserve a URI for persons. This will mostly be used for anonymous persons. Especially important fields: 

`<persName>`: It would be nice if the user had the option to choose between syriaca-tags="#anonymous-description" or syriaca-tags="syriaca-headword" as attributes. If "anonymous-description" is chosen the user will also need to label the entry using trait and label elements.

`<trait>` with `<label>` nested and a choice of text nodes for the label element of either "Anonymous", or "Anonymi" as the only acceptable options. If one of these options is chosen, we could auto-generate a `<persName>` element with @syriaca-tags="#syriaca-headword" and a text node of "Anonymous ####" or "Anonymi ####" where the #### is the URI number.

`<sex>` (possible @value options are only M, F)

`<bibl>` 
     `<ptr target="http://syriaca.org/bibl/####")>` where user would just enter the ####
     `<citedRange unit="pp">`###

Floruit dates would be icing on the cake but not really necessary

**Comment by wsalesky** [comment]
@dlschwartz Can I get an example `persName` with trait and labels?

**Comment by dlschwartz** [comment]
Sure, here's one from our live data: http://syriaca.org/person/3057/tei

**Comment by wsalesky** [comment]
Do you want me to automatically add a: 
```
<trait xml:lang="en">
<label>anonymous</label>
</trait>
```
If the user selects the `syriaca-tags="#anonymous-description"`?

**Comment by dlschwartz** [comment]
Yes, that sounds good, thanks. And if someone chooses that syriaca-tag, we could also automatically add 
`<persName xml:id="name####-#" xml:lang="en" syriaca-tags="#syriaca-headword">Anonymous ####</persName>` with the new URI number filled in. That would be perfect.

**Comment by wsalesky** [comment]
I think this has been done. There are a few bugs that should be posted in the https://github.com/srophe/srophe-admin/issues repository.
