### ISSUE TITLE
Separating work titles, rubrics, and abbreviations

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#982]
Currently all bibl/title elements of works come under the "Titles" heading. Can we have the following headers and sections instead?

**Titles**
`/TEI/text/body/bibl/title[not(@type=('initial-rubric','final-rubric','abbreviation'))]`

**Initial Rubrics**
`/TEI/text/body/bibl/title[@type='initial-rubric']`

**Final Rubrics**
`/TEI/text/body/bibl/title[@type='final-rubric']`

**Abbreviations**
`/TEI/text/body/bibl/title[@type='abbreviation']`

The odd file now contains these title types with their glosses (in singular form).

**Comment by wsalesky** [comment]
@nathangibson 
Can I have some test records?

**Comment by nathangibson** [comment]
Sure, http://wwwb.library.vanderbilt.edu/work/1 has abbreviation and final-rubric, and http://wwwb.library.vanderbilt.edu/work/9501 has initial-rubric. Thanks!

**Comment by wsalesky** [comment]
@nathangibson  How does this look?
http://wwwb.library.vanderbilt.edu/work/1
http://wwwb.library.vanderbilt.edu/work/9501

**Comment by nathangibson** [comment]
Great, thanks! I forgot to ask for them in a specific order. I'm putting this on the docket for feedback from the others on Wed, so we could decide the order then.

**Comment by nathangibson** [comment]
We want move all initial rubrics and final rubrics out of identity box to where prologue etc. is.

**Comment by wsalesky** [comment]
Above or below the relationships? 
example: http://wwwb.library.vanderbilt.edu/work/9501

Above or below this section:
'Lives of the Eastern Saints contains 59 works.'

Thanks!

**Comment by nathangibson** [comment]
Above. Also above Prologues, Incipits, and Explicits. Thanks!

**Comment by wsalesky** [comment]
Done.
