### ISSUE TITLE
URIs in "Reference Numbers"

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#983]
We're not sure we want external URIs appearing under the "Reference Numbers" header in the identity box (e.g., http://wwwb.library.vanderbilt.edu/work/1). Could we do them like we do for persons, which have a "See Also" box in the sidebar (e.g., http://wwwb.library.vanderbilt.edu/person/13)? 

I realize we discussed earlier for BHSE that the Syriaca URI for the work should appear alongside numeric identifiers in the "Reference Numbers" (e.g., http://wwwb.library.vanderbilt.edu/work/1000). Is it possible to still list the `/TEI/text/body/bibl/idno[starts-with(.,'http://syriaca.org')]` in the Reference Numbers but move all other `/TEI/text/body/bibl/idno[@type='URI']` to "See Also"? Or should we use a different type attribute on the idnos?

**Comment by wsalesky** [comment]
Done!

**Comment by nathangibson** [comment]
Great!
