### ISSUE TITLE
Module icons in page header have shifted

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#985]
As of sometime last week, I am seeing something weird happening with the module icons on page headers (all of them, I think, but including http://wwwb.library.vanderbilt.edu/work/1). The Syriac letter is separated from the colored circle, like so (FF and Safari on Mac 10.10.5). It's a cool effect, but I suppose unintentional :-)

![genesis__peshitta_version_](https://cloud.githubusercontent.com/assets/3083452/24610938/c121472c-1880-11e7-9815-ee1a218baa52.png)

**Comment by wsalesky** [comment]
Sorry, the new eXist has some issues with spaces when it pretty prints. Every time the app gets redeployed spaces are added in the SVG icons, leading to this.... I have to manually remove them. Still need to file a bug with eXist on this issue.

**Comment by wsalesky** [comment]
Submitted bug. 
https://github.com/eXist-db/exist/issues/1437#issuecomment-300460042

**Comment by wsalesky** [comment]
Solution to this bug has been found. Will need to get changes made to production and development eXistdb instances.
