### ISSUE TITLE
Deprecated record redirect not working on production or dev

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#986]
http://syriaca.org/person/1809 should redirect to http://syriaca.org/person/236
(See https://github.com/srophe/srophe-app-data/blob/master/data/deprecated/persons/tei/saints/tei/1809.xml and https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/236.xml respectively.) Instead, I get a 404 error. 

On dev, I get a 301 loop -- http://wwwb.library.vanderbilt.edu/person/1809 redirects to http://wwwb.library.vanderbilt.edu/person/236 which also gives a 301 and thus an infinite page reload. 

Another casualty of eXist 2.0?

**Comment by wsalesky** [comment]
Yes, it is on my radar. I was working on it last week. Will try to get back to it this week and resolve it.

**Comment by nathangibson** [comment]
No problem, I don’t think there’s a huge rush.

**Comment by wsalesky** [comment]
Done.
