### ISSUE TITLE
Corrections Additions button on Gazetteer does not work

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#988]
After I fill everything out and prove I am not a robot, I hit send email and get this error: "please try again"

**Comment by wsalesky** [comment]
Prod or dev?

**Comment by davidamichelson** [comment]
Prod

**Comment by wsalesky** [comment]
Looks like a recaptcha issue. I will do some more debugging tomorrow.

**Comment by davidamichelson** [comment]
Thanks!
