### ISSUE TITLE
SPEAR Sources

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#990]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=sources
The Chronicle of Edessa is listed twice

**Comment by wsalesky** [comment]
The two records that list have the Chronicle of Edessa as a title are: 
Pers_Element_Testing.xml
and
ChronEdessa_Complete_Draft.xml

Once you are ready to remove the test record that second title should disappear, or we can give it a different title, so it is easier to distinguish.
