### ISSUE TITLE
NHSL home page

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#994]
Restyle.

**Comment by nathangibson** [comment]
Like the new style! 

A couple tweaks:

- Please change the labels to "All Works", "Hagiographic Works", "Biblical Works" respectively.
- Please remove the numbers on the top titles and instead put "Volume 1" on bottom left opposite "BHSE", "Volume 2" on bottom left opposite "Bible", etc.

**Comment by wsalesky** [comment]
@nathangibson Take a look at the updated page.

**Comment by nathangibson** [comment]
I like the new titles and placement of volume numbers, thanks! Will discuss with @davidamichelson .

If I might be rather picky, the volume numbers are not aligned vertically with the volume icons, and I find the text in the bottom translucent bars somewhat difficult to read (maybe needs to be bold or something)?

**Comment by wsalesky** [comment]
How about now?

**Comment by nathangibson** [comment]
I like the bold. But now there are a couple spacing/alignment issues :-(. Ahh, those CSS grids! 

![syriaca_org__the_syriac_reference_portal](https://cloud.githubusercontent.com/assets/3083452/25616959/fbab62c6-2f3f-11e7-8429-a891dacf5e44.png)
![syriaca_org__the_syriac_reference_portal](https://cloud.githubusercontent.com/assets/3083452/25616965/000c722e-2f40-11e7-98ed-19f666c53310.png)

**Comment by nathangibson** [comment]
The second screenshot is with my window at about half-width, i.e. 800px across or so.

**Comment by wsalesky** [comment]
Okay, I think I have the alignment worked out.

**Comment by nathangibson** [comment]
Looks great! Thanks!
