### ISSUE TITLE
See all works blank for http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/10513

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#999]
Just updated this record http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/10513. Pop-up is not displaying contained works. Is this a problem with my data or a bug in the app?

**Comment by wsalesky** [comment]
I think this is a bug in the app.

**Comment by nathangibson** [comment]
Thanks!

**Comment by wsalesky** [comment]
@nathangibson is this working for you now?

**Comment by nathangibson** [comment]
Yes, thanks!
